#
# define env variables for GENEPATTERN_USERNAME and GENEPATTERN_PASSWORD
# export GENEPATTERN_USERNAME=ted
# export GENEPATTERN_PASSWORD=
#

python generate-module.py --name gatk.GetPileupSummaries --description "Summarizes counts of reads that support reference, alternate and other alleles for given sites. Results can be used with CalculateContamination." --instructions "Include only the four required arguments. Any other arguments can be passed in using the --arguments_file input to getPipelineSummaries. IMPORTANT: intervals parameter is required as well though it is not specified in the docs, make sure to include it. In tests, the intervals file can be the same as the vcf file.  IMPORTANT: the bam file needs to have a bam index (bai) file passed into GenePattern as a separate file.  In the wrapper script the wrapper must stage the BAM and its index into the writable job working directory (NOT into the input staging directory, which may be read-only on the server): copy both the BAM file and the index file into the current working directory, then pass the local copies to gatk. ALSO IMPORTANT: the vcf file needs to have a vcf index file (*.vcf.gz.tbi) passed into GenePattern as a separate file. In the wrapper script the wrapper must stage the VCF and its index into the writable job working directory the same way: copy both the VCF file and the index file into the current working directory, then pass the local copies to gatk. Never attempt to write index files into the directory where the input files were staged, as that directory may not be writable. ALSO IMPORTANT: the intervals file also requires an index file (e.g. *.vcf.gz.tbi if using a VCF as intervals) passed into GenePattern as a separate file. In the wrapper script the wrapper must stage the intervals file and its index into the writable job working directory the same way: copy both the intervals file and the index file into the current working directory, then pass the local copies to gatk. After GATK completes (whether successfully or with an error), the wrapper must clean up the locally staged copies of the BAM, BAI, VCF, VCF index, intervals, and intervals index files from the working directory using a trap on EXIT so cleanup always runs regardless of success or failure." --language Java --documentation-url https://gatk.broadinstitute.org/hc/en-us/articles/360037593451-GetPileupSummaries  --repository-url https://github.com/broadinstitute/gatk --base-image "broadinstitute/gatk:4.1.4.1"  --gp-user $GENEPATTERN_USERNAME --gp-password $GENEPATTERN_PASSWORD \
  --data /Users/liefeld/Desktop/gatk/normal.bam /Users/liefeld/Desktop/gatk/chr17_small_exac_common_3_grch38.vcf.gz /Users/liefeld/Desktop/gatk/chr17_small_exac_common_3_grch38.vcf.gz.tbi /Users/liefeld/Desktop/gatk/chr17_small_exac_common_3_grch38copy.vcf.gz /Users/liefeld/Desktop/gatk/chr17_small_exac_common_3_grch38copy.vcf.gz.tbi



