# AddFCSEventIndex  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00176:2
#Tue Feb 10 19:11:34 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00176\:2
author=Josef Spidlen, BC Cancer Agency
commandLine=<java> <java_flags> -jar <libdir>addfcseventindex.jar <Input.data.file> <Output.fcs.file.name> <Start.index> <Index.parameter.short.name> <Index.parameter.long.name>
cpuType=any
description=Adds indexes to events in a Flow Cytometry Standard (FCS) data file.
fileFormat=fcs
language=Java
name=AddFCSEventIndex
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=An FCS data file to which you want to add indexes.
p1_fileFormat=fcs
p1_name=Input.data.file
p1_optional=
p1_prefix_when_specified=-InputFCS\:
p1_type=java.io.File
p1_value=
p2_default_value=1
p2_description=The index number for the first event in the data set; the default is 1. The index will be incremented by 1 for each of the events in the data set. 
p2_fileFormat=
p2_name=Start.index
p2_optional=
p2_prefix_when_specified=-StartIndex\:
p2_type=java.lang.Integer
p2_value=
p3_default_value=Index
p3_description=The short name ($PnN keyword) of the parameter to get the index; the default is "Index." 
p3_fileFormat=
p3_name=Index.parameter.short.name
p3_optional=
p3_prefix_when_specified=-IndexParameterShortName\:
p3_type=java.lang.String
p3_value=
p4_default_value=
p4_description=The long name ($PnS keyword) of the parameter to get the index; the default is blank.
p4_fileFormat=
p4_name=Index.parameter.long.name
p4_optional=on
p4_prefix_when_specified=-IndexParameterLongName\:
p4_type=java.lang.String
p4_value=
p5_default_value=<Input.data.file_basename>
p5_description=The output file name.
p5_fileFormat=
p5_name=Output.fcs.file.name
p5_optional=
p5_prefix_when_specified=-OutputFCS\:
p5_type=java.lang.String
p5_value=
pipelineModel=
privacy=public
publicationDate=06/29/2012 15\:37 
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Flow Cytometry
userid=
version=Added fix for parsing empty keyword values
