# AddNoiseToFCS  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00179:2
#Tue Feb 10 19:11:35 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00179\:2
author=Josef Spidlen, BC Cancer Agency
commandLine=<java> <java_flags> -jar <libdir>addnoisetofcs.jar <Input.FCS.data.file> <Output.FCS.file.name> <Parameters.to.add.noise.to> <Noise.level> <Noise> <Saturated.events> <Random.Seed>
cpuType=any
description=Add noise to specified parameters in an FCS data file.
fileFormat=fcs
language=Java
name=AddNoiseToFCS
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=An FCS data file to add noise to.
p1_fileFormat=fcs
p1_name=Input.FCS.data.file
p1_optional=
p1_prefix_when_specified=-InputFile\:
p1_type=java.io.File
p1_value=
p2_default_value=<Input.FCS.data.file_basename>.with_noise.fcs
p2_description=The output FCS file name.
p2_fileFormat=
p2_name=Output.FCS.file.name
p2_optional=
p2_prefix_when_specified=-OutputFile\:
p2_type=java.lang.String
p2_value=
p3_default_value=
p3_description=List of parameters to which the module will add noise. The list may be provided as a list of indexes (e.g., "1-3,5,7") or as a list of parameter names (i.e., values of the $PnN keyword, such as "FSC-H,FL1-H,FL2-A"). By default, the noise will be added to all parameters but the Time parameter.
p3_fileFormat=
p3_name=Parameters.to.add.noise.to
p3_optional=on
p3_prefix_when_specified=-Parameters\:
p3_type=java.lang.String
p3_value=
p4_default_value=0.5
p4_description=Noise level in percent. This is the maximum noise that will be added to an event based on the current event parameter value or on the maximum range of the appropriate parameter. The latter option will be effective if the Uniform noise option is selected.
p4_fileFormat=
p4_name=Noise.level
p4_optional=
p4_prefix_when_specified=-NoiseLevel\:
p4_type=java.lang.Float
p4_value=
p5_default_value=Proportional
p5_description=How to add the noise\: Proportional (The maximum amount of noise added to each value will be based on the value itself, e.g., low values will get lower amount of noise.) or Uniform (The maximum amount of noise added to each value is only dependent on the range of the particular parameter).
p5_fileFormat=
p5_name=Noise
p5_optional=
p5_prefix_when_specified=-
p5_type=java.lang.String
p5_value=Proportional\=Proportional, default;Uniform\=Uniform
p6_default_value=RemoveSaturated
p6_description=Whether to remove saturated events. An event is considered saturated if one or more of its parameter values are closer than 0.1 percent from the maximum range for that parameter (i.e., value of the appropriate $PnR keyword).
p6_fileFormat=
p6_name=Saturated.events
p6_optional=
p6_prefix_when_specified=-
p6_type=java.lang.String
p6_value=RemoveSaturated\=Remove saturated events, default; KeepSaturated\=Keep saturated events
p7_default_value=1234567
p7_description=The seed to use for the random generator. Leave this blank if want to use a randomly selected seed.
p7_fileFormat=
p7_name=Random.Seed
p7_optional=on
p7_prefix_when_specified=-Seed\:
p7_type=java.lang.Integer
p7_value=
pipelineModel=
privacy=public
publicationDate=07/03/2012 12\:42 
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Flow Cytometry
userid=jspidlen@bccrc.ca
version=Added fix for parsing empty keyword values
