# AmpliconSuite  urn:lsid:genepattern.org:module.analysis:00427:50
#Tue Feb 10 19:11:35 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00427\:50
author=Edwin Huang;Mesirov Lab
categories=ecdna
commandLine=python3 /opt/genepatt/run_aa.py  <AA_zipped_output> <bam.file> <fastq.r1> <fastq.r2> --n_threads <job.cpuCount>  <no.filter>  <skip.QC>  <VCF.no.filter> --reference <reference> --file_prefix <Sample.Name> --RUN_AA <RUN.AA> --RUN_AC <RUN.AC>  <ploidy>  <purity>  <cnvkit.segmentation>  <AA.seed>  <CN.gain>  <Minimum.copy.number.size>   <Downsample.Argument>  <AA.runmode>  <AA.extend.mode>  <AA.std.of.insert.size>  <cnv.bed>  <normal_bam>  <VCF.file>   <sample_metadata>  <sample_type>  <tissue_of_origin>  <sample_description>    <sample_source>   <foldback.pair.support.min> <upload.to.amplicon.repository> <project.id> <project.key> <amplicon.repository.username>  <upload.server>  --mosek_server_license <mosek_server_license>  
cpuType=any
description=A multithread-enabled quickstart tool for AmpliconArchitect. Performs all preliminary steps (alignment, CNV calling, seed interval detection) required prior to running AmpliconArchitect. PrepareAA supports hg19 (or GRCh37), hg38 as well as mouse genome mm10 (or GRCm38). PrepareAA can also be invoked to start at intermediate stages of the data preparation process.\n<br>\nAll credits go to\: <a href\="https\://github.com/AmpliconSuite/AmpliconSuite-pipeline">https\://github.com/AmpliconSuite/AmpliconSuite-pipeline</a> \n<br>\nView licenses here\: <a href\="https\://github.com/genepattern/AmpliconSuite\#licenses">https\://github.com/genepattern/AmpliconSuite\#licenses</a>\n<br/>\n<p>\nTo increase your GenePattern disk space quote so you can more easily upload the input bam files, <b><a href\="https\://forms.gle/23tkh98vwkhtCeKM7">click here to join the AmpliconSuiteUsers group on this server.</b> </a> </p>\n \nTo run multiple samples at once, simply drag and drop multiple samples into the input options. There is no need to check the "Batch" box. \n\n<br>\nCurrently using Amplicon Suite version 1.3.8. 
documentationUrl=https\://github.com/AmpliconSuite/AmpliconSuite-pipeline
fileFormat=
job.docker.image=genepattern/amplicon-architect\:v3.13.0
job.memory=15 Gb
language=any
name=AmpliconSuite
os=any
p10_MODE=IN
p10_TYPE=FILE
p10_default_value=
p10_description=BED file (or CNVKit .cns file) of CNV changes. Fields in the bed file should be\: chr start end name cngain
p10_fileFormat=bed
p10_flag=--cnv_bed 
p10_name=cnv.bed
p10_numValues=0..1
p10_optional=on
p10_prefix=--cnv_bed 
p10_prefix_when_specified=--cnv_bed 
p10_type=java.io.File
p10_value=
p11_MODE=
p11_TYPE=TEXT
p11_default_value=
p11_description=The seed that sets randomness for Amplicon Architect
p11_fileFormat=
p11_flag=--AA_seed 
p11_name=AA.seed
p11_numValues=0..1
p11_optional=on
p11_prefix=--AA_seed 
p11_prefix_when_specified=--AA_seed 
p11_type=java.lang.String
p11_value=
p12_MODE=IN
p12_TYPE=FILE
p12_default_value=
p12_description=Path to a matched normal bam for CNVKit (optional).
p12_fileFormat=bam
p12_flag=--normal_bam 
p12_name=normal_bam
p12_numValues=0..1
p12_optional=on
p12_prefix=--normal_bam 
p12_prefix_when_specified=--normal_bam 
p12_type=java.io.File
p12_value=
p13_MODE=IN
p13_TYPE=FILE
p13_default_value=
p13_description=Provide a VCF file of externally-called SVs to augment SVs identified by AA internally.
p13_fileFormat=
p13_flag=--sv_vcf 
p13_name=VCF.file
p13_numValues=0..1
p13_optional=on
p13_prefix=--sv_vcf 
p13_prefix_when_specified=--sv_vcf 
p13_type=java.io.File
p13_value=
p14_MODE=
p14_TYPE=TEXT
p14_default_value=No
p14_description=Use all external SV calls from the VCF file, even those without 'PASS' in the FILTER column.
p14_fileFormat=
p14_flag=--sv_vcf_no_filter 
p14_name=VCF.no.filter
p14_numValues=0..1
p14_optional=on
p14_prefix=--sv_vcf_no_filter 
p14_prefix_when_specified=--sv_vcf_no_filter 
p14_type=java.lang.String
p14_value=Yes\=Yes;No\=No
p15_MODE=
p15_TYPE=Floating Point
p15_default_value=4.5
p15_description=Copy number gain threshold to consider for AA seeding. 
p15_fileFormat=
p15_flag=--cngain 
p15_name=CN.gain
p15_numValues=0..1
p15_optional=on
p15_prefix=--cngain 
p15_prefix_when_specified=--cngain 
p15_type=java.lang.Float
p15_value=
p16_MODE=
p16_TYPE=Integer
p16_default_value=50000
p16_description=CN interval size (in bp) to consider for AA seeding
p16_fileFormat=
p16_flag=--cnsize_min 
p16_name=Minimum.copy.number.size
p16_numValues=0..1
p16_optional=on
p16_prefix=--cnsize_min 
p16_prefix_when_specified=--cnsize_min 
p16_type=java.lang.Integer
p16_value=
p17_MODE=
p17_TYPE=Floating Point
p17_default_value=10
p17_description=Set a custom threshold for bam coverage downsampling during AA. Does not affect coverage in analyses outside of AA.
p17_fileFormat=
p17_flag=--downsample 
p17_name=Downsample.Argument
p17_numValues=0..1
p17_optional=on
p17_prefix=--downsample 
p17_prefix_when_specified=--downsample 
p17_type=java.lang.Float
p17_value=
p18_MODE=
p18_TYPE=TEXT
p18_default_value=FULL
p18_description=If --run_AA selected, set the --runmode argument to AA. Refer to AA documentation\: https\://github.com/AmpliconSuite/AmpliconArchitect\#optional-arguments.  Default mode is FULL. 
p18_fileFormat=
p18_flag=--AA_runmode 
p18_name=AA.runmode
p18_numValues=0..1
p18_optional=on
p18_prefix=--AA_runmode 
p18_prefix_when_specified=--AA_runmode 
p18_type=java.lang.String
p18_value=FULL\=FULL;BPGRAPH\=BPGRAPH;CYCLES\=CYCLES;SVVIEW\=SVVIEW
p19_MODE=
p19_TYPE=TEXT
p19_default_value=EXPLORE
p19_description=If running Amplicon Architect, set extendmode for AA. Refer to AA documentation\: https\://github.com/AmpliconSuite/AmpliconArchitect\#optional-arguments Default is EXPLORE.
p19_fileFormat=
p19_flag=--AA_extendmode 
p19_name=AA.extend.mode
p19_numValues=0..1
p19_optional=on
p19_prefix=--AA_extendmode 
p19_prefix_when_specified=--AA_extendmode 
p19_type=java.lang.String
p19_value=EXPLORE\=EXPLORE;CLUSTERED\=CLUSTERED;UNCLUSTERED\=UNCLUSTERED;VIRAL\=VIRAL
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Please provide the BAM file. There should only be one of a single bam file, 2 fastqs or a single zipped output from a previous run.
p1_fileFormat=BAM;bam
p1_flag=
p1_name=bam.file
p1_numValues=0..1
p1_optional=on
p1_prefix=
p1_prefix_when_specified=--bam   
p1_type=java.io.File
p1_value=
p20_MODE=
p20_TYPE=Floating Point
p20_default_value=3.0
p20_description=Number of standard deviations around the insert size. May need to increase for sequencing runs with high variance after insert size selection step. Default is 3.0
p20_fileFormat=
p20_flag=--AA_insert_sdevs 
p20_name=AA.std.of.insert.size
p20_numValues=0..1
p20_optional=
p20_prefix=--AA_insert_sdevs 
p20_prefix_when_specified=--AA_insert_sdevs 
p20_type=java.lang.Float
p20_value=
p21_MODE=
p21_TYPE=TEXT
p21_default_value=No
p21_description=Do not run amplified_intervals.py to identify amplified seeds. Default \= No
p21_fileFormat=
p21_flag=--no_filter 
p21_name=no.filter
p21_numValues=0..1
p21_optional=on
p21_prefix=--no_filter 
p21_prefix_when_specified=--no_filter 
p21_type=java.lang.String
p21_value=No\=No;Yes\=Yes
p22_MODE=
p22_TYPE=TEXT
p22_default_value=No
p22_description=Skip QC on the BAM file. Do not adjust AA insert_sdevs for poor-quality insert size distribution. Default \= No.
p22_fileFormat=
p22_flag=--no_QC 
p22_name=skip.QC
p22_numValues=0..1
p22_optional=on
p22_prefix=--no_QC 
p22_prefix_when_specified=--no_QC 
p22_type=java.lang.String
p22_value=No\=No;Yes\=Yes
p23_MODE=
p23_TYPE=Floating Point
p23_default_value=
p23_description=**NOT RECOMMENDED TO SET unless required** <br> Specify a ploidy estimate of the genome for CNVKit. Not used by AA itself.
p23_fileFormat=
p23_flag=--ploidy 
p23_name=ploidy
p23_numValues=0..1
p23_optional=on
p23_prefix=--ploidy 
p23_prefix_when_specified=--ploidy 
p23_range=0+
p23_type=java.lang.Float
p23_value=
p24_MODE=
p24_TYPE=Floating Point
p24_default_value=
p24_description=**NOT RECOMMENDED TO SET unless required** <br>\nSpecify a tumor purity estimate for CNVKit. Not used by AA itself. Note that specifying low purity may lead to many high copy number seed regions after rescaling is applied consider setting a higher --cn_gain threshold for low purity samples undergoing correction.
p24_fileFormat=
p24_flag=--purity 
p24_name=purity
p24_numValues=0..1
p24_optional=on
p24_prefix=--purity 
p24_prefix_when_specified=--purity 
p24_range=0+
p24_type=java.lang.Float
p24_value=
p25_MODE=IN
p25_TYPE=FILE
p25_default_value=https\://raw.githubusercontent.com/AmpliconSuite/AmpliconSuite-pipeline/refs/heads/master/paalib/sample_metadata_skeleton.json
p25_description=A .json file containing metadata information. Example metadata json\: <a href \= "https\://github.com/AmpliconSuite/AmpliconSuite-pipeline/blob/master/paalib/sample_metadata_skeleton.json"> here </a>
p25_fileFormat=
p25_flag=--metadata 
p25_name=sample_metadata
p25_numValues=0..1
p25_optional=on
p25_prefix=--metadata 
p25_prefix_when_specified=--metadata 
p25_type=java.io.File
p25_value=
p26_MODE=
p26_TYPE=TEXT
p26_default_value=
p26_description=
p26_fileFormat=
p26_flag=--metadata_sample_type
p26_name=sample_type
p26_numValues=0..1
p26_optional=on
p26_prefix=--metadata_sample_type
p26_prefix_when_specified=--metadata_sample_type
p26_type=java.lang.String
p26_value=
p27_MODE=
p27_TYPE=TEXT
p27_default_value=
p27_description=
p27_fileFormat=
p27_flag=--metadata_sample_source 
p27_name=sample_source
p27_numValues=0..1
p27_optional=on
p27_prefix=--metadata_sample_source 
p27_prefix_when_specified=--metadata_sample_source 
p27_type=java.lang.String
p27_value=
p28_MODE=
p28_TYPE=TEXT
p28_default_value=
p28_description=
p28_fileFormat=
p28_flag=--metadata_tissue_of_origin 
p28_name=tissue_of_origin
p28_numValues=0..1
p28_optional=on
p28_prefix=--metadata_tissue_of_origin 
p28_prefix_when_specified=--metadata_tissue_of_origin 
p28_type=java.lang.String
p28_value=
p29_MODE=
p29_TYPE=TEXT
p29_default_value=
p29_description=
p29_fileFormat=
p29_flag=--metadata_sample_description 
p29_name=sample_description
p29_numValues=0..1
p29_optional=on
p29_prefix=--metadata_sample_description 
p29_prefix_when_specified=--metadata_sample_description 
p29_type=java.lang.String
p29_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=First FASTQ file. There should only be one of a single bam file, 2 fastqs or a single zipped output from a previous run.
p2_fileFormat=.fastq.gz
p2_flag=
p2_name=fastq.r1
p2_numValues=0..1
p2_optional=on
p2_prefix=
p2_prefix_when_specified=--fastqs   
p2_type=java.io.File
p2_value=
p30_MODE=IN
p30_TYPE=FILE
p30_default_value=
p30_description=Output directly from Amplicon Architect. should be a zipped file, containing AA_results. There should only be one of a single bam file, 2 fastqs or a single zipped output from a previous run. 
p30_fileFormat=.gz;.tar.gz;zip
p30_flag=
p30_name=AA_zipped_output
p30_numValues=0..1
p30_optional=on
p30_prefix=
p30_prefix_when_specified=--AA_zipped_output  
p30_type=java.io.File
p30_value=
p31_MODE=
p31_TYPE=TEXT
p31_default_value=2
p31_description=Minimum number of read-pairs required to support foldback-type SVs
p31_fileFormat=
p31_flag=--foldback_pair_support_min  
p31_name=foldback.pair.support.min
p31_numValues=0..1
p31_optional=on
p31_prefix=--foldback_pair_support_min   
p31_prefix_when_specified=--foldback_pair_support_min   
p31_type=java.lang.String
p31_value=
p32_MODE=
p32_TYPE=TEXT
p32_default_value=
p32_description=Upload to ampliconrepository.org, appending to the specified project
p32_fileFormat=
p32_flag=--upload  
p32_name=upload.to.amplicon.repository
p32_numValues=0..1
p32_optional=on
p32_prefix=--upload   
p32_prefix_when_specified=
p32_type=java.lang.String
p32_value=--upload\=Yes;\=No upload
p33_MODE=
p33_TYPE=TEXT
p33_default_value=
p33_description=Username or email used for your ampliconrepository.org account
p33_fileFormat=
p33_flag=
p33_name=amplicon.repository.username
p33_numValues=0..1
p33_optional=on
p33_prefix=
p33_prefix_when_specified=--username     
p33_type=java.lang.String
p33_value=
p34_MODE=
p34_TYPE=TEXT
p34_default_value=
p34_description=Project uuid on ampliconrepository.org, found under the key icon on the project page for project owners.
p34_fileFormat=
p34_flag=
p34_name=project.id
p34_numValues=0..1
p34_optional=on
p34_prefix=
p34_prefix_when_specified=--project_uuid       
p34_type=java.lang.String
p34_value=
p35_MODE=
p35_TYPE=TEXT
p35_default_value=prod
p35_description=Developer only argument for which server to upload to. Allowed calues are prod, dev and local
p35_fileFormat=
p35_flag=
p35_name=upload.server
p35_numValues=1..1
p35_optional=
p35_prefix=
p35_prefix_when_specified=--upload_server   
p35_type=java.lang.String
p35_value=prod;dev;local
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=Second FASTQ file. There should only be one of a single bam file, 2 fastqs or a single zipped output from a previous run.
p3_fileFormat=.fastq.gz
p3_flag=
p3_name=fastq.r2
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=
p4_description=Name of the sample being run. Also used as the output prefix.
p4_fileFormat=
p4_flag=-s
p4_name=Sample.Name
p4_numValues=1..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=Yes
p5_description=Would you like to run AA at the end? Will return AA results at the end if Yes. If no, will return files necessary to input to AA. Default to "Yes", user can select "No".
p5_fileFormat=
p5_flag=--runaa
p5_name=RUN.AA
p5_numValues=0..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=Yes\=Yes;No\=No
p6_MODE=
p6_TYPE=TEXT
p6_default_value=Yes
p6_description=Whether or not to run Amplicon Classifier. Default to "Yes", user can select "No".
p6_fileFormat=
p6_flag=--ac
p6_name=RUN.AC
p6_numValues=0..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=Yes\=Yes;No\=No
p7_MODE=
p7_TYPE=TEXT
p7_default_value=GRCh38
p7_description=Reference genome. Please use drop down to select. 
p7_fileFormat=
p7_flag=--ref 
p7_name=reference
p7_numValues=0..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=hg19\=hg19;GRCh37\=GRCh37;GRCh38\=GRCh38;mm10\=mm10;GRCh38_viral\=GRCh38_viral
p8_MODE=
p8_TYPE=TEXT
p8_default_value=cbs
p8_description=Segmentation method for CNVKit (if used), defaults to CNVKit default segmentation method (cbs). Use drop down menu to select. 
p8_fileFormat=
p8_flag=--cnvkit_segmentation 
p8_name=cnvkit.segmentation
p8_numValues=0..1
p8_optional=on
p8_prefix=--cnvkit_segmentation 
p8_prefix_when_specified=--cnvkit_segmentation 
p8_type=java.lang.String
p8_value=cbs\=cbs;haar\=haar;hmm\=hmm;hmm-tumor\=hmm-tumor;hmm-germline\=hmm-germline;none\=none
p9_MODE=
p9_TYPE=TEXT
p9_default_value=
p9_description=Project key on ampliconrepository.org, found under the key icon on the project page for project owners.
p9_fileFormat=
p9_flag=
p9_name=project.key
p9_numValues=0..1
p9_optional=on
p9_prefix=
p9_prefix_when_specified=--project_key       
p9_type=java.lang.String
p9_value=
privacy=public
publicationDate=12/05/2025 12\:49 
quality=production
src.repo=https\://github.com/genepattern/AmpliconSuite
taskDoc=
taskType=ecdna
userid=edwin5588
version=Changed cnvkit-segmentation default to cbs and increased default job memory
