# ARACNE  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00090:2
#Tue Feb 10 19:11:35 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00090\:2
author=Marc-Danie Nazaire, gp-help@broad.mit.edu, Broad Institute
commandLine=<java> <java_flags> -cp <libdir>aracne-java.jar<path.separator><libdir>aracne-main.jar<path.separator><libdir>commons-cli.jar<path.separator><libdir>commons-logging-1.0.3.jar<path.separator><libdir>workbook-0.9.jar<path.separator><libdir>log4j-1.2.8.jar<path.separator><libdir>collections-generic-4.0.jar<path.separator><libdir>commons-math-1.0.jar<path.separator><libdir>gp-modules.jar org.genepattern.modules.aracne.ARACNE -i <dataset.file> -o <output.file> -h <hub.gene> -s <hub.genes.file> -l <transcription.factor.file> -k <kernel.width> -t <mi.threshold> -p <p.value> -e <dpi.tolerance> -f <mean.filter> <cv.filter>
description=Runs the ARACNE algorithm for reverse engineering cellular networks
language=Java
name=ARACNE
os=any
p10_default_value=0
p10_description=Filter out non-informative genes whose coefficient of variance is smaller than cv filter
p10_name=cv.filter
p10_optional=on
p10_prefix_when_specified=
p10_type=java.lang.Float
p10_value=
p11_default_value=<dataset.file_basename>.output.adj
p11_description=Output file name
p11_name=output.file
p11_optional=on
p11_prefix_when_specified=
p11_type=java.lang.String
p11_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Dataset file - .res, .gct
p1_fileFormat=gct;res
p1_name=dataset.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=
p2_description=The name of a gene whose network interactions you want to reconstruct
p2_name=hub.gene
p2_optional=on
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=A file containing a list of hub genes with one gene per line - .txt
p3_fileFormat=txt
p3_name=hub.genes.file
p3_optional=on
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_MODE=IN
p4_TYPE=FILE
p4_default_value=
p4_description=A file containing a list of genes with one gene per line that encode transcription factors - .txt
p4_fileFormat=txt
p4_name=transcription.factor.file
p4_optional=on
p4_prefix_when_specified=
p4_type=java.io.File
p4_value=
p5_default_value=
p5_description=The kernel width (or window width) of the Gaussian Kernel Estimator
p5_name=kernel.width
p5_optional=on
p5_prefix_when_specified=
p5_type=java.lang.Float
p5_value=
p6_default_value=0
p6_description=Threshold for the mutual information (MI) estimate to be considered statistically significant
p6_name=mi.threshold
p6_optional=on
p6_prefix_when_specified=
p6_type=java.lang.Float
p6_value=
p7_default_value=1
p7_description=Threshold for the p-value of a MI estimate to be considered statistically significant
p7_name=p.value
p7_optional=on
p7_prefix_when_specified=
p7_type=java.lang.Float
p7_value=
p8_default_value=1
p8_description=The percentage of MI estimation considered as sampling error
p8_name=dpi.tolerance
p8_optional=on
p8_prefix_when_specified=
p8_type=java.lang.Float
p8_value=
p9_default_value=0
p9_description=Filter out non-informative genes whose mean expression value is smaller than mean filter
p9_name=mean.filter
p9_optional=on
p9_prefix_when_specified=
p9_type=java.lang.Float
p9_value=
privacy=public
publicationDate=02/26/2008 00\:11 
quality=production
taskType=Pathway Analysis
userid=GenePattern
version=fix problem with processing transcription factor list parameter
