# BedToGtf  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00251:1
#Tue Feb 10 19:11:36 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00251\:1
author=GenePattern
commandLine=<java> <java_flags> -cp <libdir>bedToGtf.jar org.genepattern.gtf.BedToGtf <bed.file> <output.prefix> <output.format>
cpuType=any
description=Converts BED files to GFF or GTF format
fileFormat=gtf;gff
language=Java
name=BedToGtf
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A bed file
p1_fileFormat=bed
p1_name=bed.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=gtf
p2_description=Whether to output a gff file or exon only gtf file. The bed file must contain at least 12 columns in order to generate a gtf file.
p2_fileFormat=
p2_name=output.format
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=gff;gtf
p3_default_value=<bed.file_basename>
p3_description=The prefix for the output file
p3_fileFormat=
p3_name=output.prefix
p3_optional=
p3_prefix_when_specified=
p3_type=java.land.String
p3_value=
privacy=public
publicationDate=03/21/2011 10\:25 
quality=production
taskType=Data Format Conversion
userid=GenePattern
version=
