# BWA.aln  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00254:2.1
#Tue Feb 10 19:11:36 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00254\:2.1
author=Heng Li, Broad Institute
categories=rna-seq
commandLine=perl /opt/genepatt/BWA.aln/src/bwa_aln_wrapper.pl -bwa <BWA_0.7.4>/bwa -libdir <libdir> -w1 <BWA.index> -p1 <reads.pair.1> -p2 <reads.pair.2> -bm <bam.mapping> -n1 <max.edit.distance> -g <max.num.gap> <max.gap.extension> -d <max.deletion.length> -idl <max.indel.length> -l <seed.length> -k <max.seed.edit.distance> -m <mismatch.penalty>  -o1 <gap.open.penalty> -E <gap.extension.penalty> -r <max.best.hits> -n2 <iterative.search> -q <trim.reads> -ilmn <Illumina.1.3.format> -B <barcode.length> -a <max.insert.size> -u <max.occurrences> -x1 <max.alignments> -x2 <max.dc.alignments> -t 4 -o2 <output.prefix>
cpuType=any
description=A fast and accurate short-read alignment tool that allows for mismatches and gaps. Alignments are output in a SAM format file, which provides Phred-scale quality scores for each alignment.  Uses BWA 0.7.4 aln and samse/sampe.
documentationUrl=
fileFormat=sam
job.cpuCount=
job.docker.image=genepattern/bwa_modules\:v0.2
job.memory=
job.walltime=
language=any
name=BWA.aln
os=any
p10_MODE=
p10_TYPE=Integer
p10_default_value=
p10_description=The set of bases determined by this option in the high-quality (left) end of the read is the seed.
p10_fileFormat=
p10_flag=
p10_name=seed.length
p10_numValues=0..1
p10_optional=on
p10_prefix=
p10_prefix_when_specified=
p10_type=java.lang.Integer
p10_value=
p11_MODE=
p11_TYPE=Integer
p11_default_value=
p11_description=Maximum edit distance in the seed; that is, the maximum number of changes required to transform the reference sequence of the seed into the read sequence of the seed.
p11_fileFormat=
p11_flag=
p11_name=max.seed.edit.distance
p11_numValues=0..1
p11_optional=on
p11_prefix=
p11_prefix_when_specified=
p11_type=java.lang.Integer
p11_value=
p12_MODE=
p12_TYPE=Integer
p12_default_value=
p12_description=Mismatch penalty
p12_fileFormat=
p12_flag=
p12_name=mismatch.penalty
p12_numValues=0..1
p12_optional=on
p12_prefix=
p12_prefix_when_specified=
p12_type=java.lang.Integer
p12_value=
p13_MODE=
p13_TYPE=Integer
p13_default_value=
p13_description=Gap open penalty.  The gap open penalty is the score taken away for the initiation of the gap in sequence. To make the match more significant you can try to make the gap penalty larger.
p13_fileFormat=
p13_flag=
p13_name=gap.open.penalty
p13_numValues=0..1
p13_optional=on
p13_prefix=
p13_prefix_when_specified=
p13_type=java.lang.Integer
p13_value=
p14_MODE=
p14_TYPE=Integer
p14_default_value=
p14_description=Gap extension penalty.  The gap extension penalty is added to the standard gap penalty for each base or residue in the gap.  To reduce long gaps, increase the extension gap penalty.
p14_fileFormat=
p14_flag=
p14_name=gap.extension.penalty
p14_numValues=0..1
p14_optional=on
p14_prefix=
p14_prefix_when_specified=
p14_type=java.lang.Integer
p14_value=
p15_MODE=
p15_TYPE=Integer
p15_default_value=
p15_description=Proceed with suboptimal alignments if there are no more than this many equally best hits. This option only affects paired-end mapping.
p15_fileFormat=
p15_flag=
p15_name=max.best.hits
p15_numValues=0..1
p15_optional=on
p15_prefix=
p15_prefix_when_specified=
p15_type=java.lang.Integer
p15_value=
p16_MODE=
p16_TYPE=TEXT
p16_default_value=no
p16_description=Whether to disable iterative search
p16_fileFormat=
p16_flag=
p16_name=iterative.search
p16_numValues=1..1
p16_optional=
p16_prefix=
p16_prefix_when_specified=
p16_type=java.lang.String
p16_value=yes;no
p17_MODE=
p17_TYPE=Integer
p17_default_value=
p17_description=Specifies a quality threshold for read trimming
p17_fileFormat=
p17_flag=
p17_name=trim.reads
p17_numValues=0..1
p17_optional=on
p17_prefix=
p17_prefix_when_specified=
p17_type=java.lang.Integer
p17_value=
p18_MODE=
p18_TYPE=TEXT
p18_default_value=no
p18_description=The input is in the Illumina 1.3+ read format
p18_fileFormat=
p18_flag=
p18_name=Illumina.1.3.format
p18_numValues=1..1
p18_optional=
p18_prefix=
p18_prefix_when_specified=
p18_type=java.lang.String
p18_value=yes;no
p19_MODE=
p19_TYPE=Integer
p19_default_value=
p19_description=Length of barcode starting from the 5' end
p19_fileFormat=
p19_flag=
p19_name=barcode.length
p19_numValues=0..1
p19_optional=on
p19_prefix=
p19_prefix_when_specified=
p19_type=java.lang.Integer
p19_value=
p1_MODE=IN
p1_TYPE=FILE
p1_choiceDir=https\://datasets.genepattern.org/gpftp/module_support_files/bwa/bwa_0.6/index/index_directory.json
p1_default_value=
p1_description=A zip file or directory containing BWA index files.
p1_fileFormat=.zip;DIRECTORY
p1_flag=
p1_name=BWA.index
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p20_MODE=
p20_TYPE=Integer
p20_default_value=
p20_description=Specifies the maximum insert size for a read pair to be considered to be mapped properly
p20_fileFormat=
p20_flag=
p20_name=max.insert.size
p20_numValues=0..1
p20_optional=on
p20_prefix=
p20_prefix_when_specified=
p20_type=java.lang.Integer
p20_value=
p21_MODE=
p21_TYPE=Integer
p21_default_value=
p21_description=Specifies the maximum occurrences of a read for pairing
p21_fileFormat=
p21_flag=
p21_name=max.occurrences
p21_numValues=0..1
p21_optional=on
p21_prefix=
p21_prefix_when_specified=
p21_type=java.lang.Integer
p21_value=
p22_MODE=
p22_TYPE=Integer
p22_default_value=
p22_description=Maximum number of alignments to output in the XA tag for reads paired properly
p22_fileFormat=
p22_flag=
p22_name=max.alignments
p22_numValues=0..1
p22_optional=on
p22_prefix=
p22_prefix_when_specified=
p22_type=java.lang.Integer
p22_value=
p23_MODE=
p23_TYPE=Integer
p23_default_value=
p23_description=Maximum number of alignments to output in the XA tag for disconcordant read pairs (excluding singletons)
p23_fileFormat=
p23_flag=
p23_name=max.dc.alignments
p23_numValues=0..1
p23_optional=on
p23_prefix=
p23_prefix_when_specified=
p23_type=java.lang.Integer
p23_value=
p24_MODE=
p24_TYPE=TEXT
p24_default_value=<reads.pair.1_basename>
p24_description=Prefix to use for output file name
p24_fileFormat=
p24_flag=
p24_name=output.prefix
p24_numValues=1..1
p24_optional=
p24_prefix=
p24_prefix_when_specified=
p24_type=java.lang.String
p24_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Single-end or first paired-end reads file in FASTA, FASTQ, or BAM format.  For paired-end data, this should be the forward ("*_1" or "left") input file.  Note\: the FASTA or FASTQ can be gzipped.
p2_fileFormat=bam;fa;fa.gz;fasta;fasta.gz;fastq;fastq.gz;fn;fq;fq.gz
p2_flag=
p2_name=reads.pair.1
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=The reverse ("*_2" or "right") input file for paired-end reads in FASTA, FASTQ, or BAM format. Note\: the FASTA or FASTQ can be gzipped.
p3_fileFormat=fa;fa.gz;fasta;fasta.gz;fastq;fastq.gz;fn;fq;fq.gz
p3_flag=
p3_name=reads.pair.2
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=
p4_description=Specifies how to map BAM input. This is only required if input file is in BAM format.
p4_fileFormat=
p4_flag=
p4_name=bam.mapping
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=\=Not set...;single;first;second;paired
p5_MODE=
p5_TYPE=TEXT
p5_default_value=
p5_description=The max edit distance. This specifies a threshold of the maximum number of deletions, insertions, and substitutions needed to transform the reference sequence into the read sequence.
p5_fileFormat=
p5_flag=
p5_name=max.edit.distance
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
p6_MODE=
p6_TYPE=Integer
p6_default_value=
p6_description=Maximum number of gap opens. This specifies a threshold of the maximum number of gaps that can be initiated to match a given read to the reference.
p6_fileFormat=
p6_flag=
p6_name=max.num.gap
p6_numValues=0..1
p6_optional=on
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.Integer
p6_value=
p7_MODE=
p7_TYPE=Integer
p7_default_value=
p7_description=Maximum number of gap extensions. This specifies a threshold of the maximum number of bases by which gaps in a read can be extended.
p7_fileFormat=
p7_flag=-e\=
p7_name=max.gap.extension
p7_numValues=0..1
p7_optional=on
p7_prefix=-e\=
p7_prefix_when_specified=-e\=
p7_type=java.lang.Integer
p7_value=
p8_MODE=
p8_TYPE=Integer
p8_default_value=
p8_description=Disallow a long deletion within this many bp of the 3' end.
p8_fileFormat=
p8_flag=
p8_name=max.deletion.length
p8_numValues=0..1
p8_optional=on
p8_prefix=
p8_prefix_when_specified=
p8_type=java.lang.Integer
p8_value=
p9_MODE=
p9_TYPE=Integer
p9_default_value=
p9_description=Disallow an indel within this many bp of the ends
p9_fileFormat=
p9_flag=
p9_name=max.indel.length
p9_numValues=0..1
p9_optional=on
p9_prefix=
p9_prefix_when_specified=
p9_type=java.lang.Integer
p9_value=
pipelineModel=
privacy=public
publicationDate=02/22/2023 12\:44 
quality=production
requiredPatchLSIDs=urn\:lsid\:broadinstitute.org\:plugin\:Ant_1.8\:1,urn\:lsid\:broadinstitute.org\:plugin\:BWA_0_7_4\:1.2
requiredPatchURLs=http\://www.broadinstitute.org/webservices/gpModuleRepository/download/prod/patch/?file\=/Ant_1_8/broadinstitute.org\:plugin/Ant_1.8/1/Ant_1_8.zip,http\://www.broadinstitute.org/webservices/gpModuleRepository/download/dev/patch/?file\=/BWA_0_7_4/broadinstitute.org\:plugin/BWA_0_7_4/1.2/BWA_0_7_4.zip
serializedModel=
src.repo=
taskDoc=doc.html
taskType=rna-seq
userid=edwin5588
version=Updated BWA.Index drop down menu to new BWA module support files location at datasets.genepattern.org (Amazon S3). and specify docker image, to production
