# BWA.indexer  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00253:1.10
#Tue Feb 10 19:11:37 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00253\:1.10
author=Heng Li, Broad Institute
categories=rna-seq
commandLine=perl /opt/genepatt/BWA.indexer/src/bwa_index_wrapper.pl -bwa <BWA_0.7.4>/bwa -libdir <libdir> -f <fasta.file> -a <algorithm> -o <output.prefix>
cpuType=any
description=Creates a BWT index from a sequence FASTA file for use with the BWA 0.7.4 aligners.
documentationUrl=
fileFormat=zip
job.cpuCount=
job.docker.image=genepattern/bwa_modules\:v0.2
job.memory=
job.walltime=
language=any
name=BWA.indexer
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A sequence fasta file
p1_fileFormat=fa;fasta
p1_flag=
p1_name=fasta.file
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=
p2_description=The algorithm to use for constructing the BWT index
p2_fileFormat=
p2_flag=
p2_name=algorithm
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=is;bwtsw
p3_MODE=
p3_TYPE=TEXT
p3_default_value=<fasta.file_basename>
p3_description=A prefix for the output file name.
p3_fileFormat=
p3_flag=
p3_name=output.prefix
p3_numValues=1..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
pipelineModel=
privacy=public
publicationDate=02/22/2023 12\:58 
quality=production
requiredPatchLSIDs=urn\:lsid\:broadinstitute.org\:plugin\:Ant_1.8\:1,urn\:lsid\:broadinstitute.org\:plugin\:BWA_0_7_4\:1.2
requiredPatchURLs=http\://www.broadinstitute.org/webservices/gpModuleRepository/download/prod/patch/?file\=/Ant_1_8/broadinstitute.org\:plugin/Ant_1.8/1/Ant_1_8.zip,http\://www.broadinstitute.org/webservices/gpModuleRepository/download/dev/patch/?file\=/BWA_0_7_4/broadinstitute.org\:plugin/BWA_0_7_4/1.2/BWA_0_7_4.zip
serializedModel=
src.repo=
taskDoc=doc.html
taskType=rna-seq
userid=edwin5588
version=updated dockerfile and commandline to run script at dockerfile location, to production
