# BWA.bwasw  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00256:1.17
#Tue Feb 10 19:11:36 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00256\:1.17
author=Heng Li, Broad Institute
categories=rna-seq
commandLine=perl /opt/genepatt/BWA.bwasw/src/bwa_bwasw_wrapper.pl -bwa <BWA_0.7.4>/bwa -libdir <libdir> -w1 <BWA.index> -p <read.file> -m <mate.read.file> -a <match.score> -b <mismatch.penalty> -q <gap.open.penalty> -r <gap.extension.penalty> -w <band.width> -t2 <min.score.threshold> -c <threshold.coefficient> -z <z.best.heuristics> -s <max.sa.interval.size> -n <min.num.seeds> -t1 <num.threads> -o <output.prefix>
cpuType=any
description=Aligns long sequences (>200 bp) to a sequence database using BWA 0.7.4 bwasw.
documentationUrl=
fileFormat=sam
job.cpuCount=
job.docker.image=genepattern/bwa_modules\:v0.2
job.memory=
job.walltime=
language=any
name=BWA.bwasw
os=any
p10_MODE=
p10_TYPE=Floating Point
p10_default_value=
p10_description=Coefficient for threshold adjustment according to query length
p10_fileFormat=
p10_flag=
p10_name=threshold.coefficient
p10_numValues=0..1
p10_optional=on
p10_prefix=
p10_prefix_when_specified=
p10_type=java.lang.Float
p10_value=
p11_MODE=
p11_TYPE=Integer
p11_default_value=
p11_description=Z-best heuristics. Specifying a higher number increases accuracy at the cost of speed
p11_fileFormat=
p11_flag=
p11_name=z.best.heuristics
p11_numValues=0..1
p11_optional=on
p11_prefix=
p11_prefix_when_specified=
p11_type=java.lang.Integer
p11_value=
p12_MODE=
p12_TYPE=Integer
p12_default_value=
p12_description=Maximum SA interval size for initiating a seed. Specifying a higher number increases accuracy at the cost of speed.
p12_fileFormat=
p12_flag=
p12_name=max.sa.interval.size
p12_numValues=0..1
p12_optional=on
p12_prefix=
p12_prefix_when_specified=
p12_type=java.lang.Integer
p12_value=
p13_MODE=
p13_TYPE=Integer
p13_default_value=
p13_description=The minimum number of seeds contained in the best alignment from the forward-forward alignment process that allows the algorithm to skip performing the reverse alignment. BWA.bwasw tends to be faster and more accurate if the alignment is supported by more seeds.
p13_fileFormat=
p13_flag=
p13_name=min.num.seeds
p13_numValues=0..1
p13_optional=on
p13_prefix=
p13_prefix_when_specified=
p13_type=java.lang.Integer
p13_value=
p14_MODE=
p14_TYPE=Integer
p14_default_value=1
p14_description=Number of threads
p14_fileFormat=
p14_flag=
p14_name=num.threads
p14_numValues=0..1
p14_optional=on
p14_prefix=
p14_prefix_when_specified=
p14_type=java.lang.Integer
p14_value=1;4
p15_MODE=
p15_TYPE=TEXT
p15_default_value=<read.file_basename>
p15_description=Prefix to use for the output file name
p15_fileFormat=
p15_flag=
p15_name=output.prefix
p15_numValues=1..1
p15_optional=
p15_prefix=
p15_prefix_when_specified=
p15_type=java.lang.String
p15_value=
p1_MODE=IN
p1_TYPE=FILE
p1_choiceDir=https\://datasets.genepattern.org/gpftp/module_support_files/bwa/bwa_0.6/index/index_directory.json
p1_default_value=
p1_description=A zip file or directory containing BWA index files.
p1_fileFormat=zip
p1_flag=
p1_name=BWA.index
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Single-end or first paired-end reads file in FASTA or FASTQ format.  For paired-end data, this should be the forward ("*_1" or "left") input file.
p2_fileFormat=fa;fasta;fastq;fn;fq
p2_flag=
p2_name=read.file
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=The reverse ("*_2" or "right") reads file for paired-end reads in FASTA or FASTQ format.
p3_fileFormat=fa;fasta;fastq;fn;fq
p3_flag=
p3_name=mate.read.file
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_MODE=
p4_TYPE=Integer
p4_default_value=
p4_description=The score of the match
p4_fileFormat=
p4_flag=
p4_name=match.score
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.Integer
p4_value=
p5_MODE=
p5_TYPE=Integer
p5_default_value=
p5_description=Specifies the mismatch penalty.
p5_fileFormat=
p5_flag=
p5_name=mismatch.penalty
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.Integer
p5_value=
p6_MODE=
p6_TYPE=Integer
p6_default_value=
p6_description=Gap open penalty.  The gap open penalty is the score taken away for the initiation of the gap in sequence. To make the match more significant you can try to make the gap penalty larger.
p6_fileFormat=
p6_flag=
p6_name=gap.open.penalty
p6_numValues=0..1
p6_optional=on
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.Integer
p6_value=
p7_MODE=
p7_TYPE=Integer
p7_default_value=
p7_description=Gap extension penalty.  The gap extension penalty is added to the standard gap penalty for each base or residue in the gap.  To reduce long gaps, increase the extension gap penalty. 
p7_fileFormat=
p7_flag=
p7_name=gap.extension.penalty
p7_numValues=0..1
p7_optional=on
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.Integer
p7_value=
p8_MODE=
p8_TYPE=Integer
p8_default_value=
p8_description=band width in the banded alignment
p8_fileFormat=
p8_flag=
p8_name=band.width
p8_numValues=0..1
p8_optional=on
p8_prefix=
p8_prefix_when_specified=
p8_type=java.lang.Integer
p8_value=
p9_MODE=
p9_TYPE=Integer
p9_default_value=
p9_description=Minimum score threshold divided by the match score
p9_fileFormat=
p9_flag=
p9_name=min.score.threshold
p9_numValues=0..1
p9_optional=on
p9_prefix=
p9_prefix_when_specified=
p9_type=java.lang.Integer
p9_value=
pipelineModel=
privacy=public
publicationDate=02/22/2023 12\:45 
quality=production
requiredPatchLSIDs=urn\:lsid\:broadinstitute.org\:plugin\:Ant_1.8\:1,urn\:lsid\:broadinstitute.org\:plugin\:BWA_0_7_4\:1.2
requiredPatchURLs=http\://www.broadinstitute.org/webservices/gpModuleRepository/download/prod/patch/?file\=/Ant_1_8/broadinstitute.org\:plugin/Ant_1.8/1/Ant_1_8.zip,http\://www.broadinstitute.org/webservices/gpModuleRepository/download/dev/patch/?file\=/BWA_0_7_4/broadinstitute.org\:plugin/BWA_0_7_4/1.2/BWA_0_7_4.zip
serializedModel=
src.repo=
taskDoc=doc.html
taskType=rna-seq
userid=edwin5588
version=Update BWA.index to new index location (datasets.genepattern.org) and update dockerfile, to production
