# CellFie  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00405:5
#Tue Feb 10 19:11:37 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00405\:5
author=Benjamin Kellman;UC San Diego
categories=metabolomics
commandLine=sh /CellFie/matlab_compiled/execCellfie/for_redistribution_files_only/run_execCellfie.sh /usr/local/MATLAB/MATLAB_Runtime/v94 <Data> <Sample.Number> <Reference.Model> <Thresholding.Approach> <Percentile.Or.Value> <Global.Cutoff> <Local.Threshold.Type> <Local.Lower.Bound> <Local.Upper.Bound> ./
cpuType=any
description=CellFie\: Cellular Functions InferencE - An alternative approach to capture the breadth of cellular functions by performing a functional analysis of existing biological networks. Please refer to the documentation for details about the procedure.
documentationUrl=
fileFormat=csv;mat
job.docker.image=genepatterndev/cellfie\:v0.7.0
language=any
name=CellFie
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The gene expression matrix can be provided in a <b>.mat</b> or <b>.csv</b> format.\n<p>\nFor <b>.mat</b> files, you need to provide a structure variable (named e.g. "data")\ncontaining a cell field named "genes" with NCBI Entrez gene IDs (one gene per cell)\nand a double field named "value" containing a matrix with gene expression values\nfor each of the samples you want to evaluate (i.e. with rows corresponding to genes\nand columns corresponding to samples). See available example\n<a href\=https\://github.com/LewisLabUCSD/CellFie/blob/master/test/suite/dataTest.mat>\n    dataTest.mat</a>.\n<p>\nFor <b>.csv</b> files, you need to provide an expression matrix with rows corresponding\nto genes and columns corresponding to samples. The first column is the list of genes\nwith NCBI Entrez gene IDs and the first header row should start with "genes" and\nbe followed by the name of each sample present in your dataset. See the available\n<a href\=https\://github.com/LewisLabUCSD/CellFie/blob/master/test/suite/dataTest.csv>\n    dataTest.csv</a>\nThe list of genes and associated NCBI Entrez IDs present in each reference model\ncan be downloaded\n<a href\=https\://github.com/LewisLabUCSD/CellFie/raw/master/docs/NCBI_Entrez_gene_ID_models.xlsx>\n    here</a>.
p1_fileFormat=csv
p1_flag=
p1_name=Data
p1_numValues=0..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=Integer
p2_default_value=
p2_description=\ The number of samples in the input file to analyze
p2_fileFormat=
p2_flag=
p2_name=Sample.Number
p2_numValues=0..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.Integer
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=MT_recon_2_2_entrez.mat
p3_description=\ Name of the reference model to use to compute metabolic task scores
p3_fileFormat=
p3_flag=
p3_name=Reference.Model
p3_numValues=0..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=MT_recon_2_2_entrez.mat\=Human_recon_2_2;MT_iCHOv1_final.mat\=CHO_iCHOv1;MT_iHsa.mat\=Human_iHsa;MT_iMM1415.mat\=Mouse_iMM1415;MT_iRno.mat\=Rat_iRn
p4_MODE=
p4_TYPE=TEXT
p4_default_value=local
p4_description=Two types of thresholding approaches can be used; either GLOBAL (the threshold is the same for all the genes)  or LOCAL (the threshold is gene specific)
p4_fileFormat=
p4_flag=
p4_name=Thresholding.Approach
p4_numValues=0..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=local\=local;global\=global
p5_MODE=
p5_TYPE=TEXT
p5_default_value=percentile
p5_description=The threshold can be defined using a value introduced by the user (VALUE) or based on a percentile of the expression value distribution (PERCENTILE)
p5_fileFormat=
p5_flag=
p5_name=Percentile.Or.Value
p5_numValues=0..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=value\=value;percentile\=percentile
p6_MODE=
p6_TYPE=Integer
p6_default_value=0
p6_description=If you selected the GLOBAL thresholding approach, cutoff value or percentile defining the gene activity threshold
p6_fileFormat=
p6_flag=
p6_name=Global.Cutoff
p6_numValues=0..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.Integer
p6_value=
p7_MODE=
p7_TYPE=TEXT
p7_default_value=minmaxmean
p7_description=If you selected the LOCAL thresholding approach, you can also define the type of local approach;  either MEAN (i.e., the threshold for a gene is defined as the mean expression value of this gene across all the samples, tissues, or conditions) or MINMAXMEAN (i.e., the threshold for a gene is determined by the mean of expression values observed for that gene among all the samples, tissues, or conditions BUT the threshold \:(i) must be higher or equal to a lower bound and (ii) must be lower or equal to an upper bound)
p7_fileFormat=
p7_flag=
p7_name=Local.Threshold.Type
p7_numValues=0..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=mean\=mean;minmaxmean\=minmaxmean
p8_MODE=
p8_TYPE=Integer
p8_default_value=25
p8_description=If you selected the type MINMAXMEAN for the LOCAL thresholding approach, lower bound to define which gene are always inactive (either a value or a percentile)
p8_fileFormat=
p8_flag=
p8_name=Local.Lower.Bound
p8_numValues=0..1
p8_optional=
p8_prefix=
p8_prefix_when_specified=
p8_type=java.lang.Integer
p8_value=
p9_MODE=
p9_TYPE=TEXT
p9_default_value=75
p9_description=If you selected the type MINMAXMEAN for the LOCAL thresholding approach, upper bound  to define which gene are always inactive (either a value or a percentile)
p9_fileFormat=
p9_flag=
p9_name=Local.Upper.Bound
p9_numValues=0..1
p9_optional=
p9_prefix=
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=
privacy=public
publicationDate=06/29/2021 18\:29 
quality=production
src.repo=https\://github.com/LewisLabUCSD/CellFie
taskDoc=doc.html
taskType=metabolomics
userid=atwenzel2
version=update to reaction models
