# ClsFileCreator  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.visualizer:00261:4.1
#Tue Feb 10 19:11:37 UTC 2026
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.visualizer\:00261\:4.1
author=Marc-Danie Nazaire (Broad Institute)
categories=Preprocess & Utilities
commandLine=clsfilecreator.html ? <input.file>
cpuType=any
description=A tool to create a class label (CLS) file.
fileFormat=
language=Java
name=ClsFileCreator
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A dataset - .gct
p1_fileFormat=gct
p1_name=input.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
pipelineModel=
privacy=public
publicationDate=07/15/2021 15\:07 
quality=preproduction
repo.src=https\://github.com/genepattern/ClsFileCreator.git
requiredPatchLSIDs=urn\:lsid\:broadinstitute.org\:plugin\:GenePattern_3_9_3\:1,
requiredPatchURLs=http\://www.broadinstitute.org/webservices/gpModuleRepository/download/prod/patch/?file\=/GenePattern_3_9_3/broadinstitute.org\:plugin/GenePattern_3_9_3/1/GenePattern_3_9_3.zip
serializedModel=
taskDoc=doc.html
taskType=javascript
userid=GenePattern (gp-help@broadinstitute.org)
version=S3 file fix
