# CNToXCN  urn:lsid:broadinstitute.org:cancer.genome.analysis:00057:1
#Tue Feb 10 19:11:37 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broadinstitute.org\:cancer.genome.analysis\:00057\:1
author=gp-help@broad.mit.edu, Broad Institute
commandLine=<perl> <libdir>cn2xcn.pl <cn.file> <output.prefix>.nocalls.xcn
cpuType=any
description=
fileFormat=xcn
language=perl
name=CNToXCN
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input CN file (a tab-delimited file format that contains SNP copy numbers)
p1_fileFormat=cn
p1_name=cn.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<cn.file_basename>
p2_description=Prefix for the output XCN file name
p2_fileFormat=
p2_name=output.prefix
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
privacy=public
publicationDate=01/13/2012 14\:06 
quality=production
taskType=SNP Analysis
userid=GenePattern
version=
