# CollapseDataset  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00134:2.2.0
#Tue Feb 10 19:11:38 UTC 2026
JVMLevel=11
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00134\:2.2.0
author=Aravind Subramanian, Josh Gould, David Eby; Broad Institute
categories=gsea
commandLine=/opt/gsea/GSEA_4.3.2/gsea-cli.sh CollapseDataset -res <dataset.file> -chip <chip.platform> -mode <collapse.mode> -dev_mode <dev.mode> -include_only_symbols <omit.features.with.no.symbol.match> <output.file.name> -run_as_genepattern true
cpuType=any
description=Collapses expression values from multiple input ids that map to a single target gene to a single value on a per-sample basis
fileFormat=
job.docker.image=genepattern/gsea_4.3.2\:0.1
language=Java
name=CollapseDataset
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Dataset file - .res, .gct
p1_fileFormat=gct;res
p1_flag=
p1_name=dataset.file
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_choiceDir=https\://www.gsea-msigdb.org/gsea/msigdb/gp_modules_chip.json
p2_default_value=
p2_description=DNA Chip (array) annotation file from GSEA website.  Upload your own chip file if the one corresponding to your DNA Microarray platform is not listed in the drop-down menu.  A chip file is only required if collapse dataset is set to true.
p2_fileFormat=chip
p2_flag=
p2_name=chip.platform
p2_optional=on
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=Max_probe
p3_description=Collapsing mode.  It is also possible to remap symbols from one namespace to another without collapsing (an error will occur if multiple source genes map to a single destination gene)
p3_fileFormat=
p3_flag=
p3_name=collapse.mode
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=Max_probe;Median_of_probes;Mean_of_probes;Sum_of_probes;Abs_max_of_probes;Remap_only
p4_default_value=
p4_description=The output file name
p4_name=output.file.name
p4_optional=true
p4_prefix_when_specified=-out_file 
p4_type=java.lang.String
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=true
p5_description=If there is no known gene symbol match for a probe set, omit it from the collapsed dataset
p5_fileFormat=
p5_flag=
p5_name=omit.features.with.no.symbol.match
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=false;true
p6_MODE=
p6_TYPE=TEXT
p6_default_value=false
p6_description=Enable developer mode.
p6_fileFormat=
p6_flag=
p6_name=dev.mode
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=false;true
pipelineModel=
privacy=public
publicationDate=10/03/2022 15\:31 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskDoc=doc.html
taskType=Preprocess & Utilities
userid=eby@broadinstitute.org
version=10/03/2022 \: Updated to Human MSigDB v2022.1.Hs and Mouse MSigDB 2022.1.Mm.
