# ComBat_Seq  urn:lsid:genepattern.org:module.analysis:00430:6.1
#Tue Feb 10 19:11:38 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00430\:6.1
author=Edwin Huang;Mesirov Lab
categories=batch correction
commandLine=Rscript /opt/genepatt/src/ComBat-seq_wrapper.R --input_matrix <input.matrix>  --input_class <batch.information> --file_name <output.prefix> --shrink <shrink> --shrink_disp <shrink_disp> --output_type <output.type>  <gene.subset.n> <covariance.matrix> <covariates> 
cpuType=any
description=ComBat_Seq module. A Batch effect adjustment tool for bulk RNA-seq count data. Improvement upon ComBat,  and uses a negative binomial regression to model batch effects. ComBat-seq takes untransformed, raw count matrix as input. Provides adjusted data which preserves the integer nature of counts, so that the adjusted data are compatible with the assumptions of state-of-the-art differential expression software (e.g. edgeR, DESeq2, which request untransformed count data)\nOriginal Documentation\: https\://github.com/zhangyuqing/ComBat-seq \nCredits go to Zhang et al, https\://doi.org/10.1093/nargab/lqaa078
documentationUrl=https\://github.com/genepattern/ComBat_Seq/blob/develop/README.md
fileFormat=
job.cpuCount=1
job.docker.image=genepattern/combat_seq\:v1.3
job.memory=2
job.walltime=00\:30\:00
language=any
name=ComBat_Seq
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The input counts matrix. Can be a GCT or a .tsv (tab separated value) file. Rows should be genes, column should be samples, and the value are counts. File format documentation for GCT files\: https\://www.genepattern.org/file-formats-guide
p1_fileFormat=.csv;.tsv;gct
p1_flag=
p1_name=input.matrix
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=File containing batch and group (optional) information. Example of the file is here\: https\://github.com/genepattern/ComBat_Seq/blob/develop/README.md. Can be a CLS file containing batch information (CLS documentation here\: https\://www.genepattern.org/file-formats-guide)\n\nFirst row contains sample information (sample names).\nSecond row contains batch information of each sample (a batch number for each sample).\nThird row contains group information of each sample (biological variable for each sample).\n\nhttps\://www.genepattern.org/file-formats-guide
p2_fileFormat=.csv;.tsv;cls
p2_flag=
p2_name=batch.information
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=
p3_description=Row names for covariates to use for this run of ComBat Seq. Separate by commas. 
p3_fileFormat=
p3_flag=--cov
p3_name=covariates
p3_numValues=0..1
p3_optional=on
p3_prefix=--cov
p3_prefix_when_specified=--cov
p3_type=java.lang.String
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=<input.matrix_basename>_batch_corrected
p4_description=Prefix for output name.
p4_fileFormat=
p4_flag=
p4_name=output.prefix
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=GCT
p5_description=Filetype to output. Can be GCT, TSV, or both
p5_fileFormat=
p5_flag=
p5_name=output.type
p5_numValues=0..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=GCT\=GCT;TSV\=TSV;both\=both
p6_MODE=
p6_TYPE=TEXT
p6_default_value=No
p6_description=Whether to apply empirical Bayes estimation on parameters. 
p6_fileFormat=
p6_flag=
p6_name=shrink
p6_numValues=0..1
p6_optional=on
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=Yes\=Yes;No\=No
p7_MODE=
p7_TYPE=TEXT
p7_default_value=No
p7_description=Whether to apply empirical Bayes estimation on dispersion.
p7_fileFormat=
p7_flag=
p7_name=shrink_disp
p7_numValues=0..1
p7_optional=on
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=Yes\=Yes;No\=No
p8_MODE=
p8_TYPE=TEXT
p8_default_value=
p8_description=Number of genes to use in empirical Bayes estimation, only useful when shrink \= Yes
p8_fileFormat=
p8_flag=--gene_n
p8_name=gene.subset.n
p8_numValues=0..1
p8_optional=on
p8_prefix=--gene_n
p8_prefix_when_specified=--gene_n
p8_type=java.lang.String
p8_value=
p9_MODE=IN
p9_TYPE=FILE
p9_default_value=
p9_description=If you wish to specify multiple biological variables. Model matrix for other covariates to include in the linear model besides batch and condition of interest. 
p9_fileFormat=
p9_flag=--cov_mat
p9_name=covariance.matrix
p9_numValues=0..1
p9_optional=on
p9_prefix=--cov_mat
p9_prefix_when_specified=--cov_mat
p9_type=java.io.File
p9_value=
privacy=public
publicationDate=01/05/2024 16\:48 
quality=preproduction
src.repo=https\://github.com/genepattern/ComBat-Seq
taskDoc=
taskType=batch correction
userid=edwin5588
version=Added batch correction tag
