# ComBat  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00127:3.6
#Tue Feb 10 19:11:38 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00127\:3.6
author=Marc-Danie Nazaire, Broad Institute
categories=batch correction
commandLine=<R2.7> <libdir>gp.combat.R parseCmdLine -i<input.file> -s<sample.info.file> -c<covariate.columns> <absent.calls.filter> -p<create.prior.plots> -m<prior.method> -o<output.file> -l<libdir>
cpuType=any
description=Batch Correction - Not intended for use with single-cell RNA-seq data.
documentationUrl=
fileFormat=gct;res
job.cpuCount=
job.docker.image=
job.memory=
job.walltime=
language=any
name=ComBat
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=input file - .res, .gct (Note that this module is not intended for use with single-cell RNA-seq data)
p1_fileFormat=gct;odf;res
p1_flag=
p1_name=input.file
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2\#Wed=Jun 25 11\:53\:08 EDT 2008
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=A file containing information about the samples. The sample info file must contain the three columns\: Array, Sample, and Batch. Any additional columns are used as covariates in the analysis.(.txt file)
p2_fileFormat=txt
p2_flag=
p2_name=sample.info.file
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=all
p3_description=The covariate columns to use in analysis. This is either set to all, none, or a list specifying one or more covariate columns from sample info file to use in the analysis (i.e, 4, 5, 7, ...). If this is set to 'all' then all the covariate columns are used. If this is set to 'none' then none of the covariate columns are used.
p3_fileFormat=
p3_flag=
p3_name=covariate.columns
p3_numValues=1..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=
p4_description=The filter to apply to genes with absent calls (a value between 0 and 1). Filters genes with absent calls in 1-(absent calls filter) of the samples. Ignored if input file is not a .res file.\t
p4_fileFormat=
p4_flag=-f
p4_name=absent.calls.filter
p4_numValues=0..1
p4_optional=on
p4_prefix=-f
p4_prefix_when_specified=-f
p4_type=java.lang.String
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=F
p5_description=[Temporary deactivated\! currently the only accepted value accepted by this parameter is "no"]Whether to generate prior probability distribution plots. Ignored if non-parametric method is used.
p5_fileFormat=
p5_flag=
p5_name=create.prior.plots
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=F\=no;F\=no
p6_MODE=
p6_TYPE=TEXT
p6_default_value=T
p6_description=Empirical Bayes priors distribution estimation method to use. Either a parametric or non-parametric method can be applied. If unsure of which method to use try the parametric method first since it is faster.
p6_fileFormat=
p6_flag=
p6_name=prior.method
p6_numValues=0..1
p6_optional=on
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=T\=parametric;F\=non-parametric
p7_MODE=
p7_TYPE=TEXT
p7_default_value=<input.file_basename>.combat.<input.file_extension>
p7_description=Name of batch adjusted output file
p7_fileFormat=
p7_flag=
p7_name=output.file
p7_numValues=1..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
privacy=public
publicationDate=01/05/2024 16\:09 
quality=production
requiredPatchLSIDs=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.server.patch\:00009\:1
requiredPatchURLs=http\://www.broad.mit.edu/webservices/gpModuleRepository/download/prod/patch/?file\=/R_2_5_Check/broad.mit.edu\:cancer.software.genepattern.server.patch/00009/1/R2_5.zip
src.repo=
taskDoc=doc.html
taskType=batch correction
userid=GenePattern
version=new batch correction tag
