# ComparativeMarkerSelection  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00044:11
#Tue Feb 10 19:11:38 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00044\:11
author=Joshua Gould, Gad Getz, Stefano Monti
categories=gene list selection
commandLine=java <java_flags> -Dlibdir\=<libdir> -cp /opt/genepattern/modules/ComparativeMarkerSelection/colt.jar\:/opt/genepattern/modules/ComparativeMarkerSelection/commons-math-1.2.jar\:/opt/genepattern/modules/ComparativeMarkerSelection/gp-modules.jar\:/opt/genepattern/modules/ComparativeMarkerSelection/Jama-1.0.2.jar\:/opt/genepattern/modules/ComparativeMarkerSelection/jsci-core.jar\:/opt/genepattern/modules/ComparativeMarkerSelection/trove.jar org.broadinstitute.marker.MarkerSelection <input.file> <cls.file> <number.of.permutations> <test.direction> <output.filename> <balanced> <complete> no <test.statistic> <random.seed> false <smooth.p.values> -l<log.transformed.data> -m<min.std> -c<confounding.variable.cls.file> -p<phenotype.test>
cpuType=any
description=Identify differentially expressed genes that can discriminate between distinct classes of samples.
documentationUrl=https\://genepattern.github.io/ComparativeMarkerSelection/v11/
fileFormat=Comparative Marker Selection
job.docker.image=genepattern/comparativemarkerselection\:v11
language=any
name=ComparativeMarkerSelection
os=any
p10_MODE=
p10_TYPE=TEXT
p10_default_value=false
p10_description=Whether to perform balanced permutations
p10_fileFormat=
p10_flag=
p10_name=balanced
p10_numValues=1..1
p10_optional=
p10_prefix=
p10_prefix_when_specified=
p10_type=java.lang.String
p10_value=true\=yes;false\=no
p11_MODE=
p11_TYPE=Integer
p11_default_value=779948241
p11_description=The seed of the random number generator used to produce permutations
p11_fileFormat=
p11_flag=
p11_name=random.seed
p11_numValues=1..1
p11_optional=
p11_prefix=
p11_prefix_when_specified=
p11_type=java.lang.Integer
p11_value=
p12_MODE=
p12_TYPE=TEXT
p12_default_value=true
p12_description=Whether to smooth p-values
p12_fileFormat=
p12_flag=
p12_name=smooth.p.values
p12_numValues=1..1
p12_optional=
p12_prefix=
p12_prefix_when_specified=
p12_type=java.lang.String
p12_value=true\=yes;false\=no
p13_MODE=
p13_TYPE=TEXT
p13_default_value=one versus all
p13_description=Tests to perform when cls file has more than two classes (Note\: not fully corrected for multiple hypothesis testing)
p13_fileFormat=
p13_flag=
p13_name=phenotype.test
p13_numValues=0..1
p13_optional=on
p13_prefix=
p13_prefix_when_specified=
p13_type=java.lang.String
p13_value=one versus all;all pairs
p14_MODE=
p14_TYPE=TEXT
p14_default_value=<input.file_basename>.comp.marker.odf
p14_description=The name of the output file
p14_fileFormat=
p14_flag=
p14_name=output.filename
p14_numValues=1..1
p14_optional=
p14_prefix=
p14_prefix_when_specified=
p14_type=java.lang.String
p14_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The input file - .res, .gct. Note that if your data is log transformed, you will need to set the "log transformed data" parameter below to "yes".
p1_fileFormat=gct;res
p1_flag=
p1_name=input.file
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=The class file - .cls
p2_fileFormat=cls
p2_flag=
p2_name=cls.file
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=The class file containing the confounding variable.
p3_fileFormat=cls
p3_flag=
p3_name=confounding.variable.cls.file
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=2
p4_description=The test to perform
p4_fileFormat=
p4_flag=
p4_name=test.direction
p4_numValues=1..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=0\=Class 0;1\=Class 1;2\=2 Sided
p5_MODE=
p5_TYPE=Integer
p5_default_value=0
p5_description=The statistic to use
p5_fileFormat=
p5_flag=
p5_name=test.statistic
p5_numValues=1..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.Integer
p5_value=1\=SNR;0\=T-Test;3\=SNR (median);2\=T-Test (median);4\=T-Test (min std);5\=SNR (min std);6\=SNR (median, min std);7\=T-Test (median, min std);8\=Paired T-Test
p6_MODE=
p6_TYPE=TEXT
p6_default_value=
p6_description=The minimum standard deviation if test statistic includes min std option
p6_fileFormat=
p6_flag=
p6_name=min.std
p6_numValues=0..1
p6_optional=on
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=
p7_MODE=
p7_TYPE=TEXT
p7_default_value=10000
p7_description=The number of permutations to perform (use 0 to calculate asymptotic p-values using the standard independent two-sample t-test)
p7_fileFormat=
p7_flag=
p7_name=number.of.permutations
p7_numValues=1..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
p8_MODE=
p8_TYPE=TEXT
p8_default_value=false
p8_description=Whether the input data has been log transformed
p8_fileFormat=
p8_flag=
p8_name=log.transformed.data
p8_numValues=1..1
p8_optional=
p8_prefix=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=true\=yes;false\=no
p9_MODE=
p9_TYPE=TEXT
p9_default_value=false
p9_description=Whether to perform all possible permutations
p9_fileFormat=
p9_flag=
p9_name=complete
p9_numValues=1..1
p9_optional=
p9_prefix=
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=true\=yes;false\=no
privacy=public
publicationDate=07/22/2021 11\:57 
quality=production
src.repo=https\://github.com/genepattern/ComparativeMarkerSelection/tree/v11
taskDoc=
taskType=gene list selection
userid=bhill@broadinstitute.org
version=Updated to run in its own R 2.5 container - allowing q values to be computed.
