# ConcatenateFilelist  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00283:1
#Tue Feb 10 19:11:39 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00283\:1
author=Peter Carr, Broad Institute
commandLine=<java> <java_flags> -cp <libdir>ConcatenateFilelist.jar<path.separator><libdir>gp-annotations.jar<path.separator><libdir>jopt-simple-3.3.jar org.genepattern.module.concatenatefilelist.ConcatenateFilelist <filelist> <num.header.lines> <output.filename>
cpuType=any
description=Concatenate all of the items in the input filelist into a single large file.
fileFormat=
language=any
name=ConcatenateFilelist
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=a text file containing a list of file paths
p1_fileFormat=
p1_name=filelist
p1_optional=
p1_prefix_when_specified=--filelist\=
p1_type=java.io.File
p1_value=
p2_default_value=
p2_description=specify number of header lines so that they are output only once
p2_fileFormat=
p2_name=num.header.lines
p2_optional=on
p2_prefix_when_specified=--num.header.lines\=
p2_type=java.lang.String
p2_value=
p3_default_value=
p3_description=The name of the output file
p3_fileFormat=
p3_name=output.filename
p3_optional=
p3_prefix_when_specified=--output.filename\=
p3_type=java.lang.String
p3_value=
pipelineModel=
privacy=public
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Preprocess & Utilities
userid=
version=
