# Conos.Preprocess  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00409:3
#Tue Feb 10 19:11:39 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00409\:3
author=Edwin F. Juarez & Anthony Castanza;UCSD -- Mesirov Lab
categories=clustering;singlecell
commandLine=Rscript /module/run_conos_preprocess.R --file_list <file_list> --k <knn> --perplexity <perplexity> --pagoda_odgenes <pagoda_odgenes> --projection_method <projection_method> --ncomps <ncomps> --conos_odgenes <conos_odgenes>
cpuType=any
description=GenePattern Module which implements the preprocessing and PCA steps of Conos
documentationUrl=https\://github.com/genepattern/Conos.Preprocess/blob/develop/docs/v3/index.md
fileFormat=png;rds
job.docker.image=genepattern/conos\:v3
job.memory=4Gb
language=any
name=Conos.Preprocess
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=List of files to load.
p1_fileFormat=rds;txt
p1_flag=--file_list
p1_name=file_list
p1_numValues=0+
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=Integer
p2_default_value=40
p2_description=Pagoda2\: default number of neighbors to use in kNN graph
p2_fileFormat=
p2_flag=--k
p2_name=knn
p2_numValues=0..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.Integer
p2_value=
p3_MODE=
p3_TYPE=Integer
p3_default_value=50
p3_description=Pagoda2\: perplexity to use in generating tSNE and largeVis embeddings (default\=50)
p3_fileFormat=
p3_flag=--perplexity
p3_name=perplexity
p3_numValues=0..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.Integer
p3_value=
p4_MODE=
p4_TYPE=Integer
p4_default_value=3000
p4_description=Pagoda2\: number of top overdispersed genes to use (default\=3e3)
p4_fileFormat=
p4_flag=--pagoda_odgenes
p4_name=pagoda_odgenes
p4_numValues=0..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.Integer
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=PCA
p5_description=Whether to perform PCA or CPCA
p5_fileFormat=
p5_flag=--projection_method
p5_name=projection_method
p5_numValues=0..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=PCA\=PCA;CPCA\=CPCA
p6_MODE=
p6_TYPE=Integer
p6_default_value=50
p6_description=How many PCA components to use (?) (default\=50)
p6_fileFormat=
p6_flag=--ncomps
p6_name=ncomps
p6_numValues=0..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.Integer
p6_value=
p7_MODE=
p7_TYPE=TEXT
p7_default_value=1000
p7_description=Pagoda2\: number of top overdispersed genes to use (default\=1e3)
p7_fileFormat=
p7_flag=--conos_odgenes
p7_name=conos_odgenes
p7_numValues=0..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
privacy=public
publicationDate=05/04/2022 15\:32 
quality=production
src.repo=
taskDoc=
taskType=clustering
userid=edjuaro
version=updated accepted file formats for input file
