# ConsensusClustering  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00030:7.2
#Tue Feb 10 19:11:39 UTC 2026
JVMLevel=2.5.0
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00030\:7.2
author=Stefano Monti, Broad Institute
commandLine=<run-with-env> -u Java -u R-2.5 java <java_flags> -cp <libdir>Acme.jar<path.separator><libdir>gp-modules.jar<path.separator><libdir>broad-cg.jar<path.separator><libdir>geneweaver.jar<path.separator><libdir>RunSomAlg.jar<path.separator><libdir>jaxb-rt-1.0-ea.jar<path.separator><libdir>file_support.jar<path.separator><libdir>archiver.jar<path.separator><libdir>trove.jar<path.separator><libdir>gp-common.jar<path.separator><libdir>Jama-1.0.2.jar<path.separator><libdir>cc.jar edu.mit.broad.modules.cc.CC <input.filename> <kmax> <resampling.iterations> <normalize.type> -N <normalization.iterations> -@<seed.value> -S <resample> -t <clustering.algorithm> <cluster.by> -D <distance.measure> -L <merge.type> -i <descent.iterations> -o <output.stub> -s -d <create.heat.map> -z <heat.map.size> -l0 -v0 -b<libdir>
cpuType=any
description=Resampling-based clustering method 
fileFormat=gct;gif;clu;pdf;clsdist;stdev
language=Java, R
name=ConsensusClustering
os=any
p10_default_value=2000
p10_description=Number of SOM/NMF iterations
p10_name=descent.iterations
p10_optional=on
p10_prefix_when_specified=
p10_type=java.lang.Integer
p10_value=
p11_default_value=<input.filename_basename>
p11_description=Stub pre-pended to all the output file names
p11_name=output.stub
p11_optional=
p11_prefix_when_specified=
p11_type=java.lang.String
p11_value=
p12_default_value=-n1
p12_description=row-wise, column-wise, both
p12_name=normalize.type
p12_optional=on
p12_prefix_when_specified=
p12_type=java.lang.String
p12_value=-n1\=row-wise;-n2\=column-wise;-n3\=both;\=none
p13_default_value=0
p13_description=number of row/column normalization iterations (supercedes normalize.type)
p13_name=normalization.iterations
p13_optional=on
p13_prefix_when_specified=
p13_type=java.lang.Integer
p13_value=
p14_default_value=
p14_description=Whether to create heatmaps (one for each cluster number)
p14_name=create.heat.map
p14_optional=on
p14_prefix_when_specified=
p14_type=java.lang.String
p14_value=\=no;-p\=yes
p15_default_value=2
p15_description=point size of a consensus matrix's heat map (between 1 and 20)
p15_name=heat.map.size
p15_optional=on
p15_prefix_when_specified=
p15_type=java.lang.Integer
p15_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The data to be clustered (.gct, .res, .odf)
p1_fileFormat=gct;res;Dataset
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=5
p2_description=Try K\=2,3,...,kmax clusters (must be > 1)
p2_name=kmax
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.Integer
p2_value=
p3_default_value=20
p3_description=Number of resampling iterations
p3_name=resampling.iterations
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.Integer
p3_value=
p4_default_value=12345
p4_description=Random number generator seed
p4_name=seed.value
p4_optional=on
p4_prefix_when_specified=
p4_type=java.lang.Integer
p4_value=
p5_default_value=HIERARCHICAL
p5_description=Type of clustering algorithm
p5_name=clustering.algorithm
p5_optional=on
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=HIERARCHICAL\=Hierarchical;SOM;NMF;KMEANS\=KMeans
p6_default_value=
p6_description=Whether to cluster by rows/genes or columns/experiments
p6_name=cluster.by
p6_optional=on
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=\=columns;-c\=rows
p7_default_value=EUCLIDEAN
p7_description=Distance measure
p7_name=distance.measure
p7_optional=on
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=EUCLIDEAN\=Euclidean;PEARSON\=Pearson
p8_default_value=subsample
p8_description=resampling scheme (one of 'subsample[ratio]', 'features[nfeat]', 'nosampling'). The default is subsampling with a proportion of 0.80. NOTE\: The square brackets should not be included (i.e subsample0.7, features210).
p8_name=resample
p8_optional=on
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=
p9_default_value=average
p9_description=Ignored when algorithm other than hierarchical selected
p9_name=merge.type
p9_optional=on
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=average;complete;single
privacy=public
publicationDate=02/01/2016 14\:15
quality=preproduction
taskType=Clustering
userid=pcarr@broadinstitute.org
version=Updated command line to use <run-with-env> wrapper script
