# ConstellationMap  urn:lsid:8080.gpbroad.broadinstitute.org:genepatternmodules:345:1.4.20
#Tue Feb 10 19:11:39 UTC 2026
JVMLevel=
LSID=urn\:lsid\:8080.gpbroad.broadinstitute.org\:genepatternmodules\:345\:1.4.20
author=Felix Wu;Broad Institute
categories=gsea;pathway analysis;viewer
commandLine=Rscript <libdir>run_ConstellationMap.R <libdir> --input.gct.file\=<input.gct.file> --input.cls.file\=<input.cls.file> --gene.sets.file\=<gene.sets.file> --top.n\=<top.n> --direction\=<direction> --image.format\=<image.format> --jaccard.threshold\=<jaccard.threshold> <target.class>
cpuType=any
description=A downstream visualization and analysis tool for gene set enrichment results with interactive web visualizer.
fileFormat=odf;txt;png;pdf;html
job.docker.image=genepattern/docker-r-3-0-conmap
language=R
name=ConstellationMap
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input gene set enrichment file. Expected to be output from ssGSEAProjection module.
p1_fileFormat=gct
p1_flag=
p1_name=input.gct.file
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Phenotype labels. Input cls file describing phenotypes of gct file.
p2_fileFormat=cls
p2_flag=
p2_name=input.cls.file
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_choiceDir=https\://www.gsea-msigdb.org/gsea/msigdb/gp_modules_gmt.json
p3_default_value=
p3_description=Gene sets database from GSEA website.  Upload a gene set if your gene set is not listed as a choice from MsigDB.
p3_fileFormat=gmt;gmx;grp
p3_flag=
p3_name=gene.sets.file
p3_numValues=1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_default_value=
p4_description=The number of gene sets to be plotted.
p4_fileFormat=
p4_name=top.n
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.Integer
p4_value=
p5_default_value=positive
p5_description=The direction of correlation, as measured by mutual information, to be investigated.
p5_name=direction
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=positive;negative
p6_default_value=PNG
p6_description=The image file type of outputted plots, either bitmap (PNG) or vector graphics (PDF).
p6_name=image.format
p6_optional=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=PNG;PDF
p7_default_value=0.1
p7_description=The Jaccard index threshold above which connective edges between gene sets will be plotted.
p7_name=jaccard.threshold
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.Float
p7_value=
p8_default_value=
p8_description=The phenotypic category of interest.
p8_fileFormat=
p8_name=target.class
p8_optional=on
p8_prefix_when_specified=--target.class\=
p8_type=java.lang.String
p8_value=
privacy=public
publicationDate=10/03/2022 15\:31 
quality=production
taskDoc=doc.html
taskType=Pathway Analysis
userid=flwu
version=Updated to Human MSigDB v2022.1.Hs and Mouse MSigDB 2022.1.Mm.
