# ConvertToMAGEML  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00038:2
#Tue Feb 10 19:11:40 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00038\:2
author=Joshua Gould
className=edu.mit.wi.omnigene.service.analysis.genepattern.GenePatternAnalysisTask
commandLine=<java> <java_flags> -cp <libdir>MAGEstk-2003-10-24-v1.1-compatible.jar<path.separator><libdir>ConvertToMAGE.jar<path.separator><libdir>jakarta-oro-2.0.8.jar<path.separator><libdir>broad-cg.jar<path.separator><libdir>trove.jar<path.separator><libdir>Jama-1.0.1.jar edu.mit.broad.modules.mage.MAGECreator <input.filename> <output.file.base.name> <create.zip.file>
cpuType=any
description=Converts a gct, res, or odf dataset file to a MAGE-ML file
language=Java
name=ConvertToMAGEML
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The gct, res, or odf file to convert
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<input.filename_basename>
p2_description=The base name of the zip output file or the MAGE-ML file
p2_name=output.file.base.name
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_default_value=yes
p3_description=Whether to zip the MAGE-ML files
p3_name=create.zip.file
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=yes;no
pipelineModel=
privacy=public
quality=development
serializedModel=
taskType=Preprocess & Utilities
userid=GenePattern
version=Fixes bug in the order of the BioDataCube
