# Convert.Alevin  urn:lsid:genepattern.org:module.analysis:00426:1
#Tue Feb 10 19:11:39 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00426\:1
author=Anthony S. Castanza;UCSD-MesirovLab
categories=singlecell;single-cell
commandLine=python3 /build/alevin.vpolo.py -i <Alevin.Quants> -f <Features> -m <Merge> -o <Out.Type>
cpuType=any
description=Read alevin output files and convert them to anndata (.h5ad) or loom (.loom) format for downstream analysis. Designed to convert Alevin Velocity quantification into a compatible format for scVelo.
documentationUrl=https\://genepattern.github.io/Convert.Alevin/v1/
fileFormat=h5ad,loom,mtx,h5
job.cpuCount=
job.docker.image=genepattern/convert_alevin\:v1
job.memory=8Gb
job.walltime=
language=any
name=Convert.Alevin
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Alevin output directories. Files must be in .tar.gz format, and have unique names.
p1_fileFormat=.tar.gz;tar.gz
p1_flag=-i
p1_name=Alevin.Quants
p1_numValues=1+
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=A tab delimited file containing the list of spliced gene ids in column 1, the unspliced gene ids in column 2, and gene names (symbols) in column 3. (From PreprocessVelocityTranscriptome, or manually created)
p2_fileFormat=.tsv
p2_flag=-f
p2_name=Features
p2_numValues=0..1
p2_optional=on
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=True
p3_description=Combine multiple Alevin runs into a single output object (True), or output them individually (false).
p3_fileFormat=
p3_flag=-m
p3_name=Merge
p3_numValues=1..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=True\=true;False\=false
p4_MODE=
p4_TYPE=TEXT
p4_default_value=h5ad
p4_description=Output alevin results as anndata (.h5ad) or loom (.loom)
p4_fileFormat=
p4_flag=-o
p4_name=Out.Type
p4_numValues=1..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=h5ad\=h5ad;loom\=loom
privacy=public
publicationDate=03/11/2022 16\:19 
quality=production
src.repo=https\://github.com/genepattern/Convert.Alevin/tree/v1
taskDoc=
taskType=singlecell
userid=bhill@broadinstitute.org
version=Initial Release
