# ConvertToMAGETAB  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00188:2
#Tue Feb 10 19:11:40 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00188\:2
author=Marc-Danie Nazaire(Broad Institute)
commandLine=<java> <java_flags> -cp <libdir>gp-modules.jar<path.separator><libdir>limpopo-1.0-beta-20100420.jar<path.separator><libdir>convertMAGETAB.jar org.broadinstitute.mage.MAGETABCreator <input.file> <sample.reference.label> <feature.reference.label> <intensity.type.label> <output.prefix> <cls.file>
cpuType=any
description=A module to export data from GenePattern in MAGE-TAB format
fileFormat=txt
language=Java
name=ConvertToMAGETAB
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A dataset file  - .gct, .res
p1_fileFormat=gct;res
p1_name=input.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=A class file  - .cls
p2_fileFormat=cls
p2_name=cls.file
p2_optional=on
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_default_value=Hybridization REF
p3_description=reference label for samples in the data matrix file
p3_name=sample.reference.label
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_default_value=CompositeElement REF
p4_description=reference label for features in the data matrix file
p4_name=feature.reference.label
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_default_value=
p5_description=label that specifies the type of intensity values in data matrix file 
p5_name=intensity.type.label
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
p6_default_value=<input.file_basename>
p6_description=prefix to use for output file name
p6_name=output.prefix
p6_optional=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=
pipelineModel=
privacy=public
publicationDate=08/20/2010 14\:40 
quality=production
serializedModel=
taskType=Preprocess & Utilities
userid=GenePattern (gp-help@broadinstitute.org)
version=Added types for text parameters
