# CopyNumberDivideByNormals  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00085:3
#Tue Feb 10 19:11:40 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00085\:3
author=David Twomey and Joshua Gould
commandLine=<java> <java_flags> -cp <libdir>snp.jar<path.separator><libdir>opencsv-1.7.jar<path.separator><libdir>gp-modules.jar<path.separator><libdir>commons-math-1.2.jar<path.separator><libdir>Jama-1.0.1.jar<path.separator><libdir>log4j-1.2.13.jar org.genepattern.modules.DivideByNormals.DivideByNormals <snp.file> <sample.info.file> <output.file.name> <include.genotype.calls>
cpuType=any
description=Determines the copy number of a target SNP
fileFormat=cn;xcn
language=Java
name=CopyNumberDivideByNormals
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=SNP file containing both normal and target samples.
p1_fileFormat=snp
p1_name=snp.file
p1_optional=on
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=dChip format sample info file containing Ploidy(numeric) and Sample columns
p2_fileFormat=txt;xls
p2_name=sample.info.file
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_default_value=cn
p3_description=Whether to include genotype calls from the input snp file if they exist.
p3_name=include.genotype.calls
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=xcn\=yes (create xcn file);cn\=no (create cn file)
p4_default_value=<snp.file_basename>
p4_description=Output file name
p4_name=output.file.name
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
pipelineModel=
privacy=public
publicationDate=01/23/2012 15\:30 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=SNP Analysis
userid=GenePattern
version=Updated to accept Allele-specific SNP files.
