# CoxRegression  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00164:4
#Tue Feb 10 19:11:40 UTC 2026
JVMLevel=2.0.1
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00164\:4
author=Yujin Hoshida (Broad Institute)
categories=Survival Analysis
commandLine=<R> <libdir>CoxRegression.GP.ez.R parseCmdLine -inp<input.surv.data.filename> -cls<input.cls.filename> -out<output.file> -tim<time> -sta<status> -con<variable.continuous> -cat<variable.category> -int<variable.interaction.terms> -str<strata> -sub<input.subgroup> -sel<variable.selection>
cpuType=any
description=Cox regression using clinical data and .cls file
fileFormat=png;txt
language=R
name=CoxRegression
os=any
p10_default_value=NA
p10_description=(e.g. cls\:2) *only one subgroup can be specified
p10_fileFormat=
p10_name=input.subgroup
p10_optional=
p10_prefix_when_specified=
p10_type=java.lang.String
p10_value=
p11_default_value=none
p11_description=
p11_fileFormat=
p11_name=variable.selection
p11_optional=
p11_prefix_when_specified=
p11_type=java.lang.String
p11_value=none\=no;both\=Stepwise selection;forward\=Forward selection;backward\=Backward selection
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=input clinical data. Case ID in 1st column (.txt file)
p1_fileFormat=
p1_name=input.surv.data.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=input class information (.cls file)
p2_fileFormat=
p2_name=input.cls.filename
p2_optional=on
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_default_value=CoxRegression_result
p3_description=
p3_fileFormat=
p3_name=output.file
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_default_value=time
p4_description=Column name for survival time
p4_fileFormat=
p4_name=time
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_default_value=status
p5_description=Column name for censor (0\: censored/alive, 1\: event/death)
p5_fileFormat=
p5_name=status
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
p6_default_value=NA
p6_description=(e.g. age,labdata1,...)
p6_fileFormat=
p6_name=variable.continuous
p6_optional=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=
p7_default_value=NA
p7_description=(e.g. sex,cls,grade,...)
p7_fileFormat=
p7_name=variable.category
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
p8_default_value=NA
p8_description=(e.g. sex\:cls,sex\:grade,...)
p8_fileFormat=
p8_name=variable.interaction.terms
p8_optional=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=
p9_default_value=NA
p9_description=Fit is done for each strata
p9_fileFormat=
p9_name=strata
p9_optional=
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=
pipelineModel=
privacy=public
publicationDate=03/25/2025 16\:12 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskDoc=doc.html
taskType=Survival Analysis
userid=
version=Modified the input.cls.filename parameter to be optional
