# CreateSymlinks  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00343:1
#Tue Feb 10 19:11:40 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00343\:1
author=
commandLine=<perl> <libdir>createsymlinks.pl --inputfilelist <input.files>
cpuType=any
description=Creates symlinks to the input files in the job results directory. This is intended to be a helper module for creating scatter-gather pipelines.  Note that this module is not supported on Windows
fileFormat=
language=any
name=CreateSymlinks
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=One or more input files
p1_fileFormat=
p1_flag=
p1_name=input.files
p1_numValues=1+
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
privacy=public
publicationDate=07/17/2014 13\:20 
quality=development
taskDoc=doc.html
taskType=Preprocess & Utilities
userid=nazaire
version=
