# CsvToFcs  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00174:2
#Tue Feb 10 19:11:41 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00174\:2
author=Josef Spidlen, BC Cancer Agency
commandLine=<java> <java_flags> -jar <libdir>csv2fcs.jar <Input.CSV.data.file> <Output.FCS.file.name> <Range> <Data.type>
cpuType=any
description=Converts a Comma separated values (CSV) file to a Flow Cytometry Standard (FCS) file.
fileFormat=fcs
language=Java
name=CsvToFcs
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A CSV file to be converted to FCS.
p1_fileFormat=csv
p1_name=Input.CSV.data.file
p1_optional=
p1_prefix_when_specified=-InputFile\:
p1_type=java.io.File
p1_value=
p2_default_value=<Input.CSV.data.file_basename>.fcs
p2_description=The name of the output FCS file.
p2_fileFormat=
p2_name=Output.FCS.file.name
p2_optional=on
p2_prefix_when_specified=-OutputFile\:
p2_type=java.lang.String
p2_value=
p3_default_value=auto
p3_description=Value of the $PnR keyword for all parameters. By default, this tool will try to set the best settings based on the data in the file; use "auto", "auto-exact", "BD", or an integer value.
p3_fileFormat=
p3_name=Range
p3_optional=
p3_prefix_when_specified=-Range\:
p3_type=java.lang.String
p3_value=
p4_default_value=auto
p4_description=Value of the $DATATYPE keyword. By default, this tool will try to set the best settings based on the data in the input CSV file.
p4_fileFormat=
p4_name=Data.type
p4_optional=on
p4_prefix_when_specified=-DataType\:
p4_type=java.lang.String
p4_value=auto\=auto, default;int\=integer;float\=floating point
pipelineModel=
privacy=public
publicationDate=07/10/2012 16\:47 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Data Format Conversion
userid=jspidlen@bccrc.ca
version=Fix for parsing empty keyword values
