# CytoscapeViewer  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00097:2
#Tue Feb 10 19:11:41 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00097\:2
author=Marc-Danie Nazaire, gp-help@broad.mit.edu, Broad Institute
commandLine=<java> <java_flags> -jar <libdir>cytoscapeViewer.jar <dataset.file> <adjacency.matrix.file> <libdir>
description=Visualizes a gene network
language=Java
name=CytoscapeViewer
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Dataset file - .res, .gct
p1_fileFormat=gct;res;Dataset
p1_name=dataset.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Adjacency matrix - .adj
p2_fileFormat=adj
p2_name=adjacency.matrix.file
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
privacy=public
publicationDate=04/21/2008 19\:57 
quality=production
taskType=Visualizer
userid=GenePattern
version=Updated to Cytoscape 2.5.2
