# DeIdentifyFCS  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00268:1
#Tue Feb 10 19:11:42 UTC 2026
JVMLevel=1.6
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00268\:1
author=Josef Spidlen, BC Cancer Agency
commandLine=<java> <java_flags> -jar <libdir>deidentifyfcs.jar -Debug <Input.FCS.data.file> <Remove.keywords> <Is.regular.expression.used> <Output.FCS.file.name>
cpuType=any
description=DeIdentifyFCS an FCS data file; remove keywords from a list or matching a regular expression; useful to anonymize FCS data files and/or to remove specific (e.g., clinical) information 
fileFormat=fcs
language=Java
name=DeIdentifyFCS
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=An FCS data file to be de-identified.
p1_fileFormat=fcs
p1_name=Input.FCS.data.file
p1_optional=
p1_prefix_when_specified=-InputFile\:
p1_type=java.io.File
p1_value=
p2_default_value=
p2_description=Comma-separated list of keyword names (escape comma by '\\' if part of a keyword name) or regular expression to match keywords to be removed.
p2_fileFormat=
p2_name=Remove.keywords
p2_optional=
p2_prefix_when_specified=-Remove\:
p2_type=java.lang.String
p2_value=
p3_default_value=No
p3_description=Is a regular expression used in the list of keywords to remove? If not (default) a simple comma-separated list of keyword names is expected. In this list, comma may be escaped by '\\' if part of a keyword name, e.g., this \\, is in the keyword.
p3_fileFormat=
p3_name=Is.regular.expression.used
p3_optional=
p3_prefix_when_specified=-IsRegExUsed\:
p3_type=java.lang.String
p3_value=Yes\=Yes;No\=No, default
p4_default_value=<Input.FCS.data.file_basename>.deidentified.<Input.FCS.data.file_extension>
p4_description=Output FCS file name.
p4_fileFormat=
p4_name=Output.FCS.file.name
p4_optional=
p4_prefix_when_specified=-OutputFile\:
p4_type=java.lang.String
p4_value=
pipelineModel=
privacy=public
publicationDate=07/13/2012 15\:17 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Flow Cytometry
userid=jspidlen@bccrc.ca
version=
