# DifferentialExpressionViewer  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.visualizer:00045:10
#Tue Feb 10 19:11:42 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.visualizer\:00045\:10
author=Marc-Danie Nazaire, Thorin Tabor
categories=javascript
commandLine=cmsviewer.html ? <differential.expression.filename> <dataset.filename>
cpuType=any
description=Views differential expression results such as from the ComparativeMarkerSelection module. Formerly known as ComparativeMarkerSelectionViewer.
documentationUrl=https\://github.com/genepattern/DifferentialExpressionViewer/blob/v10/docs/v10/index.md
fileFormat=
job.docker.image=genepattern/docker-java17\:0.12
language=any
name=DifferentialExpressionViewer
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=An odf result file of model type "Comparative Marker Selection"
p1_fileFormat=Comparative Marker Selection;Differential Expression;odf
p1_flag=
p1_name=differential.expression.filename
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=The expression dataset file used as input to calculate differential expression
p2_fileFormat=gct;res
p2_flag=
p2_name=dataset.filename
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
privacy=public
publicationDate=12/13/2021 15\:41 
quality=production
requiredPatchLSIDs=urn\:lsid\:broadinstitute.org\:plugin\:GenePattern_3_9_3\:1,
requiredPatchURLs=http\://www.broadinstitute.org/webservices/gpModuleRepository/download/prod/patch/?file\=/GenePattern_3_9_3/broadinstitute.org\:plugin/GenePattern_3_9_3/1/GenePattern_3_9_3.zip
src.repo=https\://github.com/genepattern/DifferentialExpressionViewer/tree/v10
taskDoc=
taskType=javascript
userid=GenePattern
version=Renamed from ComparativeMarkerSelectionViewer
