# DiSCoVER  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00393:1.1
#Tue Feb 10 19:11:42 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00393\:1.1
author=Edwin F. Juarez;UCSD -- Mesirov Lab
categories=RNA-Seq;RNA-seq;Statistical Methods;Prediction
commandLine=python /module/call_discover.py -g <disease_subtype_gene_expression_sample> -u "Custom" -c <control_sample> -s <output_supplementary_files>
cpuType=any
description=Beta implementation of the DiSCoVER algorithm.
fileFormat=
job.docker.image=genepattern/discover\:1.3
language=Python
name=DiSCoVER
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The csv file which contains the gene expression to be used as input.
p1_fileFormat=csv
p1_flag=-g
p1_name=disease_subtype_gene_expression_sample
p1_numValues=0..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=The csv control file to use as input (to compare disease subtype samples against).
p2_fileFormat=csv
p2_flag=-c
p2_name=control_sample
p2_numValues=0..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=False
p3_description=Whether or not to output supplementary files.
p3_fileFormat=
p3_flag=-s
p3_name=output_supplementary_files
p3_numValues=0..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=False\=False;True\=True
privacy=public
publicationDate=09/17/2019 18\:52 
quality=production
taskDoc=doc.html
taskType=Prediction
userid=edjuaro
version=Showing only upload option for contol.
