# DownloadURL  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00034:1
#Tue Feb 10 19:11:42 UTC 2026
JVMLevel=1.3
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00034\:1
author=Joshua Gould
className=edu.mit.wi.omnigene.service.analysis.genepattern.GenePatternAnalysisTask
commandLine=<java> <java_flags> -cp <libdir>download.jar DownloadFile <URL> <output.file>
cpuType=any
description=Downloads a file from a URL
language=Java
name=DownloadURL
os=any
p1_default_value=
p1_description=The URL to retrieve the file from
p1_name=URL
p1_optional=
p1_prefix_when_specified=
p1_type=java.lang.String
p1_value=
p2_default_value=
p2_description=The name of the output file
p2_name=output.file
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
pipelineModel=
privacy=public
quality=production
taskType=Preprocess & Utilities
userid=GenePattern (gp-info@broad.mit.edu)
version=Added email address to owner contact
