# eREVEALER_preprocess  urn:lsid:genepattern.org:module.analysis:00477:1
#Tue Feb 10 19:11:43 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00477\:1
author=Pablo Tamayo;Broad Institute
categories=statistical methods
commandLine=REVEALER preprocess --input_file <input_file> --protein_change_identifier <protein_change_identifier> --col_genename <col_genename> --col_class <col_class> --col_sample <col_sample> --mode <mode> --ratio <ratio> <phenotype_file>  <class_file> --prefix <prefix> --class_separator <class_separator> <phenotype_name> --file_separator <file_separator> --direction <direction> --frequency_threshold <frequency_threshold> --weight_threshold <weight_threshold> <gene_list> --name_match <name_match> --make_figure <make_figure> --figure_format <figure_format> <sample_list> --total_ratio <total_ratio> --if_gmt <if_gmt> --verbose <verbose> --k_size <k_size> --bandwidth_multiplication <bandwidth_multiplication> --bandwidth_adjustment <bandwidth_adjustment> --combine <combine> --neighborhood <neighborhood>
cpuType=any
description=eREVEALER (enhanced Repeated Evaluation of VariablEs conditionAL Entropy and Redundancy) is an analysis method specifically suited to find groups of genomic alterations that match in a complementary way, a predefined functional activation, dependency of drug response target profile. The method starts by considering, if available, already known genomic alterations (seed) that are the known causes or are known or assumed associated with the target. REVEALER starts by finding the genomic alteration that best matches the target profile conditional to the known seed profile using the conditional mutual information. The newly discovered alteration is then merged with the seed to form a new summary feature, and then the process repeats itself finding additional complementary alterations that explain more and more of the target profile.
documentationUrl=https\://genepattern.github.io/eREVEALER/REVEALER_preprocess_Documentation
fileFormat=pdf
job.cpuCount=
job.docker.image=yoshihiko1218/revealer\:v0.0.8
job.error_status.exit_value=true
job.error_status.stderr=false
job.memory=24 Gb
job.walltime=24\:00\:00
language=any
name=eREVEALER_preprocess
os=any
p10_MODE=
p10_TYPE=TEXT
p10_default_value=mutall
p10_description=Mode, can be class, mutall, freq, weight, all, or comb. For more detail, check documentation. Default is class.
p10_fileFormat=
p10_flag=
p10_name=mode
p10_numValues=0..1
p10_optional=on
p10_prefix=
p10_prefix_when_specified=
p10_type=java.lang.String
p10_userSuppliedValuesOK=True
p10_value=class\=class;mutall\=mutall;freq\=freq;weight\=weight;all\=all
p11_MODE=
p11_TYPE=Floating Point
p11_default_value=0.33
p11_description=Ratio of selected features by weight that is acceptable. Default is 0.33.
p11_fileFormat=
p11_flag=
p11_name=ratio
p11_numValues=0..1
p11_optional=on
p11_prefix=
p11_prefix_when_specified=
p11_type=java.lang.Float
p11_userSuppliedValuesOK=False
p11_value=
p12_MODE=IN
p12_TYPE=FILE
p12_default_value=
p12_description=Name of phenotype file. Required if mode is one of freq, weight, all, or comb.
p12_fileFormat=.txt
p12_flag=--phenotype_file 
p12_name=phenotype_file
p12_numValues=0..1
p12_optional=on
p12_prefix=--phenotype_file 
p12_prefix_when_specified=--phenotype_file 
p12_type=java.io.File
p12_userSuppliedValuesOK=False
p12_value=
p13_MODE=IN
p13_TYPE=FILE
p13_default_value=
p13_description=File for class to use, required if input file is gct file.
p13_fileFormat=.txt
p13_flag=--class_file 
p13_name=class_file
p13_numValues=0..1
p13_optional=on
p13_prefix=--class_file 
p13_prefix_when_specified=--class_file 
p13_type=java.io.File
p13_userSuppliedValuesOK=False
p13_value=
p14_MODE=
p14_TYPE=TEXT
p14_default_value=_
p14_description=Separator between gene name and class name. default is '_'
p14_fileFormat=
p14_flag=
p14_name=class_separator
p14_numValues=0..1
p14_optional=on
p14_prefix=
p14_prefix_when_specified=
p14_type=java.lang.String
p14_userSuppliedValuesOK=False
p14_value=
p15_MODE=
p15_TYPE=TEXT
p15_default_value=0
p15_description=Name of phenotypr to be used in phenotype file. Default is first row.
p15_fileFormat=
p15_flag=--phenotype_name 
p15_name=phenotype_name
p15_numValues=0..1
p15_optional=on
p15_prefix=--phenotype_name 
p15_prefix_when_specified=--phenotype_name 
p15_type=java.lang.String
p15_userSuppliedValuesOK=False
p15_value=
p16_MODE=
p16_TYPE=TEXT
p16_default_value=\\t
p16_description=Separator of file, default is tab
p16_fileFormat=
p16_flag=
p16_name=file_separator
p16_numValues=0..1
p16_optional=on
p16_prefix=
p16_prefix_when_specified=
p16_type=java.lang.String
p16_userSuppliedValuesOK=False
p16_value=
p17_MODE=
p17_TYPE=TEXT
p17_default_value=positive
p17_description=Direction of phenotype the features should match. Default is positive.
p17_fileFormat=
p17_flag=
p17_name=direction
p17_numValues=0..1
p17_optional=on
p17_prefix=
p17_prefix_when_specified=
p17_type=java.lang.String
p17_userSuppliedValuesOK=True
p17_value=positive\=positive;negative\=negative
p18_MODE=
p18_TYPE=Integer
p18_default_value=5
p18_description=Threshold for frequency. Default is 5.
p18_fileFormat=
p18_flag=
p18_name=frequency_threshold
p18_numValues=0..1
p18_optional=on
p18_prefix=
p18_prefix_when_specified=
p18_type=java.lang.Integer
p18_userSuppliedValuesOK=False
p18_value=
p19_MODE=
p19_TYPE=Floating Point
p19_default_value=0.7
p19_description=Threshold for weight. Default is 0.7.
p19_fileFormat=
p19_flag=
p19_name=weight_threshold
p19_numValues=0..1
p19_optional=on
p19_prefix=
p19_prefix_when_specified=
p19_type=java.lang.Float
p19_userSuppliedValuesOK=False
p19_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=https\://datasets.genepattern.org/data/module_support_files/REVEALER/CCLE.maf
p1_description=The name of the input file, can be maf file or gct file.
p1_fileFormat=gct;maf
p1_flag=
p1_name=input_file
p1_numValues=0..1
p1_optional=on
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_userSuppliedValuesOK=False
p1_value=
p20_MODE=IN
p20_TYPE=FILE
p20_default_value=
p20_description=Gene Set that is extracted. File format should be txt file with single column indicating genes. 
p20_fileFormat=.txt
p20_flag=--gene_list  
p20_name=gene_list
p20_numValues=0..1
p20_optional=on
p20_prefix=--gene_list  
p20_prefix_when_specified=--gene_list  
p20_type=java.io.File
p20_userSuppliedValuesOK=False
p20_value=
p21_MODE=
p21_TYPE=TEXT
p21_default_value=True
p21_description=Indicate if sample name in phenotype file and input file are matching. Default is True. If false, the program will try to find matching part.
p21_fileFormat=
p21_flag=
p21_name=name_match
p21_numValues=0..1
p21_optional=on
p21_prefix=
p21_prefix_when_specified=
p21_type=java.lang.String
p21_userSuppliedValuesOK=True
p21_value=True\=True;False\=False
p22_MODE=IN
p22_TYPE=FILE
p22_default_value=
p22_description=List of sample to be used.File format should be txt file with single column indicating features.
p22_fileFormat=.gct
p22_flag=--sample_list 
p22_name=sample_list
p22_numValues=0..1
p22_optional=on
p22_prefix=--sample_list 
p22_prefix_when_specified=--sample_list 
p22_type=java.io.File
p22_userSuppliedValuesOK=False
p22_value=
p23_MODE=
p23_TYPE=Floating Point
p23_default_value=0.4
p23_description=Ratio of gene occrence compared to total sample number. default is 0.4
p23_fileFormat=
p23_flag=
p23_name=total_ratio
p23_numValues=0..1
p23_optional=on
p23_prefix=
p23_prefix_when_specified=
p23_type=java.lang.Float
p23_userSuppliedValuesOK=False
p23_value=
p24_MODE=
p24_TYPE=TEXT
p24_default_value=True
p24_description=If combine alleles by gene when making figures.
p24_fileFormat=
p24_flag=
p24_name=combine
p24_numValues=0..1
p24_optional=on
p24_prefix=
p24_prefix_when_specified=
p24_type=java.lang.String
p24_userSuppliedValuesOK=True
p24_value=True\=True;False\=False
p25_MODE=
p25_TYPE=TEXT
p25_default_value=False
p25_description=Indicate if figures are created. Recommended only when you run few genes. Default is False.
p25_fileFormat=
p25_flag=
p25_name=make_figure
p25_numValues=0..1
p25_optional=on
p25_prefix=
p25_prefix_when_specified=
p25_type=java.lang.String
p25_userSuppliedValuesOK=True
p25_value=True\=True;False\=False
p26_MODE=
p26_TYPE=TEXT
p26_default_value=pdf
p26_description=Format for figure. Can be any figure format available in matplotlib. Default is pdf.
p26_fileFormat=
p26_flag=
p26_name=figure_format
p26_numValues=0..1
p26_optional=on
p26_prefix=
p26_prefix_when_specified=
p26_type=java.lang.String
p26_userSuppliedValuesOK=True
p26_value=pdf\=pdf;png\=png;jpg\=jpg
p27_MODE=
p27_TYPE=TEXT
p27_default_value=True
p27_description=Indicate if gmt file should be generated. Default is True.
p27_fileFormat=
p27_flag=
p27_name=if_gmt
p27_numValues=0..1
p27_optional=on
p27_prefix=
p27_prefix_when_specified=
p27_type=java.lang.String
p27_userSuppliedValuesOK=True
p27_value=True\=True;False\=False
p28_MODE=
p28_TYPE=Integer
p28_default_value=1
p28_description=Verbose level for report. Setting 0 to get no report. Default is 1.
p28_fileFormat=
p28_flag=
p28_name=verbose
p28_numValues=0..1
p28_optional=on
p28_prefix=
p28_prefix_when_specified=
p28_type=java.lang.Integer
p28_userSuppliedValuesOK=False
p28_value=
p29_MODE=
p29_TYPE=TEXT
p29_default_value=Mut
p29_description=prefix for output files. default is Mut.
p29_fileFormat=
p29_flag=
p29_name=prefix
p29_numValues=0..1
p29_optional=on
p29_prefix=
p29_prefix_when_specified=
p29_type=java.lang.String
p29_userSuppliedValuesOK=False
p29_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=ProteinChange
p2_description=Column of the protein change identifier in the dataset.
p2_fileFormat=
p2_flag=
p2_name=protein_change_identifier
p2_numValues=0..1
p2_optional=on
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_userSuppliedValuesOK=False
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=HugoSymbol
p3_description=Column of gene name information in the dataset.
p3_fileFormat=
p3_flag=
p3_name=col_genename
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_userSuppliedValuesOK=False
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=VariantType
p4_description=Column with class information in the dataset.
p4_fileFormat=
p4_flag=
p4_name=col_class
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_userSuppliedValuesOK=False
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=ModelID
p5_description=Column with sample name information in the dataset.
p5_fileFormat=
p5_flag=
p5_name=col_sample
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_userSuppliedValuesOK=False
p5_value=
p6_MODE=
p6_TYPE=Integer
p6_default_value=5
p6_description=Size of kernel indicating k variance far from middle. Has to be int. Default is 5.
p6_fileFormat=
p6_flag=
p6_name=k_size
p6_numValues=0..1
p6_optional=on
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.Integer
p6_userSuppliedValuesOK=False
p6_value=
p7_MODE=
p7_TYPE=Floating Point
p7_default_value=0.65
p7_description=Value of bandwidth multiplier. Has to be float or int. Default is 0.65.
p7_fileFormat=
p7_flag=
p7_name=bandwidth_multiplication
p7_numValues=0..1
p7_optional=on
p7_prefix=
p7_prefix_when_specified=
p7_range=-1..1
p7_type=java.lang.Float
p7_userSuppliedValuesOK=False
p7_value=
p8_MODE=
p8_TYPE=Floating Point
p8_default_value=-0.95
p8_description=Value of bandwidth adjustment. Has to be float or int. Default is -0.95
p8_fileFormat=
p8_flag=
p8_name=bandwidth_adjustment
p8_numValues=0..1
p8_optional=on
p8_prefix=
p8_prefix_when_specified=
p8_range=-1..1
p8_type=java.lang.Float
p8_userSuppliedValuesOK=False
p8_value=
p9_MODE=
p9_TYPE=Integer
p9_default_value=4
p9_description=This indicates number of neighborhood for kernel. Higher number will lead to higher accuracy but lower speed.
p9_fileFormat=
p9_flag=
p9_name=neighborhood
p9_numValues=0..1
p9_optional=on
p9_prefix=
p9_prefix_when_specified=
p9_type=java.lang.Integer
p9_userSuppliedValuesOK=False
p9_value=
privacy=public
publicationDate=04/28/2025 17\:53 
quality=production
src.repo=
taskDoc=REVEALER_GP_documentation.v1.pdf
taskType=statistical methods
userid=yoshihiko1218
version=Update parameter
