# ExtractColumnNames  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00003:2
#Tue Feb 10 19:11:43 UTC 2026
JVMLevel=any
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00003\:2
author=Justin Lamb, Broad Institute
commandLine=<perl> <libdir>samples.pl <input.filename> <output>
cpuType=any
description=Lists the sample descriptors from a .res file.
fileFormat=txt
language=Perl
name=ExtractColumnNames
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input filename - .res
p1_fileFormat=res
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<input.filename_basename>
p2_description=Name of the output file (a .txt extension will be appended)
p2_name=output
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
pipelineModel=
privacy=public
quality=production
serializedModel=
taskType=Preprocess & Utilities
userid=GenePattern (gp-help@broad.mit.edu)
version=Annotated for GP 1.4
