# ExtractRowNames  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00004:3
#Tue Feb 10 19:11:44 UTC 2026
JVMLevel=1.4
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00004\:3
author=Joshua Gould, Broad Institute
commandLine=<java> <java_flags> -cp <libdir>ExtractRowNames.jar<path.separator><libdir>gp-modules.jar org.genepattern.modules.extractrows.ExtractRowNames <input.filename> <output> 
cpuType=any
description=Extracts the row names from a .res, .gct, or .odf file.
fileFormat=txt
language=Java
name=ExtractRowNames
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=input file - .res, .gct, .odf, file from which the row names are extracted
p1_fileFormat=res;gct;Dataset
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<input.filename_basename>.row.names.txt
p2_description=output filename containing the row names - .txt
p2_name=output
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
pipelineModel=
privacy=public
quality=production
serializedModel=
taskType=Preprocess & Utilities
userid=GenePattern (gp-help@broad.mit.edu)
version=Added support for gct and odf files
