# ExtractComparativeMarkerResults  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00046:4
#Tue Feb 10 19:11:43 UTC 2026
JVMLevel=1.4
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00046\:4
author=Joshua Gould
commandLine=<java> <java_flags> -cp <libdir>gp-modules.jar<path.separator><libdir>ExtractComparativeMarkerResults.jar edu.mit.broad.modules.marker.CreateMarkersFileModule <comparative.marker.selection.filename> <dataset.filename> -f<statistic> -n<min> -x<max> -s<number.of.neighbors> -o<base.output.name>
cpuType=any
description=Creates a derived dataset and feature list file from the results of ComparativeMarkerSelection
fileFormat=gct;res;Dataset;txt
language=Java
name=ExtractComparativeMarkerResults
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The results from ComparativeMarkerSelection - .odf
p1_fileFormat=Comparative Marker Selection
p1_name=comparative.marker.selection.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=The dataset file used to select markers - .gct, .res, Dataset
p2_fileFormat=gct;res;Dataset
p2_name=dataset.filename
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_default_value=
p3_description=The statistic to filter features on
p3_name=statistic
p3_optional=on
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=Bonferroni;FDR(BH);Feature P;Feature P High;Feature P Low;Fold Change;FWER;maxT;Q Value;Rank;Score
p4_default_value=
p4_description=Select features with statistic >\= min
p4_name=min
p4_optional=on
p4_prefix_when_specified=
p4_type=java.lang.Float
p4_value=
p5_default_value=
p5_description=Select features with statistic <\= max
p5_name=max
p5_optional=on
p5_prefix_when_specified=
p5_type=java.lang.Float
p5_value=
p6_default_value=
p6_description=Number of neighbors to select by score in each direction
p6_name=number.of.neighbors
p6_optional=on
p6_prefix_when_specified=
p6_type=java.lang.Integer
p6_value=
p7_default_value=<comparative.marker.selection.filename_basename>.filt
p7_description=The base name for the output files
p7_name=base.output.name
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
privacy=public
publicationDate=03/10/2006 14\:52 
quality=production
serializedModel=
taskType=Gene List Selection
userid=pcarr@broadinstitute.org
version=Renamed field parameter to statistic
