# ExtractFCSKeywords  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00181:2
#Tue Feb 10 19:11:44 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00181\:2
author=Josef Spidlen, BC Cancer Agency
commandLine=<java> <java_flags> -jar <libdir>extractfcskeywords.jar <Input.FCS.data.file> <Keywords.output.file.name> <Keywords.output.mode>
cpuType=any
description=Extracts keyword(s) value(s) from a Flow Cytometry Standard (FCS) file.
fileFormat=csv;txt
language=Java
name=ExtractFCSKeywords
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The input FCS data file from which the module will extract keyword/value pairs.
p1_fileFormat=fcs
p1_name=Input.FCS.data.file
p1_optional=
p1_prefix_when_specified=-InputFile\:
p1_type=java.io.File
p1_value=
p2_default_value=CSV
p2_description=The file format to be used to store the extracted keywords/value pairs.
p2_fileFormat=
p2_name=Keywords.output.mode
p2_optional=
p2_prefix_when_specified=-KeywordsMode\:
p2_type=java.lang.String
p2_value=CSV\=CSV file, default;FCS\=Text file with FCS text segment chunk 
p3_default_value=<Input.FCS.data.file_basename>
p3_description=The name for the file in which the keyword/value pairs are stored.
p3_fileFormat=
p3_name=Keywords.output.file.name
p3_optional=
p3_prefix_when_specified=-KeywordsOutputFile\:
p3_type=java.lang.String
p3_value=
pipelineModel=
privacy=public
publicationDate=07/13/2012 15\:08 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Flow Cytometry
userid=jspidlen@bccrc.ca
version=Updated to release candidate from Josef which includes more lenient CFCS library
