# FcsToCsv  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00175:3
#Tue Feb 10 19:11:44 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00175\:3
author=Josef Spidlen, BC Cancer Agency
categories=Data Format Conversion; Flow Cytometry
commandLine=<java> <java_flags> -jar <libdir>fcs2csv.jar <Input.FCS.data.file> <Output.CSV.file.name> <Use.full.names> <Output.keywords.file.name> <Output.keywords.mode> <Channel.to.scale.conversion> <Precision>
cpuType=any
description=Converts a Flow Cytometry Standard (FCS) file to a Comma Separated Values (CSV) file.
fileFormat=csv;keywords.csv;keywords.txt
language=Java
name=FcsToCsv
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=An FCS data file to be converted to CSV.
p1_fileFormat=fcs
p1_name=Input.FCS.data.file
p1_optional=
p1_prefix_when_specified=-InputFile\:
p1_type=java.io.File
p1_value=
p2_default_value=<Input.FCS.data.file_basename>.csv
p2_description=The name of the output CSV file.
p2_fileFormat=
p2_name=Output.CSV.file.name
p2_optional=
p2_prefix_when_specified=-OutputFile\:
p2_type=java.lang.String
p2_value=
p3_default_value=TRUE
p3_description=Whether to try to extract full parameter names from the FCS file.
p3_fileFormat=
p3_name=Use.full.names
p3_optional=on
p3_prefix_when_specified=-FullNames\:
p3_type=java.lang.String
p3_value=TRUE\=Use full names, default;FALSE\=Use short names only
p4_default_value=<Input.FCS.data.file_basename>
p4_description=The file name to store keyword value pairs extracted from the FCS file.
p4_fileFormat=
p4_name=Output.keywords.file.name
p4_optional=
p4_prefix_when_specified=-KeywordsFile\:
p4_type=java.lang.String
p4_value=
p5_default_value=CSV
p5_description=How to store keywords.
p5_fileFormat=
p5_name=Output.keywords.mode
p5_optional=on
p5_prefix_when_specified=-KeywordsMode\:
p5_type=java.lang.String
p5_value=CSV\=Store as a CSV file, default;FCS\=Store keywords in the FCS TEXT segment format;None\=Do not extract the keyword/value pairs
p6_default_value=TRUE
p6_description=Whether to convert log channel values to linear scale.
p6_fileFormat=
p6_name=Channel.to.scale.conversion
p6_optional=on
p6_prefix_when_specified=-ChannelToScale\:
p6_type=java.lang.String
p6_value=TRUE\=Convert channel to scale, default;NO\=No conversion, store as in the FCS file
p7_default_value=FALSE
p7_description=Whether to use regular (32bit, recommended) or double precision.
p7_fileFormat=
p7_name=Precision
p7_optional=on
p7_prefix_when_specified=-DoublePrecision\:
p7_type=java.lang.String
p7_value=FALSE\=Use regular precision, default;TRUE\=Use double precision
pipelineModel=
privacy=public
publicationDate=07/02/2012 13\:22 
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Data Format Conversion
userid=pcarr@broadinstitute.org
version=Added fix for parsing empty keyword values
