# FeatureSummaryViewer  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.visualizer:00005:5
#Tue Feb 10 19:11:45 UTC 2026
JVMLevel=1.6
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.visualizer\:00005\:5
author=Thorin Tabor, reimplemented in js by Ted Liefeld (UC San Diego, Broad Institute)
commandLine=feature_summary_viewer.html ? <feature.filename>
cpuType=any
description=Visualizes feature summary results in JavaScript
documentationUrl=https\://genepattern.github.io/FeatureSummaryViewer/
fileFormat=
language=Javascript
name=FeatureSummaryViewer
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=odf file with or without features to summarize
p1_fileFormat=odf;feat.odf;Feature Summary
p1_name=feature.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
pipelineModel=
privacy=public
publicationDate=08/20/2025 16\:01 
quality=production
requiredPatchLSIDs=urn\:lsid\:broadinstitute.org\:plugin\:GenePattern_3_9_1\:0.1,
requiredPatchURLs=http\://software.broadinstitute.org/webservices/gpModuleRepository/download/dev/patch/?file\=/GenePattern_3_9_1/broadinstitute.org\:plugin/GenePattern_3_9_1/0.1/GenePattern_3_9_1.zip
serializedModel=
src.repo=https\://github.com/genepattern/FeatureSummaryViewer.git
taskType=javascript
userid=
version=Bug fix for S3 files
