# FileSplitter  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00274:2
#Tue Feb 10 19:11:45 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00274\:2
author=Peter Carr, Broad Institute
commandLine=<java> <java_flags> -cp <libdir>FileSplitter.jar<path.separator><libdir>gp-annotations.jar<path.separator><libdir>jopt-simple-3.3.jar org.genepattern.module.filesplitter.FileSplitter <inputFile> <numFiles> <numLines>
cpuType=any
description=Splits a file into equal-sized chunks, given the number of lines per output file
fileFormat=
language=Java
name=FileSplitter
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The input file, to be split into chunks
p1_fileFormat=
p1_name=inputFile
p1_optional=
p1_prefix_when_specified=--inputFile\=
p1_type=java.io.File
p1_value=
p2_default_value=
p2_description=[Integer, >\=1], The maximum number of output files to split the file into. When both 'numFiles' and 'numLines' are set, treat this as the maximum number of output files to create, even if the files have more than the requested number of lines
p2_fileFormat=
p2_name=numFiles
p2_optional=on
p2_prefix_when_specified=--numFiles\=
p2_type=java.lang.String
p2_value=
p3_default_value=
p3_description=[Integer, >\=1], The number of lines in each output file.
p3_fileFormat=
p3_name=numLines
p3_optional=on
p3_prefix_when_specified=--numLines\=
p3_type=java.lang.String
p3_value=
pipelineModel=
privacy=public
publicationDate=12/14/2012 16\:00 
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Preprocess & Utilities
userid=
version=
