# FilterFilelist  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00280:1
#Tue Feb 10 19:11:45 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00280\:1
author=Peter Carr, Broad Institute
commandLine=<java> <java_flags> -cp <libdir>FilterFilelist.jar<path.separator><libdir>gp-annotations.jar<path.separator><libdir>jopt-simple-3.3.jar<path.separator><libdir>jakarta-oro-2.0.8.jar org.genepattern.module.filterfilelist.FilterFilelist <input.filelist> <includePattern> <type> <errorOnEmptySet> <output.filename>
cpuType=any
description=a helper module which generates a filtered filelist from the input filelist and some filter parameters.
fileFormat=
language=Java
name=FilterFilelist
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=the initial input filelist, a file containing a list of filepaths
p1_fileFormat=
p1_name=input.filelist
p1_optional=
p1_prefix_when_specified=--input.filelist\=
p1_type=java.io.File
p1_value=
p2_default_value=
p2_description=an optional list of filename patterns to match, e.g. *.cls,*.gct
p2_fileFormat=
p2_name=includePattern
p2_optional=on
p2_prefix_when_specified=--includePattern\=
p2_type=java.lang.String
p2_value=
p3_default_value=f
p3_description=Include files, directories, or both files and directories in the output filelist
p3_fileFormat=
p3_name=type
p3_optional=on
p3_prefix_when_specified=--type\=
p3_type=java.lang.String
p3_value=\=all;f\=file;d\=dir
p4_default_value=
p4_description=Whether the module should output stderr if the output result is empty
p4_fileFormat=
p4_name=errorOnEmptySet
p4_optional=on
p4_prefix_when_specified=--errorOnEmptySet\=
p4_type=java.lang.String
p4_value=\=no;yes\=yes
p5_default_value=<input.filelist_basename>.filtered.<input.filelist_extension>
p5_description=the name of the output file, if none specified, write to stdout
p5_fileFormat=
p5_name=output.filename
p5_optional=on
p5_prefix_when_specified=--output.filename\=
p5_type=java.lang.String
p5_value=
pipelineModel=
privacy=public
publicationDate=09/26/2012 10\:30 
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Preprocess & Utilities
userid=
version=
