# FLAMEPreprocess  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00159:4.2
#Tue Feb 10 19:11:45 UTC 2026
JVMLevel=2.7
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00159\:4.2
author=
commandLine=<R-2.7.2> <libdir>preprocess.gp.R parseCmdLine <libdir> <dataset> <remove.dead> <channels> <channel.names> <scatter.channels> <file.type> <transformation> <data.scale> <logicle.cofactor> <arsinh.cofactor> <output.prefix>
cpuType=any
description=Performs preprocessing of .fcs or .txt flow cytometric data files
fileFormat=
language=R
name=FLAMEPreprocess
os=any
p10_default_value=250
p10_description=A cofactor that tunes the arsinh transformation. The cofactor is 0 usually between 0 exclusively and a few thousand.
p10_fileFormat=
p10_name=arsinh.cofactor
p10_optional=
p10_prefix_when_specified=
p10_type=java.lang.Integer
p10_value=
p11_default_value=<dataset_basename>
p11_description=A prefix for output files
p11_fileFormat=
p11_name=output.prefix
p11_optional=
p11_prefix_when_specified=
p11_type=java.lang.String
p11_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A .zip file containing flow files in .txt or .fcs format. (The files should be all .txt or all .fcs, but not both.)
p1_fileFormat=zip
p1_name=dataset
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=fcs
p2_description=File type of input sample data.
p2_fileFormat=
p2_name=file.type
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=fcs;txt
p3_default_value=262144
p3_description=The original data scale. 18-bit (default) or 4-decade.
p3_fileFormat=
p3_name=data.scale
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.Integer
p3_value=262144\=18-bit;10000\=4-decade
p4_default_value=F
p4_description=Whether to attempt removing dead cells from the samples.
p4_fileFormat=
p4_name=remove.dead
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=T\=yes;F\=no
p5_default_value=
p5_description=A comma-separated list of channel numbers indicating which columns (antibodies) to keep (e.g., 1, 2, 3, 7).
p5_fileFormat=
p5_name=channels
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
p6_default_value=
p6_description=A comma-separated list of channel/antibody names that corresponds to the channel numbers (e.g., FSC, SSC, CD4, CD45RA).
p6_fileFormat=
p6_name=channel.names
p6_optional=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=
p7_default_value=1,2
p7_description=A comma-separated list of scatter channel numbers (e.g., 1, 2, 3).
p7_fileFormat=
p7_name=scatter.channels
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
p8_default_value=logicle
p8_description=The transformation to apply
p8_fileFormat=
p8_name=transformation
p8_optional=
p8_prefix_when_specified=
p8_type=java.lang.Integer
p8_value=none;logicle;arsinh
p9_default_value=3
p9_description=A cofactor that tunes the logicle transformation. The cofactor is usually greater than 0 and less than 10.
p9_fileFormat=
p9_name=logicle.cofactor
p9_optional=
p9_prefix_when_specified=
p9_type=java.lang.Integer
p9_value=
pipelineModel=
privacy=public
publicationDate=02/11/2016 19\:16 
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Flow Cytometry
userid=xinlihu
version=Pin common.R to the one associated with v. 4 release of this module
