# GctToPcl  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00152:1
#Tue Feb 10 19:11:45 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00152\:1
author=Jeremy Hubble, Stanford University, gp-help@broad.mit.edu
commandLine=<perl> <libdir>gctToPcl.pl -o <output.filename> <input.filename>
cpuType=any
description=Convert .gct to .pcl
fileFormat=pcl;Prediction Results
language=Perl
name=GctToPcl
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=GCT file to convert
p1_fileFormat=gct
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<input.filename_basename>.pcl
p2_description=PCL file that will be produced
p2_fileFormat=
p2_name=output.filename
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
pipelineModel=
privacy=public
publicationDate=10/17/2008 11\:10 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Data Format Conversion
userid=
version=
