# GeneListSignificanceViewer  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.visualizer:00006:5
#Tue Feb 10 19:11:45 UTC 2026
JVMLevel=1.6
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.visualizer\:00006\:5
author=Joshua Gould, reimplemented in js by Ted Liefeld (UC San Diego, Broad Institute)
commandLine=gene_list_significance_viewer.html ? <inputfilename>
cpuType=any
description=Views the results of marker analysis
documentationUrl=https\://genepattern.github.io/GeneListSignificanceViewer/
fileFormat=
language=Javascript
name=GeneListSignificanceViewer
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=odf file with or without features to summarize
p1_fileFormat=odf;markerlist.odf;Gene List
p1_name=inputfilename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
pipelineModel=
privacy=public
publicationDate=08/25/2025 10\:50 
quality=production
requiredPatchLSIDs=urn\:lsid\:broadinstitute.org\:plugin\:GenePattern_3_9_1\:0.1,
requiredPatchURLs=http\://software.broadinstitute.org/webservices/gpModuleRepository/download/dev/patch/?file\=/GenePattern_3_9_1/broadinstitute.org\:plugin/GenePattern_3_9_1/0.1/GenePattern_3_9_1.zip
serializedModel=
src.repo=https\://github.com/genepattern/GeneListSignificanceViewer.git
taskType=javascript
userid=
version=Rewrite as javascript
