# GeneNeighbors  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00007:4
#Tue Feb 10 19:11:46 UTC 2026
JVMLevel=1.4
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00007\:4
author=Ken Ross, Broad Institute
commandLine=<java> <java_flags> -cp <libdir>gp-modules.jar<path.separator><libdir>RunMarkerSelection.jar edu.mit.wi.genome.expresso.alg.RunMarkerSelection.RunMarkerSelection -t <data.filename> \r\n-H -m <min.threshold> -M <max.threshold> -f -F <min.fold.diff> -D <min.abs.diff> -o <marker.list.file> -C -N <num.neighbors> -O <marker.dataset.file> -g <gene.accession> -k <distance.metric> -G <filter.data>
cpuType=any
description=Select genes that most closely resemble a continuous profile (e.g., another gene)
fileFormat=Gene List;gct
language=Java
name=GeneNeighbors
os=any
p10_default_value=5
p10_description=minimum fold difference for filtering genes
p10_name=min.fold.diff
p10_optional=
p10_prefix_when_specified=
p10_type=java.lang.String
p10_value=
p11_default_value=50
p11_description=minimum absolute difference for filtering genes
p11_name=min.abs.diff
p11_optional=
p11_prefix_when_specified=
p11_type=java.lang.String
p11_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=data file - .gct, .res, .odf
p1_fileFormat=gct;res;Dataset
p1_name=data.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=
p2_description=reference gene accession from data file to find neighbors for
p2_name=gene.accession
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_default_value=50
p3_description=number of neighbors to find
p3_name=num.neighbors
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_default_value=<data.filename_basename>.markerlist
p4_description=output filename for analysis results - .odf file
p4_name=marker.list.file
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_default_value=<data.filename_basename>.markerdata
p5_description=output filename raw data for selected markers - .gct file
p5_name=marker.dataset.file
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
p6_default_value=3
p6_description=continuous metric for finding neighbors
p6_name=distance.metric
p6_optional=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=0\=Cosine distance;1\=Euclidean distance;2\=Manhattan distance;3\=Pearson distance
p7_default_value=no
p7_description=if no, values below will be ignored
p7_name=filter.data
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=yes;no
p8_default_value=20
p8_description=minimum threshold for data
p8_name=min.threshold
p8_optional=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=
p9_default_value=20000
p9_description=maximum threshold for data
p9_name=max.threshold
p9_optional=
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=
pipelineModel=
privacy=public
publicationDate=06/15/2012 11\:35 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Gene List Selection
userid=GenePattern (gp-help@broad.mit.edu)
version=updated thresholds to post-2002 Affy Values
