# GEOImporter  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00042:6
#Tue Feb 10 19:11:46 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00042\:6
author=Joshua Gould, Broad Institute; Anthony Castanza, UCSD
categories=preprocess & utilities;preprocess & utilities
commandLine=Rscript --no-save --quiet --slave --no-restore /GEOImporter/main.R /GEOImporter/ -n<Drop.NA.Rows> -d<data.column.name> -o<output.filename> -a<GEO.accession> -f<GEO.SOFT.file> -1<ftp.proxy.server> -2<ftp.proxy.username> -3<ftp.proxy.password> -4<http.proxy.server> -5<http.proxy.username> -6<http.proxy.password>
cpuType=any
description=Imports data from the Gene Expression Omnibus (GEO)
fileFormat=gct
job.docker.image=genepattern/geoimporter\:1
language=any
name=GEOImporter
os=any
p10_MODE=
p10_TYPE=TEXT
p10_default_value=
p10_description=HTTP Proxy username
p10_fileFormat=
p10_flag=
p10_name=http.proxy.username
p10_numValues=0..1
p10_optional=on
p10_prefix=
p10_prefix_when_specified=
p10_type=java.lang.String
p10_value=
p11_MODE=
p11_TYPE=PASSWORD
p11_default_value=
p11_description=HTTP Proxy password
p11_fileFormat=
p11_flag=
p11_name=http.proxy.password
p11_numValues=0..1
p11_optional=on
p11_prefix=
p11_prefix_when_specified=
p11_type=PASSWORD
p11_value=
p1_MODE=
p1_TYPE=TEXT
p1_default_value=
p1_description=GEO Series record (GSExxx) or a GEO Dataset (GDSxxx). Either a GEO accession or a GEO SOFT file must be given.
p1_fileFormat=
p1_flag=
p1_name=GEO.accession
p1_numValues=0..1
p1_optional=on
p1_prefix=
p1_prefix_when_specified=
p1_type=java.lang.String
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=A previously downloaded GEO SOFT file or its gzipped representation. Either a GEO SOFT file or a GEO accession must be given.
p2_fileFormat=gz;soft
p2_flag=
p2_name=GEO.SOFT.file
p2_numValues=0..1
p2_optional=on
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=FALSE
p3_description=Omit rows containing all "NA" values from GSExxx data series.
p3_fileFormat=
p3_flag=-n
p3_name=Drop.NA.Rows
p3_numValues=1..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=FALSE\=false;TRUE\=true
p4_MODE=
p4_TYPE=TEXT
p4_default_value=VALUE
p4_description=The name of the column that contains the expression values
p4_fileFormat=
p4_flag=
p4_name=data.column.name
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=<GEO.accession><GEO.SOFT.file_basename>
p5_description=The name of the output file
p5_fileFormat=
p5_flag=
p5_name=output.filename
p5_numValues=1..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=
p6_description=FTP Proxy server
p6_fileFormat=
p6_flag=
p6_name=ftp.proxy.server
p6_numValues=0..1
p6_optional=on
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=
p7_MODE=
p7_TYPE=TEXT
p7_default_value=
p7_description=FTP Proxy username
p7_fileFormat=
p7_flag=
p7_name=ftp.proxy.username
p7_numValues=0..1
p7_optional=on
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
p8_MODE=
p8_TYPE=PASSWORD
p8_default_value=
p8_description=FTP Proxy password
p8_fileFormat=
p8_flag=
p8_name=ftp.proxy.password
p8_numValues=0..1
p8_optional=on
p8_prefix=
p8_prefix_when_specified=
p8_type=PASSWORD
p8_value=
p9_MODE=
p9_TYPE=TEXT
p9_default_value=
p9_description=HTTP Proxy server
p9_fileFormat=
p9_flag=
p9_name=http.proxy.server
p9_numValues=0..1
p9_optional=on
p9_prefix=
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=
privacy=public
publicationDate=02/12/2021 12\:58 
quality=production
src.repo=https\://github.com/genepattern/GEOImporter/releases/tag/v6
taskDoc=GEOImporter.pdf
taskType=preprocess & utilities
userid=bhill@broadinstitute.org
version=Updated NCIBI FTP paths. Added ability to omit rows with all NA values. Updated to use R 4.0.3 via module specific Docker container.
