# GlobalAlignment  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00008:0
#Tue Feb 10 19:11:46 UTC 2026
JVMLevel=any
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00008\:0
author=Mike Kamal, gp-help@broad.mit.edu
className=edu.mit.wi.omnigene.service.analysis.genepattern.GenePatternAnalysisTask
commandLine=<java> <java_flags> -cp <libdir>DPJava.jar DemoStandardGlobal <query.filename> <subject.fasta.filename> <match> <mismatch> <gapopen> <gapextend> <output.file>
cpuType=any
description=standard global sequence analysis
language=Java
name=GlobalAlignment
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=filename of subject FASTA file
p1_name=subject.fasta.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=
p2_description=> 0
p2_name=match
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_default_value=
p3_description=< 0
p3_name=mismatch
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_default_value=
p4_description=< 0
p4_name=gapopen
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_default_value=
p5_description=< 0
p5_name=gapextend
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
p6_MODE=IN
p6_TYPE=FILE
p6_default_value=
p6_description=FASTA file
p6_name=query.filename
p6_optional=
p6_prefix_when_specified=
p6_type=java.io.File
p6_value=
p7_default_value=<subject.fasta.filename_basename>
p7_description=filename of output
p7_name=output.file
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
pipelineModel=
privacy=public
quality=production
serializedModel=
taskType=Sequence Analysis
userid=GenePattern
version=
