# GSEAPreranked  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00317:7.4.0
#Tue Feb 10 19:11:47 UTC 2026
=\=\=\=\=\=\=
<<<<<<<=HEAD
>>>>>>>=refs/heads/master
JVMLevel=11
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00317\:7.4.0
author=Chet Birger, David Eby; Broad Institute
categories=gsea;pathway analysis
commandLine=/opt/gsea/GSEA_4.3.2/gsea-cli.sh GSEAPreranked -gmx_list <gene.sets.database> -norm <normalization.mode> -nperm <number.of.permutations> -rnk <ranked.list> -collapse <collapse.dataset> <chip.platform.file> -mode <collapsing.mode.for.probe.sets.with.more.than.one.match> -scoring_scheme <scoring.scheme> -include_only_symbols <omit.features.with.no.symbol.match> -make_sets <make.detailed.gene.set.report> -plot_top_x <num.top.sets> -rnd_seed <random.seed> -set_max <max.gene.set.size> -set_min <min.gene.set.size> -create_svgs <create.svgs> <selected.gene.sets> <output.file.name> <alt.delim> -dev_mode <dev.mode> -zip_report true -run_as_genepattern true
cpuType=any
description=Runs the gene set enrichment analysis against a user-supplied ranked list of genes.
fileFormat=
job.docker.image=genepattern/gsea_4.3.2\:0.1
job.memory=4Gb
language=Java
name=GSEAPreranked
os=any
p10_MODE=
p10_TYPE=TEXT
p10_default_value=meandiv
p10_description=Normalization mode
p10_fileFormat=
p10_flag=
p10_name=normalization.mode
p10_optional=
p10_prefix=
p10_prefix_when_specified=
p10_type=java.lang.String
p10_value=meandiv;None
p11_MODE=
p11_TYPE=TEXT
p11_default_value=true
p11_description=If there is no known gene symbol match for a probe set, omit it from the collapsed dataset
p11_fileFormat=
p11_flag=
p11_name=omit.features.with.no.symbol.match
p11_optional=
p11_prefix=
p11_prefix_when_specified=
p11_type=java.lang.String
p11_value=false;true
p12_MODE=
p12_TYPE=TEXT
p12_default_value=true
p12_description=Create detailed gene set report (heat map, mountain plot, etc.) for every enriched gene set
p12_fileFormat=
p12_flag=
p12_name=make.detailed.gene.set.report
p12_optional=
p12_prefix=
p12_prefix_when_specified=
p12_type=java.lang.String
p12_value=false;true
p13_MODE=
p13_TYPE=Integer
p13_default_value=20
p13_description=Plot GSEA mountain and related plots for the top sets of each phenotype
p13_fileFormat=
p13_flag=
p13_name=num.top.sets
p13_optional=
p13_prefix=
p13_prefix_when_specified=
p13_type=java.lang.Integer
p13_value=
p14_MODE=
p14_TYPE=TEXT
p14_default_value=timestamp
p14_description=Seed to use for generating random permutations.
p14_fileFormat=
p14_flag=
p14_name=random.seed
p14_optional=
p14_prefix=
p14_prefix_when_specified=
p14_type=java.lang.String
p14_value=
p15_MODE=
p15_TYPE=TEXT
p15_default_value=false
p15_description=Whether to create SVG images (compressed) along with PNGs
p15_fileFormat=
p15_flag=
p15_name=create.svgs
p15_optional=
p15_prefix=
p15_prefix_when_specified=
p15_type=java.lang.String
p15_value=false;true
p16_MODE=
p16_TYPE=TEXT
p16_default_value=<ranked.list_basename>.zip
p16_description=Name of the output ZIP file.
p16_fileFormat=
p16_flag=
p16_name=output.file.name
p16_optional=on
p16_prefix=
p16_prefix_when_specified=-output_file_name 
p16_type=java.lang.String
p16_value=
p17_MODE=
p17_TYPE=TEXT
p17_default_value=
p17_description=Semicolon-separated list of gene sets from the provided gene sets database files (GMT/GMX/GRP).  If you are using multiple files then you *must* prefix each selected gene set with its file name followed by '\#' (like "my_file1.gmt\#selected_gene_set1,my_file2.gmt\#selected_gene_set2").  With a single file only the names are necessary.  Leave this blank to select all gene sets.
p17_fileFormat=
p17_flag=
p17_name=selected.gene.sets
p17_optional=on
p17_prefix=
p17_prefix_when_specified=-selected_gene_sets 
p17_type=java.lang.String
p17_value=
p18_MODE=
p18_TYPE=TEXT
p18_default_value=
p18_description=Optional alternate delimiter character for gene set names instead of comma for use with selected.gene.sets.  If used, a semicolon is recommended.
p18_fileFormat=
p18_flag=
p18_name=alt.delim
p18_optional=on
p18_prefix=
p18_prefix_when_specified=--altDelim\=
p18_type=java.lang.String
p18_value=
p19_MODE=
p19_TYPE=TEXT
p19_default_value=false
p19_description=Enable developer mode.
p19_fileFormat=
p19_flag=
p19_name=dev.mode
p19_optional=
p19_prefix=
p19_prefix_when_specified=
p19_type=java.lang.String
p19_value=false;true
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Rank ordered gene list - .rnk
p1_fileFormat=rnk
p1_flag=
p1_name=ranked.list
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_choiceDir=https\://www.gsea-msigdb.org/gsea/msigdb/gp_modules_gmt.json
p2_default_value=
p2_description=Gene sets database from GSEA website.
p2_fileFormat=gmt;gmx;grp
p2_flag=
p2_name=gene.sets.database
p2_numValues=1+
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=
p3_TYPE=Integer
p3_default_value=1000
p3_description=Number of permutations to perform
p3_fileFormat=
p3_flag=
p3_name=number.of.permutations
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.Integer
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=Remap_Only
p4_description=Select whether to collapse each probe set in the expression dataset into a single vector for the gene, which gets identified by its gene symbol.  It is also possible to remap symbols from one namespace to another without collapsing (an error will occur if multiple source genes map to a single destination gene).  No_Collapse will use the dataset as-is.
p4_fileFormat=
p4_flag=
p4_name=collapse.dataset
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=No_Collapse;Collapse;Remap_Only
p5_MODE=IN
p5_TYPE=FILE
p5_choiceDir=https\://www.gsea-msigdb.org/gsea/msigdb/gp_modules_chip.json
p5_default_value=
p5_description=DNA Chip (array) annotation file from GSEA website.  Upload your own chip file if the one corresponding to your DNA Microarray platform is not listed in the drop-down menu.  A chip file is only required if collapse dataset is set to true.
p5_fileFormat=chip
p5_flag=
p5_name=chip.platform.file
p5_optional=on
p5_prefix=-chip 
p5_prefix_when_specified=-chip 
p5_type=java.io.File
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=weighted
p6_description=The statistic used to score hits (gene set members) and misses (non-members)
p6_fileFormat=
p6_flag=
p6_name=scoring.scheme
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=classic\=classic Kolmogorov-Smirnov;weighted;weighted_p2;weighted_p1.5
p7_MODE=
p7_TYPE=Integer
p7_default_value=500
p7_description=Gene sets larger than this are excluded from the analysis
p7_fileFormat=
p7_flag=
p7_name=max.gene.set.size
p7_optional=
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.Integer
p7_value=
p8_MODE=
p8_TYPE=Integer
p8_default_value=15
p8_description=Gene sets smaller than this are excluded from the analysis
p8_fileFormat=
p8_flag=
p8_name=min.gene.set.size
p8_optional=
p8_prefix=
p8_prefix_when_specified=
p8_type=java.lang.Integer
p8_value=
p9_MODE=
p9_TYPE=TEXT
p9_default_value=Abs_max_of_probes
p9_description=Collapsing mode.  This has no effect when remapping symbols.  For custom ranking metrics, be very cautious when selecting any of these modes to be sure it is compatible with your metric. 
p9_fileFormat=
p9_flag=
p9_name=collapsing.mode.for.probe.sets.with.more.than.one.match
p9_optional=
p9_prefix=
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=Abs_max_of_probes;Max_probe;Median_of_probes;Mean_of_probes;Sum_of_probes
pipelineModel=
privacy=public
publicationDate=10/03/2022 15\:31 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskDoc=doc.html
taskType=Pathway Analysis
userid=eby@broadinstitute.org
version=10/03/2022 \: Fixed a manifest typo. Updated to Human MSigDB v2022.1.Hs. Direct support for Mouse MSigDB 2022.1.Mm is not yet available
