# GSEALeadingEdgeViewer  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.visualizer:00073:6
#Tue Feb 10 19:11:47 UTC 2026
JVMLevel=1.8
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.visualizer\:00073\:6
author=GenePattern
categories=gsea
commandLine=<java> <java_flags> -cp <libdir>gsea-4.2.3.jar<path.separator><libdir>batik-codec-1.10.jar org.genepattern.gsea.LeadingEdgeWidget <zip.file> 
cpuType=any
description=Leading Edge Viewer for GSEA results
documentationUrl=https\://genepattern.github.io/GSEALeadingEdgeViewer/v6/
language=Java
name=GSEALeadingEdgeViewer
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=zip output file from GSEA - .zip. 
p1_fileFormat=zip
p1_name=zip.file
p1_optional=on
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
privacy=public
publicationDate=03/02/2022 19\:36 
quality=production
src.repo=https\://github.com/genepattern/GSEALeadingEdgeViewer/tree/v5.1
taskType=Visualizer
userid=GenePattern
version=Updated to the GSEA 4.2.3 code base, removing Log4J entirely from the code base.
