# Harmony  urn:lsid:genepattern.org:module.analysis:00435:6
#Tue Feb 10 19:11:47 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00435\:6
author=Justin Lee;GenePattern Team
commandLine=Rscript /opt/genepatt/src/Harmony_Wrapper_Script.R --file_list <Input.RDS.Files> --output_file <Output.Name>  <Data.Set.Labels>  <Colors>  <reduction>  <dims.use>  <theta>  <lambda>  <sigma>  <nclust>  <tau>  <block.size>  <max.iter.harmony>  <max.iter.cluster>  <epsilon.cluster>  <epsilon.harmony>  <plot_convergence>  <verbose>  <reference_values>  <reduction.save>  <project.dim>  <assay.use> <stop.early.cluster>  <stop.early.harmony> <Group.Name> <Animate> <animation.iterations>
cpuType=any
description=Harmony is a batch correction tool. Upon use, this module will produce three scatterplots. One plot will show the data pre-Harmony, and can be found in the 'BeforeHarmonyPlot.png' file. In this plot, the x and y axes represent the 1st and 2nd principal components from PCA dimensional reduction (unless specified otherwise by the user). Another plot will show the data post-Harmony, and can be found in the 'AfterHarmonyPlot.png' file. In this plot, the x and y axes the same dimensions used in the pre-Harmony plot are shown, but adjusted by Harmony. Lastly, the third plot shows the pre-Harmony and post-Harmony plots side by side for comparison.
documentationUrl=https\://github.com/genepattern/Harmony/blob/develop/README.md
fileFormat=
job.cpuCount=
job.docker.image=genepattern/harmony\:v1
job.memory=
job.walltime=
language=any
name=Harmony
os=any
p10_MODE=
p10_TYPE=Floating Point
p10_default_value=1
p10_description=Ridge regression penalty parameter. Specify for each variable in group.by.vars. Lambda must be strictly positive. Smaller values result in more aggressive correction.\nDefault\: 1
p10_fileFormat=
p10_flag=--lambda 
p10_name=lambda
p10_numValues=0..1
p10_optional=on
p10_prefix=--lambda 
p10_prefix_when_specified=--lambda 
p10_range=0+
p10_type=java.lang.Float
p10_value=
p11_MODE=
p11_TYPE=Floating Point
p11_default_value=0.1
p11_description=Width of soft kmeans clusters. Sigma scales the distance from a cell to cluster centroids. Larger values of sigma result in cells assigned to more clusters. Smaller values of sigma make soft kmeans cluster approach hard clustering.\nDefault\: 0.1
p11_fileFormat=
p11_flag=--sigma 
p11_name=sigma
p11_numValues=0..1
p11_optional=on
p11_prefix=--sigma 
p11_prefix_when_specified=--sigma 
p11_type=java.lang.Float
p11_value=
p12_MODE=
p12_TYPE=Integer
p12_default_value=
p12_description=Number of clusters in model. nclust \= 1 equivalent to simple linear regression.
p12_fileFormat=
p12_flag=--nclust 
p12_name=nclust
p12_numValues=0..1
p12_optional=on
p12_prefix=--nclust 
p12_prefix_when_specified=--nclust 
p12_type=java.lang.Integer
p12_value=
p13_MODE=
p13_TYPE=Integer
p13_default_value=0
p13_description=Protection against overclustering small datasets with large ones. tau is the expected number of cells per cluster.\nDefault\: 0
p13_fileFormat=
p13_flag=--tau 
p13_name=tau
p13_numValues=0..1
p13_optional=on
p13_prefix=--tau 
p13_prefix_when_specified=--tau 
p13_range=1+
p13_type=java.lang.Integer
p13_value=
p14_MODE=
p14_TYPE=Floating Point
p14_default_value=0.05
p14_description=What proportion of cells to update during clustering. Between 0 to 1. Larger values may be faster but less accurate.\nDefault\: 0.05
p14_fileFormat=
p14_flag=--block.size 
p14_name=block.size
p14_numValues=0..1
p14_optional=on
p14_prefix=--block.size 
p14_prefix_when_specified=--block.size 
p14_range=0..1
p14_type=java.lang.Float
p14_value=
p15_MODE=
p15_TYPE=Integer
p15_default_value=10
p15_description=Maximum number of iterations that Harmony will run.\nDefault\: 10
p15_fileFormat=
p15_flag=--max.iter.harmony 
p15_name=max.iter.harmony
p15_numValues=0..1
p15_optional=on
p15_prefix=--max.iter.harmony 
p15_prefix_when_specified=--max.iter.harmony 
p15_type=java.lang.Integer
p15_value=
p16_MODE=
p16_TYPE=Integer
p16_default_value=20
p16_description=Maximum number of rounds to run clustering at each round of Harmony. \nDefault\: 20
p16_fileFormat=
p16_flag=--max.iter.cluster 
p16_name=max.iter.cluster
p16_numValues=0..1
p16_optional=on
p16_prefix=--max.iter.cluster 
p16_prefix_when_specified=--max.iter.cluster 
p16_type=java.lang.Integer
p16_value=
p17_MODE=
p17_TYPE=TEXT
p17_default_value=TRUE
p17_description=Whether or not to stop clustering early. If TRUE, then the convergence tolerance is specified by the epsilon cluster parameter.\nDefault\: TRUE
p17_fileFormat=
p17_flag=--stop.early.cluster 
p17_name=stop.early.cluster
p17_numValues=0..1
p17_optional=on
p17_prefix=--stop.early.cluster 
p17_prefix_when_specified=--stop.early.cluster 
p17_type=java.lang.String
p17_value=TRUE\=TRUE;FALSE\=FALSE
p18_MODE=
p18_TYPE=Floating Point
p18_default_value=0.00005
p18_description=Convergence tolerance for clustering round of Harmony. A higher value indicates less tolerance, while a lower value indicates more tolerance.\nDefault\: 0.00005
p18_fileFormat=
p18_flag=--epsilon.cluster 
p18_name=epsilon.cluster
p18_numValues=0..1
p18_optional=on
p18_prefix=--epsilon.cluster 
p18_prefix_when_specified=--epsilon.cluster 
p18_type=java.lang.Float
p18_value=
p19_MODE=
p19_TYPE=TEXT
p19_default_value=TRUE
p19_description=Whether or not to stop harmony early. If TRUE, then the convergence tolerance is specified by the epsilon harmony parameter.\nDefault\: TRUE
p19_fileFormat=
p19_flag=--stop.early.harmony 
p19_name=stop.early.harmony
p19_numValues=0..1
p19_optional=on
p19_prefix=--stop.early.harmony 
p19_prefix_when_specified=--stop.early.harmony 
p19_type=java.lang.String
p19_value=TRUE\=TRUE;FALSE\=FALSE
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=List of two or more Seurat objects to read in. The objects must be in .rds files.
p1_fileFormat=.rds
p1_flag=--file_list
p1_name=Input.RDS.Files
p1_numValues=2+
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p20_MODE=
p20_TYPE=Floating Point
p20_default_value=0.0004
p20_description=Convergence tolerance for Harmony. A higher value indicates less tolerance, while a lower value indicates more tolerance.\nDefault\: 0.0004
p20_fileFormat=
p20_flag=--epsilon.harmony 
p20_name=epsilon.harmony
p20_numValues=0..1
p20_optional=on
p20_prefix=--epsilon.harmony 
p20_prefix_when_specified=--epsilon.harmony 
p20_type=java.lang.Float
p20_value=
p21_MODE=
p21_TYPE=TEXT
p21_default_value=FALSE
p21_description=Whether to print the convergence plot of the clustering objective function. TRUE to plot, FALSE to suppress. This can be useful for debugging.\nDefault\: FALSE
p21_fileFormat=
p21_flag=--plot_convergence 
p21_name=plot_convergence
p21_numValues=0..1
p21_optional=on
p21_prefix=--plot_convergence 
p21_prefix_when_specified=--plot_convergence 
p21_type=java.lang.String
p21_value=TRUE\=TRUE;FALSE\=FALSE
p22_MODE=
p22_TYPE=TEXT
p22_default_value=TRUE
p22_description=Whether to print progress messages. TRUE to print, FALSE to suppress.\nDefault\: TRUE
p22_fileFormat=
p22_flag=--verbose 
p22_name=verbose
p22_numValues=0..1
p22_optional=on
p22_prefix=--verbose 
p22_prefix_when_specified=--verbose 
p22_type=java.lang.String
p22_value=TRUE\=TRUE;FALSE\=FALSE
p23_MODE=
p23_TYPE=TEXT
p23_default_value=
p23_description=Defines reference dataset(s). Cells that have batch variables values matching reference_values will not be moved
p23_fileFormat=
p23_flag=--reference_values 
p23_name=reference_values
p23_numValues=0..1
p23_optional=on
p23_prefix=--reference_values 
p23_prefix_when_specified=--reference_values 
p23_type=java.lang.String
p23_value=
p24_MODE=
p24_TYPE=TEXT
p24_default_value=harmony
p24_description=Keyword to save Harmony reduction. Useful if you want to try Harmony with multiple parameters and save them as e.g. 'harmony_theta0', 'harmony_theta1', 'harmony_theta2'. \nDefault\: harmony
p24_fileFormat=
p24_flag=--reduction.save 
p24_name=reduction.save
p24_numValues=0..1
p24_optional=on
p24_prefix=--reduction.save 
p24_prefix_when_specified=--reduction.save 
p24_type=java.lang.String
p24_value=
p25_MODE=
p25_TYPE=TEXT
p25_default_value=
p25_description=Which assay to run PCA on if no PCA present?
p25_fileFormat=
p25_flag=--assay.use 
p25_name=assay.use
p25_numValues=0..1
p25_optional=on
p25_prefix=--assay.use 
p25_prefix_when_specified=--assay.use 
p25_type=java.lang.String
p25_value=
p26_MODE=
p26_TYPE=TEXT
p26_default_value=TRUE
p26_description=Project dimension reduction loadings. \nDefault\: TRUE
p26_fileFormat=
p26_flag=--project.dim 
p26_name=project.dim
p26_numValues=0..1
p26_optional=on
p26_prefix=--project.dim 
p26_prefix_when_specified=--project.dim 
p26_type=java.lang.String
p26_value=TRUE\=TRUE;FALSE\=FALSE
p27_MODE=
p27_TYPE=Integer
p27_default_value=3
p27_description=Number of iterations to animate.
p27_fileFormat=
p27_flag=--animation.iterations 
p27_name=animation.iterations
p27_numValues=0..1
p27_optional=on
p27_prefix=--animation.iterations 
p27_prefix_when_specified=--animation.iterations 
p27_type=java.lang.Integer
p27_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=harmonized_data
p2_description=Name of the file to save the data to.
p2_fileFormat=
p2_flag=--output_file
p2_name=Output.Name
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=
p3_description=Labels of the datasets, separated by commas. These labels will assigned in the order of the input RDS files. The dataset names will be assigned to the file names by default.
p3_fileFormat=
p3_flag=--data_sets 
p3_name=Data.Set.Labels
p3_numValues=0..1
p3_optional=on
p3_prefix=--data_sets 
p3_prefix_when_specified=--data_sets 
p3_type=java.lang.String
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=dataset_name
p4_description=The name of the group that you would like to color by during the visualization steps. Harmony will color by dataset by default.\nDefault\: dataset_name
p4_fileFormat=
p4_flag=--group_name 
p4_name=Group.Name
p4_numValues=0..1
p4_optional=on
p4_prefix=--group_name 
p4_prefix_when_specified=--group_name 
p4_type=java.lang.String
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=
p5_description=The colors you want to use to label the groups specified by the "Group Name" parameter, separated by commas. If no colors are specified, then colors will be automatically assigned. Refer to this link to see the list of colors you can choose from\: https\://www.datanovia.com/en/blog/awesome-list-of-657-r-color-names/
p5_fileFormat=
p5_flag=--colors 
p5_name=Colors
p5_numValues=0..1
p5_optional=on
p5_prefix=--colors 
p5_prefix_when_specified=--colors 
p5_type=java.lang.String
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=FALSE
p6_description=Whether or not to produce an animation of the Harmony iterations.
p6_fileFormat=
p6_flag=--animate 
p6_name=Animate
p6_numValues=0..1
p6_optional=on
p6_prefix=--animate 
p6_prefix_when_specified=--animate 
p6_type=java.lang.String
p6_value=FALSE\=NO;TRUE\=YES
p7_MODE=
p7_TYPE=TEXT
p7_default_value=pca
p7_description=Name of dimension reduction to use. \nDefault\: pca
p7_fileFormat=
p7_flag=--reduction 
p7_name=reduction
p7_numValues=0..1
p7_optional=on
p7_prefix=--reduction 
p7_prefix_when_specified=--reduction 
p7_type=java.lang.String
p7_value=
p8_MODE=
p8_TYPE=Integer
p8_default_value=
p8_description=Which PCA dimensions to use for Harmony. The PCA dimensions specified should be in numerical form and separated by commas. By default, use all
p8_fileFormat=
p8_flag=--dims.use 
p8_name=dims.use
p8_numValues=0..1
p8_optional=on
p8_prefix=--dims.use 
p8_prefix_when_specified=--dims.use 
p8_type=java.lang.Integer
p8_value=
p9_MODE=
p9_TYPE=Floating Point
p9_default_value=2
p9_description=Diversity clustering penalty parameter. Specify for each variable in group.by.vars. theta \= 0 does not encourage any diversity. Larger values of theta result in more diverse clusters.\nDefault\: 2
p9_fileFormat=
p9_flag=--theta 
p9_name=theta
p9_numValues=0..1
p9_optional=on
p9_prefix=--theta 
p9_prefix_when_specified=--theta 
p9_type=java.lang.Float
p9_value=
privacy=public
publicationDate=05/29/2024 15\:26 
quality=production
src.repo=https\://github.com/genepattern/Harmony
taskDoc=
taskType=
userid=jzl010
version=changed default values to be blank
