# HeatMapViewer  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.visualizer:00010:13.11
#Tue Feb 10 19:11:47 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.visualizer\:00010\:13.11
author=GenePattern
commandLine=heatmap.html ? <dataset>
cpuType=any
description=A configurable heat map viewer that provides users with several options for manipulating and visualizing array-based data
language=HTML,JQuery
name=HeatMapViewer
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The dataset to display - .gct
p1_fileFormat=res;gct;odf;Dataset
p1_name=dataset
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
privacy=public
publicationDate=07/14/2021 17\:53 
quality=preproduction
src.repo=https\://github.com/genepattern/HeatMapViewer.git
taskDoc=doc.html
taskType=javascript
userid=GenePattern
version=Bug fix to support S3 files
