# HierarchicalClusteringViewer  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.visualizer:00031:11.5
#Tue Feb 10 19:11:48 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.visualizer\:00031\:11.5
author=Marc-Danie Nazaire, Thorin Tabor
commandLine=hclViewer.html ? <cdt.file> <gtr.file> <atr.file>
cpuType=any
description=Views results of hierarchical clustering.
language=HTML,jQuery
name=HierarchicalClusteringViewer
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Clustered data table, contains the original data, but reordered
p1_fileFormat=cdt
p1_name=cdt.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Gene tree file, records the order in which genes (rows) were joined (at least one of gtr file and atr file is required)
p2_fileFormat=gtr
p2_name=gtr.file
p2_optional=on
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=Array tree file, records the order in which samples (columns) were joined (at least one of gtr file and atr file is required)
p3_fileFormat=atr
p3_name=atr.file
p3_optional=on
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
privacy=public
publicationDate=07/15/2021 12\:08 
quality=preproduction
src.repo=https\://github.com/genepattern/HierarchicalClusteringViewer.git
taskType=javascript
userid=GenePattern (gp-help@broadinstitute.org)
version=Bug fix for S3 files
