# HISAT2.indexer  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00368:1.9
#Tue Feb 10 19:11:48 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00368\:1.9
author=Ted Liefeld;UCSD
categories=RNA-Seq
commandLine=python <libdir>/hisat_indexer_wrapper.py <gtf.file> -fasta <fasta.file> -indexname <index.name.prefix> -dryRun <dry.run>
cpuType=any
description=Indexes one or more Fasta files for use in the HISAT2.aligner.  
documentationUrl=https\://genepattern.github.io/HISAT2.indexer/v2/
fileFormat=
job.docker.image=genepattern/docker-hisat2\:v0.12
language=any
name=HISAT2.indexer
os=any
p1_MODE=
p1_TYPE=TEXT
p1_default_value=genome
p1_description=The name prefix of the resulting index files and of the zip file which contains them.
p1_fileFormat=
p1_flag=-indexname 
p1_name=index.name.prefix
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=ja 
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=One or more FASTA files (or a zip file containing one or more FASTA files) containing the reference sequences to be aligned to. E.g., <reference_in> might be chr1.fa,chr2.fa,chrX.fa,chrY.fa.
p2_fileFormat=fasta
p2_flag=-fasta 
p2_name=fasta.file
p2_numValues=1+
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=Optional GTF file with information about exons.  If present this will run extract_exons.py and extrac_splice_sites.py on the GTF file and then add the splice sites and exons to the index
p3_fileFormat=gtf
p3_flag=-gtf 
p3_name=gtf.file
p3_numValues=0..1
p3_optional=on
p3_prefix=-gtf 
p3_prefix_when_specified=-gtf 
p3_type=java.io.File
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=False
p4_description=If true, this just generates the hisat2 command lines and exits without executing.
p4_fileFormat=
p4_flag=-dryRun 
p4_name=dry.run
p4_numValues=0..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=True\=True;False\=False
privacy=public
publicationDate=01/18/2022 12\:33 
quality=preproduction
src.repo=https\://github.com/genepattern/HISAT2.indexer/tree/v1.9
taskDoc=doc.html
taskType=RNA-Seq
userid=ted
version=Updating module name and doc location
