# HTSeq.Count  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00412:4
#Tue Feb 10 19:11:48 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00412\:4
author=Barbara Hill;Broad Institute, Guy Bottu;VIB BioinformaticsCore
categories=RNA-seq
commandLine=/htseq_count/htseqcount_input_detect_and_sort.py --htseqcount htseq-count --input <input.files> <sample.names> --gtf <GTF.file> --strand <strandedness> --minqual <min.qual> --mode <mode> --nonunique <count.nonunique> --secondary <count.secondary> --supplementary <count.supplementary> --featuretype <feature.type> --idtype <id.type> <gene.name> --output <output.file> --outformat <output.format>
cpuType=any
description=Takes alignment files in SAM/BAM format and a feature file in GTF/GFF format (usually with exon annotation), name sorts the alignment file and calculates for each sample the number of reads mapping to each feature. (HTSeq.count v0.11.2)
fileFormat=bam;sam
job.docker.image=genepattern/htseq_count\:0.6
language=Python
name=HTSeq.Count
os=any
p10_MODE=
p10_TYPE=TEXT
p10_default_value=exon
p10_description=Name in the 3<sup>rd</sup> column of the GTF/GFF input file that is used to identify the features that must be counted.
p10_fileFormat=
p10_flag=--featuretype 
p10_name=feature.type
p10_numValues=1..1
p10_optional=
p10_prefix=
p10_prefix_when_specified=
p10_type=java.lang.String
p10_value=
p11_MODE=
p11_TYPE=TEXT
p11_default_value=gene_id
p11_description=GTF/GFF attribute used to group features.
p11_fileFormat=
p11_flag=--idtype 
p11_name=id.type
p11_numValues=1..1
p11_optional=
p11_prefix=
p11_prefix_when_specified=
p11_type=java.lang.String
p11_value=
p12_MODE=
p12_TYPE=TEXT
p12_default_value=
p12_description=GTF/GFF attribute with the name of the gene or some other information that can help to identify the gene in a more user-friendly way than the ID (optional). If you fill this in an extra column will be added to the output table. For Ensembl data <b>gene_id</b> is suitable.
p12_fileFormat=
p12_flag=--genename 
p12_name=gene.name
p12_numValues=0..1
p12_optional=on
p12_prefix=--genename 
p12_prefix_when_specified=--genename 
p12_type=java.lang.String
p12_value=
p13_MODE=
p13_TYPE=TEXT
p13_default_value=HTSeq.counts
p13_description=output file name - <i>Inputfile_Basename.Output_Filename</i> (if you choose GCT format .gct will automatically be added)
p13_fileFormat=
p13_flag=--output 
p13_name=output.file
p13_numValues=1..1
p13_optional=
p13_prefix=
p13_prefix_when_specified=
p13_type=java.lang.String
p13_value=
p14_TYPE=TEXT
p14_default_value=htseq
p14_description=
p14_fileFormat=
p14_flag=--outformat 
p14_name=output.format
p14_numValues=1..1
p14_optional=
p14_prefix=
p14_prefix_when_specified=
p14_type=java.lang.String
p14_value=htseq\=raw HTSeq format;excel\=with header added, suitable for import in Excel;gct\=GCT
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input file(s) in SAM or BAM format.
p1_fileFormat=bam;sam
p1_flag=--input 
p1_name=input.files
p1_numValues=1+
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Text file with the names of the samples, one per line (optional and only relevant if you request Excel or GCT format). The names in the file must be in the same order as the input SAM/BAM files. If you do not provide a file the sample names will be derived from the SAM/BAM file names.
p2_fileFormat=txt
p2_flag=--names 
p2_name=sample.names
p2_numValues=0..1
p2_optional=on
p2_prefix=--names 
p2_prefix_when_specified=--names 
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_choiceDir=https\://datasets.genepattern.org/gpftp/module_support_files/annotation/index_directory_htseq.json
p3_choiceDirFilter=
p3_default_value=
p3_description=A GTF or GFF file containing a list of gene model annotations. (This file can be gzipped)
p3_fileFormat=gff;gff3;gtf;gtf.gz;gff.gz;gff3.gz
p3_flag=--gtf 
p3_name=GTF.file
p3_numValues=1..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=yes
p4_description=none \: a read is considered overlapping with a feature regardless of whether it is mapped to the same or the opposite strand as the feature.\n<p>\nforward \: a single-end read has to be mapped to the same strand as the feature, for paired-end reads  the first read has to be on the same strand and the second read on the opposite strand.\n<p>\nreverse \: the above rules are reversed.\n<p>\n<b><i>set to 'none' if your input file contains no strand information.</i></b>
p4_fileFormat=
p4_flag=--strand 
p4_name=strandedness
p4_numValues=1..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=no\=none;yes\=forward;reverse\=reverse
p5_MODE=
p5_TYPE=Integer
p5_default_value=10
p5_description=Minimum quality to accept a read.
p5_fileFormat=
p5_flag=--minqual 
p5_name=min.qual
p5_numValues=1..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_range=0+
p5_type=java.lang.Integer
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=union
p6_description=Mode to handle reads overlapping more than one feature. Consult the documentation for a full explanation.
p6_fileFormat=
p6_flag=--mode 
p6_name=mode
p6_numValues=1..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=union\=union;intersection-strict\=intersection-strict;intersection-nonempty\=intersection-nonempty
p7_MODE=
p7_TYPE=TEXT
p7_default_value=none
p7_description=Whether to count reads that are not uniquely aligned or are ambiguously assigned to features.
p7_fileFormat=
p7_flag=--nonunique 
p7_name=count.nonunique
p7_numValues=1..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=all\=yes;none\=no
p8_MODE=
p8_TYPE=TEXT
p8_default_value=ignore
p8_description=Whether to count secondary alignments (which are marked in the SAM/BAM file by a 0x100 flag).
p8_fileFormat=
p8_flag=--secondary 
p8_name=count.secondary
p8_numValues=1..1
p8_optional=
p8_prefix=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=score\=yes;ignore\=no
p9_MODE=
p9_TYPE=TEXT
p9_default_value=ignore
p9_description=Whether to count supplementary alignments (which are marked in the SAM/BAM file by a 0x800 flag).
p9_fileFormat=
p9_flag=--supplementary 
p9_name=count.supplementary
p9_numValues=1..1
p9_optional=
p9_prefix=
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=score\=yes;ignore\=no
privacy=public
publicationDate=02/08/2023 14\:48 
quality=production
src.repo=https\://github.com/genepattern/HTSeq.Count/releases/tag/v3.0
taskDoc=htseq_count_doc.html
taskType=RNA-seq
userid=bhill@broadinstitute.org
version=Modified to use datasets.genepattern.org instead of ftp\://gpftp.broadinstitutue.org as source for default gtf files 
