# Hu68kHu35kAtoU95  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00011:1
#Tue Feb 10 19:11:49 UTC 2026
JVMLevel=any
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00011\:1
author=Justin Lamb (gp-help@broad.mit.edu)
className=edu.mit.wi.omnigene.service.analysis.genepattern.GenePatternAnalysisTask
commandLine=<perl> <libdir>GCM_to_U95.pl <input.filename> <output> <libdir>
cpuType=any
description=Converts a list of Affymetrix Hu6800/Hu35KsubA probes to the corresponding Affymetrix U95Av2 probes.
language=Perl
name=Hu68kHu35kAtoU95
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=the .pol, .tag or .grp file to be converted
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<input.filename_basename>.U95
p2_description=name of the output file (same format as input file)
p2_name=output
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
pipelineModel=
privacy=public
quality=production
serializedModel=
taskType=Preprocess & Utilities
userid=GenePattern (gp-info@broad.mit.edu)
version=Updated documentation
