# igv.js  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00363:2.5
#Tue Feb 10 19:11:49 UTC 2026
JVMLevel=1.6
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00363\:2.5
author=Barbara Hill, Marc-Danie Nazaire, Thorin Tabor, Jim Robinson, Peter Carr (Broad Institute)
categories=viewer
commandLine=igv_web.html ? <input.file> <index.file> <genome> <locus>
cpuType=any
description=Launches igv.js with input file(s)
fileFormat=
language=Javascript
name=igv.js
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Track dataset to be viewed in igv.js
p1_fileFormat=bam;bed;cbs.txt;clm;cls;cn;Comparative Marker Selection;csv;Dataset;gct;glad;igv;loh;maf;Matrix;sam;res;seg;snp;txt;xcn;xls;xml;zip;gff;gff3;gtf;wig;psl;bedgraph;bw;bigwig;bb;bigbed;tdf;vcf;gz
p1_name=input.file
p1_numValues=1+
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_url=on
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=The index file (i.e .bai, .idx, or .tbi).
p2_fileFormat=bai;sai;idx;tbi;gz
p2_name=index.file
p2_numValues=0+
p2_optional=on
p2_prefix_when_specified=-i
p2_type=java.io.File
p2_url=on
p2_value=
p3_default_value=
p3_description=Choose the genome for your data.
p3_fileFormat=
p3_name=genome
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=\=Select a genome;none\=Custom genome (provide files below);hg38\=Human (GRCh38/hg38);hg19\=Human (CRCh37/hg19);hg18\=Human (hg18);mm10\=Mouse (GRCm38/mm10);panTro4\=Chimp (SAC 2.1.4/panTro4);panPan2\=Bonobo (MPI-EVA panpan1.1/panPan2);bosTau8\=Cow (UMD_3.1.1/bosTau8);ce11\=C. elegans (ce11);canFam3\=Dog (Broad CanFam3.1/canFam3);dm6\=D. melanogaster (dm6);gorGor4\=Gorilla (gorGor4.1/gorGor4);susScr11\=Pig (SGSC Sscrofa11.1/susScr11);rn6\=Rat (RGCS 6.0/rn6);sacCer3\=S. cerevisiae (sacCer3);danRer11\=Zebrafish (GRCZ11/danRer11);danRer10\=Zebrafish (GRCZ10/danRer10)
p4_MODE=IN
p4_TYPE=FILE
p4_default_value=
p4_description=Fasta file to use for a reference genome. Only necessary if genome is not provided above.
p4_fileFormat=fasta;fa
p4_name=genome.fasta.file
p4_numValues=0..1
p4_optional=on
p4_prefix_when_specified=
p4_type=java.io.File
p4_url=on
p4_value=
p5_MODE=IN
p5_TYPE=FILE
p5_default_value=
p5_description=Index file to use for a reference genome. Only necessary if genome is not provided above.
p5_fileFormat=fai
p5_name=genome.index.file
p5_numValues=0..1
p5_optional=on
p5_prefix_when_specified=
p5_type=java.io.File
p5_url=on
p5_value=
p6_MODE=IN
p6_TYPE=FILE
p6_default_value=
p6_description=Index file to use for a reference genome. Only necessary if genome is not provided above.
p6_fileFormat=txt;gz
p6_name=genome.cytoband.file
p6_numValues=0..1
p6_optional=on
p6_prefix_when_specified=
p6_type=java.io.File
p6_url=on
p6_value=
p7_default_value=
p7_description=Provide a locus or gene of interest for your data. If left blank, igv.js will launch on all.
p7_fileFormat=
p7_name=locus
p7_optional=on
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
pipelineModel=
privacy=public
publicationDate=07/14/2021 18\:27 
quality=preproduction
requiredPatchLSIDs=urn\:lsid\:broadinstitute.org\:plugin\:GenePattern_3_9_1\:0.1,
requiredPatchURLs=http\://www.broadinstitute.org/webservices/gpModuleRepository/download/dev/patch/?file\=/GenePattern_3_9_1/broadinstitute.org\:plugin/GenePattern_3_9_1/0.1/GenePattern_3_9_1.zip
serializedModel=
src.repo=https\://github.com/genepattern/igv.js.git
taskDoc=doc.html
taskType=javascript
userid=
version=Bug fix for S3 files
