# IlluminaExpressionFileCreator  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00189:2
#Tue Feb 10 19:11:49 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00189\:2
author=David Eby (eby@broadinstitute.org)
commandLine=<java> <java_flags> -cp <libdir>IlluminaExpressionFileCreator.jar<path.separator><libdir>commons-cli-1.2.jar<path.separator><libdir>commons-codec-1.4.jar<path.separator><libdir>commons-io-1.4.jar<path.separator><libdir>commons-lang-2.5.jar<path.separator><libdir>dom4j-1.6.1.jar org.genepattern.illumina.expression.ExpressionFileCreator -manifestfile <custom.manifest> -manifesturl <manifest> -inputfile <idat.zip> -outputfile <output.file> -bg <background.subtraction.mode> -collapse <collapse.mode> -chipfile <custom.chip> -chipurl <chip> -clmfile <clm>
cpuType=any
description=Creates a GCT file from a zip of Illumina IDAT files and an Illumina manifest file
fileFormat=gct
language=Java
name=IlluminaExpressionFileCreator
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Zip of Illumina IDAT files
p1_fileFormat=
p1_name=idat.zip
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=
p2_description=Illumina manifest file in tab-delimited (TXT) format. A manifest file is required; either selected from this list or specified in custom manifest below.
p2_fileFormat=
p2_name=manifest
p2_optional=on
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=\=Select a manifest file;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/HumanHT-12_V3_0_R2_11283641_A.txt\=HumanHT-12_V3_0_R2_11283641_A.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/HumanHT-12_V4_0_R2_15002873_B.txt\=HumanHT-12_V4_0_R2_15002873_B.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/HumanHT-12_V3_0_R3_11283641_A.txt\=HumanHT-12_V3_0_R3_11283641_A.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/HumanHT-12_V4_0_R1_15002873_B.txt\=HumanHT-12_V4_0_R1_15002873_B.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/HumanMI_V1_R2_XS0000122-MAP.txt\=HumanMI_V1_R2_XS0000122-MAP.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/HumanMI_V2_R0_XS0000124-MAP.txt\=HumanMI_V2_R0_XS0000124-MAP.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/HumanRef-8_V2_0_R4_11223162_A.txt\=HumanRef-8_V2_0_R4_11223162_A.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/HumanRef-8_V3_0_R1_11282963_A_WGDASL.txt\=HumanRef-8_V3_0_R1_11282963_A_WGDASL.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/HumanRef-8_V3_0_R2_11282963_A.txt\=HumanRef-8_V3_0_R2_11282963_A.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/HumanRef-8_V3_0_R3_11282963_A.txt\=HumanRef-8_V3_0_R3_11282963_A.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/HumanWG-6_V2_0_R4_11223189_A.txt\=HumanWG-6_V2_0_R4_11223189_A.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/HumanWG-6_V3_0_R2_11282955_A.txt\=HumanWG-6_V3_0_R2_11282955_A.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/HumanWG-6_V3_0_R3_11282955_A.txt\=HumanWG-6_V3_0_R3_11282955_A.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/MouseMI_V1_R2_XS0000127-MAP.txt\=MouseMI_V1_R2_XS0000127-MAP.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/MouseMI_V2_R0_XS0000129-MAP.txt\=MouseMI_V2_R0_XS0000129-MAP.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/MouseRef-8_V1_1_R4_11234312_A.txt\=MouseRef-8_V1_1_R4_11234312_A.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/MouseRef-8_V2_0_R2_11278551_A.txt\=MouseRef-8_V2_0_R2_11278551_A.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/MouseRef-8_V2_0_R3_11278551_A.txt\=MouseRef-8_V2_0_R3_11278551_A.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/MouseWG-6_V1_1_R4_11234304_A.txt\=MouseWG-6_V1_1_R4_11234304_A.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/MouseWG-6_V2_0_R2_11278593_A.txt\=MouseWG-6_V2_0_R2_11278593_A.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/MouseWG-6_V2_0_R3_11278593_A.txt\=MouseWG-6_V2_0_R3_11278593_A.txt;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/manifests/RatRef-12_V1_0_R5_11222119_A.txt\=RatRef-12_V1_0_R5_11222119_A.txt
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=Other Illumina manifest file in tab-delimited (TXT) format. A manifest file is required; either selected from the list above or specified here.
p3_fileFormat=
p3_name=custom.manifest
p3_optional=on
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_default_value=<idat.zip_basename>.gct
p4_description=Output file name
p4_fileFormat=
p4_name=output.file
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_default_value=false
p5_description=Perform background subtraction.
p5_fileFormat=
p5_name=background.subtraction.mode
p5_optional=on
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=false;true
p6_default_value=none
p6_description=Collapse probes to genes based on the manifest or CHIP file (if provided).
p6_fileFormat=
p6_name=collapse.mode
p6_optional=on
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=none;max;median
p7_default_value=
p7_description=CHIP file to map probes to genes.
p7_fileFormat=
p7_name=chip
p7_optional=on
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=\=Select a chip file;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/chip/ilmn_HumanHT_12_V3_0_R3_11283641_A.chip\=ilmn_HumanHT_12_V3_0_R3_11283641_A.chip;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/chip/ilmn_HumanHT_12_V4_0_R1_15002873_B.chip\=ilmn_HumanHT_12_V4_0_R1_15002873_B.chip;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/chip/ilmn_HumanRef_8_V2_0_R4_11223162_A.chip\=ilmn_HumanRef_8_V2_0_R4_11223162_A.chip;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/chip/ilmn_HumanReF_8_V3_0_R1_11282963_A_WGDASL.chip\=ilmn_HumanReF_8_V3_0_R1_11282963_A_WGDASL.chip;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/chip/ilmn_HumanRef_8_V3_0_R3_11282963_A.chip\=ilmn_HumanRef_8_V3_0_R3_11282963_A.chip;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/chip/ilmn_HumanWG_6_V2_0_R4_11223189_A.chip\=ilmn_HumanWG_6_V2_0_R4_11223189_A.chip;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/chip/ilmn_HumanWG_6_V3_0_R3_11282955_A.chip\=ilmn_HumanWG_6_V3_0_R3_11282955_A.chip;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/chip/ilmn_MouseRef_8_V1_1_R4_11234312_A.chip\=ilmn_MouseRef_8_V1_1_R4_11234312_A.chip;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/chip/ilmn_MouseRef_8_V2_0_R3_11278551_A.chip\=ilmn_MouseRef_8_V2_0_R3_11278551_A.chip;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/chip/ilmn_MouseWG_6_V1_1_R4_11234304_A.chip\=ilmn_MouseWG_6_V1_1_R4_11234304_A.chip;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/chip/ilmn_MouseWG_6_V2_0_R3_11278593_A.chip\=ilmn_MouseWG_6_V2_0_R3_11278593_A.chip;ftp\://ftp.broadinstitute.org/pub/genepattern/modules/IlluminaExpressionFileCreator/chip/ilmn_RatRef_12_V1_0_R5_11222119_A.chip\=ilmn_RatRef_12_V1_0_R5_11222119_A.chip
p8_MODE=IN
p8_TYPE=FILE
p8_default_value=
p8_description=Other CHIP file to map probes to genes.
p8_fileFormat=
p8_name=custom.chip
p8_optional=on
p8_prefix_when_specified=
p8_type=java.io.File
p8_value=
p9_MODE=IN
p9_TYPE=FILE
p9_default_value=
p9_description=CLM file to map file names to sample names.
p9_fileFormat=
p9_name=clm
p9_optional=on
p9_prefix_when_specified=
p9_type=java.io.File
p9_value=
pipelineModel=
privacy=public
publicationDate=05/12/2011 03\:04 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Preprocess & Utilities
userid=cwill
version=Improved handling of manifests and zip files; removed required string "_Grn" in input filenames
