# JavaTreeView  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.visualizer:00063:2
#Tue Feb 10 19:11:49 UTC 2026
JVMLevel=1.4
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.visualizer\:00063\:2
author=Joshua Gould, Broad Institute
commandLine=<java> <java_flags> -cp <libdir>TreeView.jar<path.separator><libdir>GIFEncoder.jar<path.separator><libdir>nanoxml-2.2.2.jar TreeView -f <cdt.filename> <gtr.filename> <atr.filename> 
cpuType=any
description=Hierarchical clustering viewer that reads in Eisen's cdt, atr, and gtr files. A detailed description of these formats is available from http\://microarray.ccgb.umn.edu/smd/html/MicroArray/help/formats.shtml
language=Java
name=JavaTreeView
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Clustered data table, contains the original data, but reordered
p1_fileFormat=cdt
p1_name=cdt.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Gene Tree file, records the order in which genes (rows) were joined (at least one of gtr filename and atr filename is required)
p2_fileFormat=gtr
p2_name=gtr.filename
p2_optional=on
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=Array Tree file, records the order in which samples (columns) were joined (at least one of gtr filename and atr filename is required)
p3_fileFormat=atr
p3_name=atr.filename
p3_optional=on
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
pipelineModel=
privacy=public
publicationDate=04/13/2007 13\:25 
quality=production
serializedModel=
taskType=Visualizer
userid=GenePattern (gp-help@broad.mit.edu)
version=
