# KMeansClustering  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00081:2
#Tue Feb 10 19:11:50 UTC 2026
JVMLevel=1.4
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00081\:2
author=Marc-Danie Nazaire, gp-help@broad.mit.edu, Broad Institute
commandLine=<java> <java_flags> -cp <libdir>kmeansclustering.jar<path.separator><libdir>gp-modules.jar org.genepattern.modules.kmeans.KMeansClustering <input.filename> <output.base.name> <number.of.clusters> <seed.value> <cluster.by> <distance.metric>
cpuType=any
description=Module that performs the K-Means Clustering algorithm
fileFormat=gct
language=Java
name=KMeansClustering
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=File containing data to cluster - .res, .gct, .odf
p1_fileFormat=gct;res;odf;
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<input.filename_basename>_KMcluster_output
p2_description=The base output file name - .gct
p2_name=output.base.name
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_default_value=
p3_description=Number of centroids (clusters)
p3_name=number.of.clusters
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.Integer
p3_value=
p4_default_value=12345
p4_description=Seed value for random number generator
p4_name=seed.value
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.Integer
p4_value=
p5_default_value=
p5_description=Whether to cluster by rows or columns
p5_name=cluster.by
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=0\=rows;1\=columns
p6_default_value=0
p6_description=How to compute distance between points
p6_name=distance.metric
p6_optional=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=0\=Euclidean;1\=
privacy=public
publicationDate=07/18/2010 22\:14 
quality=development
taskType=Clustering
userid=GenePattern
version=Fixed listing of acceptable input file formats
