# KNN  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00012:4
#Tue Feb 10 19:11:50 UTC 2026
JVMLevel=1.4
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00012\:4
author=Joshua Korn, Joshua Gould (Broad Institute)
commandLine=<java> <java_flags> -cp <libdir>gp-modules.jar org.genepattern.prediction.knn.KNN -t<train.filename> -c<train.class.filename> -T<test.filename> -C<test.class.filename> -o<pred.results.file> -s<saved.model.filename> -m<model.file> -n<num.features> -b<num.neighbors> -w<weighting.type> -f<feature.list.filename> -d<distance.measure> -S<feature.selection.statistic> -M<min.std>
cpuType=any
description=K-nearest neighbors classification
fileFormat=Prediction Results;KNN Prediction Model
language=Java
name=KNN
os=any
p10_MODE=IN
p10_TYPE=FILE
p10_default_value=
p10_description=features to use for prediction
p10_name=feature.list.filename
p10_optional=on
p10_prefix_when_specified=
p10_type=java.io.File
p10_value=
p11_default_value=3
p11_description=number of neighbors for KNN
p11_name=num.neighbors
p11_optional=on
p11_prefix_when_specified=
p11_type=java.lang.Integer
p11_value=
p12_default_value=distance
p12_description=weighting type for neighbors
p12_name=weighting.type
p12_optional=on
p12_prefix_when_specified=
p12_type=java.lang.String
p12_value=1\=none;2\=One-over-k;3\=distance
p13_default_value=1
p13_description=distance measure
p13_name=distance.measure
p13_optional=on
p13_prefix_when_specified=
p13_type=java.lang.String
p13_value=2\=Cosine Distance;1\=Euclidean Distance
p14_default_value=<test.filename_basename>.pred.odf
p14_description=name of output file for prediction results - .odf
p14_name=pred.results.file
p14_optional=on
p14_prefix_when_specified=
p14_type=java.lang.String
p14_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=training data file name - .gct, .res, .odf type \= Dataset, ignored if a saved model (saved.model.filename) is used
p1_fileFormat=res;gct;Dataset
p1_name=train.filename
p1_optional=on
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=class file for training data - .cls, ignored if a saved model (saved.model.filename) is used
p2_fileFormat=cls
p2_name=train.class.filename
p2_optional=on
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=input KNN model file - .odf type \= KNN Prediction Model
p3_fileFormat=KNN Prediction Model
p3_name=saved.model.filename
p3_optional=on
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_default_value=<train.filename_basename>.model
p4_description=name of output KNN model file  - .odf type \= KNN Prediction Model
p4_name=model.file
p4_optional=on
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_MODE=IN
p5_TYPE=FILE
p5_default_value=
p5_description=test data file name - .gct, .res, .odf type \= Dataset
p5_fileFormat=gct;res;Dataset
p5_name=test.filename
p5_optional=on
p5_prefix_when_specified=
p5_type=java.io.File
p5_value=
p6_MODE=IN
p6_TYPE=FILE
p6_default_value=
p6_description=class file for test data - .cls
p6_fileFormat=cls
p6_name=test.class.filename
p6_optional=on
p6_prefix_when_specified=
p6_type=java.io.File
p6_value=
p7_default_value=10
p7_description=number of selected features if feature list filename is not specified
p7_name=num.features
p7_optional=on
p7_prefix_when_specified=
p7_type=java.lang.Integer
p7_value=
p8_default_value=0
p8_description=statistic to use to perform feature selection
p8_name=feature.selection.statistic
p8_optional=on
p8_prefix_when_specified=
p8_type=java.lang.Integer
p8_value=0\=SNR;1\=T-Test;2\=SNR (median);3\=T-Test (median);4\=SNR (min std);5\=T-Test (min std);6\=SNR (median, min std);7\=T-Test (median, min std)
p9_default_value=
p9_description=minimum standard deviation if feature selection statistic includes min std option
p9_name=min.std
p9_optional=on
p9_prefix_when_specified=
p9_type=java.lang.Float
p9_value=
pipelineModel=
privacy=public
publicationDate=03/24/2010 13\:43 
quality=production
serializedModel=
taskType=Prediction
userid=GenePattern (gp-help@broadinstitute.org)
version=Set default distance measure to Euclidean
