# KSscore  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00014:1
#Tue Feb 10 19:11:50 UTC 2026
JVMLevel=any
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00014\:1
author=Justin Lamb
className=edu.mit.wi.omnigene.service.analysis.genepattern.GenePatternAnalysisTask
commandLine=<perl> <libdir>KSscore.pl <input.filename> <query.filename> <output> 
cpuType=any
description=Computes the Kolmogorov-Smirnov score for a set of genes within an ordered list.
language=Perl
name=KSscore
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=query gene set file containing one identifier per line
p1_name=query.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=file containing an ordered list of genes (.pol format)
p2_name=input.filename
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_default_value=<query.filename_basename>
p3_description=output file name (a .pol extension will be appended)
p3_name=output
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
pipelineModel=
privacy=public
quality=production
serializedModel=
taskType=Statistical Methods
userid=GenePattern (gp-info@broad.mit.edu)
version=Added email address to owner contact
