# LandmarkMatch  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00083:2
#Tue Feb 10 19:11:50 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00083\:2
author=Vincent Fusaro
commandLine=<perl> <libdir>LandmarkMatch.pl <libdir> <os.name> <peakList.filename> <retentionTime.filename> <sampleInfo.filename> <globalID.filename> <Bootstrap> <running.on.LSF> <accurateMass.filename> <prefitCoef.filename>
cpuType=any
description=A proteomics method to propogate identifed peptides across multiple MS runs
domain=
fileFormat=zip
language=any
name=LandmarkMatch
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Zip file containing peak lists
p1_fileFormat=
p1_name=peakList.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Zip file containing retention time (in this case from mapquant)
p2_fileFormat=
p2_name=retentionTime.filename
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=CSV file with header\: experiment, sample, class
p3_fileFormat=
p3_name=sampleInfo.filename
p3_optional=
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_MODE=IN
p4_TYPE=FILE
p4_default_value=
p4_description=Global list of identified peptides
p4_fileFormat=
p4_name=globalID.filename
p4_optional=
p4_prefix_when_specified=
p4_type=java.io.File
p4_value=
p5_MODE=IN
p5_TYPE=FILE
p5_default_value=
p5_description=OPTIONAL\: Specify the accurate mass table
p5_fileFormat=txt
p5_name=accurateMass.filename
p5_optional=on
p5_prefix_when_specified=
p5_type=java.io.File
p5_value=
p6_MODE=IN
p6_TYPE=FILE
p6_default_value=
p6_description=OPTIONAL\: Specify the prefit coefficients in a file
p6_fileFormat=txt
p6_name=prefitCoef.filename
p6_optional=on
p6_prefix_when_specified=
p6_type=java.io.File
p6_value=
p7_default_value=
p7_description=Use bootstrapping to calculate landmark match statistics
p7_fileFormat=
p7_name=Bootstrap
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=0\=No;1\=Yes
p8_default_value=no
p8_description=Whether you are running on an LSF cluster version of GenePattern
p8_name=running.on.LSF
p8_optional=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=no;yes
pipelineModel=
privacy=public
publicationDate=02/05/2007 16\:12 
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Proteomics
userid=vfusaro@broad.mit.edu
version=1.0
