# ListFiles  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00275:0.3
#Tue Feb 10 19:11:50 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00275\:0.3
author=Peter Carr, Broad Institute
commandLine=<java> -cp <libdir>ListFiles.jar<path.separator><libdir>jopt-simple-3.3.jar<path.separator><libdir>jakarta-oro-2.0.8.jar org.genepattern.module.find.FindCommand <dir> <recursive> <includePattern> <pruneDir> <type> <order.by> <output.filename>
cpuType=any
description=a helper module which outputs a filelist, the list of all files in the input directory, similar to the unix 'ls' command
fileFormat=
language=any
name=ListFiles
os=any
p1_default_value=
p1_description=a directory
p1_fileFormat=
p1_name=dir
p1_optional=
p1_prefix_when_specified=--dir\=
p1_type=DIRECTORY
p1_value=
p2_default_value=
p2_description=
p2_fileFormat=
p2_name=recursive
p2_optional=on
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=\=no, default;-R\=yes
p3_default_value=
p3_description=an optional list of filename patterns, e.g. *.cls,*.gct
p3_fileFormat=
p3_name=includePattern
p3_optional=on
p3_prefix_when_specified=--include-file\=
p3_type=java.lang.String
p3_value=
p4_default_value=
p4_description=an optional list of directory name patterns to ignore, e.g. *.svn
p4_fileFormat=
p4_name=pruneDir
p4_optional=on
p4_prefix_when_specified=--prune-dir\=
p4_type=java.lang.String
p4_value=
p5_default_value=
p5_description=an optional flag for how to order the files
p5_fileFormat=
p5_name=order.by
p5_optional=on
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=\=alphabetical, default;-t\=timestamp
p6_default_value=
p6_description=
p6_fileFormat=
p6_name=type
p6_optional=on
p6_prefix_when_specified=--type\=
p6_type=java.lang.String
p6_value=\=all, default;f\=file;d\=dir
p7_default_value=
p7_description=the name of the output file, if none specified, write to stdout
p7_fileFormat=
p7_name=output.filename
p7_optional=on
p7_prefix_when_specified=--o\=
p7_type=java.lang.String
p7_value=
pipelineModel=
privacy=public
publicationDate=10/26/2011 21\:19 
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Preprocess & Utilities
userid=pcarr@broadinstitute.org
version=Updated source code to use FindCommand and FileVisitor pattern
