# LocatePeaks  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00051:2
#Tue Feb 10 19:11:51 UTC 2026
JVMLevel=2.5.0
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00051\:2
author=D.R. Mani, Broad Institute
commandLine=<R2.5> <libdir>pipeline.wrapper.R peaks.locate.wrapper <peaks.output.filename> <output.file> <locate.peaks.as> <libdir>
cpuType=any
description=Locates detected peaks in a spectrum.
fileFormat=Spectrum Peaks Locate
language=R
name=LocatePeaks
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The output from the Peaks module
p1_fileFormat=Spectrum Peaks
p1_name=peaks.output.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<peaks.output.filename_basename>.locate.odf
p2_description=output file name
p2_name=output.file
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_default_value=
p3_description=max-location of maximum filtered value, area-center of area of the peak
p3_name=locate.peaks.as
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=max;area
privacy=public
publicationDate=02/19/2008 16\:34 
quality=production
requiredPatchLSIDs=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.server.patch\:00009\:1
requiredPatchURLs=http\://www.broad.mit.edu/webservices/gpModuleRepository/download/prod/patch/?file\=/R_2_5_Check/broad.mit.edu\:cancer.software.genepattern.server.patch/00009/1/R2_5.zip
taskType=Proteomics
userid=GenePattern
version=Updated for R 2.5.0
