# LogicleTransformFCS  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00192:1
#Tue Feb 10 19:11:51 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00192\:1
author=Josef Spidlen, BC Cancer Agency
commandLine=<java> <java_flags> -jar <libdir>logicletransform.jar <Input.fcs.data.file> <Output.fcs.file.name> <Parameters.to.transform> <T> <M> <W> <A> <Use.Fast.Implementation>
cpuType=any
description=Logicle transformation of (selected) parameters in a list mode FCS data file.
fileFormat=fcs
language=Java
name=LogicleTransformFCS
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=FCS data file to transform.
p1_fileFormat=fcs
p1_name=Input.fcs.data.file
p1_optional=
p1_prefix_when_specified=-InputFile\:
p1_type=java.io.File
p1_value=
p2_default_value=
p2_description=Comma-separated list of parameters to transform, parameters are specified by their short names ($PnN values); Optional. By default, all parameters with the "FL" prefix in their short name will be transformed.
p2_fileFormat=
p2_name=Parameters.to.transform
p2_optional=on
p2_prefix_when_specified=-ParametersToTransform\:
p2_type=java.lang.String
p2_value=
p3_default_value=
p3_description=T > 0; Data value at the top of the scale range to be displayed, optional. The maximum input value will be used if no explicit value for T is provided.
p3_fileFormat=
p3_name=T
p3_optional=on
p3_prefix_when_specified=-T\:
p3_type=java.lang.Float
p3_value=
p4_default_value=4.5
p4_description=M < 0; Full width of the intended Logicle display in asymptotic decades, optional. The default value is 4.5 (decades). Note also that for the resulting Logicle transformation, Logicle (T) \= M.
p4_fileFormat=
p4_name=M
p4_optional=on
p4_prefix_when_specified=-M\:
p4_type=java.lang.Float
p4_value=
p5_default_value=
p5_description=W >\= 0; Linearization width in asymptotic decades; optional. The described calculation will be used to set W for each of the transformed FCS parameters if no explicit value for W is provided.
p5_fileFormat=
p5_name=W
p5_optional=on
p5_prefix_when_specified=-W\:
p5_type=java.lang.Float
p5_value=
p6_default_value=0
p6_description=A, usually <\= 0; Additional negative display range in asymptotic decades; optional. The default value is 0.
p6_fileFormat=
p6_name=A
p6_optional=on
p6_prefix_when_specified=-A\:
p6_type=java.lang.Float
p6_value=
p7_default_value=no
p7_description=Use a fast implementation of Logicle with less precision; optional.
p7_fileFormat=
p7_name=Use.Fast.Implementation
p7_optional=
p7_prefix_when_specified=-Fas
p7_type=java.lang.String
p7_value=no\=Use regular implementation, default;t\=Use fast implementation
p8_default_value=<Input.fcs.data.file_basename>.logicle_transformed.fcs
p8_description=The output FCS file name
p8_fileFormat=
p8_name=Output.fcs.file.name
p8_optional=
p8_prefix_when_specified=-OutputFile\:
p8_type=java.lang.String
p8_value=
pipelineModel=
privacy=public
publicationDate=07/11/2012 15\:21 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Flow Cytometry
userid=jspidlen@bccrc.ca
version=
