# LOHPaired  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00094:3
#Tue Feb 10 19:11:51 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00094\:3
author=Jim Robinson, David Twomey, Joshua Gould
commandLine=<java> <java_flags> -cp <libdir>snp.jar<path.separator><libdir>gp-modules.jar<path.separator><libdir>opencsv-1.7.jar  edu.mit.broad.cg.visualization.LOHComputation <input.filename> <sample.info.filename> <output.file>
cpuType=any
description=Computes LOH for paired samples
fileFormat=loh
language=Java
name=LOHPaired
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A .snp file that contains genotypes
p1_fileFormat=snp
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=A sample info file with the paired information
p2_fileFormat=txt
p2_name=sample.info.filename
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_default_value=<input.filename_basename>.loh
p3_description=Output file
p3_name=output.file
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
privacy=public
publicationDate=03/05/2008 16\:06 
quality=production
taskType=SNP Analysis
userid=GenePattern
version=Pairings based on array name instead of sample name
