# MAGETABImportViewer  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.visualizer:00173:2
#Tue Feb 10 19:11:51 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.visualizer\:00173\:2
author=Marc-Danie Nazaire(Broad Institute)
commandLine=<java> <java_flags> -cp <libdir>jargs.jar<path.separator><libdir>Jama-1.0.2.jar<path.separator><libdir>trove.jar<path.separator><libdir>gp-modules.jar<path.separator><libdir>ant.jar<path.separator><libdir>gp-modules.jar<path.separator><libdir>limpopo-1.0-beta-20100420.jar<path.separator><libdir>MAGETABImportViewer.jar org.broadinstitute.mage.MAGETABImportViewer -s <sdrf.file> -z <data.files>
cpuType=any
description=A visualizer to import data in MAGE-TAB format into GenePattern
fileFormat=
language=Java
name=MAGETABImportViewer
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The sdrf file - .txt
p1_fileFormat=txt
p1_name=sdrf.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=A zip file containing MAGE-TAB data matrix files - .zip
p2_fileFormat=zip
p2_name=data.files
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
pipelineModel=
privacy=public
publicationDate=12/05/2012 13\:48 
quality=production
serializedModel=
taskType=Visualizer
userid=GenePattern (gp-help@broadinstitute.org)
version=Fixed bug with merging multiple data matrix files and also modified input parameters.
