# MapChipFeaturesGeneral  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00015:3
#Tue Feb 10 19:11:51 UTC 2026
JVMLevel=any
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00015\:3
author=Justin Lamb gp-help@broad.mit.edu and Pablo Tamayo gp-help@broad.mit.edu
commandLine=<perl> <libdir>MapChipFeaturesGeneral.pl -F <input.filename> -T <lookup.table.filename> -d <direction> -f <table.format> -o <output.prefix>
cpuType=any
description=Change (map) the features (genes) of a dataset
language=Perl
name=MapChipFeaturesGeneral
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input filename - .res
p1_fileFormat=res
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Name of the look up table file with the feature mapping
p2_name=lookup.table.filename
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_default_value=
p3_description=Table format
p3_name=table.format
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=0\=2 column;1\=4-column
p4_default_value=
p4_description=Direction of look up
p4_name=direction
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=1\=direct;0\=reverse
p5_default_value=<input.filename_basename>.fea
p5_description=prefix for output file
p5_name=output.prefix
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
pipelineModel=
privacy=public
publicationDate=06/06/2013 11\:35 
quality=production
serializedModel=
taskType=Preprocess & Utilities
userid=GenePattern (gp-help@broad.mit.edu)
version=Fixed a broken script reference
