# MergeFCSDataFiles  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00187:1
#Tue Feb 10 19:11:52 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00187\:1
author=Josef Spidlen, BC Cancer Agency
commandLine=<java> <java_flags> -jar <libdir>mergefcsdatafiles.jar <Input.files> <Output.file.name> <Subsampling.rate> <Keep.n.events> <Random.seed>
cpuType=any
description=Merge multiple FCS data files into a single FCS datasets; includes multimple subsampling options.
fileFormat=fcs
language=Java
name=MergeFCSDataFiles
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The input FCS files to be merged; either a zip file or a pointer to a directory or a text file with FCS file names (full path) with one filename per line.
p1_fileFormat=zip;txt
p1_name=Input.files
p1_optional=
p1_prefix_when_specified=-InputFile\:
p1_type=java.io.File
p1_value=
p2_default_value=100
p2_description=Subsampling rate as percentage of events to be included from each data set, value between 0 and 100, optional, default 100%, cannot be combined with keep n events.
p2_fileFormat=
p2_name=Subsampling.rate
p2_optional=on
p2_prefix_when_specified=-SubsamplingRate\:
p2_type=java.lang.Float
p2_value=
p3_default_value=
p3_description=Keep approximately n events from each dataset, optional, cannot be combined with subsampling rate.
p3_fileFormat=
p3_name=Keep.n.events
p3_optional=on
p3_prefix_when_specified=-KeepNEvents\:
p3_type=java.lang.Integer
p3_value=
p4_default_value=1234567
p4_description=The random seed
p4_fileFormat=
p4_name=Random.seed
p4_optional=on
p4_prefix_when_specified=-RandomSeed\:
p4_type=java.lang.Float
p4_value=
p5_default_value=MergedFCSDataFiles.fcs
p5_description=The output FCS file name.
p5_fileFormat=
p5_name=Output.file.name
p5_optional=
p5_prefix_when_specified=-OutputFile\:
p5_type=java.lang.String
p5_value=
pipelineModel=
privacy=public
publicationDate=07/03/2012 16\:57 
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Flow Cytometry
userid=jspidlen@bccrc.ca
version=
