# MergeColumns  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00070:1
#Tue Feb 10 19:11:52 UTC 2026
JVMLevel=1.4
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00070\:1
author=Joshua Gould, gp-help@broad.mit.edu, Broad Institute
commandLine=<java> <java_flags> -cp <libdir>MergeColumns.jar<path.separator><libdir>gp-modules.jar org.genepattern.modules.merge.MergeColumns -1<input.filename1> -2<input.filename2> -o<output> -z<zip.filename>
cpuType=any
description=Merge datasets by column.
fileFormat=gct;res;Dataset;snp;cn;loh
language=Java
name=MergeColumns
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=first file to merge
p1_fileFormat=gct;res;Dataset;snp;cn;loh
p1_name=input.filename1
p1_optional=on
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=second file to merge
p2_fileFormat=gct;res;Dataset;snp;cn;loh
p2_name=input.filename2
p2_optional=on
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=zip file containing files to merge. Either a zip file or the input files above must be provided.
p3_fileFormat=zip
p3_name=zip.filename
p3_optional=on
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_default_value=<input.filename1_basename><zip.filename_basename>.merged
p4_description=name of the merged file
p4_name=output
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
privacy=public
publicationDate=04/30/2007 14\:09 
quality=production
taskType=Preprocess & Utilities
userid=GenePattern
version=
