# MetageneProjection  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00092:1
#Tue Feb 10 19:11:52 UTC 2026
JVMLevel=2.5.0
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00092\:1
author=Pablo Tamayo, Marc-Danie Nazaire
commandLine=<R2.5> <libdir>MetageneProjection.R metagene.projection.cmdline -l<libdir> -m<model.gct.file> -d<model.cls.file> -p<model.preprocessing.file> <test.gct.file> <test.cls.file> <test.preprocessing.file> -u<num.characters> -i<identifier> -k<k.projection> -o<algorithm> -n<number.of.iterations> -s<seed> -j<post.projection.normalization> -w<heatmap.row.norm> -h<heatmap.color.scheme> -f<confidence.threshold> -v<phenotype.plotting.colors> -q<phenotype.plotting.symbols> -y<symbol.scaling> -e<kernel> -c<cost> -g<gamma> -a<theta> -b<lambda> -r<model.set.refinement>
cpuType=any
description=Projects one or more data sets onto the metagene representation of another data set
fileFormat=
language=R
name=MetageneProjection
os=
p10_default_value=NMF.div
p10_description=Algorithm for Metagene Projection
p10_name=algorithm
p10_optional=on
p10_prefix_when_specified=
p10_type=java.lang.String
p10_value=NMF.div\=NMF w/ divergence;NMF\=NMF;NSNMF.div\=NSNMF w/ divergence;SNMF\=SNMF;PCA\=PCA
p11_default_value=2000
p11_description=Number of algorithm iterations
p11_name=number.of.iterations
p11_optional=on
p11_prefix_when_specified=
p11_type=java.lang.Integer
p11_value=
p12_default_value=1234
p12_description=Random seed to initialize metagene matrices (Note\: results may only be reproducible on the same platform)
p12_name=seed
p12_optional=on
p12_prefix_when_specified=
p12_type=java.lang.Integer
p12_value=
p13_default_value=yes
p13_description=apply post-projection normalization
p13_name=post.projection.normalization
p13_optional=on
p13_prefix_when_specified=
p13_type=java.lang.String
p13_value=T\=yes;F\=no
p14_default_value=no
p14_description=row-normalize (standardize) the rows in the heat map
p14_name=heatmap.row.norm
p14_optional=on
p14_prefix_when_specified=
p14_type=java.lang.String
p14_value=T\=yes;F\=no
p15_default_value=reddish color map
p15_description=
p15_name=heatmap.color.scheme
p15_optional=on
p15_prefix_when_specified=
p15_type=java.lang.Integer
p15_value=1\=vintage pinkogram;2\=scale of grays;4\=high resolution pinkogram;6\=reddish color map
p16_default_value=0.3
p16_description=Confidence threshold (Brier score) to separate call from no-calls
p16_name=confidence.threshold
p16_optional=on
p16_prefix_when_specified=
p16_type=java.lang.Float
p16_value=
p17_MODE=IN
p17_TYPE=FILE
p17_default_value=
p17_description=Plotting colors for phenotypes
p17_fileFormat=txt;
p17_name=phenotype.plotting.colors
p17_optional=on
p17_prefix_when_specified=
p17_type=java.io.File
p17_value=
p18_MODE=IN
p18_TYPE=FILE
p18_default_value=
p18_description=Plotting symbols for phenotypes
p18_fileFormat=txt;
p18_name=phenotype.plotting.symbols
p18_optional=on
p18_prefix_when_specified=
p18_type=java.io.File
p18_value=
p19_default_value=1
p19_description=Graphical scaling for symbols in plots and plot legends
p19_name=symbol.scaling
p19_optional=on
p19_prefix_when_specified=
p19_type=java.lang.Integer
p19_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The model .gct data file
p1_fileFormat=gct
p1_name=model.gct.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p20_default_value=radial
p20_description=Kernel function for SVM
p20_name=kernel
p20_optional=on
p20_prefix_when_specified=
p20_type=java.lang.String
p20_value=radial\=radial;linear\=linear
p21_default_value=1
p21_description=cost function for SVM
p21_name=cost
p21_optional=on
p21_prefix_when_specified=
p21_type=java.lang.Integer
p21_value=
p22_default_value=0.05
p22_description=Gamma coefficient for radial base function kernel
p22_name=gamma
p22_optional=on
p22_prefix_when_specified=
p22_type=java.lang.Integer
p22_value=
p23_default_value=0
p23_description=Smoothing parameter only used for the NSNMF.div algorithm
p23_name=theta
p23_optional=on
p23_prefix_when_specified=
p23_type=java.lang.Integer
p23_value=
p24_default_value=0
p24_description=Sparse parameter used only for the SNMF algorithm
p24_name=lambda
p24_optional=on
p24_prefix_when_specified=
p24_type=java.lang.Integer
p24_value=
p25_default_value=yes
p25_description=perform model set refinement
p25_name=model.set.refinement
p25_optional=on
p25_prefix_when_specified=
p25_type=java.lang.String
p25_value=T\=yes;F\=no
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=The model .cls data file
p2_fileFormat=cls
p2_name=model.cls.file
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=The pre-processing parameters for the model dataset
p3_fileFormat=txt;
p3_name=model.preprocessing.file
p3_optional=
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_MODE=IN
p4_TYPE=FILE
p4_default_value=
p4_description=The test .gct or zip of .gct data files
p4_fileFormat=gct;
p4_name=test.gct.file
p4_optional=on
p4_prefix_when_specified=-z
p4_type=java.io.File
p4_value=
p5_MODE=IN
p5_TYPE=FILE
p5_default_value=
p5_description=The test .cls or zip of .cls data files
p5_fileFormat=cls
p5_name=test.cls.file
p5_optional=on
p5_prefix_when_specified=-x
p5_type=java.io.File
p5_value=
p6_MODE=IN
p6_TYPE=FILE
p6_default_value=
p6_description=The pre-processing parameters for the test dataset
p6_fileFormat=txt;
p6_name=test.preprocessing.file
p6_optional=on
p6_prefix_when_specified=-t
p6_type=java.io.File
p6_value=
p7_default_value=9
p7_description=Number of characters to use to identify classes from the .cls files
p7_name=num.characters
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.Integer
p7_value=
p8_default_value=<model.gct.file_basename>.output
p8_description=Prefix to name output files
p8_name=identifier
p8_optional=on
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=
p9_default_value=3
p9_description=Number of metagenes in projection
p9_name=k.projection
p9_optional=on
p9_prefix_when_specified=
p9_type=java.lang.Integer
p9_value=
privacy=public
publicationDate=09/09/2010 13\:50 
quality=production
requiredPatchLSIDs=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.server.patch\:00009\:1
requiredPatchURLs=http\://www.broad.mit.edu/webservices/gpModuleRepository/download/prod/patch/?file\=/R_2_5_Check/broad.mit.edu\:cancer.software.genepattern.server.patch/00009/1/R2_5.zip
taskType=Projection
version=
