# MethylationCNVAnalysis  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00379:4
#Tue Feb 10 19:11:52 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00379\:4
author=Owen Chapman;Clarence Mah;Mesirov Lab
categories=Methylation;CNV Analysis
commandLine=<Rscript> <libdir>run.R --data <query.sample.data> --controlsdata <control.sample.data> --controls <control.sample.names> --ignorefile <ignore.regions> --xy <sex.chromosomes>
cpuType=any
description=Methylation array preprocessing with the minfi R package and copy-number variation analysis with the conumee R package. Compatible with both 450k or EPIC array data.
fileFormat=pdf;seg;txt
job.docker.image=genepattern/docker-r-3-4-methylationanalysis\:1.0
job.memory=12Gb
language=R
name=MethylationCNVAnalysis
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Provide a ZIP or GZ file containing your sample(s) methylation microarray data in the Illumina Demo Dataset folder structure. See documentation for more details.
p1_fileFormat=tar.gz;gz;zip
p1_flag=--data
p1_name=query.sample.data
p1_numValues=0..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=none
p2_description=Specify a list of control sample names separated by commas if the control sample data is included in the "sample data" file. Otherwise write "none" if control samples data is separate.
p2_fileFormat=
p2_flag=--controls
p2_name=control.sample.names
p2_numValues=0..1
p2_optional=on
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=Provide a ZIP or GZ file containing your control samples methylation microarray data in the Illumina Demo Dataset folder structure. See documentation for more details.
p3_fileFormat=tar.gz;gz;zip
p3_flag=--controlsdata
p3_name=control.sample.data
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_MODE=IN
p4_TYPE=FILE
p4_default_value=https\://datasets.genepattern.org/gpftp/methylation/common_cancer_genes.txt
p4_description=A file with a list of genes (HUGO gene symbols) to highlight in output plots. Format as one gene symbol per line.
p4_fileFormat=
p4_flag=
p4_name=genes.to.highlight
p4_numValues=0..1
p4_optional=on
p4_prefix=--genesfile
p4_prefix_when_specified=--genesfile
p4_type=java.io.File
p4_value=
p5_MODE=IN
p5_TYPE=FILE
p5_default_value=https\://datasets.genepattern.org/gpftp/methylation/ignore_regions.bed
p5_description=A bed file specifying genomic regions to exclude from copy number analysis (hg19).
p5_fileFormat=bed
p5_flag=--ignorefile
p5_name=ignore.regions
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=
p5_type=java.io.File
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=Yes
p6_description=Include analysis of X & Y sex chromosomes.
p6_fileFormat=
p6_flag=--xy
p6_name=sex.chromosomes
p6_numValues=0..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=Yes\=Yes;No\=No
privacy=public
publicationDate=01/04/2024 14\:23 
quality=production
taskDoc=doc.html
taskType=Methylation
userid=chapmano
version=Switch defaults to datasets from gpftp
