# MINDY  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00107:2
#Tue Feb 10 19:11:53 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00107\:2
author=Marc-Danie Nazaire
commandLine=<java> <java_flags> -cp <libdir>mindy-gp.jar<path.separator><libdir>jargs.jar<path.separator><libdir>gp-modules.jar<path.separator><libdir>jama-1.0.1.jar<path.separator><libdir>trove.jar<path.separator><libdir>aracne-0.1.jar<path.separator><libdir>workbook-0.91.jar<path.separator><libdir>commons-cli.jar<path.separator><libdir>commons-math-1.0.jar<path.separator><libdir>log4j-1.2.8.jar<path.separator><libdir>collections-generic-4.0.jar<path.separator><libdir>swingx-2006_10_27.jar<path.separator><libdir>commons-logging.jar<path.separator><libdir>mindy-0.2.jar org.genepattern.modules.mindy.MINDY -i <input.file> -c <modulator.list> -h <transcription.factor> -s <sample.percentage>  -m <conditional.mi.threshold> -p <conditional.mi.p.value> -d <dpi.tolerance> -t <unconditional.mi.threshold> -n <unconditional.mi.p.value> -o <output.file>
cpuType=any
description=Runs the MINDY algorithm for inferring genes that modulate the activity of a transcription factor at post-transcriptional levels 
fileFormat=res;gct
language=Java
name=MINDY
os=any
p10_default_value=1.0
p10_description=Unconditional mutual information p-value threshold (ignored if unconditonal MI threshold >0)
p10_name=unconditional.mi.p.value
p10_optional=
p10_prefix_when_specified=
p10_type=java.lang.Float
p10_value=
p11_default_value=<input.file_basename>.mindy
p11_description=Output file name
p11_name=output.file
p11_optional=
p11_prefix_when_specified=
p11_type=java.lang.String
p11_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The dataset file - .res, .gct
p1_fileFormat=res;gct
p1_name=input.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=A list of possible modulator genes to analyze - .txt
p2_fileFormat=txt
p2_name=modulator.list
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=List of transcription factors in dataset - .txt
p3_fileFormat=txt
p3_name=dpi.transcription.factor.list
p3_optional=on
p3_prefix_when_specified=-a <dpi.transcription.factor.list>
p3_type=java.io.File
p3_value=
p4_default_value=
p4_description=Transcription factor
p4_name=transcription.factor
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_default_value=35.0
p5_description=Percentage of samples to use in analysis (must be <\=50)
p5_name=sample.percentage
p5_optional=on
p5_prefix_when_specified=
p5_type=java.lang.Float
p5_value=
p6_default_value=0.0
p6_description=Conditional mutual information (MI) score threshold (number between 0 and 1)
p6_name=conditional.mi.threshold
p6_optional=
p6_prefix_when_specified=
p6_type=java.lang.Float
p6_value=
p7_default_value=1.0
p7_description=Conditional mutual info p-value threshold (ignored if conditonal MI threshold >0)
p7_name=conditional.mi.p.value
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.Float
p7_value=
p8_default_value=1.0
p8_description=The data processing inequality tolerance (number between 0 and 1)
p8_name=dpi.tolerance
p8_optional=
p8_prefix_when_specified=
p8_type=java.lang.Float
p8_value=
p9_default_value=0.0
p9_description=Unconditional mutual information (MI) score threshold (number between 0 and 1)
p9_name=unconditional.mi.threshold
p9_optional=
p9_prefix_when_specified=
p9_type=java.lang.Float
p9_value=
pipelineModel=
privacy=public
publicationDate=05/26/2010 10\:29 
quality=production
taskType=Pathway Analysis
userid=GenePattern
version=Fixed parsing of optional parameter dpi transcription factor list on command line
