# MINDYViewer  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00110:1
#Tue Feb 10 19:11:53 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00110\:1
author=Marc-Danie Nazaire
commandLine=<java> <java_flags> -cp <libdir>swingx-0.9.1.jar<path.separator><libdir>jargs.jar<path.separator><libdir>gp-modules.jar<path.separator><libdir>jama-1.0.1.jar<path.separator><libdir>trove.jar<path.separator><libdir>collections-generic-4.0.jar<path.separator><libdir>commons-logging.jar<path.separator><libdir>ostermillerutils_1_04_03_for_kaffe.jar<path.separator><libdir>geworkbench-mindy.jar<path.separator><libdir>mindy-viewer.jar org.genepattern.modules.mindy.MINDYViewer -i <dataset.file> -m <mindy.file>
cpuType=any
description=Visualizes the results of MINDY
fileFormat=mindy
language=Java
name=MINDYViewer
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The dataset file - .res, .gct
p1_fileFormat=res;gct
p1_name=dataset.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Output from MINDY- .mindy
p2_fileFormat=mindy
p2_name=mindy.file
p2_optional=on
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
pipelineModel=
privacy=public
publicationDate=03/06/2008 13\:51 
quality=production
taskType=Visualizer
userid=GenePattern
version=Visualizes the results of MINDY
