# MultiplotStudio  urn:lsid:127.0.0.1:genepatternmodules:4:1.5.62
#Tue Feb 10 19:11:53 UTC 2026
JVMLevel=1.8
LSID=urn\:lsid\:127.0.0.1\:genepatternmodules\:4\:1.5.62
author=Scott Davis (GlaxoSmithKline)
commandLine=<java> -Dfile.encoding\=UTF8 -Dsun.java2d.d3d\=true -Dsun.java2d.dpiaware\=true -Dsun.java2d.ddscale\=true -Dsun.java2d.translaccel\=true -Xms192m -XX\:+UseG1GC -jar <libdir>MultiplotStudio.jar <dataFile> <classFile>
cpuType=any
description=Scatterplot visualization tool for analyzing differential gene expression.
fileFormat=gct;txt;tab;png;svg;csv
language=Java
name=MultiplotStudio
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=GenePattern dataset (*.gct), Multiplot Studio Workspace file (*.msdata) or CSV (see help for format requirements).
p1_fileFormat=gct;csv;msdata
p1_flag=
p1_name=dataFile
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Class file (*.cls). Not required, but lack of a class file will result in fewer calculation options. Ignored if dataFile is a Workspace.
p2_fileFormat=cls
p2_flag=
p2_name=classFile
p2_optional=on
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
pipelineModel=
privacy=public
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskDoc=MultiplotStudio.pdf
taskType=Visualizer
userid=sdavis
version=Completely rewritten and vastly improved replacement for Multiplot
