# Mutect2  urn:lsid:genepattern.org:module.analysis:00481:2
#Tue Feb 10 19:11:53 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00481\:2
author=Garvit Agarwal
commandLine=python3 <libdir>mutect2Parallel.py -R <Reference>  -I <Tumor.BAM> -O <Output>  -N <Normal.BAM> --tumor_sample <Tumor.sample> --normal_sample <Normal.sample>  --germline_resource <Germline.resource> -L <intervals> -Pon <Pannel.of.Normals> -J <job.cpuCount> <Parallel.Processing> 
cpuType=any
description=Runs Gatk Mutect2
documentationUrl=https\://github.com/garvit192/Genepattern-mutect2/blob/main/README.md
fileFormat=
job.cpuCount=
job.docker.image=broadinstitute/gatk
job.memory=
job.walltime=
language=any
name=Mutect2
os=any
p10_MODE=
p10_TYPE=TEXT
p10_default_value=
p10_description=When selected, will run a separate instance of Mutect2 for each of the 22 chromosomes, outputs a seperate VCF file for each. Can not be used with intervals. Output files will be named chr1_somatic.vcf, chr2_somatic.vcf, ...
p10_fileFormat=
p10_flag=
p10_name=Parallel.Processing
p10_numValues=0..1
p10_optional=on
p10_prefix=
p10_prefix_when_specified=
p10_type=java.lang.String
p10_userSuppliedValuesOK=True
p10_value=-S\=Yes; \=No
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Reference genome
p1_fileFormat=fa
p1_flag=
p1_name=Reference
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_userSuppliedValuesOK=False
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Input BAM (tumor)
p2_fileFormat=BAM;bam
p2_flag=
p2_name=Tumor.BAM
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_userSuppliedValuesOK=False
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=
p3_description=Output file name
p3_fileFormat=
p3_flag=
p3_name=Output
p3_numValues=1..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_userSuppliedValuesOK=False
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=
p4_description=Tumor sample name
p4_fileFormat=
p4_flag=
p4_name=Tumor.sample
p4_numValues=1..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_userSuppliedValuesOK=False
p4_value=
p5_MODE=IN
p5_TYPE=FILE
p5_default_value=
p5_description=Input BAM (normal)
p5_fileFormat=BAM;bam
p5_flag=
p5_name=Normal.BAM
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=
p5_type=java.io.File
p5_userSuppliedValuesOK=False
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=
p6_description=Normal sample name (Required if Normal.BAM is passed through)
p6_fileFormat=
p6_flag=
p6_name=Normal.sample
p6_numValues=0..1
p6_optional=on
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_userSuppliedValuesOK=False
p6_value=
p7_MODE=IN
p7_TYPE=FILE
p7_default_value=
p7_description=Germline-resource file (vcf)
p7_fileFormat=.gz;VCF;vcf
p7_flag=
p7_name=Germline.resource
p7_numValues=0..1
p7_optional=on
p7_prefix=
p7_prefix_when_specified=
p7_type=java.io.File
p7_userSuppliedValuesOK=False
p7_value=
p8_MODE=IN
p8_TYPE=FILE
p8_default_value=
p8_description=Pannel of Normals file (vcf)
p8_fileFormat=.gz;VCF;vcf
p8_flag=
p8_name=Pannel.of.Normals
p8_numValues=0..1
p8_optional=on
p8_prefix=
p8_prefix_when_specified=
p8_type=java.io.File
p8_userSuppliedValuesOK=False
p8_value=
p9_MODE=IN
p9_TYPE=FILE
p9_default_value=
p9_description=One or more genomic intervals over which to operate.
p9_fileFormat=.intervals
p9_flag=
p9_name=intervals
p9_numValues=0..1
p9_optional=on
p9_prefix=
p9_prefix_when_specified=
p9_type=java.io.File
p9_userSuppliedValuesOK=False
p9_value=
privacy=public
publicationDate=01/14/2026 09\:19 
quality=production
src.repo=https\://github.com/garvit192/Genepattern-mutect2/tree/main
taskDoc=
taskType=
userid=Garvit19
version=Initial module revision
