# mzXMLToCsv  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00069:1
#Tue Feb 10 19:11:53 UTC 2026
JVMLevel=1.4
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00069\:1
author=Joshua Gould, Broad Institute
commandLine=<java> <java_flags> -cp <libdir>mzXMLToCSV.jar<path.separator><libdir>jrap.jar<path.separator><libdir>xerces.jar org.genepattern.modules.mzxml.Convert <input.filename> <output.file> 
cpuType=any
description=Converts a mzXML file to a zip of csv files
fileFormat=zip
language=Java
name=mzXMLToCsv
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=input filename - .mzXML
p1_fileFormat=mzXML
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<input.filename_basename>.zip
p2_description=output file containing zip of csv files
p2_name=output.file
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
privacy=public
publicationDate=11/07/2005 11\:03 
quality=production
taskType=Proteomics
userid=GenePattern (gp-help@broad.mit.edu)
version=
