# NMF  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00016:2.1
#Tue Feb 10 19:11:54 UTC 2026
JVMLevel=any
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00016\:2.1
author=Pablo Tamayo, Broad Institute
commandLine=<perl> <libdir>NMF_prototype.pl -s <seed> -n <niter> -f <nfact> -v <input.filename> -p <print.dump> -c <cnorm.flag> -r <rnorm.flag>  -g <gshift> -m <norm.type> -o <output.file> 
cpuType=any
description=Non-negative Matrix Factorization
job.docker.image=genepattern/docker-perl52\:0.1
language=Perl
name=NMF
os=any
p10_default_value=12345
p10_description=Random seed used to initialize W and H matrices by the randon number generator. e.g. 4585, 4567, 5980
p10_name=seed
p10_optional=on
p10_prefix_when_specified=
p10_type=java.lang.Integer
p10_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input file in GCT format with input data (V matrix) (GCT format only). e.g. ALL_vs_AML.gct
p1_fileFormat=gct
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<input.filename_basename>.log
p2_description=Output log file. e.g. NMF.log
p2_name=output.file
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_default_value=4
p3_description=Number of NMF factors. e.g. 2, 4, 10
p3_name=nfact
p3_optional=on
p3_prefix_when_specified=
p3_type=java.lang.Integer
p3_value=
p4_default_value=100
p4_description=Number of NMF iterations. e.g. 100, 250, 500
p4_name=niter
p4_optional=on
p4_prefix_when_specified=
p4_type=java.lang.Integer
p4_value=
p5_default_value=0
p5_description=Print matrices in output for debug
p5_name=print.dump
p5_optional=on
p5_prefix_when_specified=
p5_type=java.lang.Integer
p5_value=0\=no;1\=yes
p6_default_value=0
p6_description=Column normalization flag
p6_name=cnorm.flag
p6_optional=on
p6_prefix_when_specified=
p6_type=java.lang.Integer
p6_value=0\=no normalization;1\=normalization
p7_default_value=0
p7_description=Row normalization flag
p7_name=rnorm.flag
p7_optional=on
p7_prefix_when_specified=
p7_type=java.lang.Integer
p7_value=0\=no normalization;1\=normalization
p8_default_value=0
p8_description=Global additive shift after normalization. e.g. 1, 4
p8_name=gshift
p8_optional=on
p8_prefix_when_specified=
p8_type=java.lang.Integer
p8_value=
p9_default_value=0
p9_description=Type of normalization
p9_name=norm.type
p9_optional=on
p9_prefix_when_specified=
p9_type=java.lang.Integer
p9_value=0\=standardize;1\=rescale\: min\=0, max\=1
pipelineModel=
privacy=public
publicationDate=01/05/2024 15\:56 
quality=preproduction
serializedModel=
taskType=Dimension Reduction
userid=GenePattern (gp-help@broad.mit.edu)
version=Annotated for GP 1.4
