# NMFConsensus  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00057:5
#Tue Feb 10 19:11:54 UTC 2026
JVMLevel=2.5.0
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00057\:5
author=Jean-Phillipe Brunet and Pablo Tamayo, The Broad Institute
commandLine=<R2.5> <libdir>nmfconsensus.R nmfconsensus <dataset.filename> <k.initial> <k.final> <num.clusterings> <max.num.iterations> <error.function> <random.seed> <stop.convergence> <stop.frequency> T <output.file.prefix> 
cpuType=any
description=Non-negative Matrix Factorization (NMF) Consensus Clustering
fileFormat=membership.gct;cophenetic.txt;cophenetic.plot.pdf;consensus.k.2.gct;consensus.k.3.gct;consensus.k.4.gct;consensus.k.5.gct
language=R 2.5
name=NMFConsensus
os=any
p10_default_value=10
p10_description=Frequency (NMF iterations) of "no change" checks
p10_domain=
p10_fileFormat=
p10_name=stop.frequency
p10_optional=
p10_prefix_when_specified=
p10_type=java.lang.Integer
p10_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input dataset (gct or res)
p1_domain=
p1_fileFormat=
p1_name=dataset.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=2
p2_description=Initial value of K
p2_domain=
p2_fileFormat=
p2_name=k.initial
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.Integer
p2_value=
p3_default_value=5
p3_description=Final value of K
p3_domain=
p3_fileFormat=
p3_name=k.final
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.Integer
p3_value=
p4_default_value=20
p4_description=Number of clusterings per value of K
p4_domain=
p4_fileFormat=
p4_name=num.clusterings
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.Integer
p4_value=
p5_default_value=2000
p5_description=Maximum number of NMF iterations per clustering
p5_domain=
p5_fileFormat=
p5_name=max.num.iterations
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.Integer
p5_value=
p6_default_value=divergence
p6_description=Error function
p6_domain=
p6_fileFormat=
p6_name=error.function
p6_optional=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=divergence;euclidean
p7_default_value=123456789
p7_description=Seed for random number generator
p7_domain=
p7_fileFormat=
p7_name=random.seed
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.Integer
p7_value=
p8_default_value=<dataset.filename_basename>
p8_description=Prefix to append to all output files
p8_domain=
p8_fileFormat=
p8_name=output.file.prefix
p8_optional=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=
p9_default_value=40
p9_description=How many "no change" checks are needed to stop NMF iterations before max iterations is reached(convergence)
p9_domain=
p9_fileFormat=
p9_name=stop.convergence
p9_optional=
p9_prefix_when_specified=
p9_type=java.lang.Integer
p9_value=
pipelineModel=
privacy=public
publicationDate=08/17/2012 12\:37 
quality=production
requiredPatchLSIDs=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.server.patch\:00009\:1
requiredPatchURLs=http\://www.broad.mit.edu/webservices/gpModuleRepository/download/prod/patch/?file\=/R_2_5_Check/broad.mit.edu\:cancer.software.genepattern.server.patch/00009/1/R2_5.zip
serializedModel=
taskType=Clustering
userid=GenePattern
version=Added output files to manifest. Doc edits.
