# OutSplice.plotJunctions  urn:lsid:genepattern.org:module.analysis:00433:3
#Tue Feb 10 19:11:55 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00433\:3
author=Joseph Bendik;UCSD
categories=alternative splicing
commandLine=Rscript /build/source/outsplice_plotjunctions_wrapper.R <data.file>  <junctions>       <out.file.prefix>  <gene> <symbol> <tumor.color> <normal.color>  <p.value>   <tail>    <number>
cpuType=any
description=Using the result file from OutSplice, OutSplice.plotJunctions creates bar and waterfall plots of junction expression in both the tumor and normal samples.
documentationUrl=https\://genepattern.github.io/OutSplice.plotJunctions/v1/
fileFormat=
job.cpuCount=
job.docker.image=genepattern/outsplice.plotjunctions\:0.5
job.memory=
job.walltime=
language=any
name=OutSplice.plotJunctions
os=any
p10_MODE=
p10_TYPE=TEXT
p10_default_value=red
p10_description=Color for tumors on graph. Default is red \n
p10_fileFormat=
p10_flag=--tumor.color 
p10_name=tumor.color
p10_numValues=1..1
p10_optional=
p10_prefix=--tumor.color 
p10_prefix_when_specified=--tumor.color 
p10_type=java.lang.String
p10_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=R Data file containing output from the SplicingOutliers or TCGA_SplicingOutliers Functions generated by OutSpplice.
p1_fileFormat=RData;rdata;.rda;.RDa
p1_flag=--data.file 
p1_name=data.file
p1_numValues=0..1
p1_optional=
p1_prefix=--data.file 
p1_prefix_when_specified=--data.file 
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=1
p2_description=The number of junctions to plot. This can be top number of junctions (over or under expressed), or can be specific junctions in a list.  Default is 1 
p2_fileFormat=
p2_flag=--number 
p2_name=number
p2_numValues=0..1
p2_optional=
p2_prefix=--number 
p2_prefix_when_specified=--number 
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=
p3_description=The specific junction you want to graph (or comma delimited list of junctions). 
p3_fileFormat=
p3_flag=--junctions 
p3_name=junctions
p3_numValues=0..1
p3_optional=on
p3_prefix=--junctions 
p3_prefix_when_specified=--junctions 
p3_type=java.lang.String
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=
p4_description=Specify tail\='RIGHT' for junctions overexpressed in tumors,  tail\='LEFT' for junctions underexpressed in tumors. If neither is specified, plot the first N number of junctions specified in the number parameter, regardless of significance or expression level. Default is neither.
p4_fileFormat=
p4_flag=--tail  
p4_name=tail
p4_numValues=0..1
p4_optional=on
p4_prefix=--tail  
p4_prefix_when_specified=--tail  
p4_type=java.lang.String
p4_value=NULL\= ;RIGHT\=RIGHT;LEFT\=LEFT
p5_MODE=
p5_TYPE=TEXT
p5_default_value=<data.file_basename>_plot
p5_description=Prefix that will be used for all output files.
p5_fileFormat=
p5_flag=--out.file.prefix  
p5_name=out.file.prefix
p5_numValues=1..1
p5_optional=
p5_prefix=--out.file.prefix  
p5_prefix_when_specified=--out.file.prefix  
p5_type=java.lang.String
p5_value=
p6_MODE=
p6_TYPE=Floating Point
p6_default_value=.05
p6_description=p-value threshold to use when plotting the top over or under-expressed junctions with "tail". Default is 0.05 [OPTIONAL]
p6_fileFormat=
p6_flag=--p.value  
p6_name=p.value
p6_numValues=0..1
p6_optional=on
p6_prefix=--p.value  
p6_prefix_when_specified=--p.value  
p6_type=java.lang.Float
p6_value=
p7_MODE=
p7_TYPE=TEXT
p7_default_value=FALSE
p7_description=Pick junctions based on a specific gene. TRUE means you will pick all the junctions mapping to a certain gene.  FALSE means you do not pick based on the gene. Default is False. 
p7_fileFormat=
p7_flag=--gene 
p7_name=gene
p7_numValues=0..1
p7_optional=on
p7_prefix=--gene 
p7_prefix_when_specified=--gene 
p7_type=java.lang.String
p7_value=TRUE\=TRUE;FALSE\=FALSE
p8_MODE=
p8_TYPE=TEXT
p8_default_value=
p8_description=HGNC SYMBOL of gene you want to graph.
p8_fileFormat=
p8_flag=--symbol  
p8_name=symbol
p8_numValues=0..1
p8_optional=on
p8_prefix=--symbol  
p8_prefix_when_specified=--symbol  
p8_type=java.lang.String
p8_value=
p9_MODE=
p9_TYPE=TEXT
p9_default_value=blue
p9_description=Color for normals on graph. Default is blue
p9_fileFormat=
p9_flag=--normal.color  
p9_name=normal.color
p9_numValues=0..1
p9_optional=
p9_prefix=--normal.color  
p9_prefix_when_specified=--normal.color  
p9_type=java.lang.String
p9_value=
privacy=public
publicationDate=01/03/2024 14\:08 
quality=production
src.repo=https\://github.com/genepattern/OutSplice.plotJunctions
taskDoc=
taskType=beta
userid=ted
version=Initial Revision.
