# OutSplice  urn:lsid:genepattern.org:module.analysis:00431:3
#Tue Feb 10 19:11:54 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00431\:3
author=Joseph Bendik;UCSD
categories=alternative splicing
commandLine=Rscript /build/source/outsplice_wrapper.R <junction.file> <gene.expression.file> <rawcounts.file>     <out.file.prefix> <filter.sex>    <offsets.value> <correction.setting> <p.value>   <sample.labels.file>   <genome.annotations> <use_junc_col> <use_gene_col> <use_rc_col> <use_labels_col>
cpuType=any
description=OutSplice is a package that compares alternative splicing events between tumor and normal samples. This package is specifically designed for analyzing the gene and junction information from RNA sequencing data provided by the user, or from the TCGA. This package generates a matrix of splicing outliers, which are junctions that are either significantly over or under-expressed compared to a control sample. OutSplice further designates observed outliers as skipping, insertion, or deletion events. Overall, OutSplice is novel in that it determines differential splicing burdens between tumors and normal samples and characterizes the nature of splicing outliers.
documentationUrl=https\://genepattern.github.io/OutSplice/v1/
fileFormat=.RDa;.rda;RData;rdata
job.cpuCount=
job.docker.image=genepattern/outsplice\:0.4
job.memory=
job.walltime=
language=any
name=OutSplice
os=any
p10_MODE=
p10_TYPE=TEXT
p10_default_value=Hg19
p10_description=Genome and transcript annotations to use.
p10_fileFormat=
p10_flag=--preset.genome.annotation 
p10_name=genome.annotations
p10_numValues=0..1
p10_optional=
p10_prefix=--preset.genome.annotation 
p10_prefix_when_specified=--preset.genome.annotation 
p10_type=java.lang.String
p10_value=Hg19\=Hg19;Hg38\=Hg38;mm39\=mm39;mm10\=mm10
p11_MODE=
p11_TYPE=Integer
p11_default_value=1
p11_description=An integer indicating which column in the junction matrix contains the junction regions in your matrices. Uses 1 by default.
p11_fileFormat=
p11_flag=--use_junc_col 
p11_name=use_junc_col
p11_numValues=0..1
p11_optional=
p11_prefix=--use_junc_col 
p11_prefix_when_specified=--use_junc_col 
p11_type=java.lang.Integer
p11_value=1
p12_MODE=
p12_TYPE=Integer
p12_default_value=1
p12_description=.An integer indicating which column in the gene_expr matrix contains the entrez ids of your genes Uses 1 by default.
p12_fileFormat=
p12_flag=--use_gene_col 
p12_name=use_gene_col
p12_numValues=0..1
p12_optional=
p12_prefix=--use_gene_col 
p12_prefix_when_specified=--use_gene_col 
p12_type=java.lang.Integer
p12_value=1
p13_MODE=
p13_TYPE=Integer
p13_default_value=1
p13_description=An integer indicating which column in the rawcounts matrix contains the row names. Uses 1 by default.
p13_fileFormat=
p13_flag=--use_rc_col 
p13_name=use_rc_col
p13_numValues=0..1
p13_optional=
p13_prefix=--use_rc_col 
p13_prefix_when_specified=--use_rc_col 
p13_type=java.lang.Integer
p13_value=1
p14_MODE=
p14_TYPE=Integer
p14_default_value=1
p14_description=An integer indicating which column in the sample_labels matrix contains the sample names. Uses 1 by default.
p14_fileFormat=
p14_flag=--use_labels_col 
p14_name=use_labels_col
p14_numValues=0..1
p14_optional=
p14_prefix=--use_labels_col 
p14_prefix_when_specified=--use_labels_col 
p14_type=java.lang.Integer
p14_value=1
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Matrix of junction raw read counts
p1_fileFormat=
p1_flag=--junction.file 
p1_name=junction.file
p1_numValues=0..1
p1_optional=
p1_prefix=--junction.file 
p1_prefix_when_specified=--junction.file 
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Matrix of normalized gene expression data. RSEM quartile normalized data is recommended.
p2_fileFormat=
p2_flag=--rsem.file 
p2_name=gene.expression.file
p2_numValues=1..1
p2_optional=
p2_prefix=--rsem.file 
p2_prefix_when_specified=--rsem.file 
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=Matrix of raw read counts for each gene. Can either be per gene, or a summed total for each sample.
p3_fileFormat=
p3_flag=--rawcounts.file 
p3_name=rawcounts.file
p3_numValues=1..1
p3_optional=
p3_prefix=--rawcounts.file 
p3_prefix_when_specified=--rawcounts.file 
p3_type=java.io.File
p3_value=
p4_MODE=IN
p4_TYPE=FILE
p4_default_value=
p4_description=Matrix of phenotypes, 2 columns with sample name in column 1 and either T or N in column two (for tumor or normal).
p4_fileFormat=
p4_flag=--sample.labels.file 
p4_name=sample.labels.file
p4_numValues=0..1
p4_optional=on
p4_prefix=--sample.labels.file 
p4_prefix_when_specified=--sample.labels.file 
p4_type=java.io.File
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=<gene.expression.file_basename>
p5_description=Prefix that will be used for all output files.
p5_fileFormat=
p5_flag=--out.file.prefix  
p5_name=out.file.prefix
p5_numValues=0..1
p5_optional=
p5_prefix=--out.file.prefix  
p5_prefix_when_specified=--out.file.prefix  
p5_type=java.lang.String
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=True
p6_description=Ignores sex chromosomes when generating results. True by default.
p6_fileFormat=
p6_flag=--filter.sex  
p6_name=filter.sex
p6_numValues=0..1
p6_optional=
p6_prefix=--filter.sex  
p6_prefix_when_specified=--filter.sex  
p6_type=java.lang.String
p6_value=True\=True;False\=False
p7_MODE=
p7_TYPE=Floating Point
p7_default_value=0.00001
p7_description=The normalized junction expression threshold. Uses 0.00001 by default.
p7_fileFormat=
p7_flag=--offsets.value 
p7_name=offsets.value
p7_numValues=0..1
p7_optional=
p7_prefix=--offsets.value 
p7_prefix_when_specified=--offsets.value 
p7_type=java.lang.Float
p7_value=
p8_MODE=
p8_TYPE=TEXT
p8_default_value=fdr
p8_description=The correction value to be used for p-value adjustment during Fisher analyses. Uses fdr by default. Allowed values are fdr, holm, hochberg, hommel, bonferonni, BY.
p8_fileFormat=
p8_flag=--correction.setting 
p8_name=correction.setting
p8_numValues=0..1
p8_optional=
p8_prefix=--correction.setting 
p8_prefix_when_specified=--correction.setting 
p8_type=java.lang.String
p8_value=fdr\=fdr;holm\=holm;hochberg\=hochberg;hommel\=hommel;bonferroni\=bonferroni;BY\=BY
p9_MODE=
p9_TYPE=Floating Point
p9_default_value=.05
p9_description=The final corrected significance threshold to use during Fisher analyses. Uses 0.05 by default.
p9_fileFormat=
p9_flag=--p.value  
p9_name=p.value
p9_numValues=0..1
p9_optional=
p9_prefix=--p.value  
p9_prefix_when_specified=--p.value  
p9_type=java.lang.Float
p9_value=
privacy=public
publicationDate=01/03/2024 13\:54 
quality=production
src.repo=https\://github.com/genepattern/OutSplice
taskDoc=
taskType=beta
userid=ted
version=Remove genome, txdb and annotation parameters, leaving only the presets
