# PCA  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00017:4.2
#Tue Feb 10 19:11:55 UTC 2026
JVMLevel=1.3
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00017\:4.2
author=TIGR, http\://www.tm4.org/mev/, mev@tigr.org
commandLine=<java> <java_flags> -cp <libdir>jaxb-rt-1.0-ea.jar<path.separator><libdir>pca.jar<path.separator><libdir>algorithms-gui.jar<path.separator><libdir>algorithms-impl.jar<path.separator><libdir>algorithms.jar<path.separator><libdir>file_support.jar<path.separator><libdir>gp-common.jar<path.separator><libdir>mev_pca.jar<path.separator><libdir>ui_support.jar  edu.mit.wi.genome.gp.mev.PCAAlgorithmWrapper <input.filename> <compute.pcs.of> <output.file>
cpuType=any
description=Principal Component Analysis (adapted from MeV, <a href\="http\://mev.tm4.org">http\://mev.tm4.org</a>)
fileFormat=matrix
language=Java
name=PCA
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=input file - .gct, .res, .odf
p1_fileFormat=res;gct;Dataset
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=3
p2_description=Compute principal components of columns (samples) or rows (genes/features)
p2_name=compute.pcs.of
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.Integer
p2_value=1\=rows;3\=columns
p3_default_value=<input.filename_basename>
p3_description=stub name of the output files
p3_name=output.file
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
pipelineModel=
privacy=public
publicationDate=04/27/2008 13\:15 
quality=production
taskType=Dimension Reduction
userid=GenePattern (gp-help@broad.mit.edu)
version=Updated documentation
