# PCAViewer  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.visualizer:00018:6
#Tue Feb 10 19:11:55 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.visualizer\:00018\:6
author=TIGR, http\://www.tigr.org/software/tm4/mev.html, mev@tigr.org
commandLine=<java> <java_flags> -jar <libdir>pcaviewer.jar <dataset.file> <s.matrix.file> <t.matrix.file> <u.matrix.file> -c<cls.or.sample.info.file> -k<sample.info.class> -f<featureset.file>
cpuType=any
description=Principal Component Analysis Visualizer (adapted from MeV, http\://www.tigr.org/software/tm4/mev.html)
language=Java
name=PCAViewer
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The dataset - .res, .gct
p1_fileFormat=res;gct
p1_name=dataset.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=The s matrix - .odf
p2_fileFormat=Matrix
p2_name=s.matrix.file
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=The t matrix - .odf
p3_fileFormat=Matrix
p3_name=t.matrix.file
p3_optional=
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_MODE=IN
p4_TYPE=FILE
p4_default_value=
p4_description=The u matrix - .odf
p4_fileFormat=Matrix
p4_name=u.matrix.file
p4_optional=
p4_prefix_when_specified=
p4_type=java.io.File
p4_value=
p5_MODE=IN
p5_TYPE=FILE
p5_default_value=
p5_description=A cls or sample info file - .cls, .txt
p5_fileFormat=cls
p5_name=cls.or.sample.info.file
p5_optional=on
p5_prefix_when_specified=
p5_type=java.io.File
p5_value=
p6_MODE=IN
p6_default_value=
p6_description=The name of the class column to use in the sample info file (required if sample info file provided)
p6_name=sample.info.class
p6_optional=on
p6_prefix_when_specified=
p6_type=
p6_value=
p7_MODE=IN
p7_TYPE=FILE
p7_default_value=
p7_description=The feature set file - .gmt, .gmx, .grp
p7_fileFormat=gmt;gmx;grp
p7_name=featureset.file
p7_optional=on
p7_prefix_when_specified=
p7_type=java.io.File
p7_value=
privacy=public
publicationDate=07/08/2010 14\:55 
quality=production
taskType=Visualizer
userid=GenePattern (gp-help@broad.mit.edu)
version=Fixed bug with 3D plot with legend not properly saved on non-Windows machines
