# PclToGct  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00151:1
#Tue Feb 10 19:11:55 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00151\:1
author=Jeremy Hubble, Stanford University, gp-help@broad.mit.edu
commandLine=<perl> <libdir>pclToGct.pl -w <weight.handling> -o <output.filename> <input.filename>
cpuType=any
description=Convert Stanford preclustering file (.pcl) to .gct
fileFormat=gct
language=Perl
name=PclToGct
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=pcl file to convert
p1_fileFormat=pcl
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<input.filename_basename>.gct
p2_description=output gct file
p2_fileFormat=
p2_name=output.filename
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_default_value=3
p3_description=How to handle manually edited weights (weights not equal to 1) present in PCL file
p3_fileFormat=
p3_name=weight.handling
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=1\=ignore weights;2\=multiply values by weights (altering biological data);3\=print error if weights not equal to 1 present
pipelineModel=
privacy=public
publicationDate=10/18/2008 07\:52 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Data Format Conversion
userid=
version=
