# Picard.SortSam  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00245:4
#Tue Feb 10 19:11:57 UTC 2026
JVMLevel=1.6
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00245\:4
author=GenePattern
commandLine=<java> <java_flags> -cp <libdir>SortSam.jar<path.separator><libdir>commons-io-1.4.jar<path.separator><libdir>commons-cli-1.2.jar<path.separator><libdir>commons-lang-2.5.jar<path.separator><libdir>SortSamWrapper.jar SortSamWrapper -i <input.file> -s <sort.order> -o <output.prefix>.sorted.<output.format>
cpuType=any
description=Sorts a SAM or BAM file in a specified order
fileFormat=sam;bam;bai
language=Java
name=Picard.SortSam
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input file in SAM or BAM format
p1_fileFormat=sam;bam
p1_name=input.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=coordinate
p2_description=Sort order
p2_fileFormat=
p2_name=sort.order
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=coordinate\=coordinate;queryname\=queryname;unsorted\=unsorted
p3_default_value=
p3_description=Whether the file output format should be SAM or BAM
p3_fileFormat=
p3_name=output.format
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=sam\=SAM;bam\=BAM
p4_default_value=<input.file_basename>
p4_description=prefix for the name of output file
p4_fileFormat=
p4_name=output.prefix
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
pipelineModel=
privacy=public
publicationDate=05/07/2013 03\:21 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Preprocess & Utilities
userid=bhill
version=Renamed from SortSam to Picard.SortSam
