# Picard.AddOrReplaceReadGroups  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00266:3
#Tue Feb 10 19:11:55 UTC 2026
JVMLevel=1.6
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00266\:3
author=Picard Tools
commandLine=<java> <java_flags> -cp <libdir>AddOrReplaceReadGroups.jar<path.separator><libdir>commons-cli-1.2.jar<path.separator><libdir>commons-lang-2.5.jar<path.separator><libdir>gp-AddOrReplaceReadGroups.jar org.genepattern.sam.AddOrReplaceReadGroupsWrapper -inputFileName <input.file> -groupId <read.group.id> -lib <read.group.library> -platform <read.group.platform> -pUnit <read.group.platform.unit> -sample <read.group.sample.name> -center <read.group.sequencing.center.name> -desc <read.group.description> -outputFileName <output.prefix>
cpuType=any
description=Replaces all read groups in the input file with a new read group and assigns all reads to this read group in the output
fileFormat=bam;sam
language=Java
name=Picard.AddOrReplaceReadGroups
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input file (BAM or SAM).
p1_fileFormat=sam;bam
p1_name=input.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=
p2_description=Read Group ID
p2_fileFormat=
p2_name=read.group.id
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_default_value=
p3_description=DNA preparation library. Note that this field is required by the module Picard.MarkDuplicates. It is used to determine which read groups may contain molecular duplicates, in the case where the same DNA library was sequenced on multiple lanes.
p3_fileFormat=
p3_name=read.group.library
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_default_value=
p4_description=Read Group platform (e.g., Illumina, SOLID).
p4_fileFormat=
p4_name=read.group.platform
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_default_value=
p5_description=Read Group platform unit (e.g., run barcode).
p5_fileFormat=
p5_name=read.group.platform.unit
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
p6_default_value=
p6_description=Read Group sample name.
p6_fileFormat=
p6_name=read.group.sample.name
p6_optional=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=
p7_default_value=
p7_description=Read Group sequencing center name.
p7_fileFormat=
p7_name=read.group.sequencing.center.name
p7_optional=on
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
p8_default_value=
p8_description=Read Group description.
p8_fileFormat=
p8_name=read.group.description
p8_optional=on
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=
p9_default_value=<input.file_basename>
p9_description=A label used to name the output file
p9_fileFormat=
p9_name=output.prefix
p9_optional=
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=
pipelineModel=
privacy=public
publicationDate=03/19/2013 16\:06 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Preprocess & Utilities
userid=gp-help@broadinstitute.org
version=Read Group ID is now a required Parameter.
