# Picard.SamToBam  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00234:2
#Tue Feb 10 19:11:56 UTC 2026
JVMLevel=1.6
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00234\:2
author=Picard Tools
commandLine=<java> <java_flags> -cp <libdir>SamToBam.jar<path.separator><libdir>commons-cli-1.2.jar<path.separator><libdir>commons-lang-2.5.jar<path.separator><libdir>SamFormatConverter.jar org.genepattern.sam.SamFormat.SamToBam -inputFileName <input.file> -outputFileName <output.prefix>
cpuType=any
description=Converts a SAM file to a BAM file
fileFormat=bam
language=Java
name=Picard.SamToBam
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A SAM file
p1_fileFormat=sam
p1_name=input.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<input.file_basename>
p2_description=A label used to name the output file
p2_fileFormat=
p2_name=output.prefix
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
pipelineModel=
privacy=public
publicationDate=05/07/2013 02\:32 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Data Format Conversion
userid=bhill
version=Renamed from SamToBam to Picard.SamToBam
