# Picard.CreateSequenceDictionary  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00244:1
#Tue Feb 10 19:11:56 UTC 2026
JVMLevel=1.6
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00244\:1
author=GenePattern
commandLine=<java> <java_flags> -cp <libdir>CreateSequenceDictionary.jar<path.separator><libdir>gp-CreateSequenceDictionary.jar org.genepattern.sam.CreateSeqDictWrapper -r<reference.sequence.file> -g<genome.assembly> -u<uri> -t<truncate.names.at.white.space> -n<num.sequences> -o<output.file>
cpuType=any
description=Reads FASTA or FASTA.GZ files containing reference sequences, and writes them as a SAM file containing a sequence dictionary
fileFormat=dict
language=Java
name=Picard.CreateSequenceDictionary
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input reference fasta or fasta.gz 
p1_fileFormat=fasta;fa
p1_name=reference.sequence.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=
p2_description=The genome assembly to put into AS field of sequence dictionary entry
p2_fileFormat=
p2_name=genome.assembly
p2_optional=on
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_default_value=
p3_description=The uri to put into UR field of sequence dictionary entry
p3_fileFormat=
p3_name=uri
p3_optional=on
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_default_value=no
p4_description=Make sequence name the first word from the > line in the reference file
p4_fileFormat=
p4_name=truncate.names.at.white.space
p4_optional=on
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=true\=yes;false\=no
p5_default_value=
p5_description=Stop after writing this many sequences
p5_fileFormat=
p5_name=num.sequences
p5_optional=on
p5_prefix_when_specified=
p5_type=java.lang.Integer
p5_value=
p6_default_value=<reference.sequence.file_basename>.dict
p6_description=The name of the output file
p6_fileFormat=
p6_name=output.file
p6_optional=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=
privacy=public
publicationDate=07/08/2011 13\:42 
quality=production
taskType=Preprocess & Utilities
userid=GenePattern
version=
