# Picard.FastqToSam  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00241:2
#Tue Feb 10 19:11:56 UTC 2026
JVMLevel=1.6
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00241\:2
author=GenePattern
commandLine=<java> <java_flags> -cp <libdir>jargs.jar<path.separator><libdir>FastqToSam.jar<path.separator><libdir>gp-fastqToSam.jar org.genepattern.sam.FastqToSamWrapper -i<fastq.file> -f<fastq.file.2> -q<quality.format> -n<sample.name>  -r<read.group.name> -l<library.name> -u<platform.unit> -p<platform> -s<sort.order> -o<output.prefix>.<output.format>
cpuType=any
description=Extracts read sequences and qualities from the input fastq file and writes them into the output file in unaligned SAM or BAM format
fileFormat=bam;sam
language=Java
name=Picard.FastqToSam
os=any
p10_default_value=bam
p10_description=Whether the file output format should be SAM or BAM
p10_fileFormat=
p10_name=output.format
p10_optional=
p10_prefix_when_specified=
p10_type=java.lang.String
p10_value=sam\=SAM;bam\=BAM
p11_default_value=<fastq.file_basename>
p11_description=The prefix to use for the output file name
p11_fileFormat=
p11_name=output.prefix
p11_optional=
p11_prefix_when_specified=
p11_type=java.lang.String
p11_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input fastq file (optionally gzipped) for single end data, or first read in paired end data
p1_fileFormat=fastq
p1_name=fastq.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=The fastq file (optionally gzipped) for second read in paired end data
p2_fileFormat=fastq
p2_name=fastq.file.2
p2_optional=on
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_default_value=Standard
p3_description=A value describing how the quality values are encoded in the fastq
p3_fileFormat=
p3_name=quality.format
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=Solexa;Illumina;Standard
p4_default_value=
p4_description=Read group name
p4_fileFormat=
p4_name=read.group.name
p4_optional=on
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_default_value=
p5_description=Sample name to insert into the read group header
p5_fileFormat=
p5_name=sample.name
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
p6_default_value=
p6_description=The library name to insert into the LB attribute in the read group header
p6_fileFormat=
p6_name=library.name
p6_optional=on
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=
p7_default_value=
p7_description=The platform unit (often run_barcode.lane) to insert into the read group header
p7_fileFormat=
p7_name=platform.unit
p7_optional=on
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
p8_default_value=
p8_description=The platform type (e.g., Illumina, SOLiD) to insert into the read group header
p8_fileFormat=
p8_name=platform
p8_optional=on
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=
p9_default_value=coordinate
p9_description=
p9_fileFormat=
p9_name=sort.order
p9_optional=
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=unsorted;queryname;coordinate
privacy=public
publicationDate=05/07/2013 03\:06 
quality=production
taskType=Data Format Conversion
userid=GenePattern
version=Renamed from FastqToSam to Picard.FastqToSam
