# Picard.ReorderSam  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00264:1
#Tue Feb 10 19:11:56 UTC 2026
JVMLevel=1.6
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00264\:1
author=Picard Tools
commandLine=<java> <java_flags> -cp <libdir>ant.jar<path.separator><libdir>ReorderSam.jar<path.separator><libdir>commons-cli-1.2.jar<path.separator><libdir>commons-lang-2.5.jar<path.separator><libdir>gp-ReorderSam.jar org.genepattern.sam.ReorderSamWrapper -inputFileName <input.file> -allowInc <allow.partial.overlap> -contigLen <allow.contig.length.discordance> -refFileName <reference.file> -dict <reference.sequence.dictionary> -outputFileName <output.prefix>
cpuType=any
description=Reorders a SAM file or a BAM file to match contig ordering in a provided reference file
fileFormat=bam;sam
language=Java
name=Picard.ReorderSam
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A SAM or BAM file.
p1_fileFormat=sam;bam
p1_name=input.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Reference sequence to which to reorder reads in FASTA format.
p2_fileFormat=fasta;fa;fna
p2_name=reference.file
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=The sequence dictionary for the reference sequence file
p3_fileFormat=dict
p3_name=reference.sequence.dictionary
p3_optional=
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_default_value=false
p4_description=If yes, then allows only a partial overlap of the BAM contigs with the new reference sequence contigs. This requires a corresponding contig in the new reference for each read contig.
p4_fileFormat=
p4_name=allow.partial.overlap
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=true\=yes;false\=no
p5_default_value=false
p5_description=If yes, then permits mapping from a read contig to a new reference contig with the same name but a different length. Use with extreme caution and a full knowledge of the possible consequences.
p5_fileFormat=
p5_name=allow.contig.length.discordance
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=true\=yes;false\=no
p6_default_value=<input.file_basename>
p6_description=The prefix of the output SAM or BAM file.
p6_fileFormat=
p6_name=output.prefix
p6_optional=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=
pipelineModel=
privacy=public
publicationDate=07/15/2011 20\:29 
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Preprocess & Utilities
userid=gp-help@broadinstitute.org
version=
