# Picard.SamToFastq  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00240:3
#Tue Feb 10 19:11:56 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00240\:3
author=GenePattern
commandLine=<java> <java_flags> -cp <libdir>jargs.jar<path.separator><libdir>SamToFastq.jar<path.separator><libdir>gp-samToFastq.jar org.genepattern.sam.SamToFastqWrapper -i<input.file> -g<per.read.group> -r<re-reverse.bases> -p<include.non.pf.reads> -c<clipping.attribute> -a<clipping.action> -q<clipping.action.quality.value> -o<fastq.output.prefix.1> -f<fastq.output.prefix.2>
cpuType=any
description=Convert SAM or BAM files to FASTQ format
fileFormat=fastq
language=Java
name=Picard.SamToFastq
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The SAM or BAM file
p1_fileFormat=bam;sam
p1_flag=-i
p1_name=input.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=no
p2_description=Whether to output a fastq file per read group
p2_fileFormat=
p2_flag=-g
p2_name=per.read.group
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=yes;no
p3_default_value=no
p3_description=Whether to re-reverse bases and qualities of reads with negative strand flag set
p3_fileFormat=
p3_flag=-r
p3_name=re-reverse.bases
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=yes;no
p4_default_value=no
p4_description=Whether to include non-PF reads
p4_fileFormat=
p4_flag=-p
p4_name=include.non.pf.reads
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=yes;no
p5_default_value=
p5_description=Attribute that stores the position at which the SAM record should be clipped
p5_fileFormat=
p5_flag=-c
p5_name=clipping.attribute
p5_optional=on
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
p6_default_value=none
p6_description=Action to take with clipped reads when a clipping attribute is specified
p6_fileFormat=
p6_flag=-a
p6_name=clipping.action
p6_optional=on
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=none\=;X\=trim reads and qualities;N\=change bases to Ns;change\=change base quality values
p7_default_value=
p7_description=Value to set base qualities to when clipping action is "change base quality values"
p7_fileFormat=
p7_flag=-q
p7_name=clipping.action.quality.value
p7_optional=on
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
p8_MODE=
p8_TYPE=TEXT
p8_default_value=
p8_description=The fastq output file name for single-end fastq or first end of a paired fastq. Only specify when "per read group" is "no".
p8_fileFormat=
p8_flag=-o
p8_name=fastq.output.prefix.1
p8_optional=on
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=
p9_default_value=
p9_description=The second end of a paired fastq. Only specify when "per read group" is "no".
p9_fileFormat=
p9_flag=-f
p9_name=fastq.output.prefix.2
p9_optional=on
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=
pipelineModel=
privacy=public
publicationDate=06/21/2013 19\:50 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskDoc=doc.html
taskType=Data Format Conversion
userid=bhill@broad.mit.edu
version=Fixed issue with choice parameters not appearing as drop downs
