# Picard.MarkDuplicates  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00267:2
#Tue Feb 10 19:11:56 UTC 2026
JVMLevel=1.6
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00267\:2
author=Picard Tools
commandLine=<java> <java_flags> -cp <libdir>MarkDuplicates.jar<path.separator><libdir>commons-cli-1.2.jar<path.separator><libdir>commons-lang-2.5.jar<path.separator><libdir>gp-MarkDuplicates.jar org.genepattern.sam.MarkDuplicatesWrapper -inputFileName <input.file> -removeDup <remove.duplicates> -maxFileH <max.file.handles> -rnRegex <read.name.regex> -dist <optical.duplicate.distance> -outputFileName <output.prefix> -ratio <sorting.collection.size.ratio>
cpuType=any
description=Examines aligned records in the supplied SAM or BAM file to locate duplicate reads.
fileFormat=bam;sam;metrics.txt
language=Java
name=Picard.MarkDuplicates
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A SAM or BAM file
p1_fileFormat=sam;bam
p1_name=input.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=false
p2_description=Whether to remove duplicates
p2_fileFormat=
p2_name=remove.duplicates
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=true\=yes;false\=no
p3_default_value=8000
p3_description=Maximum number of file handles to keep open when spilling read ends to disk
p3_fileFormat=
p3_name=max.file.handles
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_default_value=
p4_description=Regular expression that can be used to parse read names in the input file
p4_fileFormat=
p4_name=read.name.regex
p4_optional=on
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_default_value=100
p5_description=The maximum offset between two duplicate clusters in order to consider them optical duplicates. This should usually be set to some fairly small number (e.g. 5-10 pixels) unless using later versions of the Illumina pipeline that multiply pixel values by 10, in which case 50-100 is more normal
p5_fileFormat=
p5_name=optical.duplicate.distance
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
p6_default_value=0.25
p6_description=This number, plus the maximum RAM available to the JVM, determine the memory footprint used by some of the sorting collections.  If you are running out of memory, try reducing this number
p6_fileFormat=
p6_name=sorting.collection.size.ratio
p6_optional=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=
p7_default_value=<input.file_basename>
p7_description=The prefix to use for the output file name
p7_fileFormat=
p7_name=output.prefix
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
pipelineModel=
privacy=public
publicationDate=08/16/2011 15\:57 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Preprocess & Utilities
userid=gp-help@broadinstitute.org
version=Added sorting collection size ratio parameter and modified to print warning message about failed file delete attempts to stdout
