# PreprocessDataset  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00020:5.1
#Tue Feb 10 19:11:57 UTC 2026
JVMLevel=1.6
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00020\:5.1
author=Joshua Gould, Broad Institute
commandLine=<java> <java_flags> -cp <libdir>Preprocess.jar<path.separator><libdir>broad-cg.jar<path.separator><libdir>trove.jar<path.separator><libdir>Jama-1.0.1.jar<path.separator><libdir>gp-modules.jar edu.mit.broad.modules.preprocess.Preprocess -F <input.filename> -r <output.file.format> -V <threshold.and.filter> -n <row.normalization> -f <min.fold.change> -d <min.delta> -t <floor> -c <ceiling> -p <row.sampling.rate> -e <num.outliers.to.exclude> -O <output.file> -g <log2.transform> <threshold.for.removing.rows> <number.of.columns.above.threshold>
cpuType=any
description=Performs several preprocessing steps on a res, gct, or odf input file
fileFormat=res;gct;Dataset
language=Java
name=PreprocessDataset
os=any
p10_default_value=
p10_description=Threshold for removing rows
p10_name=threshold.for.removing.rows
p10_optional=on
p10_prefix_when_specified=-b 
p10_type=java.lang.Float
p10_value=
p11_default_value=
p11_description=Remove row if this number of columns not >\= given threshold
p11_name=number.of.columns.above.threshold
p11_optional=on
p11_prefix_when_specified=-a 
p11_type=java.lang.Integer
p11_value=
p12_default_value=0
p12_description=Apply log2 transform after all other preprocessing steps
p12_name=log2.transform
p12_optional=on
p12_prefix_when_specified=
p12_type=java.lang.String
p12_value=0\=no;1\=yes
p13_default_value=3
p13_description=Output file format
p13_name=output.file.format
p13_optional=on
p13_prefix_when_specified=
p13_type=java.lang.String
p13_value=0\=gct;1\=res;3\=same as input
p14_default_value=<input.filename_basename>.preprocessed
p14_description=Output file name
p14_name=output.file
p14_optional=
p14_prefix_when_specified=
p14_type=java.lang.String
p14_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input filename - .res, .gct, .odf
p1_fileFormat=res;gct;Dataset
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=1
p2_description=Apply floor, ceiling and variation filter
p2_name=threshold.and.filter
p2_optional=on
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=0\=no;1\=yes
p3_default_value=20
p3_description=Value for floor threshold
p3_name=floor
p3_optional=on
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_default_value=20000
p4_description=Value for ceiling threshold
p4_name=ceiling
p4_optional=on
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_default_value=3
p5_description=Minimum fold change for variation filter
p5_name=min.fold.change
p5_optional=on
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
p6_default_value=100
p6_description=Minimum delta for variation filter
p6_name=min.delta
p6_optional=on
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=
p7_default_value=0
p7_description=Number of outliers per row to ignore when calculating row min and max for variation filter
p7_name=num.outliers.to.exclude
p7_optional=on
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
p8_default_value=0
p8_description=Perform row normalization
p8_name=row.normalization
p8_optional=on
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=0\=no;1\=yes
p9_default_value=1
p9_description=Sample rows without replacement to obtain this fraction of the total number of rows
p9_name=row.sampling.rate
p9_optional=on
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=
pipelineModel=
privacy=public
publicationDate=02/11/2016 14\:34 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskDoc=doc.html
taskType=Preprocess & Utilities
userid=ted
version=Bug fix for optional 'threshold.for.removing.rows' and 'number.of.columns.above.threshold' module params
