# PreviewFCS  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00185:2
#Tue Feb 10 19:11:57 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00185\:2
author=Josef Spidlen, BC Cancer Agency
commandLine=<java> <java_flags> -jar <libdir>previewfcs.jar <Input.FCS.data.file> <Output.file.name> <Output.file.format>
cpuType=any
description=Allows viewing of structural metadata, parameters, and descriptive statistics from a Flow Cytometry Standard (FCS) data file
fileFormat=html;xml
language=Java
name=PreviewFCS
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=An input FCS data file to be described.
p1_fileFormat=fcs
p1_name=Input.FCS.data.file
p1_optional=
p1_prefix_when_specified=-InputFile\:
p1_type=java.io.File
p1_value=
p2_default_value=HTML
p2_description=Output file format, either HTML or XML, default HTML.
p2_fileFormat=
p2_name=Output.file.format
p2_optional=
p2_prefix_when_specified=-OutputFormat\:
p2_type=java.lang.String
p2_value=HTML\=HTML, default;XML\=XML
p3_default_value=<Input.FCS.data.file_basename>
p3_description=The output file name (optional).
p3_fileFormat=
p3_name=Output.file.name
p3_optional=
p3_prefix_when_specified=-OutputFile\:
p3_type=java.lang.String
p3_value=
pipelineModel=
privacy=public
publicationDate=07/13/2012 09\:49 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Flow Cytometry
userid=jspidlen@bccrc.ca
version=Fix for parsing empty keyword values
