# ProteomicsAnalysis  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00048:2
#Tue Feb 10 19:11:58 UTC 2026
JVMLevel=2.5.0
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00048\:2
author=D.R. Mani, Broad Institute
commandLine=<R2.5> <libdir>pipeline.wrapper.R pipeline.wrapper <zip.filename> <output.file> <libdir> -_3<quality.threshold> -_40.00125 -_5<fill.na> -_6<normalize> -_7<peak.detection.method> -_8<filter.peaks> -_9<filter.peaks.factor> -10<peak.list.filename> -11<random.seed> -12<random.n.peaks> -13<low.Da> -14<high.Da> -15<percentile> -16<smoothing.size> -17<adaptive.background.correction.strength> -18<adaptive.background.correction.size> -19<high.pass.filter.strength> -20<high.pass.filter.factor> 
cpuType=any
description=Runs the proteomics analysis on the set of input spectra
fileFormat=gct;EM Gaussian Mixtures;Actual Peaks to EM-matched Peaks;Actual Peaks;Proteomics Analysis Statistics
language=R
name=ProteomicsAnalysis
os=any
p10_default_value=
p10_description=random seed when peaks\=random
p10_name=random.seed
p10_optional=on
p10_prefix_when_specified=
p10_type=java.lang.Integer
p10_value=
p11_default_value=
p11_description=number of random M/Z's selected when peaks\=random
p11_name=random.n.peaks
p11_optional=on
p11_prefix_when_specified=
p11_type=java.lang.Integer
p11_value=
p12_default_value=
p12_description=Minimum M/Z to include
p12_name=low.Da
p12_optional=
p12_prefix_when_specified=
p12_type=java.lang.Float
p12_value=
p13_default_value=
p13_description=Maximum M/Z to include
p13_name=high.Da
p13_optional=
p13_prefix_when_specified=
p13_type=java.lang.Float
p13_value=
p14_default_value=0.65
p14_description=After applying filters, threshold above which peaks are located
p14_name=percentile
p14_optional=
p14_prefix_when_specified=
p14_type=java.lang.Float
p14_value=
p15_default_value=21
p15_description=Size of the smoothing filter
p15_name=smoothing.size
p15_optional=
p15_prefix_when_specified=
p15_type=java.lang.Float
p15_value=
p16_default_value=0.75
p16_description=Strength of the adaptive background correction filter
p16_name=adaptive.background.correction.strength
p16_optional=
p16_prefix_when_specified=
p16_type=java.lang.Float
p16_value=
p17_default_value=21
p17_description=Size of the adaptive background correction filter
p17_name=adaptive.background.correction.size
p17_optional=
p17_prefix_when_specified=
p17_type=java.lang.Float
p17_value=
p18_default_value=10
p18_description=Strength of the high pass filter
p18_name=high.pass.filter.strength
p18_optional=
p18_prefix_when_specified=
p18_type=java.lang.Float
p18_value=
p19_default_value=5
p19_description=Filter factor for the high pass filter
p19_name=high.pass.filter.factor
p19_optional=
p19_prefix_when_specified=
p19_type=java.lang.Float
p19_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Zip file containing spectra data. Spectra data are stored as M/Z,Intensity
p1_fileFormat=zip
p1_name=zip.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<zip.filename_basename>
p2_description=The base name for output files
p2_name=output.file
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_default_value=0.45
p3_description=discard spectra with quality < quality threshold
p3_name=quality.threshold
p3_optional=on
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_default_value=yes
p4_description=whether to fill missing peaks
p4_name=fill.na
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=yes;no
p5_default_value=tan
p5_description=normalization strategy
p5_name=normalize
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=tan;tin;01;none
p6_default_value=detect
p6_description=peak detection method
p6_name=peak.detection.method
p6_optional=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=detect;input;random
p7_default_value=yes
p7_description=filter peaks based on peak intensity / noise 
p7_name=filter.peaks
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=yes;no
p8_default_value=10
p8_description=retains peaks if peak intensity >\= filter.peaks.factor * stdev(noise)
p8_name=filter.peaks.factor
p8_optional=on
p8_prefix_when_specified=
p8_type=java.lang.Float
p8_value=
p9_MODE=IN
p9_TYPE=FILE
p9_default_value=
p9_description=file containing one M/Z per line when peaks\=input
p9_name=peak.list.filename
p9_optional=on
p9_prefix_when_specified=
p9_type=java.io.File
p9_value=
privacy=public
publicationDate=02/19/2008 16\:48 
quality=production
requiredPatchLSIDs=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.server.patch\:00009\:1
requiredPatchURLs=http\://www.broad.mit.edu/webservices/gpModuleRepository/download/prod/patch/?file\=/R_2_5_Check/broad.mit.edu\:cancer.software.genepattern.server.patch/00009/1/R2_5.zip
taskType=Proteomics
userid=GenePattern
version=Updated for R 2.5
