# ProteoArray  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00068:1
#Tue Feb 10 19:11:58 UTC 2026
JVMLevel=1.4
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00068\:1
author=Brian Piening (Fred Hutchinson Cancer Research Center)
commandLine=<java> <java_flags> -cp <libdir>ProteoArray.jar<path.separator><libdir>jrap.jar<path.separator><libdir>xerces.jar org.fhcrc.edi.proteoArray.ProteoArray <input.zip.filename> <output.file>
cpuType=any
description=LC-MS proteomic data processing module
fileFormat=gct
language=Java
name=ProteoArray
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=zip file of LC-MS runs in mzXML format.
p1_fileFormat=zip
p1_name=input.zip.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<input.zip.filename_basename>.prot
p2_description=output filename
p2_name=output.file
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
privacy=public
publicationDate=10/24/2005 16\:20 
quality=production
taskType=Proteomics
userid=GenePattern (gp-help@broad.mit.edu)
version=
