# PTM_SEA  urn:lsid:8080.gpserver.ip-172-31-26-71.ip-172-31-26-71.ec2.internal:genepatternmodules:69:4
#Tue Feb 10 19:11:58 UTC 2026
JVMLevel=
LSID=urn\:lsid\:8080.gpserver.ip-172-31-26-71.ip-172-31-26-71.ec2.internal\:genepatternmodules\:69\:4
author=Karsten Krug and D. R. Mani;Broad Institute
categories=Proteomics
commandLine=Rscript <libdir>ssgsea-cli.R <input.data> <output.prefix> <pathway.db> <normalization> <weight> <correlation> <test.type> <score.type> <n.permutations> <min.overlap> <extended.output> <export>  <global.FDR> <light.speed>
cpuType=any
description=PTM-SEA for use with PTMsigDB
fileFormat=
job.docker.image=broadcptac/pgdac_ssgsea\:4
language=R
name=PTM_SEA
os=any
p10_MODE=
p10_TYPE=Integer
p10_default_value=5
p10_description=Minimum overlap between signature and data set
p10_fileFormat=
p10_flag=--minoverlap 
p10_name=min.overlap
p10_numValues=0..1
p10_optional=
p10_prefix=--minoverlap 
p10_prefix_when_specified=--minoverlap 
p10_type=java.lang.Integer
p10_value=
p11_MODE=
p11_TYPE=TEXT
p11_default_value=TRUE
p11_description=If TRUE additional stats on signature coverage etc. will be included as row annotations in the GCT results files
p11_fileFormat=
p11_flag=--extendedoutput 
p11_name=extended.output
p11_numValues=0..1
p11_optional=
p11_prefix=--extendedoutput 
p11_prefix_when_specified=--extendedoutput 
p11_type=java.lang.String
p11_value=TRUE\=TRUE;FALSE\=FALSE
p12_MODE=
p12_TYPE=TEXT
p12_default_value=FALSE
p12_description=For each signature export expression GCT files
p12_fileFormat=
p12_flag=--export 
p12_name=export
p12_numValues=0..1
p12_optional=
p12_prefix=--export 
p12_prefix_when_specified=--export 
p12_type=java.lang.String
p12_value=FALSE\=FALSE;TRUE\=TRUE
p13_MODE=
p13_TYPE=TEXT
p13_default_value=TRUE
p13_description=If TRUE global FDR across all data columns is calculated
p13_fileFormat=
p13_flag=--globalfdr 
p13_name=global.FDR
p13_numValues=0..1
p13_optional=
p13_prefix=--globalfdr 
p13_prefix_when_specified=--globalfdr 
p13_type=java.lang.String
p13_value=TRUE\=TRUE;FALSE\=FALSE
p14_MODE=
p14_TYPE=TEXT
p14_default_value=TRUE
p14_description=If TRUE processing will be parallized across gene sets
p14_fileFormat=
p14_flag=--lightspeed 
p14_name=light.speed
p14_numValues=0..1
p14_optional=
p14_prefix=--lightspeed 
p14_prefix_when_specified=--lightspeed 
p14_type=java.lang.String
p14_value=TRUE\=TRUE;FALSE\=FALSE
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input data file (gct format)
p1_fileFormat=gct
p1_flag=-i 
p1_name=input.data
p1_numValues=0..1
p1_optional=
p1_prefix=-i 
p1_prefix_when_specified=-i 
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=<input.data_basename>
p2_description=Prefix for output file names
p2_fileFormat=
p2_flag=-o 
p2_name=output.prefix
p2_numValues=0..1
p2_optional=
p2_prefix=-o 
p2_prefix_when_specified=-o 
p2_type=java.lang.String
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=Pathway database (gmt format)
p3_fileFormat=gmt
p3_flag=--db 
p3_name=pathway.db
p3_numValues=0..1
p3_optional=
p3_prefix=--db 
p3_prefix_when_specified=--db 
p3_type=java.io.File
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=rank
p4_description=Sample normalization method
p4_fileFormat=
p4_flag=--norm 
p4_name=normalization
p4_numValues=0..1
p4_optional=
p4_prefix=--norm 
p4_prefix_when_specified=--norm 
p4_type=java.lang.String
p4_value=rank\=rank;log\=log;log.rank\=log.rank;none\=none
p5_MODE=
p5_TYPE=Floating Point
p5_default_value=0.75
p5_description=When weight\=\=0, all genes have the same weight; if weight>0 actual values matter and can change the resulting score
p5_fileFormat=
p5_flag=--weight 
p5_name=weight
p5_numValues=0..1
p5_optional=
p5_prefix=--weight 
p5_prefix_when_specified=--weight 
p5_type=java.lang.Float
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=z.score
p6_description=Correlation type
p6_fileFormat=
p6_flag=--correl 
p6_name=correlation
p6_numValues=0..1
p6_optional=
p6_prefix=--correl 
p6_prefix_when_specified=--correl 
p6_type=java.lang.String
p6_value=z.score\=z.score;rank\=rank;symm.rank\=symm.rank
p7_MODE=
p7_TYPE=TEXT
p7_default_value=area.under.RES
p7_description=Test statistic
p7_fileFormat=
p7_flag=--test 
p7_name=test.type
p7_numValues=0..1
p7_optional=
p7_prefix=--test 
p7_prefix_when_specified=--test 
p7_type=java.lang.String
p7_value=area.under.RES\=area.under.RES;Kolmogorov-Smirnov\=Kolmogorov-Smirnov
p8_MODE=
p8_TYPE=TEXT
p8_default_value=NES
p8_description=Enrichment score type
p8_fileFormat=
p8_flag=--score 
p8_name=score.type
p8_numValues=0..1
p8_optional=
p8_prefix=--score 
p8_prefix_when_specified=--score 
p8_type=java.lang.String
p8_value=NES\=NES;ES\=ES
p9_MODE=
p9_TYPE=Integer
p9_default_value=1000
p9_description=Number of permutations
p9_fileFormat=
p9_flag=--perm 
p9_name=n.permutations
p9_numValues=0..1
p9_optional=
p9_prefix=--perm 
p9_prefix_when_specified=--perm 
p9_type=java.lang.Integer
p9_value=
privacy=public
quality=development
taskDoc=
taskType=Proteomics
userid=manidr
version=Initial Version to accompany PTM-SEA manuscript
