# PyCoGAPS  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00417:4
#Tue Feb 10 19:11:58 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00417\:4
author=Ashley Tsang, Johns-Hopkins - Fertig Lab, Ted Liefeld ;UCSD - Mesirov Lab
categories=dimension reduction
commandLine=python3 /home/user/pycogaps-gpn/run_pycogaps.py  <input.file> <output.filename> <num.patterns> <num.iterations> <seed> <use.sparse.optimization> <num.threads> <messages> <output.frequency> <uncertainty> <checkpoint.out.filename> <checkpoint.in.file>  <worker.ID> <asynchronous.updates> <n.snapshots> <snapshot.phase> <alpha.A> <alpha.P> <max.Gibbs.Mass.A> <max.Gibbs.Mass.P> <distributed> <num.sets> <cut> <min.NS> <max.NS> <explicit.sets> <sampling.annotation> <sampling.weight> <subset.indices> <subset.dimension> <gene.names> <sample.names> <fixed.patterns> <which.matrix.fixed> <take.pump.samples> <hdf.key> <hdf.row.key> <hdf.col.key>  <transpose.data>
cpuType=any
description=Coordinated Gene Activity in Pattern Sets (CoGAPS) implements a Bayesian MCMC matrix factorization algorithm, GAPS, and links it to gene set statistic methods to infer biological process activity. It can be used to perform sparse matrix factorization on any data, and when this data represents biomolecules, to do gene set analysis. This package, PyCoGAPS, presents a unified Python interface, with a parallel, efficient underlying implementation.
documentationUrl=https\://genepattern.github.io/PyCoGAPS/v1/index
fileFormat=pkl
job.cpuCount=
job.docker.image=fertiglab/pycogaps-gpn\:0.2.2
job.memory=64Gb
job.walltime=
language=any
name=PyCoGAPS
os=any
p10_MODE=
p10_TYPE=Integer
p10_default_value=500
p10_description=The number of iterations between each output (set to 0 to disable status updates).
p10_fileFormat=
p10_flag=--outputFrequency 
p10_name=output.frequency
p10_numValues=0..1
p10_optional=
p10_prefix=--outputFrequency 
p10_prefix_when_specified=--outputFrequency 
p10_type=java.lang.Integer
p10_value=
p11_MODE=IN
p11_TYPE=FILE
p11_default_value=
p11_description=The uncertainty matrix - in csv format.
p11_fileFormat=.csv;csv;csv, txt
p11_flag=--uncertainty 
p11_name=uncertainty
p11_numValues=0..1
p11_optional=on
p11_prefix=--uncertainty 
p11_prefix_when_specified=--uncertainty 
p11_type=java.io.File
p11_value=
p12_MODE=
p12_TYPE=TEXT
p12_default_value=gaps_checkpoint.out
p12_description=The name of the checkpoint file to create.
p12_fileFormat=
p12_flag=--checkpointOutFile 
p12_name=checkpoint.out.filename
p12_numValues=0..1
p12_optional=
p12_prefix=--checkpointOutFile 
p12_prefix_when_specified=--checkpointOutFile 
p12_type=java.lang.String
p12_value=
p13_MODE=IN
p13_TYPE=FILE
p13_default_value=
p13_description=If this is provided, CoGAPS runs from the checkpoint contained in this file.
p13_fileFormat=
p13_flag=--checkpointInFile 
p13_name=checkpoint.in.file
p13_numValues=0..1
p13_optional=on
p13_prefix=--checkpointInFile 
p13_prefix_when_specified=--checkpointInFile 
p13_type=java.io.File
p13_value=
p14_MODE=
p14_TYPE=Integer
p14_default_value=1
p14_description=If calling CoGAPS in parallel the worker ID can be specified.
p14_fileFormat=
p14_flag=--workerID 
p14_name=worker.ID
p14_numValues=0..1
p14_optional=
p14_prefix=--workerID 
p14_prefix_when_specified=--workerID 
p14_type=java.lang.Integer
p14_value=
p15_MODE=
p15_TYPE=TEXT
p15_default_value=False
p15_description=Enable asynchronous updating which allows for multi-threaded runs.
p15_fileFormat=
p15_flag=--asynchronousUpdates 
p15_name=asynchronous.updates
p15_numValues=0..1
p15_optional=
p15_prefix=--asynchronousUpdates 
p15_prefix_when_specified=--asynchronousUpdates 
p15_type=java.lang.String
p15_value=True\=True;False\=False
p16_MODE=
p16_TYPE=Integer
p16_default_value=0
p16_description=Sets how many snapshots to take in each phase, setting this to 0 disables snapshots.
p16_fileFormat=
p16_flag=--nSnapshots 
p16_name=n.snapshots
p16_numValues=0..1
p16_optional=
p16_prefix=--nSnapshots 
p16_prefix_when_specified=--nSnapshots 
p16_type=java.lang.Integer
p16_value=
p17_MODE=
p17_TYPE=TEXT
p17_default_value=sampling
p17_description=During which phase to take snapshots in e.g. \u201cequilibration\u201d, \u201csampling\u201d, \u201call\u201d.
p17_fileFormat=
p17_flag=--snapshotPhase 
p17_name=snapshot.phase
p17_numValues=0..1
p17_optional=
p17_prefix=--snapshotPhase 
p17_prefix_when_specified=--snapshotPhase 
p17_type=java.lang.String
p17_value=sampling\=sampling;equilibration\=equilibration;all\=all
p18_MODE=
p18_TYPE=Floating Point
p18_default_value=.01
p18_description=The sparsity parameter for feature matrix.
p18_fileFormat=
p18_flag=--alphaA 
p18_name=alpha.A
p18_numValues=0..1
p18_optional=
p18_prefix=--alphaA 
p18_prefix_when_specified=--alphaA 
p18_type=java.lang.Float
p18_value=
p19_MODE=
p19_TYPE=Floating Point
p19_default_value=.01
p19_description=The sparsity parameter for sample matrix.
p19_fileFormat=
p19_flag=--alphaP 
p19_name=alpha.P
p19_numValues=0..1
p19_optional=
p19_prefix=--alphaP 
p19_prefix_when_specified=--alphaP 
p19_type=java.lang.Float
p19_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input data file in h5ad, csv, gct or txt format.
p1_fileFormat=.csv;csv;csv, txt;gct;txt;txt,gct;h5ad
p1_flag=--path 
p1_name=input.file
p1_numValues=0..1
p1_optional=
p1_prefix=--path 
p1_prefix_when_specified=--path 
p1_type=java.io.File
p1_value=
p20_MODE=
p20_TYPE=Floating Point
p20_default_value=100
p20_description=The atomic mass restriction for feature matrix.
p20_fileFormat=
p20_flag=--maxGibbsMassA 
p20_name=max.Gibbs.Mass.A
p20_numValues=0..1
p20_optional=
p20_prefix=--maxGibbsMassA 
p20_prefix_when_specified=--maxGibbsMassA 
p20_type=java.lang.Float
p20_value=
p21_MODE=
p21_TYPE=Floating Point
p21_default_value=100
p21_description=The atomic mass restriction for sample matrix.
p21_fileFormat=
p21_flag=--maxGibbsMassP 
p21_name=max.Gibbs.Mass.P
p21_numValues=0..1
p21_optional=
p21_prefix=--maxGibbsMassP 
p21_prefix_when_specified=--maxGibbsMassP 
p21_type=java.lang.Float
p21_value=
p22_MODE=
p22_TYPE=TEXT
p22_default_value=
p22_description=Either null (None) or genome-wide.
p22_fileFormat=
p22_flag=--distributed 
p22_name=distributed
p22_numValues=0..1
p22_optional=on
p22_prefix=--distributed 
p22_prefix_when_specified=--distributed 
p22_type=java.lang.String
p22_value=\ \=None;Genome-wide\=Genome-wide
p23_MODE=
p23_TYPE=Integer
p23_default_value=4
p23_description=The number of sets to break data into.
p23_fileFormat=
p23_flag=--nSets 
p23_name=num.sets
p23_numValues=1..1
p23_optional=
p23_prefix=--nSets 
p23_prefix_when_specified=--nSets 
p23_type=java.lang.Integer
p23_value=
p24_MODE=
p24_TYPE=Integer
p24_default_value=
p24_description=The number of branches at which to cut dendrogram used in pattern matching.\n default\: nPatterns
p24_fileFormat=
p24_flag=--cut 
p24_name=cut
p24_numValues=0..1
p24_optional=on
p24_prefix=--cut 
p24_prefix_when_specified=--cut 
p24_type=java.lang.Integer
p24_value=
p25_MODE=
p25_TYPE=Integer
p25_default_value=
p25_description=The minimum of individual set contributions a cluster must contain. default\: Math.ceil(cut / 2)
p25_fileFormat=
p25_flag=--minNS 
p25_name=min.NS
p25_numValues=0..1
p25_optional=on
p25_prefix=--minNS 
p25_prefix_when_specified=--minNS 
p25_type=java.lang.Integer
p25_value=
p26_MODE=
p26_TYPE=Integer
p26_default_value=
p26_description=The maximum of individual set contributions a cluster can contain.\n default\: minNS + nSets
p26_fileFormat=
p26_flag=--maxNS 
p26_name=max.NS
p26_numValues=0..1
p26_optional=on
p26_prefix=--maxNS 
p26_prefix_when_specified=--maxNS 
p26_type=java.lang.Integer
p26_value=
p27_MODE=IN
p27_TYPE=FILE
p27_default_value=
p27_description=Whether to specify subsets by index or name.
p27_fileFormat=.csv;csv;csv, txt
p27_flag=--explicitSets 
p27_name=explicit.sets
p27_numValues=0..1
p27_optional=on
p27_prefix=--explicitSets 
p27_prefix_when_specified=--explicitSets 
p27_type=java.io.File
p27_value=
p28_MODE=IN
p28_TYPE=FILE
p28_default_value=
p28_description=Specify categories along the rows (cols) to use for weighted sampling.\t
p28_fileFormat=.csv;csv;csv, txt
p28_flag=--samplingAnnotation 
p28_name=sampling.annotation
p28_numValues=0..1
p28_optional=on
p28_prefix=--samplingAnnotation 
p28_prefix_when_specified=--samplingAnnotation 
p28_type=java.io.File
p28_value=
p29_MODE=IN
p29_TYPE=FILE
p29_default_value=
p29_description=The weights associated with sampling annotation.\t
p29_fileFormat=txt
p29_flag=--samplingWeight 
p29_name=sampling.weight
p29_numValues=0..1
p29_optional=on
p29_prefix=--samplingWeight 
p29_prefix_when_specified=--samplingWeight 
p29_type=java.io.File
p29_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=<input.file_basename>_result.h5ad
p2_description=The result output file name (output is saved as a .h5ad file).\t
p2_fileFormat=
p2_flag=--resultFile 
p2_name=output.filename
p2_numValues=0..1
p2_optional=
p2_prefix=--resultFile 
p2_prefix_when_specified=--resultFile 
p2_type=java.lang.String
p2_value=
p30_MODE=IN
p30_TYPE=FILE
p30_default_value=
p30_description=The set of indices to use from the data.\t
p30_fileFormat=
p30_flag=--subsetIndices 
p30_name=subset.indices
p30_numValues=0..1
p30_optional=on
p30_prefix=--subsetIndices 
p30_prefix_when_specified=--subsetIndices 
p30_type=java.io.File
p30_value=
p31_MODE=
p31_TYPE=TEXT
p31_default_value=0
p31_description=Which dimension (rows, columns) to subset.\t
p31_fileFormat=
p31_flag=--subsetDim 
p31_name=subset.dimension
p31_numValues=0..1
p31_optional=
p31_prefix=--subsetDim 
p31_prefix_when_specified=--subsetDim 
p31_type=java.lang.String
p31_value=0\=Rows;1\=Columns
p32_MODE=IN
p32_TYPE=FILE
p32_default_value=
p32_description=The vector of names of genes in the data.\t
p32_fileFormat=
p32_flag=--geneNames 
p32_name=gene.names
p32_numValues=0..1
p32_optional=on
p32_prefix=--geneNames 
p32_prefix_when_specified=--geneNames 
p32_type=java.io.File
p32_value=
p33_MODE=IN
p33_TYPE=FILE
p33_default_value=
p33_description=The vector of names of samples in the data.\t
p33_fileFormat=
p33_flag=--sampleNames 
p33_name=sample.names
p33_numValues=0..1
p33_optional=on
p33_prefix=--sampleNames 
p33_prefix_when_specified=--sampleNames 
p33_type=java.io.File
p33_value=
p34_MODE=IN
p34_TYPE=FILE
p34_default_value=
p34_description=The provided fixedPatterns matrix (either \u2018A\u2019 or \u2018P\u2019 matrix) allows for manual pattern matching. In distributed CoGAPS (distributed\=\u2019genome-wide\u2019), the first phase is skipped and fixedPatterns is used for all sets. In standard CoGAPS, fixedPatterns allows for fixed runs.
p34_fileFormat=.csv;csv;csv, txt
p34_flag=--fixedPatterns 
p34_name=fixed.patterns
p34_numValues=0..1
p34_optional=on
p34_prefix=--fixedPatterns 
p34_prefix_when_specified=--fixedPatterns 
p34_type=java.io.File
p34_value=
p35_MODE=
p35_TYPE=TEXT
p35_default_value=A
p35_description=Either \u2018A\u2019 or \u2018P\u2019, indicating which matrix is fixed.\t
p35_fileFormat=
p35_flag=--whichMatrixFixed 
p35_name=which.matrix.fixed
p35_numValues=0..1
p35_optional=on
p35_prefix=--whichMatrixFixed 
p35_prefix_when_specified=--whichMatrixFixed 
p35_type=java.lang.String
p35_value=A\=A;P\=P
p36_MODE=
p36_TYPE=TEXT
p36_default_value=False
p36_description=Whether or not to take PUMP samples.\t
p36_fileFormat=
p36_flag=--takePumpSamples 
p36_name=take.pump.samples
p36_numValues=0..1
p36_optional=
p36_prefix=--takePumpSamples 
p36_prefix_when_specified=--takePumpSamples 
p36_type=java.lang.String
p36_value=True\=True;False\=False
p37_MODE=
p37_TYPE=TEXT
p37_default_value=
p37_description=Hdf key for reading .h5 files.\t
p37_fileFormat=
p37_flag=--hdfKey 
p37_name=hdf.key
p37_numValues=0..1
p37_optional=on
p37_prefix=--hdfKey 
p37_prefix_when_specified=--hdfKey 
p37_type=java.lang.String
p37_value=
p38_MODE=
p38_TYPE=TEXT
p38_default_value=
p38_description=Hdf row key for reading .h5 files.\t
p38_fileFormat=
p38_flag=--hdfRowKey 
p38_name=hdf.row.key
p38_numValues=0..1
p38_optional=on
p38_prefix=--hdfRowKey 
p38_prefix_when_specified=--hdfRowKey 
p38_type=java.lang.String
p38_value=
p39_MODE=
p39_TYPE=TEXT
p39_default_value=
p39_description=Hdf column key for reading .h5 files.\t
p39_fileFormat=
p39_flag=--hdfColKey 
p39_name=hdf.col.key
p39_numValues=0..1
p39_optional=on
p39_prefix=--hdfColKey 
p39_prefix_when_specified=--hdfColKey 
p39_type=java.lang.String
p39_value=
p3_MODE=
p3_TYPE=Integer
p3_default_value=3
p3_description=The number of patterns PyCoGAPS will learn.
p3_fileFormat=
p3_flag=--nPatterns 
p3_name=num.patterns
p3_numValues=0..1
p3_optional=
p3_prefix=--nPatterns 
p3_prefix_when_specified=--nPatterns 
p3_type=java.lang.Integer
p3_value=
p4_MODE=
p4_TYPE=Integer
p4_default_value=1000
p4_description=The number of iterations for each phase of the algorithm.
p4_fileFormat=
p4_flag=--nIterations 
p4_name=num.iterations
p4_numValues=0..1
p4_optional=
p4_prefix=--nIterations 
p4_prefix_when_specified=--nIterations 
p4_type=java.lang.Integer
p4_value=
p5_MODE=
p5_TYPE=Integer
p5_default_value=0
p5_description=Random number generator seed.
p5_fileFormat=
p5_flag=--seed 
p5_name=seed
p5_numValues=0..1
p5_optional=
p5_prefix=--seed 
p5_prefix_when_specified=--seed 
p5_type=java.lang.Integer
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=False
p6_description=When true, speeds up performance with sparse data (roughly >80% of data is zero), note this can only be used with the default uncertainty.
p6_fileFormat=
p6_flag=--useSparseOptimization 
p6_name=use.sparse.optimization
p6_numValues=0..1
p6_optional=
p6_prefix=--useSparseOptimization 
p6_prefix_when_specified=--useSparseOptimization 
p6_type=java.lang.String
p6_value=True\=True;False\=False
p7_MODE=
p7_TYPE=TEXT
p7_default_value=False
p7_description=Transpose the dataset before processing.
p7_fileFormat=
p7_flag=--transposeData  
p7_name=transpose.data
p7_numValues=0..1
p7_optional=
p7_prefix=--transposeData  
p7_prefix_when_specified=--transposeData  
p7_type=java.lang.String
p7_value=False\=False;True\=True
p8_MODE=
p8_TYPE=Integer
p8_default_value=1
p8_description=The maximum number of threads to run on.
p8_fileFormat=
p8_flag=--nThreads 
p8_name=num.threads
p8_numValues=0..1
p8_optional=
p8_prefix=--nThreads 
p8_prefix_when_specified=--nThreads 
p8_type=java.lang.Integer
p8_value=
p9_MODE=
p9_TYPE=TEXT
p9_default_value=False
p9_description=When True, display additional outputs to stdout.txt.
p9_fileFormat=
p9_flag=--messages 
p9_name=messages
p9_numValues=0..1
p9_optional=
p9_prefix=--messages 
p9_prefix_when_specified=--messages 
p9_type=java.lang.String
p9_value=True\=True;False\=False
privacy=public
publicationDate=01/03/2024 14\:18 
quality=production
src.repo=https\://github.com/genepattern/PyCoGAPS
taskDoc=
taskType=beta
userid=ted
version=Updated parameter descriptions for max gibbs A and P
