# Read_group_trackingToGct  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00339:0.15
#Tue Feb 10 19:11:59 UTC 2026
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00339\:0.15
author=David Eby, Broad Institute
categories=RNA-seq;Data Format Conversion;Preprocess & Utilities
commandLine=<java> <java_flags> -jar <libdir>ReadGroupTrackingToGct.jar --input.file\=<input.file> --output.file.name\=<output.file.name> --expression.value.column\=<expression.value.column> --screen.out.errors\=<screen.out.errors> --output.value.for.error\=<output.value.for.error> <gtf.file> --feature.level.for.symbol.lookup\=<feature.level.for.symbol.lookup> --choose.gct.column.for.mapping\=<choose.gct.column.for.mapping> --report.naming.conflict.details\=<report.naming.conflict.details> <override.attribute.name.for.lookup> <override.attribute.name.for.retrieval>
description=[**Beta Release** Contact gp-help with any issues. Check stdout.txt and stderr.txt for errors] Converts a Cufflinks read_group_tracking file into GCT format
fileFormat=gct
license=
minGenePatternVersion=
name=Read_group_trackingToGct
os=any
p10_default_value=
p10_description=Use this to override the name of the attribute to search against to look up IDs when mapping with a GTF (gene_id, for example). Type in the attribute name exactly as it appears in the GTF.  The retrieval override must also be provided if this parameter is set.
p10_name=override.attribute.name.for.lookup
p10_optional=on
p10_prefix_when_specified=--override.attribute.name.for.lookup\=
p10_type=java.lang.String
p10_value=
p11_default_value=
p11_description=Use this to override the name of the attribute to retrieve on match when mapping with a GTF (gene_name, for example). Type in the attribute name exactly as it appears in the GTF.  The lookup override must also be provided if this parameter is set.
p11_name=override.attribute.name.for.retrieval
p11_optional=on
p11_prefix_when_specified=--override.attribute.name.for.retrieval\=
p11_type=java.lang.String
p11_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The read_group_tracking file to be converted into GCT format.
p1_fileFormat=read_group_tracking
p1_name=input.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<input.file_basename>.gct
p2_description=The name to be given to the GCT output file.
p2_name=output.file.name
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_default_value=3
p3_description=The column to use for extracting expression values.
p3_fileFormat=
p3_name=expression.value.column
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=0\=raw_frags;1\=internal_scaled_frags;2\=external_scaled_frags;3\=FPKM
p4_default_value=false
p4_description=Set to 'yes' to exclude from the GCT file any feature having at least one non-OK quantification status across all of the sequenced samples.
p4_fileFormat=
p4_name=screen.out.errors
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=true\=yes;false\=no
p5_default_value=NA
p5_description=This parameter controls what expression value to write to a GCT file in those cases where a feature's expression estimate carries a non-OK quantification status.  The parameter is only relevant to your final GCT when 'screen out errors' is set to 'no'.  We strongly recommend treating these as missing values (select 'NA' or 'blank').
p5_fileFormat=
p5_name=output.value.for.error
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=NA\=NA;blank\=blank;actual\=actual value (discouraged)
p6_MODE=IN
p6_TYPE=FILE
p6_default_value=
p6_description=An optional GTF file.  If provided, this should be the same file that you provided to Cuffdiff. You can use this to map tracking IDs in the read_group_tracking file to gene symbols for output in the GCT.  Make sure that you set the feature level to match your read_group_tracking file.
p6_fileFormat=gtf
p6_name=gtf.file
p6_optional=on
p6_prefix_when_specified=--gtf.file\=
p6_type=java.io.File
p6_value=
p7_default_value=gene
p7_description=Select the feature level of the read_group_tracking file for mapping gene symbols from a GTF. This is ignored if no GTF is provided.
p7_name=feature.level.for.symbol.lookup
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=gene\=Gene;isoform\=Isoform;tss\=TSS;cds\=CDS
p8_default_value=auto
p8_description=Use this to explicitly set the GCT column to use when writing symbols retrieved from the GCT. This is automatic by default, meaning that retrieved symbols go into the Name column for gene-level files and into the Description column for other feature levels.
p8_fileFormat=
p8_name=choose.gct.column.for.mapping
p8_optional=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=auto\=Auto (default);Name;Description
p9_default_value=false
p9_description=Include the naming conflict details in the summary report, rather than just giving counts of the issues. 
p9_fileFormat=
p9_name=report.naming.conflict.details
p9_optional=
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=true\=yes;false\=no
privacy=public
publicationDate=09/27/2014 10\:14 
requiredPatchLSIDs=
requiredPatchURLs=
taskDoc=doc.html
taskType=RNA-seq
userid=pcarr@broadinstitute.org
version=Updated to accept a mapping file to convert tracking IDs to gene names.
