# RemoveMissingValues  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00184:1
#Tue Feb 10 19:11:59 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00184\:1
author=Michael Reich
commandLine=<R2.5> <libdir>remove_missing.R remove_missing -l<libdir> -i<input.file> -r<remove.opt> -o<output.filename>
cpuType=any
description=Removes features and/or samples containing missing (NA) values
fileFormat=gct
language=R
name=RemoveMissingValues
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input file (gct, res)
p1_fileFormat=gct, res
p1_name=input.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=1
p2_description=Remove rows, columns, or both containing missing values
p2_fileFormat=
p2_name=remove.opt
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=1\=rows;2\=cols;3\=both
p3_default_value=<input.file_basename>.na-rm.gct
p3_description=output file
p3_fileFormat=
p3_name=output.filename
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
pipelineModel=
privacy=public
publicationDate=11/24/2010 15\:31 
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Missing Value Imputation
userid=admin
version=Public Release
