# RemoveSaturatedFCSEvents  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00210:1
#Tue Feb 10 19:11:59 UTC 2026
JVMLevel=1.6
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00210\:1
author=Josef Spidlen, BC Cancer Agency
commandLine=<java> <java_flags> -jar <libdir>removesaturated.jar <Input.FCS.data.file> <Output.FCS.file.name>
cpuType=any
description=Remove saturated events from an FCS data file
fileFormat=fcs
language=Java
name=RemoveSaturatedFCSEvents
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=An FCS data file to remove saturated events from.
p1_fileFormat=fcs
p1_name=Input.FCS.data.file
p1_optional=
p1_prefix_when_specified=-InputFile\:
p1_type=java.io.File
p1_value=
p2_default_value=<Input.FCS.data.file_basename>.without_saturated.fcs
p2_description=The output FCS file name.
p2_fileFormat=
p2_name=Output.FCS.file.name
p2_optional=on
p2_prefix_when_specified=-OutputFile\:
p2_type=java.lang.String
p2_value=
pipelineModel=
privacy=public
publicationDate=07/12/2012 14\:48 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Flow Cytometry
userid=jspidlen@bccrc.ca
version=
