# RenameFile  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00338:1
#Tue Feb 10 19:11:59 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00338\:1
author=David Eby
commandLine=<perl> <libdir>rename_file_for_GP.pl --inputFile <input.file> --outputFilename <output.filename> --screenFilename <screen.filename> --forceCopy <force.copy>
cpuType=any
description=Creates a result file with the contents of the input but with a new name.  Where possible, this is done without copying the file but instead by simply making a link.  While it is possible to run this with a submitted file, the common use will be to change the name of a result file or a previously uploaded file.  Note that the original file will still be present in its original location. 
fileFormat=
language=any
name=RenameFile
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input file to be renamed
p1_fileFormat=bam;sam;gtf;gff;gct;res;clm;zip;bed;fasta;fastq;fq;atr;cdt;gtr;bai;sai;fai;txt;csv;wig;cdf;chip;dict;maf;seg;snp;fq1;odf
p1_name=input.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<input.file_basename>.cp.<input.file_extension>
p2_description=The name to give the output file
p2_fileFormat=
p2_name=output.filename
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_default_value=yes
p3_description=Automatically screen out problematic characters in the filename
p3_fileFormat=
p3_name=screen.filename
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=yes\=yes;no\=no
p4_default_value=no
p4_description=Force a copy to be made rather than a link. 
p4_fileFormat=
p4_flag=
p4_name=force.copy
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=yes\=yes;no\=no
pipelineModel=
privacy=public
publicationDate=03/19/2014 17\:23 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskDoc=doc.html
taskType=Preprocess & Utilities
userid=eby
version=
