# ReorderByClass  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00033:3
#Tue Feb 10 19:11:59 UTC 2026
JVMLevel=1.3
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00033\:3
author=Joshua Gould, Broad Institute
commandLine=<java> <java_flags> -cp <libdir>ReorderByClass.jar<path.separator><libdir>broad-cg.jar<path.separator><libdir>trove.jar<path.separator><libdir>Jama-1.0.1.jar<path.separator><libdir>gp-modules.jar org.genepattern.modules.reorderbyclass.ReorderByClass <expression.data.filename> <class.filename> <expression.data.file.output.name> <class.file.output.name>
cpuType=any
description=Reorder the samples in an expression dataset and class file by class
fileFormat=
language=Java
name=ReorderByClass
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Expression data - .res, .gct, .odf
p1_fileFormat=res;gct;Dataset
p1_name=expression.data.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Class file - .cls
p2_fileFormat=cls
p2_name=class.filename
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_default_value=<expression.data.filename_basename>_reordered
p3_description=Name of expression data output file
p3_name=expression.data.file.output.name
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_default_value=<class.filename_basename>_reordered
p4_description=Name of class output file
p4_name=class.file.output.name
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
pipelineModel=
privacy=public
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Preprocess & Utilities
userid=GenePattern (gp-help@broad.mit.edu)
version=Fixed default value for class file output name
