# RNASeQC  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00263:2.15
#Tue Feb 10 19:11:59 UTC 2026
If=you are supplying a zipped set of BAM files, the ZIP archive must also include the appropriate BAI files.A file or zip of files containing alignments in BAM format. - .zip, .bam
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00263\:2.15
author=David Deluca, Broad Institute
commandLine=<perl> <libdir>qcmetrics_wrapper.pl -libdir <libdir> -cache <libdir>../shared/RNASeQC_refSequence_cache/ -jCmd <java> -jarFile RNA-SeQC.jar -b <bam.files> -s <sample.info.file> -g <annotation.gtf> -a <annotation.gtf.file> <rRNA.interval.file> -r <reference.sequence> -rf <reference.sequence.file> -i <reference.sequence.index> -d <reference.sequence.dictionary>  -c <gc.content.file> -f <output.prefix> <rRNA.reference.file.index> -- <transcript.type.field> <correlation.comparison.file> <single.end> <num.downsampling.reads> -e <transcript.end.length> -n <num.genes> <transcript.level.metrics> <gc.margin> <num.rRNA.downsampling.reads> <GATK.flags> -o ./ -jFlags <java_flags>
cpuType=any
description=[**Beta Release** Contact gp-help with any issues. Check stdout.txt and stderr.txt for errors] Calculates metrics on aligned RNA-seq data.
fileFormat=zip
language=Java
name=RNASeQC
os=any
p10_default_value=1000
p10_description=The number of top-expressed genes for which to calculate metrics.
p10_name=num.genes
p10_optional=
p10_prefix_when_specified=
p10_type=java.lang.String
p10_value=
p11_default_value=
p11_description=Specifies the column of the GTF file in which the transcript type is specified. By default, the module looks for an attribute called transcript_type in the annotation gtf.
p11_fileFormat=
p11_name=transcript.type.field
p11_optional=on
p11_prefix_when_specified=-ttype 
p11_type=java.lang.Integer
p11_value=
p12_MODE=IN
p12_TYPE=FILE
p12_default_value=
p12_description=A file containing the genomic coordinates of rRNA. - .list
p12_fileFormat=list
p12_name=rRNA.interval.file
p12_optional=on
p12_prefix_when_specified=-n 
p12_type=java.io.File
p12_value=
p13_MODE=IN
p13_TYPE=FILE
p13_default_value=
p13_description=zip of index files created by BWA for the supplied rRNA reference file. Required if rRNA reference file is supplied. -.zip
p13_fileFormat=zip
p13_name=rRNA.reference.file.index
p13_optional=on
p13_prefix_when_specified=-BWArRNAIndex 
p13_type=java.io.File
p13_value=
p14_default_value=1000000
p14_description=Downsamples to calculate rRNA rate more efficiently. Default is 1 million. Set to 0 to disable.
p14_name=num.rRNA.downsampling.reads
p14_optional=on
p14_prefix_when_specified=-rRNAdSampleTarget 
p14_type=java.lang.String
p14_value=
p15_default_value=200
p15_description=The length of the 3' or 5' end of a transcript.
p15_name=transcript.end.length
p15_optional=
p15_prefix_when_specified=
p15_type=java.lang.String
p15_value=50;100;200
p16_default_value=
p16_description=Whether to calculate transcript-level metrics in addition to sample-level metrics.
p16_name=transcript.level.metrics
p16_optional=on
p16_prefix_when_specified=
p16_type=java.lang.String
p16_value=-transcriptDetails\=yes;\=no
p17_MODE=IN
p17_TYPE=FILE
p17_default_value=
p17_description=A file containing GC content for each of the transcripts. The file must be tab-delimited with 2 columns containing transcript name and GC content. The transcript name must appear in the GTF file.
p17_fileFormat=txt
p17_name=gc.content.file
p17_optional=on
p17_prefix_when_specified=
p17_type=java.io.File
p17_value=
p18_default_value=0.375
p18_description=Used in conjunction with the gc content file to specify the percent gc content to use as boundaries. E.g. 0.25 would set a lower cutoff of 25% and an upper cutoff of 75% (default is 0.375).
p18_fileFormat=txt
p18_name=gc.margin
p18_optional=on
p18_prefix_when_specified=-gcMargin 
p18_type=java.lang.String
p18_value=
p19_default_value=
p19_description=Perform downsampling on the given number of reads. It randomly samples the specified number of reads in all experimental samples when calculating metrics.
p19_name=num.downsampling.reads
p19_optional=on
p19_prefix_when_specified=-d 
p19_type=java.lang.String
p19_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=An indexed BAM file or zipped set of indexed BAM files to be analyzed. If you are supplying a single BAM file, it should be located in the same folder as its associated index file (BAI). (If SortSam is used to index the BAM file, then the BAM and BAI files are located in the same folder.)
p1_fileFormat=zip;bam
p1_name=bam.files
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p20_MODE=IN
p20_TYPE=FILE
p20_default_value=
p20_description=A GCT file to use to calculate correlation between expression values (only uses first sample if gct file contains more than one sample. Note also that expression values must be log normalized, and the identifiers must match those of the annotation GTF file)
p20_fileFormat=gct
p20_name=correlation.comparison.file
p20_optional=on
p20_prefix_when_specified=-corr 
p20_type=java.io.File
p20_value=
p21_default_value=
p21_description=Whether to plot the distribution of gap lengths
p21_name=gap.length
p21_optional=on
p21_prefix_when_specified=
p21_type=java.lang.String
p21_value=-gld\=yes;\=no
p22_default_value=
p22_description=Pass a string of flags directly to the GATK (e.g. "-DBQ 0" to set missing base qualities to zero).
p22_name=GATK.flags
p22_optional=on
p22_prefix_when_specified=-gatkFlags 
p22_type=java.lang.String
p22_value=
p23_default_value=<bam.files_basename>
p23_description=The prefix to use for the output file name
p23_name=output.prefix
p23_optional=
p23_prefix_when_specified=
p23_type=java.lang.String
p23_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=A TXT format sample info file containing a sample ID, sample file name, and notes column in tab-delimited format. - .txt
p2_fileFormat=txt
p2_name=sample.info.file
p2_optional=on
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_default_value=yes
p3_description=Whether the bam file contains single end reads. Select no for paired-end reads.
p3_name=single.end
p3_optional=on
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=-singleEnd\=yes;\=no
p4_default_value=
p4_description=A file containing annotations in GTF format. Either an annotation gtf or annotation gtf file must be provided.Note that the provided hg19 reference sequence requires contigs using in the '1' format.
p4_name=annotation.gtf
p4_optional=on
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=;<libdir>gencode.v3c.annotation.NCBI36.gtf\=Hg 18, GenCode,'chr1' format contigs;<libdir>gencode.v7.annotation.NCBI37.gtf\=Hg 19, GenCode,'chr1' format contigs;<libdir>gencode.v7.annotation_goodContig.gtf\=Hg19, Gencode, '1' format contigs
p5_MODE=IN
p5_TYPE=FILE
p5_default_value=
p5_description=A file containing annotations in GTF format. Either an annotation gtf file or annotation gtf must be provided.
p5_fileFormat=gtf
p5_name=annotation.gtf.file
p5_optional=on
p5_prefix_when_specified=
p5_type=java.io.File
p5_value=
p6_default_value=
p6_description=A FASTA file containing a reference sequence. The reference sequence provided here has an index (.fai) and a sequence dictionary (.dict). Either a reference sequence or reference sequence file (with index and dictionary) must be provided, but not both. Note that the provided hg19 reference sequence requires contigs using in the '1' format.
p6_name=reference.sequence
p6_optional=on
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=\=;Homo_sapiens_assembly19\=Home_sapiens_assembly19
p7_MODE=IN
p7_TYPE=FILE
p7_default_value=
p7_description=A FASTA file containing a reference sequence. The reference sequence must have an index (.fai) and a sequence dictionary (.dict) either in the same location or specified in the reference sequence index and reference sequence dictionary parameters. Reference sequence human_assembly19 is available in the documentation. Click on the "documentation" link in the upper right hand corner of this page.
p7_fileFormat=fasta;fa
p7_name=reference.sequence.file
p7_optional=on
p7_prefix_when_specified=
p7_type=java.io.File
p7_value=
p8_MODE=IN
p8_TYPE=FILE
p8_default_value=
p8_description=A file containing the index for the reference sequence - .fai
p8_fileFormat=fai
p8_name=reference.sequence.index
p8_optional=on
p8_prefix_when_specified=
p8_type=java.io.File
p8_value=
p9_MODE=IN
p9_TYPE=FILE
p9_default_value=
p9_description=A file containing the dictionary for the reference sequence. - .dict
p9_fileFormat=dict
p9_name=reference.sequence.dictionary
p9_optional=on
p9_prefix_when_specified=
p9_type=java.io.File
p9_value=
pipelineModel=
privacy=public
publicationDate=08/09/2013 14\:46 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=RNA-seq
userid=pcarr@broadinstitute.org
version=Beta Release\: Updated with RNASeQC.jar build 8.7.13. Currently outputs INFO and WARNING to stdout
