# SageKda2Cys  urn:lsid:7070.genepatt.genepatterntest.broadinstitute.org:genepatternmodules:268:6
#Tue Feb 10 19:12:00 UTC 2026
JVMLevel=
LSID=urn\:lsid\:7070.genepatt.genepatterntest.broadinstitute.org\:genepatternmodules\:268\:6
author=Alex Pico, Ted Liefeld
commandLine=<perl> <libdir>kda2cys.pl <input.filename> <libdir>
cpuType=any
description=Takes a zip of KeyDriverAnalysis output files and formats them as a cytoscape .cys session file
fileFormat=cys
language=Perl
name=SageKda2Cys
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=a zip file containing the outputs from the SageKeyDriverAnalysis module
p1_fileFormat=zip
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
pipelineModel=
privacy=public
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Sage
userid=
version=
