# Salmon.Indexer  urn:lsid:genepattern.org:module.analysis:00419:0.5
#Tue Feb 10 19:12:00 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00419\:0.5
author=Anthony S. Castanza;UCSD-MesirovLab
categories=preprocess & utilities;rna-seq
commandLine=<libdir>salmon_index.sh -a <GTF.gz> -t <Transcriptome.fa.gz> -g <Genome.fa.gz> -k <kmer> -m <Index.Mode> -f <Use.Gencode> -l <libdir> -j <job.cpuCount>
cpuType=any
description=Salmon (version 1.6.0) transcriptome indexer.<br>\n\nSee\: <a href\="https\://salmon.readthedocs.io/en/latest/salmon.html\#using-salmon" target\="_blank">The Salmon User Guide</a>\nfor detailed usage guidelines.
fileFormat=tar.gz
job.cpuCount=8
job.docker.image=genepattern/salmon-indexer\:beta_1.6.0
job.memory=32Gb
job.walltime=4\:00\:00
language=any
name=Salmon.Indexer
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=GTF file (must be gzipped).\nOnly used if a transcriptome fasta is not provided to the 'Transcriptome fa gz' parameter, or producing a decoy-aware index. Both require that a genome fasta is provided to the 'Genome fa gz' parameter.
p1_fileFormat=.gtf.gz;gtf.gz
p1_flag=-a
p1_name=GTF.gz
p1_numValues=0..1
p1_optional=on
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Transcriptome FASTA file (must be gzipped)<br>\nIf no Transcriptome FASTA is provided the module will attempt to generate one from the GTF and Genomic FASTA using gffread. This procedure has not been fully tested.\n
p2_fileFormat=.fa.gz;.fastq.gz;.fq.gz;fa.gz;fastq.gz;fq.gz
p2_flag=-t
p2_name=Transcriptome.fa.gz
p2_numValues=0..1
p2_optional=on
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=Genomic FASTA file (must be gzipped). Used when producing a decoy-aware index, or when reconstructing a transcriptome from a provided gtf.
p3_fileFormat=.fa.gz;.fastq.gz;.fq.gz;fa.gz;fastq.gz;fq.gz
p3_flag=-g
p3_name=Genome.fa.gz
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_MODE=
p4_TYPE=Integer
p4_default_value=31
p4_description=kmer size used for indexing (must be odd)
p4_fileFormat=
p4_flag=-k
p4_name=kmer
p4_numValues=1..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.Integer
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=full
p5_description=There are two options for generating a decoy-aware transcriptome\:\n<br>\nFull\: Uses the entire genome of the organism as the decoy sequence. This scheme provides a more comprehensive set of decoys resulting in more accurate quantification, but, produces a substantially larger index, requires considerably more memory to build and quantify against the index, and quantifications against the index are slower.\n<br>\nPartial\: Computes a set of decoy sequences by mapping the annotated transcripts you wish to index against a hard-masked version of the organism's genome. This produces a smaller index and requires substantially less memory quantify against, but may be more susceptible to spurious mappings.\n<br>\nIf no Genome fasta is provided, this parameter will be ignored.
p5_fileFormat=
p5_flag=-m
p5_name=Index.Mode
p5_numValues=1..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=full\=Full;partial\=Partial
p6_MODE=
p6_TYPE=TEXT
p6_default_value=TRUE
p6_description=Use Gencode format parsing for Transcriptome fasta record IDs
p6_fileFormat=
p6_flag=-f
p6_name=Use.Gencode
p6_numValues=1..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=TRUE\=true;FALSE\=false
privacy=public
publicationDate=03/31/2022 15\:39 
quality=preproduction
src.repo=https\://github.com/genepattern/Salmon.Indexer/tree/v0.5
taskDoc=Salmon.Indexer.pdf
taskType=rna-seq
userid=acastanza
version=Updated to Salmon 1.6.0 and added support for transcriptome only index
