# SelectFeaturesRows  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00022:4
#Tue Feb 10 19:12:01 UTC 2026
JVMLevel=1.4
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00022\:4
author=Joshua Gould, Broad Institute
commandLine=<java> <java_flags> -cp <libdir>SelectFeaturesRows.jar<path.separator><libdir>gp-modules.jar org.genepattern.modules.selectfeaturesrows.SelectFeaturesRows <input.filename> <list.filename> <output>
cpuType=any
description=Generate a .res, .gct, .snp, .cn, .loh, or .odf file containing only specified features (i.e. rows).
fileformat=gct;res;Dataset;snp;cn;loh
language=Java
name=SelectFeaturesRows
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=input file - .res, .gct, .snp, .cn, .loh, or .odf file from which the slice is extracted
p1_fileFormat=gct;res;Dataset;snp;cn;loh
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=text file containing one identifier per line that specifies the rows to select. 
p2_name=list.filename
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_default_value=<list.filename_basename>.slice
p3_description=output filename - .res, .gct, .snp, .cn, .loh, .odf
p3_name=output
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
pipelineModel=
privacy=public
publicationDate=04/30/2007 14\:01 
quality=production
serializedModel=
taskType=Gene List Selection
userid=GenePattern (gp-help@broad.mit.edu)
version=Added support for .snp, .cn, and .loh files
