# SelectSNPProbes  urn:lsid:broadinstitute.org:cancer.genome.analysis:00065:0.4
#Tue Feb 10 19:12:01 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broadinstitute.org\:cancer.genome.analysis\:00065\:0.4
author=gp-help@broadinstitute.org, Broad Institute
commandLine=<perl> <libdir>select_snp_probes.pl <input.file> <output.prefix>
description=Filter to keep just copy number probes
fileFormat=cn;xcn;snp;bsnp
language=Perl
name=SelectSNPProbes
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The input file - .cn, .xcn, .snp, .bsnp
p1_fileFormat=cn;xcn;snp;bsnp
p1_name=input.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<input.file_basename>
p2_description=The prefix to use for the output file
p2_name=output.prefix
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
privacy=public
publicationDate=12/28/2011 13\:55 
quality=production
taskType=SNP Analysis
userid=GenePattern
version=Modified to append extension of input file to output file and input and output file formats and added doc
