# SelectFileMatrix  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00285:1
#Tue Feb 10 19:12:01 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00285\:1
author=David Eby, Broad Institute
commandLine=<java> <java_flags> -cp <libdir>SelectFileMatrix.jar<path.separator><libdir>gp-annotations.jar<path.separator><libdir>jopt-simple-3.3.jar<path.separator><libdir>jakarta-oro-2.0.8.jar<path.separator><libdir>commons-lang-2.5.jar<path.separator><libdir>commons-io-2.3.jar org.broadinstitute.modules.selectfilematrix.SelectFileMatrix <input.file> <output.file.base.name> <delimiter> <start.row> <end.row> <start.column> <end.column> <row.select> <column.select> <output.rejects>
cpuType=any
description=A helper module which selects a matrix out of a delimited text file.
fileFormat=csv;txt
language=Java
name=SelectFileMatrix
os=any
p10_default_value=false
p10_description=Produce an output file containing the items not meeting the selection criteria.  The file will be named <output.file.base.name>.REJECT.<ext>
p10_fileFormat=
p10_name=output.rejects
p10_optional=on
p10_prefix_when_specified=--output.rejects\=
p10_type=java.lang.String
p10_value=false;true
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Name of the input file from which to pull the matrix.  Must be a delimited text file.
p1_fileFormat=csv;txt;gct;res;cdt;chip;clm;cls;cn;glad;gmt;gmx;grp;loh;maf;odf;snp;xcn
p1_name=input.file
p1_optional=
p1_prefix_when_specified=--input.file\=
p1_type=java.io.File
p1_value=
p2_default_value=<input.file_basename>.select
p2_description=Base name for the output file.  The module will add an appropriate extension, either .csv for a comma-delimted file or .txt for a space- or tab-delimited file).
p2_fileFormat=
p2_name=output.file.base.name
p2_optional=
p2_prefix_when_specified=--output.file.base.name\=
p2_type=java.lang.String
p2_value=
p3_default_value=TAB
p3_description=Token naming the character for the output column delimiter. Choices are TAB, COMMA, and SPACE. TAB is the default.
p3_fileFormat=
p3_name=delimiter
p3_optional=on
p3_prefix_when_specified=--delimiter\=
p3_type=java.lang.String
p3_value=TAB\=tab;COMMA\=comma;SPACE\=space
p4_default_value=
p4_description=Starting row of the matrix (line number within the file).  Defaults to the first row.
p4_fileFormat=
p4_name=start.row
p4_optional=on
p4_prefix_when_specified=--start.row\=
p4_type=java.lang.Integer
p4_value=
p5_default_value=
p5_description=Ending row of the matrix (line number within the file).  Defaults to the last row.
p5_fileFormat=
p5_name=end.row
p5_optional=on
p5_prefix_when_specified=--end.row\=
p5_type=java.lang.Integer
p5_value=
p6_default_value=
p6_description=Starting column of the matrix.  Defaults to the first column.
p6_fileFormat=
p6_name=start.column
p6_optional=on
p6_prefix_when_specified=--start.column\=
p6_type=java.lang.Integer
p6_value=
p7_default_value=
p7_description=Ending column of the matrix. Defaults to the last column.
p7_fileFormat=
p7_name=end.column
p7_optional=on
p7_prefix_when_specified=--end.column\=
p7_type=java.lang.Integer
p7_value=
p8_default_value=
p8_description=Select specific rows to include in the matrix (e.g. "3,5,7-12").  Note that start/end row parameters may limit this selection.
p8_fileFormat=
p8_name=row.select
p8_optional=on
p8_prefix_when_specified=--row.select\=
p8_type=java.lang.String
p8_value=
p9_default_value=
p9_description=Select specific columns to include in the matrix (e.g. "1,2,4-6").  Note that start/end column parameters may limit this selection
p9_fileFormat=
p9_name=column.select
p9_optional=on
p9_prefix_when_specified=--column.select\=
p9_type=java.lang.String
p9_value=
pipelineModel=
privacy=public
publicationDate=07/09/2012 12\:45 
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Preprocess & Utilities
userid=
version=
