# SetFCSKeywords  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00186:2
#Tue Feb 10 19:12:02 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00186\:2
author=Josef Spidlen, BC Cancer Agency
commandLine=<java> <java_flags> -jar <libdir>setfcskeywords.jar <Input.FCS.data.file> <Keywords.input.file> <Output.fcs.file.name>
cpuType=any
description=Sets keyword/value(s) in a Flow Cytometry Standard (FCS) file.
fileFormat=fcs
language=Java
name=SetFCSKeywords
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The input FCS data file in which to set keyword/value pairs.
p1_fileFormat=fcs
p1_name=Input.FCS.data.file
p1_optional=
p1_prefix_when_specified=-InputFile\:
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=The file with keyword/value pairs to add (or change values of existing keywords). The keyword/value pairs can be submitted either as an CSV file with two columns\: "Keyword" and "Value" (heading is optional) or as a text file with a chunk of FCS TEXT segment, e.g., /$P3S/MUC 1 APC/$P4S/Thy1 PE/BD$CUSTOM_VALUE23/12/.
p2_fileFormat=csv;txt
p2_name=Keywords.input.file
p2_optional=
p2_prefix_when_specified=-KeywordsFile\:
p2_type=java.io.File
p2_value=
p3_default_value=
p3_description=The file name for the output FCS data file.
p3_fileFormat=
p3_name=Output.fcs.file.name
p3_optional=on
p3_prefix_when_specified=-OutputFile\:
p3_type=java.lang.String
p3_value=
pipelineModel=
privacy=public
publicationDate=07/11/2012 14\:16 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Flow Cytometry
userid=jspidlen@bccrc.ca
version=Fix for parsing empty keyword values
