# Seurat.VisualizeMarkerExpression  urn:lsid:genepattern.org:module.analysis:00421:2
#Tue Feb 10 19:12:02 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00421\:2
author=Edwin F. Juarez;UCSD - Mesirov Lab
categories=single-cell;singlecell
commandLine=Rscript --no-save --quiet --slave --no-restore  <libdir>seurat_visualize.R --input_file <input_file> --genes <genes> --group_plots <group_plots> --output_file_name <output_file_name>
cpuType=any
description=Visualize Marker Expression as violin plots and on a UMap. To be used after Seurat.Clustering
documentationUrl=https\://github.com/genepattern/Seurat.VisualizeMarkerExpression/blob/v2/documentation.md
fileFormat=pdf
job.docker.image=genepattern/seurat-suite\:4.0.3
language=any
name=Seurat.VisualizeMarkerExpression
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=RDS file to load.
p1_fileFormat=rds
p1_flag=--input_file
p1_name=input_file
p1_numValues=0..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=
p2_description=List of genes to visualize. If you write multiple genes they must be separated by a comma and a space (for example\: MS4A1, CD8A, CD14).
p2_fileFormat=
p2_flag=--genes
p2_name=genes
p2_numValues=0..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=Horizontally
p3_description=How to group plots that are associated with the same marker.
p3_fileFormat=
p3_flag=--group_plots
p3_name=group_plots
p3_numValues=0..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=Horizontally\=Horizontally;Vertically\=Vertically;No\=No
p4_MODE=
p4_TYPE=TEXT
p4_default_value=SeuratMarkers
p4_description=Basename of the file to be saved.
p4_fileFormat=
p4_flag=--output_file_name
p4_name=output_file_name
p4_numValues=0..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
privacy=public
publicationDate=07/15/2021 16\:03 
quality=production
src.repo=https\://github.com/genepattern/Seurat.VisualizeMarkerExpression/releases/tag/v2
taskDoc=documentation.md
taskType=single-cell
userid=edjuaro
version=Same as first version, oficial release.
