# Seurat.IntegrateData  urn:lsid:8080.gpserver.ip-172-31-26-71.ip-172-31-26-71.ec2.internal:genepatternmodules:941:1.3
#Tue Feb 10 19:12:02 UTC 2026
JVMLevel=
LSID=urn\:lsid\:8080.gpserver.ip-172-31-26-71.ip-172-31-26-71.ec2.internal\:genepatternmodules\:941\:1.3
author=Jonathan Zamora and Edwin Juarez;UCSD-MesirovLab
categories=dimension reduction;preprocess & utilities
commandLine=Rscript --no-save --quiet --slave --no-restore <libdir>integrate_data.R --input_files  <input_files>  --use_batch_names <use_batch_names> --ncomps <ncomps> --nCount_RNA <nCount_RNA> --nFeature_RNA <nFeature_RNA> --output_file_name <output_file_name>
cpuType=any
description=Batch Correction for Seurat Objects
documentationUrl=
fileFormat=pdf;rds;txt
job.docker.image=genepattern/seurat-suite\:4.0.3
language=any
name=Seurat.IntegrateData
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Gene expression matrices (columns are cell IDs and rows are genes) stored in a `.txt` or one Seurat Object (`.rds`) file per batch. \n<br><br>\nIf your files are in 10x Genomics (Cell Ranger) format or stored in a `.tar`, or `.gz` file, please use the <a href\="https\://cloud.genepattern.org/gp/pages/index.jsf?lsid\=urn\:lsid\:genepattern.org\:module.analysis\:00416\:2">Seurat.QC</a> module to pre-process your data and then use the `.txt` or `.rds` output from Seurat.QC in this module.\n<br><br>\nFor sample data see \n<a href\="https\://datasets.genepattern.org/data/module_support_files/Conos/small_500x500_HNSCC_noribo.txt">test data file 1</a> and <a href\="https\://datasets.genepattern.org/data/module_support_files/Conos/small_500x500_MEL_noribo.txt">test data file 2</a>.
p1_fileFormat=txt
p1_flag=--input_files
p1_name=input_files
p1_numValues=1+
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=TRUE
p2_description=(default \= TRUE) Map each input file to Batch Numbers beginning with Batch 1 and going up to Batch n where n represents the number of input files.\n<br><br>\nWhen set to FALSE, the batch names will be set to the file names.
p2_fileFormat=
p2_flag=--use_batch_names
p2_name=use_batch_names
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=TRUE\=TRUE;FALSE\=FALSE
p3_MODE=
p3_TYPE=Integer
p3_default_value=50
p3_description=(default \= 50) The number of principal components to be used in the Principal Component Analysis (PCA) for batch correction.
p3_fileFormat=
p3_flag=--ncomps
p3_name=ncomps
p3_numValues=1..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.Integer
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=TRUE
p4_description=(default \= TRUE) Whether or not the batch correction script will produce a violin plot of the number of molecules detected within a cell for our single-cell datasets.
p4_fileFormat=
p4_flag=--nCount_RNA
p4_name=nCount_RNA
p4_numValues=1..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=TRUE\=TRUE;FALSE\=FALSE
p5_MODE=
p5_TYPE=TEXT
p5_default_value=TRUE
p5_description=(default \= TRUE) Whether or not the batch correction script will produce a violin plot of the number of genes detected within each cell of our single-cell datasets.
p5_fileFormat=
p5_flag=--nFeature_RNA
p5_name=nFeature_RNA
p5_numValues=1..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=TRUE\=TRUE;FALSE\=FALSE
p6_MODE=
p6_TYPE=TEXT
p6_default_value=batch_correction_results
p6_description=(default \= 'batch_correction_results') Base name for the .pdf and .rds output files.
p6_fileFormat=
p6_flag=--output_file_name
p6_name=output_file_name
p6_numValues=1..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=
privacy=public
publicationDate=03/22/2021 18\:03 
quality=production
src.repo=https\://github.com/genepattern/Seurat.BatchCorrection/tree/v3
taskDoc=doc.html
taskType=dimension reduction
userid=edjuaro
version=Upgrading to Seurat V4 and fixing a bug in the command line and file name
