# Seurat.QC  urn:lsid:genepattern.org:module.analysis:00416:4.11
#Tue Feb 10 19:12:02 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00416\:4.11
author=Edwin F. Juarez & Jonathan Zamora;UCSD - Mesirov Lab
categories=preprocess & utilities;single-cell
commandLine=Rscript --no-save --quiet --no-restore <libdir>seurat_qc.R <input_file><hca_url> --column_name <column_name> --pattern <pattern> --first_feature <first_feature> --second_feature <second_feature> --third_feature <third_feature> --file_name <file_name> --export_txt <export_txt>
cpuType=any
description=Seurat quality control (First step in the Seurat Suite), using Seurat version 4.0.3.
documentationUrl=https\://github.com/genepattern/Seurat.QC/blob/v4.0/doc.md
fileFormat=rds
job.docker.image=genepattern/seurat-qc\:3.3
language=any
name=Seurat.QC
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=10x zip file to load or Loom file from HCA.
p1_fileFormat=.tar.gz;gz;loom;tar;tar.gz;zip
p1_flag=--input_file 
p1_name=input_file
p1_numValues=0..1
p1_optional=on
p1_prefix=--input_file 
p1_prefix_when_specified=--input_file 
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=
p2_description=URL to the Project Loom file from the Human Cell Atlas, obtained by the HCA api.
p2_fileFormat=
p2_flag=--hca_url 
p2_name=hca_url
p2_numValues=0..1
p2_optional=on
p2_prefix=--hca_url 
p2_prefix_when_specified=--hca_url 
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=percent.mt
p3_description=Column name of percent mitochondrial genes. \nNote\: not all datasets have this column, those who do often times name it percent.mt.
p3_fileFormat=
p3_flag=--column_name 
p3_name=column_name
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=MT-
p4_description=What pattern to use to label mitochondrial genes [often times this is annotated as MT-].
p4_fileFormat=
p4_flag=--pattern 
p4_name=pattern
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=seurat_qcd_dataset
p5_description=Basename of the file to be saved.
p5_fileFormat=
p5_flag=--file_name
p5_name=file_name
p5_numValues=0..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=nFeature_RNA
p6_description=First feature to plot as a violin plot [recommended to be the number of genes per cell, nFeature_RNA].
p6_fileFormat=
p6_flag=--first_feature
p6_name=first_feature
p6_numValues=0..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=
p7_MODE=
p7_TYPE=TEXT
p7_default_value=nCount_RNA
p7_description=Second feature to plot as a violin plot [recommended to be the number of reads per cell, nCount_RNA].
p7_fileFormat=
p7_flag=--second_feature
p7_name=second_feature
p7_numValues=1..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
p8_MODE=
p8_TYPE=TEXT
p8_default_value=percent.mt
p8_description=Third feature to plot as a violin plot [typically percent.mt]. Leave blank if you don't want this to be plotted.
p8_fileFormat=
p8_flag=--third_feature
p8_name=third_feature
p8_numValues=0..1
p8_optional=on
p8_prefix=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=
p9_MODE=
p9_TYPE=TEXT
p9_default_value=False
p9_description=Wether or not to create a TXT file compatible with some other modules (this requires a large amount of memory and for large datasets it causes unpredicted errors).
p9_fileFormat=
p9_flag=--export_txt
p9_name=export_txt
p9_numValues=0..1
p9_optional=
p9_prefix=
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=False\=False;True\=True
privacy=public
publicationDate=08/10/2021 18\:56 
quality=preproduction
src.repo=https\://github.com/genepattern/Seurat.QC/releases/tag/v4.0
taskDoc=doc.html
taskType=preprocess & utilities
userid=edjuaro
version=Reading new version of HCA (Loom), fixing the url reading bug (added a new parameter)
