# Seurat.Clustering  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00408:1.2
#Tue Feb 10 19:12:02 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00408\:1.2
author=Satija Lab New York Genome Canter, Wrapped as a module by Ted Liefeld & Edwin Juarez, UCSD School of Medicine.;UCSD - Mesirov Lab
categories=clustering;singlecell
commandLine=Rscript --no-save --quiet --slave --no-restore <libdir>run_seurat_clustering.R --input.file\=<input.seurat.rds.file> --output.file\=<output.filename> --max_dim\=<maximum_dimension> --resolution\=<resolution> --reduction\=<reduction> --nmarkers\=<nmarkers> --seed\=<seed>
cpuType=any
description=Companion module for the <a href\="https\://notebook.genepattern.org/services/sharing/notebooks/376/preview/">Seurat notebook</a>. Performs clustering and marker identification on single cell data.
documentationUrl=https\://genepattern.github.io/Seurat.Clustering/
fileFormat=pdf,rds
job.docker.image=genepattern/seurat-suite\:4.0.3
language=any
minGenePatternVersion=3.9.13
name=Seurat.Clustering
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=RDS file containing a preprocessed Seurat object
p1_fileFormat=rds
p1_flag=
p1_name=input.seurat.rds.file
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=<input.seurat.rds.file_basename>.clustered
p2_description=Name for output rds file
p2_fileFormat=
p2_flag=
p2_name=output.filename
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=10
p3_description=Max num dimensions to cluster
p3_fileFormat=
p3_flag=
p3_name=maximum_dimension
p3_numValues=1..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=0.05
p4_description=resolution
p4_fileFormat=
p4_flag=
p4_name=resolution
p4_numValues=1..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=umap
p5_description=The reduction to use (only umap is implemented in version 1.1 of this module, version 2 will include tsne)
p5_fileFormat=
p5_flag=
p5_name=reduction
p5_numValues=1..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=umap
p6_MODE=
p6_TYPE=Integer
p6_default_value=50
p6_description=How many cluster markers to output (a CSV file with this number of top markers per cluster will be created in addition to a CSV file with all of the cluster markers found)
p6_fileFormat=
p6_flag=--nmarkers
p6_name=nmarkers
p6_numValues=0..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.Integer
p6_value=
p7_MODE=
p7_TYPE=TEXT
p7_default_value=17
p7_description=Random number seed.
p7_fileFormat=
p7_flag=
p7_name=seed
p7_numValues=1..1
p7_optional=on
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
privacy=public
publicationDate=07/14/2021 02\:29 
quality=preproduction
requiredPatchLSIDs=
requiredPatchURLs=
src.repo=https\://github.com/genepattern/Seurat.Clustering
taskDoc=doc.html
taskType=clustering
userid=edjuaro
version=Updating to run Seurat 4.0.3
