# shRNAscores  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00217:0.4
#Tue Feb 10 19:12:02 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00217\:0.4
author=Barbara Weir, Broad Institute
commandLine=<R2.5> <libdir>HPscores.R HPscores -i<gct> -s<array.info> -r<reference> -a<annotation> -e<output.prefix> -l<libdir> 
cpuType=any
description=Outputs fold change, signal to noise and modified score (which deweights highly variable hps from reference control) for RNAI HP scoring
fileFormat=gct;txt
language=R
name=shRNAscores
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=
p1_fileFormat=gct
p1_name=gct
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Array annotation from 'makeArrayInfo' module
p2_fileFormat=txt
p2_name=array.info
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_default_value=DNA
p3_description=Reference to compare each cell line to - name can partially or totally match 'Array_timepoint' column of array.info file
p3_fileFormat=
p3_name=reference
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_MODE=IN
p4_TYPE=FILE
p4_default_value=
p4_description=TRChuV2.chip file (hp annotation)
p4_fileFormat=txt
p4_name=annotation
p4_optional=
p4_prefix_when_specified=
p4_type=java.io.File
p4_value=
p5_default_value=test
p5_description=prefix for output file name
p5_fileFormat=
p5_name=output.prefix
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
pipelineModel=
privacy=public
publicationDate=06/23/2011 14\:10 
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=RNAi
userid=
version=changed name of module
