# Single.Cell.ssGSEA  urn:lsid:genepattern.org:module.analysis:00437:8
#Tue Feb 10 19:12:03 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00437\:8
author=Alexander T. Wenzel & John Jun
categories=gsea;pathway analysis;projection;single-cell;singlecell
commandLine=bash <libdir>sc_ssGSEA_driver.sh <input_file> <gene_set_database_file> <output_file_name> <job.cpuCount> <cluster_data_label> <chip_file>
cpuType=any
description=Perform Single Cell ssGSEA. Can be used after Seurat.Clustering module.
documentationUrl=https\://genepattern.github.io/Single.Cell.ssGSEA/v1/
fileFormat=.tsv;.gct
job.cpuCount=3
job.docker.image=atwenzel/sc_ssgsea\:v1.3.0
job.memory=8Gb
job.walltime=
language=any
name=Single.Cell.ssGSEA
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Input Seurat RDS, h5seurat, or h5ad file.
p1_fileFormat=rds;h5ad;h5seurat
p1_flag=--input_file
p1_name=input_file
p1_numValues=0..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_choiceDir=https\://www.gsea-msigdb.org/gsea/msigdb/gp_modules_gmt.json
p2_default_value=
p2_description=Gene sets database from GSEA website. Upload a gene set if your gene set is not listed as a choice from MsigDB.
p2_fileFormat=gmt
p2_flag=--gene_set_data_base
p2_name=gene_set_database_file
p2_numValues=0+
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=scGSEA_scores
p3_description=Base name of the output files to be saved.
p3_fileFormat=
p3_flag=--output_file_name
p3_name=output_file_name
p3_numValues=0..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_MODE=IN
p4_TYPE=FILE
p4_choiceDir=https\://www.gsea-msigdb.org/gsea/msigdb/gp_modules_chip.json
p4_default_value=
p4_description=Chip file containing Gene ID to Gene Symbol mappings. Leave blank if the gene names are already in gene symbols.
p4_fileFormat=chip
p4_flag=--chip_file 
p4_name=chip_file
p4_numValues=0..1
p4_optional=on
p4_prefix=--chip_file 
p4_prefix_when_specified=
p4_type=java.io.File
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=seurat_clusters
p5_description=Name of the label for cluster metadata. The default label is <seurat_clusters> that is generated from the Seurat.Clustering module. 
p5_fileFormat=
p5_flag=--cluster_data_label
p5_name=cluster_data_label
p5_numValues=1..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
privacy=public
publicationDate=08/21/2025 13\:22 
quality=production
src.repo=https\://github.com/genepattern/scGSEA/tree/main/src
taskDoc=
taskType=gsea
version=Release after updates 0262025
