# SNPFileCreator_1chip  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00095:0.3
#Tue Feb 10 19:12:03 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00095\:0.3
author=David Twomey
commandLine=<java> <java_flags> -cp <libdir>snp.jar<path.separator><libdir>commons-math-1.1.jar<path.separator><libdir>Jama-1.0.1.jar<path.separator><libdir>log4j-1.2.13.jar<path.separator><libdir>gp-modules.jar edu.mit.broad.cg.modules.PreProcess.PreProcess -lib<libdir> -cdf<chip.type> -dir<network.directory.name> -zip<zip.file> -rmt<reference.method> -ref<reference.file> -out<output.file> -mmt<model.method> -oclno -olcyes -txtno -nmt<normalization.method> -gifgenome.info.6.0_build35 -srt<sort.snp.file> -als<allele.specific> -fmt<output.file.format> -log<libdir>log4j.properties
cpuType=any
description=Processes Affymetrix SNP probe-level data into expression values
fileFormat=snp
language=Java
name=SNPFileCreator_1chip
os=any
p10_default_value=
p10_description=The name of the output file.
p10_fileFormat=
p10_name=output.file
p10_optional=
p10_prefix_when_specified=
p10_type=java.lang.String
p10_value=
p11_default_value=mpg
p11_description=Output file format
p11_fileFormat=
p11_name=output.file.format
p11_optional=
p11_prefix_when_specified=
p11_type=java.lang.String
p11_value=cg\=Cancer Genome Format;mpg\=Med Pop Format
p1_default_value=
p1_description=Networked directory name where the CEL (and optionally TXT) files reside.
p1_fileFormat=
p1_name=network.directory.name
p1_optional=on
p1_prefix_when_specified=
p1_type=java.lang.String
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=A zip file containing CEL (and optionally TXT) files.
p2_fileFormat=zip
p2_name=zip.file
p2_optional=on
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_default_value=GenomeWideSNP_6.cdf
p3_description=Specify the chip type.
p3_fileFormat=
p3_name=chip.type
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=GenomeWideSNP_5.cdf;GenomeWideSNP_6.cdf
p4_default_value=2
p4_description=The normalization method to apply.
p4_name=normalization.method
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=0\=None;1\=Quantile Normalization(dChip);2\=Invariant Set Normalization(dChip);3\=Divide by median, multiply by 1000
p5_default_value=median
p5_description=Reference method to use in normalization
p5_fileFormat=
p5_name=reference.method
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=median\=Median;reference\=Reference Supplied
p6_MODE=IN
p6_TYPE=FILE
p6_default_value=
p6_description=Reference file to use. Leave blank if reference method is median.
p6_fileFormat=
p6_name=reference.file
p6_optional=on
p6_prefix_when_specified=
p6_type=java.io.File
p6_value=
p7_default_value=5
p7_description=The summarization method to apply.
p7_name=model.method
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=1\=Average Difference;3\=Median Probe;4\=Trimmed Mean;5\=Median Polish
p8_default_value=yes
p8_description=Create Allele Specific probe intensities
p8_fileFormat=
p8_name=allele.specific
p8_optional=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=yes\=Allele-Specific;no\=Non Allele-Specific
p9_default_value=yes
p9_description=Sorts output file by chromosome and location. Filters out probesets without location information
p9_fileFormat=
p9_name=sort.snp.file
p9_optional=
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=yes\=Sort;no\=Do no sort
privacy=public
publicationDate=11/20/2007 14\:50 
quality=production
taskType=SNP Analysis
userid=GenePattern
version=
