# SNPFileSorter  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00096:1
#Tue Feb 10 19:12:03 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00096\:1
author=Jim Robinson, David Twomey
commandLine=<java> <java_flags>  -cp <libdir>snp.jar<path.separator><libdir>commons-math-1.1.jar<path.separator><libdir>Jama-1.0.1.jar<path.separator><libdir>log4j-1.2.13.jar  edu.mit.broad.cg.util.SnpDataSorter <snp.filename> <output.file>
cpuType=any
description=Sorts a .snp file by Chromosome and location
fileFormat=snp
language=Java
name=SNPFileSorter
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=snp file to sort
p1_fileFormat=snp
p1_name=snp.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<snp.filename_basename>.sorted.snp
p2_description=output file name
p2_fileFormat=snp
p2_name=output.file
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
privacy=public
publicationDate=04/30/2007 08\:59 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=SNP Analysis
userid=GenePattern
