# SNPMultipleSampleAnalysis  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00106:1.3
#Tue Feb 10 19:12:03 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00106\:1.3
author=Mitchell Guttman and Gregory R. Grant, University of Pennsylvania Center for Bioinformatics
commandLine=<java> <java_flags> -Djava.awt.headless\=true -cp <libdir>MSACommandLine041007.jar<path.separator><libdir>gp_wrapper.jar org.genepattern.SNP_MSA_Wrapper -libdir <libdir> -file <input.filename> -cytoband <cytoband.filename> -saveDir ./ -chromosomes <chromosomes> -permutations <permutations> -useArms <analyze.by> -numberTests <num.tests> -binParam <num.positions.bin> -resolution <resolution> -significanceLevel <significance.level> -saveImages ./ -runName <output.prefix>
cpuType=any
description=Determine Regions of Concordant Copy Number Aberrations
fileFormat=
language=any
name=SNPMultipleSampleAnalysis
os=any
p10_default_value=<input.filename_basename>_
p10_description=The prefix for output files
p10_fileFormat=
p10_name=output.prefix
p10_optional=
p10_prefix_when_specified=
p10_type=java.lang.String
p10_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The input file to analyze - .cn, .xcn, .snp, .txt
p1_fileFormat=txt
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=<libdir>CytoBands.txt
p2_description=Cytoband file to use
p2_fileFormat=txt
p2_name=cytoband.filename
p2_optional=on
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_default_value=500
p3_description=Number of permutations to use
p3_fileFormat=
p3_name=permutations
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_default_value=9
p4_description=Number of MSA tests to use
p4_fileFormat=
p4_name=num.tests
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_default_value=6
p5_description=Number of positions per bin
p5_fileFormat=
p5_name=num.positions.bin
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
p6_default_value=250000
p6_description=The size of the plotted chromosome diagram
p6_fileFormat=
p6_name=resolution
p6_optional=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=
p7_default_value=chr22
p7_description=Comma delimited list of chromosomes to analyze
p7_fileFormat=
p7_name=chromosomes
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
p8_default_value=false
p8_description=
p8_fileFormat=
p8_name=analyze.by
p8_optional=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=true\=arms;false\=chromosomes
p9_default_value=.05
p9_description=The value at which a region is called significant
p9_fileFormat=
p9_name=significance.level
p9_optional=
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=
pipelineModel=
privacy=public
publicationDate=03/08/2012 10\:20 
quality=production
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=SNP Analysis
userid=nazaire@broad.mit.edu
version=changed cytoband to <libdir>CytoBands.txt - per Josh's suggestion in gpat-189
