# SOMClusterViewer  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.visualizer:00023:5.1
#Tue Feb 10 19:12:04 UTC 2026
JVMLevel=1.7
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.visualizer\:00023\:5.1
author=Ken Ross, Joshua Gould, Broad Institute
commandLine=<java> <java_flags> -cp <libdir>somviewer.jar<path.separator><libdir>gp-modules.jar org.genepattern.modules.som.SOM <som.cluster.filename>
cpuType=any
description=Visualize clusters created with the SOM algorithm
language=Java
name=SOMClusterViewer
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=SOM Properties ODF file
p1_fileFormat=SOM Cluster
p1_name=som.cluster.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
pipelineModel=
privacy=public
publicationDate=10/16/2015 17\:09 
quality=preproduction
taskType=Visualizer
userid=pcarr@broadinstitute.org
version=Added ability to scroll the left panel
