# SOMClustering  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00029:2
#Tue Feb 10 19:12:04 UTC 2026
JVMLevel=1.3
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00029\:2
author=GenePattern
className=edu.mit.wi.omnigene.service.analysis.genepattern.GenePatternAnalysisTask
commandLine=<java> <java_flags> -Domnigene.conf\=<java.io.tmpdir><file.separator>gp<file.separator>resources -cp <libdir>trove.jar<path.separator><libdir>jaxb-rt-1.0-ea.jar<path.separator><libdir>gp-common.jar<path.separator><libdir>common_cmdline.jar<path.separator><libdir>RunSomAlg.jar<path.separator><libdir>file_support.jar<path.separator><libdir>archiver.jar<path.separator><libdir>broad-cg.jar<path.separator><libdir>jakarta-oro-2.0.8.jar<path.separator><libdir>gp-modules.jar edu.mit.genome.gp.executers.RunSomAlg <dataset.filename> <cluster.range> <iterations> <seed.range> <som.rows> <som.cols> <initialization> <neighborhood> <alpha.initial> <alpha.final> <sigma.initial> <sigma.final> <output.stub> <cluster.by>
cpuType=any
description=Self-Organizing Maps algorithm
fileFormat=SOM Cluster
language=Java
name=SOMClustering
os=any
p10_default_value=Bubble
p10_description=Neighborhood function determining how centroids near the target centroid are updated
p10_name=neighborhood
p10_optional=
p10_prefix_when_specified=
p10_type=java.lang.String
p10_value=Bubble;Gaussian
p11_default_value=0.1
p11_description=Initial learning weight for centroid updates
p11_name=alpha.initial
p11_optional=
p11_prefix_when_specified=
p11_type=java.lang.Float
p11_value=
p12_default_value=0.005
p12_description=Final learning weight for centroid updates
p12_name=alpha.final
p12_optional=
p12_prefix_when_specified=
p12_type=java.lang.Float
p12_value=
p13_default_value=5.0
p13_description=Initial sigma to determine update neighborhood size around the target centroid
p13_name=sigma.initial
p13_optional=
p13_prefix_when_specified=
p13_type=java.lang.Float
p13_value=
p14_default_value=0.5
p14_description=Final sigma to determine update neighborhood size around the target centroid
p14_name=sigma.final
p14_optional=
p14_prefix_when_specified=
p14_type=java.lang.Float
p14_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Dataset (res, gct, or odf dataset)
p1_fileFormat=res;gct;Dataset
p1_name=dataset.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<dataset.filename_basename>
p2_description=The base output file name - .odf
p2_name=output.stub
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_default_value=2-3
p3_description=Range of values can be entered and the program will automatically run the algorithm for each number of clusters in the range.
p3_name=cluster.range
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_default_value=42
p4_description=The seed for the random number generator, is exposed to allow the user to recreate a given session at a later time, (as opposed to allowing the program to generate a random initial seed which could result in different outcomes even if all the other parameters are identical).
p4_name=seed.range
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_default_value=50000
p5_description=How many times the algorithm should try to refine the clusters. Initially, this value can be set low for faster exploration, but should be set high (e.g., 50,000) for good convergence.
p5_name=iterations
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.Integer
p5_value=
p6_default_value=rows
p6_description=Whether to cluster by rows or columns
p6_name=cluster.by
p6_optional=on
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=rows;columns
p7_default_value=0
p7_description=Setting this and som.cols to a non zero value will override cluster.range and the computation will be for the specified geometry
p7_name=som.rows
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
p8_default_value=0
p8_description=Setting this and som.rows to a non zero value will override cluster.range and the computation will be for the specified geometry
p8_name=som.cols
p8_optional=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=
p9_default_value=Random_Vectors
p9_description=How to select inital random centroids
p9_name=initialization
p9_optional=
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=Random_Vectors;Random_Datapoints
pipelineModel=
privacy=public
quality=production
serializedModel=
taskType=Clustering
userid=GenePattern (gp-help@broad.mit.edu)
version=Updated to latest file parsers and annotated for GP 1.4
