# SparseHierarchicalClustering  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00227:1.1
#Tue Feb 10 19:12:04 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00227\:1.1
author=Daniela Witten, Stanford University
commandLine=<R2.5> <libdir>HSC2.R sparsecluster <libdir> <input.filename> <method> <wbound>  <cluster.features> <method.features> <maxnumgenes> <standardize.arrays>
cpuType=any
description=Cluster the samples in a data matrix using an adaptively-chosen subset of the features.
fileFormat=atr;gtr
language=R
name=SparseHierarchicalClustering
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A GCT file containing data to cluster
p1_fileFormat=gct
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=average
p2_description=The type of linkage to use in the hierarchical clustering - "single", "complete", "centroid", or "average."
p2_fileFormat=
p2_name=method
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=average;complete;single;centroid
p3_default_value=-1
p3_description=The sum of gene weights; this is the tuning parameter for sparse hierarchical clustering. If a non-negative number is given, then this tuning parameter is used. Otherwise, a tuning parameter is selected via a permutation approach. Note\: The program runs much more quickly if wbound is specified rather than left at -1.
p3_fileFormat=
p3_name=wbound
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.Integer
p3_value=
p4_default_value=5000
p4_description=By default, only the 5000 genes with highest variance will be used (for computational reasons). To use all the genes, set to -1. Warning\: using all genes will be slow if there are many genes in the data set.
p4_fileFormat=
p4_name=maxnumgenes
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.Integer
p4_value=
p5_default_value=false
p5_description=If a clustering of the genes with non-zero weights is desired, set to TRUE.
p5_fileFormat=
p5_name=cluster.features
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=true;false
p6_default_value=average
p6_description=The type of linkage used to cluster the features (if desired) - "single", "complete", "centroid", or "average". Used only if cluster features is set to "TRUE"
p6_fileFormat=
p6_name=method.features
p6_optional=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=average;complete;single;centroid
p7_default_value=true
p7_description=Whether or not the arrays should be standardized to have mean zero and standard deviation one before clustering is performed.
p7_fileFormat=
p7_name=standardize.arrays
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=true;false
pipelineModel=
privacy=public
publicationDate=11/29/2010 17\:35 
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Clustering
userid=
version=Public Release
