# spatialGE.STenrich  urn:lsid:genepattern.org:module.analysis:00461:3
#Tue Feb 10 19:12:05 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00461\:3
author=Thorin Tabor;UCSD - Mesirov Lab
categories=spatial transcriptomics
commandLine=Rscript /spatialGE/wrapper.R -f <input.file> -g <gene.sets.database> -p <permutations> -r <random.seed> -s <minimum.spots> -m <minimum.genes> -d <standard.deviations> -w <filter.p.values> -i <filter.gene.proportion>
cpuType=any
description=Detect genes showing spatial expression patterns (e.g., hotspots). Tests if spots/cells with high average expression of a gene set shows evidence of spatial aggregation.
documentationUrl=https\://genepattern.github.io/spatialGE.STenrich/v1/
fileFormat=
job.cpuCount=7
job.docker.image=genepattern/spatialge-stenrich\:0.5
job.memory=4Gb
language=R
name=spatialGE.STenrich
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Normalized spatial transcriptomics data coming from the spatialGE.Preprocessing module.
p1_fileFormat=rds
p1_flag=-f
p1_name=input.file
p1_numValues=0..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_choiceDir=https\://www.gsea-msigdb.org/gsea/msigdb/gp_modules_gmt.json
p2_default_value=
p2_description=Select a gene set database to test for spatial enrichment. Upload a gene set if your gene set is not listed as a choice from MSigDB.
p2_fileFormat=gmt;gmx;grp
p2_flag=
p2_name=gene.sets.database
p2_numValues=0..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=
p3_TYPE=Integer
p3_default_value=100
p3_description=The number of permutations to estimate the null distribution (no-spatial pattern). The more permutations, the longer STenrich takes to complete, but p-values may be more accurate.
p3_fileFormat=
p3_flag=-p
p3_name=permutations
p3_numValues=0..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.Integer
p3_value=
p4_MODE=
p4_TYPE=Integer
p4_default_value=12345
p4_description=A seed number to replicate results. It is advisable to run STenrich with different seed values to check for consistency. Different seed values could yield slightly different p-values.
p4_fileFormat=
p4_flag=-r
p4_name=random.seed
p4_numValues=0..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.Integer
p4_value=
p5_MODE=
p5_TYPE=Integer
p5_default_value=5
p5_description=The minimum number of high expression ROIs/spots/cells required for a gene set to be tested. If a sample has less than this number of high expression ROIs/spots/cells, the gene set is not tested in that sample.
p5_fileFormat=
p5_flag=-s
p5_name=minimum.spots
p5_numValues=0..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.Integer
p5_value=
p6_MODE=
p6_TYPE=Integer
p6_default_value=5
p6_description=The minimum number of genes of a set required to be present in a sample, for that gene set to be tested in that sample. If a sample has less genes of a set than this number, the gene set is ignored in that sample.
p6_fileFormat=
p6_flag=-m
p6_name=minimum.genes
p6_numValues=0..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.Integer
p6_value=
p7_MODE=
p7_TYPE=Float
p7_default_value=1.0
p7_description=The number of standard deviations to define the high expression threshold. If an ROI/spot/cell has average gene set expression larger than the entire sample average plus this many standard deviations, it will be considered a high-expression ROI/spot/cell.
p7_fileFormat=
p7_flag=-d
p7_name=standard.deviations
p7_numValues=0..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.Float
p7_value=
p8_MODE=
p8_TYPE=Float
p8_default_value=0.05
p8_description=Plot only gene sets whose multiple test adjusted p-value is less than this threshold.
p8_fileFormat=
p8_flag=-d
p8_name=filter.p.values
p8_numValues=0..1
p8_optional=
p8_prefix=
p8_prefix_when_specified=
p8_type=java.lang.Float
p8_value=
p9_MODE=
p9_TYPE=Float
p9_default_value=0.3
p9_description=Plot only gene sets where the proportional number genes in the set present in the field of view equals or exceeds this threshold.
p9_fileFormat=
p9_flag=-d
p9_name=filter.gene.proportion
p9_numValues=0..1
p9_optional=
p9_prefix=
p9_prefix_when_specified=
p9_type=java.lang.Float
p9_value=
privacy=public
publicationDate=02/20/2025 13\:16 
quality=production
src.repo=https\://github.com/genepattern/spatialGE.STenrich
taskDoc=
taskType=spatial transcriptomics
userid=tabor
version=Write stlist rds to disk
