# spatialGE.STplot  urn:lsid:genepattern.org:module.analysis:00469:2
#Tue Feb 10 19:12:05 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00469\:2
author=Thorin Tabor;UCSD - Mesirov Lab
categories=spatial transcriptomics
commandLine=Rscript /spatialGE/wrapper.R -f <input.file> <genes> <samples> <color.palette> <colors> <point.size> <spatial.weights> <dynamic.tree.cut> <minimum.clusters> <maximum.clusters> <deep.split> -j <display.in.grid> <grid.rows> <grid.columns> -m <common.legend> -n <legend.location>
cpuType=any
description=Plots of gene expression, cluster memberships, and metadata in spatial context
documentationUrl=https\://genepattern.github.io/spatialGE.STplot/v1/
fileFormat=
job.docker.image=genepattern/spatialge-stplot\:0.1
language=R
name=spatialGE.STplot
os=any
p10_MODE=
p10_TYPE=String
p10_default_value=
p10_description=The maximum number of clusters (tissue domains) to plot. Must match one of of the clusterings previously run in spatialGE.STclust. Only used if Dynamic Tree Cut is false.
p10_fileFormat=
p10_flag=
p10_name=maximum.clusters
p10_numValues=0..1
p10_optional=on
p10_prefix=
p10_prefix_when_specified=-i 
p10_type=java.lang.String
p10_value=
p11_MODE=
p11_TYPE=TEXT
p11_default_value=
p11_description=Whether deepSplit was used in the earlier spatialGE.STclust step. If you have not previously run spatialGE.STclust with this data, leave the value blank.
p11_fileFormat=
p11_flag=
p11_name=deep.split
p11_numValues=0..1
p11_optional=on
p11_prefix=
p11_prefix_when_specified=-e 
p11_type=java.lang.String
p11_value=FALSE\=FALSE;TRUE\=TRUE
p12_MODE=
p12_TYPE=String
p12_default_value=FALSE
p12_description=Whether to display the results in a singular grid containing all plots. If set to false, each plot will be saved as its own image file.
p12_fileFormat=
p12_flag=-j
p12_name=display.in.grid
p12_numValues=1
p12_optional=
p12_prefix=
p12_prefix_when_specified=
p12_type=java.lang.String
p12_value=FALSE\=FALSE;TRUE\=TRUE
p13_MODE=
p13_TYPE=Integer
p13_default_value=
p13_description=The number of rows in the grid containing all plots. Ignored unless <em>display in grid</em> is set to true.
p13_fileFormat=
p13_flag=
p13_name=grid.rows
p13_numValues=0..1
p13_optional=
p13_prefix=
p13_prefix_when_specified=-r 
p13_type=java.lang.Integer
p13_value=
p14_MODE=
p14_TYPE=Integer
p14_default_value=
p14_description=The number of columns in the grid containing all plots. Ignored unless <em>display in grid</em> is set to true.
p14_fileFormat=
p14_flag=
p14_name=grid.columns
p14_numValues=0..1
p14_optional=
p14_prefix=
p14_prefix_when_specified=-k 
p14_type=java.lang.Integer
p14_value=
p15_MODE=
p15_TYPE=String
p15_default_value=TRUE
p15_description=Whether the grid of plots should share a common legend. If set to false, each grid will have its own accompanying legend. Ignored unless <em>display in grid</em> is set to true.
p15_fileFormat=
p15_flag=-m
p15_name=common.legend
p15_numValues=1
p15_optional=
p15_prefix=
p15_prefix_when_specified=
p15_type=java.lang.String
p15_value=TRUE\=TRUE;FALSE\=FALSE
p16_MODE=
p16_TYPE=String
p16_default_value=bottom
p16_description=The location of the legend accompanying the plots.
p16_fileFormat=
p16_flag=-n
p16_name=legend.location
p16_numValues=1
p16_optional=
p16_prefix=
p16_prefix_when_specified=
p16_type=java.lang.String
p16_value=bottom\=bottom;top\=top;right\=right;left\=left
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Spatial transcriptomics data coming from spatialGE.Preprocessing or another spatialGE module.
p1_fileFormat=rds
p1_flag=-f
p1_name=input.file
p1_numValues=0..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=String
p2_default_value=
p2_description=Comma-separated list of gene names to plot. If left blank, all genes will be used.
p2_fileFormat=
p2_flag=
p2_name=genes
p2_numValues=0..1
p2_optional=on
p2_prefix=
p2_prefix_when_specified=-g 
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=String
p3_default_value=
p3_description=Comma-separated list of sample names to include. If left blank, all samples will be used.
p3_fileFormat=
p3_flag=
p3_name=samples
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=-s 
p3_type=java.lang.String
p3_value=
p4_MODE=
p4_TYPE=String
p4_default_value=
p4_description=Alternative color palette to use when generating the plot.
p4_fileFormat=
p4_flag=
p4_name=color.palette
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=-p 
p4_type=java.lang.String
p4_value=BuRd\=BuRd;highcontrast\=highcontrast;YlOrBr\=YlOrBr;discreterainbow\=discreterainbow
p5_MODE=
p5_TYPE=String
p5_default_value=
p5_description=A comma separated list of specific colors to use when generating the plot.
p5_fileFormat=
p5_flag=
p5_name=colors
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=-c 
p5_type=java.lang.String
p5_value=
p6_MODE=
p6_TYPE=Float
p6_default_value=
p6_description=Alternative size of points marked by the plot, provided as a floating point number.
p6_fileFormat=
p6_flag=
p6_name=point.size
p6_numValues=0..1
p6_optional=on
p6_prefix=
p6_prefix_when_specified=-q 
p6_type=java.lang.Float
p6_value=
p7_MODE=
p7_TYPE=String
p7_default_value=
p7_description=Plot tissue domains for clusters created using the following spatial weights. Provide as a comma separated list. Must match spatial weights previously used in spatialGE.STclust.
p7_fileFormat=
p7_flag=
p7_name=spatial.weights
p7_numValues=0..1
p7_optional=on
p7_prefix=
p7_prefix_when_specified=-w 
p7_type=java.lang.String
p7_value=
p8_MODE=
p8_TYPE=String
p8_default_value=
p8_description=Whether the number of clusters was determined using Dynamic Tree Cut in the earlier spatialGE.STclust step. If you have not previously run spatialGE.STclust with this data, leave the value blank.
p8_fileFormat=
p8_flag=
p8_name=dynamic.tree.cut
p8_numValues=0..1
p8_optional=on
p8_prefix=
p8_prefix_when_specified=-d 
p8_type=java.lang.String
p8_value=\=;FALSE\=FALSE;TRUE\=TRUE
p9_MODE=
p9_TYPE=Integer
p9_default_value=
p9_description=The minimum number of clusters (tissue domains) to plot. Must match one of of the clusterings previously run in spatialGE.STclust. Only used if Dynamic Tree Cut is false.
p9_fileFormat=
p9_flag=
p9_name=minimum.clusters
p9_numValues=0..1
p9_optional=on
p9_prefix=
p9_prefix_when_specified=-l 
p9_type=java.lang.Integer
p9_value=
privacy=public
publicationDate=06/24/2025 17\:59 
quality=production
src.repo=https\://github.com/genepattern/spatialGE.STplot
taskDoc=
taskType=spatial transcriptomics
userid=tabor
version=Fixing prerelease
