# spatialGE.STgradient  urn:lsid:genepattern.org:module.analysis:00465:2
#Tue Feb 10 19:12:05 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00465\:2
author=Thorin Tabor;UCSD - Mesirov Lab
categories=spatial transcriptomics
commandLine=Rscript /spatialGE/wrapper.R -f <input.file> <samples> -v <num.variable.genes> <annotation.to.test> <reference.cluster> <exclude.clusters> -r <robust.regression> -i <ignore.outliers> <correlation.limit> -n <min.neighbors> -d <distance.summary>
cpuType=any
description=Tests for genes for which there is evidence of expression spatial gradients with respect to a "reference" tissue niche/domain (e.g., higher expression closer to reference tissue niche, lower expression as farther from reference tissue niche).<br/><br/>If you just ran <strong>spatialGE.STclust</strong>, you probably want the <strong>spatialGE.STgradient.Launcher</strong> module instead.
documentationUrl=https\://genepattern.github.io/spatialGE.STgradient/v1/
fileFormat=
job.cpuCount=7
job.docker.image=genepattern/spatialge-stgradient\:0.2
job.walltime=4\:00\:00
language=R
name=spatialGE.STgradient
os=any
p10_MODE=
p10_TYPE=Integer
p10_default_value=3
p10_description=The minimum number of immediate neighbors a reference spot/cell must have to be included in the analysis. This parameter intends to reduce the effect of isolated spots/cells in the calculation of the correlation coefficients. Unsupervised clustering algorithms (such as STclust) can assign niches to isolated spots. Reference spots with less neighbors than specified, will be omitted from the analysis, and hence distances from that spot will not be calculated.
p10_fileFormat=
p10_flag=-n
p10_name=min.neighbors
p10_numValues=1
p10_optional=
p10_prefix=
p10_prefix_when_specified=
p10_type=java.lang.Integer
p10_value=
p11_MODE=
p11_TYPE=String
p11_default_value=min
p11_description=Distance summary metric\: 'average' or 'minimum'
p11_fileFormat=
p11_flag=-d
p11_name=distance.summary
p11_numValues=1
p11_optional=
p11_prefix=
p11_prefix_when_specified=
p11_type=java.lang.String
p11_value=min\=Minimum;avg\=Average
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Normalized spatial transcriptomics data with clusters, coming from the spatialGE.STclust module.
p1_fileFormat=rds
p1_flag=-f
p1_name=input.file
p1_numValues=0..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=String
p2_default_value=
p2_description=Comma-separated list of sample names to include. If left blank, all samples will be used.
p2_fileFormat=
p2_flag=
p2_name=samples
p2_numValues=0..1
p2_optional=on
p2_prefix=
p2_prefix_when_specified=-s 
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=Integer
p3_default_value=3000
p3_description=Maximum number of genes per sample to test for spatial gradients. The genes to be tested are selected based on standard deviation.
p3_fileFormat=
p3_flag=-v
p3_name=num.variable.genes
p3_numValues=1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.Integer
p3_value=
p4_MODE=IN
p4_TYPE=String
p4_default_value=
p4_description=The tissue niches on which to run STgradient. This parameter should be set to the name of a column in @spatial_meta containing the tissue domain assignments for each spot or cell. These are generated by STclust. If left blank, STgradient will be run for all tissue niches.
p4_fileFormat=
p4_flag=
p4_name=annotation.to.test
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=-a 
p4_type=java.lang.String
p4_value=
p5_MODE=
p5_TYPE=String
p5_default_value=
p5_description=Reference cluster from which spatial gradients are to be tested. The reference cluster could be, for example, a tumor region detected by STclust. One of the tissue domains in the niche specified in annotation to test. Corresponds to the "reference" cluster or domain. Spearman's correlations will be calculated using spots assigned to domains other than this reference domain (or domains specified in exclude clusters). If left blank, values will be individually calculated for all possible tissue domains.
p5_fileFormat=
p5_flag=
p5_name=reference.cluster
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=-c 
p5_type=java.lang.String
p5_value=
p6_MODE=
p6_TYPE=String
p6_default_value=
p6_description=Comma-separated list of clusters to exclude. Exclude regions/niches from the analysis. By specifying one or more niches, the distances of those spots/cells will not be calculated and will be excluded from the analyses. This option could be useful when removing tissue niches that show necrosis and could add noise to the Spearman's coefficients.
p6_fileFormat=
p6_flag=
p6_name=exclude.clusters
p6_numValues=0..1
p6_optional=on
p6_prefix=
p6_prefix_when_specified=-e 
p6_type=java.lang.String
p6_value=
p7_MODE=
p7_TYPE=String
p7_default_value=True
p7_description=In robust regression, outliers are given less weight towards the calculation of the regression coefficient.
p7_fileFormat=
p7_flag=-r
p7_name=robust.regression
p7_numValues=1
p7_optional=
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=False\=False;True\=True
p8_MODE=
p8_TYPE=String
p8_default_value=False
p8_description=Whether to ignore outliers. This option is ignored if robust regression is selected. If outliers are ignored, traditional linear regression is carried out after removing spots/cells defined as outliers by the interquartile range method. If set to false, all spots are considered in the analysis.
p8_fileFormat=
p8_flag=-i
p8_name=ignore.outliers
p8_numValues=1
p8_optional=
p8_prefix=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=False\=False;True\=True
p9_MODE=
p9_TYPE=Float
p9_default_value=
p9_description=A distance value to restrict the correlation analysis. Some tissues can be very heterogeneous in composition. As a result it could be reasonable to test for spatial gradients within a restricted area of the tissue.
p9_fileFormat=
p9_flag=
p9_name=correlation.limit
p9_numValues=0..1
p9_optional=on
p9_prefix=
p9_prefix_when_specified=-l 
p9_type=java.lang.Float
p9_value=
privacy=public
publicationDate=02/20/2025 13\:17 
quality=production
src.repo=https\://github.com/genepattern/spatialGE.STgradient
taskDoc=
taskType=spatial transcriptomics
userid=tabor
version=Fixing prerelease
