# spatialGE.STclust  urn:lsid:genepattern.org:module.analysis:00462:5
#Tue Feb 10 19:12:05 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00462\:5
author=GenePattern Team
categories=clustering;spatial transcriptomics
commandLine=Rscript <libdir>stclust_wrapper_ai.R -j <job_id> -e <input.file> --ws <spatial.weight> --dist_metric <distance.metric> --linkage <linkage.method> --ks <dynamic.tree.cut> --mink <minimum.clusters> --maxk <maximum.clusters> --topgenes <number.of.genes> --deepSplit <deep.split> --output <output.file>    <tissue.images>
cpuType=any
description=This function performs spatial clustering on gene expression data using the STclust method.
documentationUrl=https\://github.com/genepattern/spatialGE.STclust/blob/develop/docs/v1/index.md
fileFormat=RData
job.cpuCount=
job.docker.image=genepattern/spatialgp.preprocessing\:0.4
job.memory=
job.walltime=
language=any
name=spatialGE.STclust
os=any
p10_MODE=
p10_TYPE=TEXT
p10_default_value=2
p10_description=Minimum number of clusters (tissue domains). Must be >\= 2. Only used if Dynamic Tree Cut is false.
p10_fileFormat=
p10_flag=--mink
p10_name=minimum.clusters
p10_numValues=0..1
p10_optional=on
p10_prefix=
p10_prefix_when_specified=
p10_type=java.lang.String
p10_userSuppliedValuesOK=False
p10_value=
p11_MODE=
p11_TYPE=TEXT
p11_default_value=5
p11_description=Maximum number of clusters (tissue domains). Only used if Dynamic Tree Cut is false.
p11_fileFormat=
p11_flag=--maxk
p11_name=maximum.clusters
p11_numValues=0..1
p11_optional=on
p11_prefix=
p11_prefix_when_specified=
p11_type=java.lang.String
p11_userSuppliedValuesOK=False
p11_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=STList object in .RDS file format to cluster on.
p1_fileFormat=
p1_flag=-e
p1_name=input.file
p1_numValues=0..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_userSuppliedValuesOK=False
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=spatialGE_STclustered.rds
p2_description=Path to save the output STlist object. Default is 'output.RData'.
p2_fileFormat=
p2_flag=--output
p2_name=output.file
p2_numValues=0..1
p2_optional=on
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_userSuppliedValuesOK=False
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=Tar gz compressed file of the images of the samples in the STList object.
p3_fileFormat=
p3_flag=--images
p3_name=tissue.images
p3_numValues=0..1
p3_optional=on
p3_prefix=--images
p3_prefix_when_specified=--images
p3_type=java.io.File
p3_userSuppliedValuesOK=False
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=0.025
p4_description=Weight to be applied to spatial distances (0-1). Default is 0.025.
p4_fileFormat=
p4_flag=--ws
p4_name=spatial.weight
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_userSuppliedValuesOK=False
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=euclidean
p5_description=Distance metric to be used. Default is 'euclidean'.
p5_fileFormat=
p5_flag=--dist_metric
p5_name=distance.metric
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_userSuppliedValuesOK=False
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=ward.D2
p6_description=Linkage method applied to hierarchical clustering. Default is 'ward.D2'
p6_fileFormat=
p6_flag=--linkage
p6_name=linkage.method
p6_numValues=0..1
p6_optional=on
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_userSuppliedValuesOK=False
p6_value=
p7_MODE=
p7_TYPE=TEXT
p7_default_value=TRUE
p7_description=Whether to automatically determine the number of clusters using Dynamic Tree Cut.
p7_fileFormat=
p7_flag=--ks
p7_name=dynamic.tree.cut
p7_numValues=1
p7_optional=
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_userSuppliedValuesOK=False
p7_value=FALSE\=FALSE;TRUE\=TRUE
p8_MODE=
p8_TYPE=TEXT
p8_default_value=2000
p8_description=Number of genes with highest spot-to-spot expression variation. Default is 2000
p8_fileFormat=
p8_flag=--topgenes
p8_name=number.of.genes
p8_numValues=0..1
p8_optional=on
p8_prefix=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_userSuppliedValuesOK=False
p8_value=
p9_MODE=
p9_TYPE=TEXT
p9_default_value=FALSE
p9_description=Logical or integer (1-4) to control cluster resolution. Default is FALSE
p9_fileFormat=
p9_flag=--deepSplit
p9_name=deep.split
p9_numValues=0..1
p9_optional=on
p9_prefix=
p9_prefix_when_specified=
p9_type=java.lang.String
p9_userSuppliedValuesOK=True
p9_value=FALSE\=FALSE;TRUE\=TRUE
privacy=public
publicationDate=06/24/2025 18\:00 
quality=production
src.repo=
taskDoc=
taskType=spatial transcriptomics
userid=edwin5588
version=
