# spatialGE.STgradient.Launcher  urn:lsid:genepattern.org:module.analysis:00468:4
#Tue Feb 10 19:12:05 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00468\:4
author=Thorin Tabor;UCSD - Mesirov Lab
categories=spatial transcriptomics, javascript
commandLine=app.html ? <dataset> <sample.info> <domain.info>
cpuType=any
description=Reads the output of spatialGE.STclust and then launches an analysis to test for genes for which there is evidence of expression spatial gradients with respect to a "reference" tissue niche/domain (e.g., higher expression closer to reference tissue niche, lower expression as farther from reference tissue niche).
language=Javascript
name=spatialGE.STgradient.Launcher
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Normalized spatial transcriptomics data with clusters, coming from the spatialGE.STclust module.
p1_fileFormat=rds
p1_name=dataset
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=JSON file containing spot/cell and gene statistics for each sample, coming from the spatialGE.Preprocessing module.
p2_fileFormat=json
p2_name=sample.info
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=JSON file containing domain/cluster statistics for each sample, coming from the spatialGE.STclust module.
p3_fileFormat=json
p3_name=domain.info
p3_optional=
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
privacy=public
publicationDate=07/24/2025 13\:59 
quality=production
src.repo=https\://github.com/genepattern/spatialGE.STgradient.Launcher.git
taskDoc=https\://genepattern.github.io/spatialGE.STgradient.Launcher/v1/
taskType=javascript
userid=tabor
version=Initial version
