# spatialGE.SpatialAutocorrelation  urn:lsid:genepattern.org:module.analysis:00466:2
#Tue Feb 10 19:12:04 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00466\:2
author=GenePattern Team
categories=spatial transcriptomics
commandLine=Rscript /spatialGE/sthet_wrapper.R --input  <stlist.rds.input> --genes  "<genes>"   <samples> --method  <method> --neighbors  <num.neighbors>  --overwrite <overwrite> --cores <job.cpuCount> <point.size> <samplemeta> <color.by> --categorical <categorical> <color.pallette> --output_filename <output.filename>
cpuType=any
description=This function performs spatial statistics analysis on spatial transcriptomics data using the SThet module.
documentationUrl=https\://genepattern.github.io/spatialGE.SpatialAutocorrelation/v1/
fileFormat=rds
job.cpuCount=
job.docker.image=genepattern/spatialge.spatialautocorrelation\:0.5
job.memory=
job.walltime=
language=any
name=spatialGE.SpatialAutocorrelation
os=any
p10_MODE=
p10_TYPE=java.lang.String
p10_default_value=muted
p10_description=A string of a color palette from khroma or RColorBrewer, or a vector with colors with enough elements to plot categories.
p10_fileFormat=
p10_name=color.pallette
p10_numValues=0..1
p10_optional=on
p10_prefix=
p10_prefix_when_specified=--color_pal 
p10_type=java.lang.String
p10_value=
p11_MODE=
p11_TYPE=java.lang.Double
p11_default_value=1
p11_description=A number specifying the size of the points. Passed to the size aesthetic.
p11_fileFormat=
p11_name=point.size
p11_numValues=0..1
p11_optional=on
p11_prefix=
p11_prefix_when_specified=--ptsize 
p11_type=java.lang.Double
p11_value=
p12_MODE=
p12_TYPE=java.lang.String
p12_default_value=<stlist.rds.input_basename>
p12_description=Prefix for all output filenames (rds and png).
p12_fileFormat=
p12_flag=--output_filename
p12_name=output.filename
p12_numValues=1
p12_optional=
p12_prefix=
p12_prefix_when_specified=
p12_type=java.lang.String
p12_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=An STList RDS object containing normalized data generated by spatialGE.Preprocessing. 
p1_fileFormat=rds
p1_flag=--input
p1_name=stlist.rds.input
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=java.lang.String
p2_default_value=NDRG1,IGKC
p2_description=Comma-separated list of gene names to compute statistics. Do not include any spaces between sample names and commas.
p2_fileFormat=
p2_flag=--genes
p2_name=genes
p2_numValues=1
p2_optional=on
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=java.lang.String
p3_default_value=
p3_description=Comma-separated list of sample names or indices to compute statistics. If left blank, all samples are used. Do not include any spaces between sample names and commas.
p3_fileFormat=
p3_flag=
p3_name=samples
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=--samples  
p3_type=java.lang.String
p3_value=
p4_MODE=
p4_TYPE=CHOICE
p4_default_value=moran
p4_description=Spatial statistic(s) to estimate\: 'moran', 'geary', or both.
p4_fileFormat=
p4_flag=--method
p4_name=method
p4_numValues=1..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=CHOICE
p4_value=moran;geary;both
p5_MODE=
p5_TYPE=Integer
p5_default_value=20
p5_description=Number of neighbors to estimate weights. 
p5_fileFormat=
p5_flag=--neighbors
p5_name=num.neighbors
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=
p5_type=Integer
p5_value=
p6_MODE=
p6_TYPE=CHOICE
p6_default_value=FALSE
p6_description=Logical indicating if previous statistics should be overwritten.
p6_fileFormat=
p6_flag=--overwrite
p6_name=overwrite
p6_numValues=1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=CHOICE
p6_value=TRUE;FALSE
p7_MODE=
p7_TYPE=java.lang.String
p7_default_value=
p7_description=A string indicating the name of the variable in the clinical data frame. If NULL, uses sample names.
p7_fileFormat=
p7_name=samplemeta
p7_numValues=0..1
p7_optional=on
p7_prefix=
p7_prefix_when_specified=--samplemeta 
p7_type=java.lang.String
p7_value=
p8_MODE=
p8_TYPE=java.lang.String
p8_default_value=
p8_description=The variable in x@spatial_meta used to color points in the plot. If NULL, each sample is assigned a different color.
p8_fileFormat=
p8_name=color.by
p8_numValues=0..1
p8_optional=on
p8_prefix=
p8_prefix_when_specified=--color_by 
p8_type=java.lang.String
p8_value=
p9_MODE=
p9_TYPE=CHOICE
p9_default_value=TRUE
p9_description=Logical indicating whether or not to treat color_by as a categorical variable. Default is TRUE.
p9_fileFormat=
p9_flag=--categorical
p9_name=categorical
p9_numValues=1
p9_optional=
p9_prefix=
p9_prefix_when_specified=
p9_type=CHOICE
p9_value=TRUE;FALSE
privacy=public
publicationDate=06/25/2025 17\:43 
quality=production
src.repo=
taskType=spatial transcriptomics
