# spatialGE.STplot.Launcher  urn:lsid:genepattern.org:module.analysis:00471:3
#Tue Feb 10 19:12:06 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00471\:3
author=Thorin Tabor;UCSD - Mesirov Lab
categories=spatial transcriptomics, javascript
commandLine=app.html ? <dataset> <sample.info> <gene.info> <domain.info>
cpuType=any
description=Generates high-quality figures showing the expression of genes in spatial context. 
language=Javascript
name=spatialGE.STplot.Launcher
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Spatial transcriptomics data, coming from spatialGE.Preprocessing, spatialGE.STclust or another spatialGE module.
p1_fileFormat=rds
p1_name=dataset
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=JSON file containing spot/cell and gene statistics for each sample, coming from the spatialGE.Preprocessing module.
p2_fileFormat=json
p2_name=sample.info
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=JSON file containing gene names for each sample, coming from the spatialGE.Preprocessing module.
p3_fileFormat=json
p3_name=gene.info
p3_optional=
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_MODE=IN
p4_TYPE=FILE
p4_default_value=
p4_description=Optionally, a JSON file containing domain/cluster statistics for each sample, coming from the spatialGE.STclust module, may be provided if using clustering data in plots.
p4_fileFormat=json
p4_name=domain.info
p4_optional=on
p4_prefix_when_specified=
p4_type=java.io.File
p4_value=
privacy=public
publicationDate=07/24/2025 14\:00 
quality=production
src.repo=https\://github.com/genepattern/spatialGE.STplot.Launcher.git
taskDoc=https\://genepattern.github.io/spatialGE.STplot.Launcher/v1/
taskType=javascript
userid=tabor
version=Initial version
