# spatialGE.STdiff  urn:lsid:genepattern.org:module.analysis:00473:4.2
#Tue Feb 10 19:12:05 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00473\:4.2
author=GenePattern Team + ChatGPT
categories=differential expression;spatial transcriptomics
commandLine=Rscript <libdir>stdiff_wrapper_ai.R --x <x> <samples> <annot> <w> <k> <deepSplit> <topgenes> <pval_thr> <pval_adj> <sp_topgenes> <clusters> <pairwise> <verbose> <cores> <plot>
cpuType=any
description=STdiff function for differential expression analysis in spatial transcriptomics data.
documentationUrl=https\://github.com/genepattern/spatialGE.STdiff/blob/develop/docs/v1/index.md
fileFormat=rds
job.cpuCount=
job.docker.image=genepattern/spatialgp.preprocessing\:0.4
job.memory=
job.walltime=
language=any
name=spatialGE.STdiff
os=any
p10_MODE=
p10_TYPE=Floating Point
p10_default_value=0.2
p10_description=Proportion of DE genes from non-spatial models to use in spatial models
p10_fileFormat=
p10_name=sp_topgenes
p10_numValues=
p10_optional=on
p10_prefix=
p10_prefix_when_specified=--sp_topgenes 
p10_type=Floating Point
p10_value=
p11_MODE=
p11_TYPE=java.lang.String
p11_default_value=
p11_description=Comma-separated list of cluster names to test DE genes
p11_fileFormat=
p11_name=clusters
p11_numValues=
p11_optional=on
p11_prefix=
p11_prefix_when_specified=--clusters 
p11_type=java.lang.String
p11_value=
p12_MODE=
p12_TYPE=CHOICE
p12_default_value=FALSE
p12_description=Whether to carry tests on a pairwise manner
p12_fileFormat=
p12_name=pairwise
p12_numValues=
p12_optional=on
p12_prefix=
p12_prefix_when_specified=--pairwise 
p12_type=CHOICE
p12_value=
p13_MODE=
p13_TYPE=Integer
p13_default_value=1
p13_description=Output progress indicators. 0 for no text, 1 for basic, 2 for detailed
p13_fileFormat=
p13_name=verbose
p13_numValues=
p13_optional=on
p13_prefix=
p13_prefix_when_specified=--verbose 
p13_type=Integer
p13_value=
p14_MODE=
p14_TYPE=Integer
p14_default_value=
p14_description=Number of cores to use in parallelization
p14_fileFormat=
p14_name=cores
p14_numValues=
p14_optional=on
p14_prefix=
p14_prefix_when_specified=--cores 
p14_type=Integer
p14_value=
p15_MODE=
p15_TYPE=CHOICE
p15_default_value=FALSE
p15_description=Option to plot intermediate results
p15_fileFormat=
p15_name=plot
p15_numValues=
p15_optional=on
p15_prefix=
p15_prefix_when_specified=--plot 
p15_type=CHOICE
p15_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=STList object in .RDS file format to cluster on.
p1_fileFormat=
p1_flag=--x
p1_name=x
p1_numValues=0..1
p1_optional=off
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=java.lang.String
p2_default_value=
p2_description=Comma-separated list of sample indices or names to include in DE tests
p2_fileFormat=
p2_name=samples
p2_numValues=
p2_optional=on
p2_prefix=
p2_prefix_when_specified=--samples 
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=java.lang.String
p3_default_value=
p3_description=Column name in x@spatial_meta containing groups/clusters to be tested
p3_fileFormat=
p3_name=annot
p3_numValues=
p3_optional=on
p3_prefix=
p3_prefix_when_specified=--annot 
p3_type=java.lang.String
p3_value=
p4_MODE=
p4_TYPE=Floating Point
p4_default_value=
p4_description=Spatial weight used in STclust. Required if annot is empty
p4_fileFormat=
p4_name=w
p4_numValues=
p4_optional=on
p4_prefix=
p4_prefix_when_specified=--w 
p4_type=Floating Point
p4_value=
p5_MODE=
p5_TYPE=java.lang.String
p5_default_value=
p5_description=k value used in STclust, or 'dtc' for dynamicTreeCut clusters. Required if annot is empty
p5_fileFormat=
p5_name=k
p5_numValues=
p5_optional=on
p5_prefix=
p5_prefix_when_specified=--k 
p5_type=java.lang.String
p5_value=
p6_MODE=
p6_TYPE=CHOICE
p6_default_value=
p6_description=deepSplit value if used in STclust. Required if k\='dtc'
p6_fileFormat=
p6_name=deepSplit
p6_numValues=
p6_optional=on
p6_prefix=
p6_prefix_when_specified=--deepSplit 
p6_type=CHOICE
p6_value=
p7_MODE=
p7_TYPE=Integer
p7_default_value=5000
p7_description=Number of top variable genes to select from each sample based on variance
p7_fileFormat=
p7_name=topgenes
p7_numValues=
p7_optional=on
p7_prefix=
p7_prefix_when_specified=--topgenes 
p7_type=Integer
p7_value=
p8_MODE=
p8_TYPE=Floating Point
p8_default_value=0.05
p8_description=Cut-off of adjusted p-values to define differentially expressed genes
p8_fileFormat=
p8_name=pval_thr
p8_numValues=
p8_optional=on
p8_prefix=
p8_prefix_when_specified=--pval_thr 
p8_type=Floating Point
p8_value=
p9_MODE=
p9_TYPE=java.lang.String
p9_default_value=fdr
p9_description=Method to adjust p-values. Defaults to 'FDR'
p9_fileFormat=
p9_name=pval_adj
p9_numValues=
p9_optional=on
p9_prefix=
p9_prefix_when_specified=--pval_adj 
p9_type=java.lang.String
p9_value=
privacy=public
publicationDate=06/25/2025 17\:41 
quality=preproduction
taskType=spatial transcriptomics
