# SplitDatasetTrainTest  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00024:4
#Tue Feb 10 19:12:06 UTC 2026
JVMLevel=2.5.0
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00024\:4
author=Stefano Monti, Marc-Danie Nazaire
commandLine=<R2.5> <libdir>SplitDatasetTrainTest.R parseCmdLine <input.dataset.file> <cls.file> <output.prefix> <split.method> <stratified> <folds> <seed> <libdir> <percentage.split.proportion>
cpuType=any
description=Splits a dataset (and cls file) into a number of train and test subsets
fileFormat=gct;cls;res;train.0.gct;train.0.cls;train.0.res;test.0.gct;test.0.cls;test.0.res;train.1.gct;train.1.cls;train.1.res;test.1.gct;test.1.cls;test.1.res;
language=R
name=SplitDatasetTrainTest
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=input dataset - .gct, .res
p1_fileFormat=res;gct
p1_name=input.dataset.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=class template - .cls
p2_fileFormat=cls
p2_name=cls.file
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_default_value=random
p3_description=whether to split the data using a percentage split or cross validation approach
p3_name=split.method
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=random\=percentage split;CV\=cross-validation
p4_default_value=T
p4_description=whether to create splits stratified with respect to the class template
p4_name=stratified
p4_optional=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=T\=yes;F\=no
p5_default_value=1
p5_description=number of train/test splits to generate
p5_name=folds
p5_optional=
p5_prefix_when_specified=
p5_type=java.lang.Integer
p5_value=
p6_default_value=0.5
p6_description=proportion of data to be allocated to train file when split method is percentage split (ignored when split method is cross-validation)
p6_name=percentage.split.proportion
p6_optional=on
p6_prefix_when_specified=
p6_type=java.lang.Float
p6_value=
p7_default_value=123456
p7_description=random number generator seed
p7_name=seed
p7_optional=
p7_prefix_when_specified=
p7_type=java.lang.Integer
p7_value=
p8_default_value=<input.dataset.file_basename>
p8_description=output saved to output.prefix.{train,test}.n.{gct|res,cls}, where n is the fold index
p8_name=output.prefix
p8_optional=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=
privacy=public
publicationDate=08/06/2012 13\:36 
quality=production
taskType=Preprocess & Utilities
userid=gp-help@broad.mit.edu
version=Added output types train.0.gct, test.0.gct, train.1.gct, test.1.gct, et cetera
