# SplitColumns  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00300:1
#Tue Feb 10 19:12:06 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00300\:1
author=
commandLine=<perl> <libdir>splitcolumns.pl -i <input.file> <split.columns> <additional.columns> -o <output.prefix>
cpuType=any
description=Creates a separate file for each column specified from the input file
fileFormat=splitcol.txt
language=Perl
name=SplitColumns
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A tab delimited file
p1_fileFormat=cn;seg;seg.txt;xcn;txt
p1_flag=-i 
p1_name=input.file
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=
p2_description=Specify columns to extract (i.e. 2,4, 5-, 11-17,). Leave blank to split all columns.
p2_fileFormat=
p2_flag=-c 
p2_name=split.columns
p2_optional=
p2_prefix=-c 
p2_prefix_when_specified=-c 
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=
p3_description=Specify subset of additional columns to include in each (i.e. 2,4, 5-, 11-17) output file.
p3_fileFormat=
p3_flag=-a 
p3_name=additional.columns
p3_optional=on
p3_prefix=-a 
p3_prefix_when_specified=-a 
p3_type=java.lang.String
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=<input.file_basename>
p4_description=The prefix to use for the output file name.
p4_fileFormat=
p4_flag=-o 
p4_name=output.prefix
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
pipelineModel=
privacy=public
publicationDate=09/17/2012 15\:27 
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Preprocess & Utilities
userid=gp-help@broadinstitute.org
version=
