# ssGSEA.ROC  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00414:1
#Tue Feb 10 19:12:06 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00414\:1
author=Anthony S. Castanza;UCSD-MesirovLab
categories=statistical methods;gsea
commandLine=<Rscript> <libdir>ssGSEA_ROC.R --ssmatrix <PROJ.gct> --clsfile <CLS> --reverse <Reverse> --plotnsets <Plot.Top.Results>
cpuType=any
description=Generate ROC curves and calculate the AUC from ssGSEA results and a binary phenotype classification.
fileFormat=pdf;tsv
job.docker.image=genepattern/ssgsea_roc\:1.1
language=any
name=ssGSEA.ROC
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=PROJ.gct result from ssGSEA.
p1_fileFormat=gct
p1_flag=--ssmatrix
p1_name=PROJ.gct
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Two Phenotype CLS file for classifying the ssGSEA projections.
p2_fileFormat=cls
p2_flag=--clsfile
p2_name=CLS
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=FALSE
p3_description=Reverse direction of the projections. <br> By default (FALSE) ROCR will calculate statistics for the first phenotype in the cls vs. the second phenotype. <br> Setting this flag to "TRUE" will calculate the second phenotype vs. the first phenotype.
p3_fileFormat=
p3_flag=--reverse
p3_name=Reverse
p3_numValues=1..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=FALSE\=FALSE;TRUE\=TRUE
p4_MODE=
p4_TYPE=Integer
p4_default_value=20
p4_description=Plot ROC curves for the top N gene sets in each direction.
p4_fileFormat=
p4_flag=--plotnsets
p4_name=Plot.Top.Results
p4_numValues=1..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_range=1+
p4_type=java.lang.Integer
p4_value=
privacy=public
publicationDate=05/17/2022 09\:46 
quality=production
taskDoc=ssGSEA_ROC.pdf
taskType=beta
userid=acastanza
version=
