# STAR.aligner  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00370:2
#Tue Feb 10 19:12:06 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00370\:2
author=Guy Bottu;V.I.B.-B.I.T.S.
categories=RNA-seq
commandLine=perl /usr/local/bin/star_aligner_wrapper.pl --index <star.index> --reads1 <reads.pair.1> <reads.pair.2> <max.reads.to.align> --alignendtoend <align.read.end.to.end> --maxNmismatch <max.number.mismatches> --maxFmismatch <max.fraction.mistaches> --minoverhangannot <min.overhang.annotated.read> --minoverhangnotannot <min.overhang.not.annotated.read> --minintronlength <min.intron.length> --maxintronlength <max.intron.length> --matesmaxgap <mates.max.gap> --multimapmismatchrange <secondary.mapping.mismatches.range> --maxmultimap <max.multimapping> --canonicaloverhang <min.report.canonical.junction.overhang> --noncanonicaloverhang <min.report.noncanonical.junction.overhang> --maponlyreportedjunctions <map.only.reported.juntions> --twopass <two.pass> --detectchimeric <detect.chimeric.transcripts> --outputunmapped <output.unmapped.reads> --quantify <quantify.genes> --wiggle <output.wiggle.file> --wigglesignal <wiggle.signal>  --format <output.format> --HIflag <HI.flag> <output.prefix>
cpuType=any
description=STAR (Spliced Transcripts Alignment to a Reference) 2.7.10b is a fast RNA-seq reads to genome mapper. It differs from other mappers as TopHat in that it gains speed at the expense of consuming more RAM and that it incorporates transcriptome annotation at the indexing build stage rather than at the analysis stage. It can optionally detect non-canonical splices and chimeric transcripts.
fileFormat=bam;bg;sam;tab;wig
job.docker.image=genepattern/star.aligner\:v0.50
language=C++
name=STAR.aligner
os=any
p10_MODE=
p10_TYPE=Integer
p10_default_value=21
p10_description=Minimum size of intron. A gap in the alignment between a read and the genome that is smaller is considered a deletion, not an intron.
p10_fileFormat=
p10_flag=--minintronlength 
p10_name=min.intron.length
p10_numValues=1..1
p10_optional=
p10_prefix=
p10_prefix_when_specified=
p10_range=1+
p10_type=java.lang.Integer
p10_value=
p11_MODE=
p11_TYPE=Integer
p11_default_value=500000
p11_description=Maximum size of intron. If a read aligns to the genome with a gap larger than this it is considered a chimeric read. <b><i>The default value of 500,000 is fine-tuned to mammalian genomes, for plant and yeast genomes you will have to decrease it.</i></b>
p11_fileFormat=
p11_flag=--maxintronlength 
p11_name=max.intron.length
p11_numValues=1..1
p11_optional=
p11_prefix=
p11_prefix_when_specified=
p11_range=1+
p11_type=java.lang.Integer
p11_value=
p12_MODE=
p12_TYPE=Integer
p12_default_value=500000
p12_description=Maximum distance between mate pair reads. If reads map to the genome farther apart the fragment is considered to be chimeric. <b><i>The default value of 500,000 is fine-tuned to mammalian genomes, for plant and yeast genomes you will have to decrease it.</i></b>
p12_fileFormat=
p12_flag=--matesmaxgap 
p12_name=mates.max.gap
p12_numValues=1..1
p12_optional=
p12_prefix=
p12_prefix_when_specified=
p12_range=1+
p12_type=java.lang.Integer
p12_value=
p13_MODE=
p13_TYPE=Integer
p13_default_value=0
p13_description=By default STAR only reports reads that map to multiple locations on the genome when they map with the highest possible score. You can ask STAR to report also secondary mappings with up to this much more mismatches than the primary mappings.
p13_fileFormat=
p13_flag=--multimapmismatchrange 
p13_name=secondary.mapping.mismatches.range
p13_numValues=1..1
p13_optional=
p13_prefix=
p13_prefix_when_specified=
p13_range=0+
p13_type=java.lang.Integer
p13_value=
p14_MODE=
p14_TYPE=Integer
p14_default_value=10
p14_description=Do not report reads that map to more than that many different locations on the genome.
p14_fileFormat=
p14_flag=--maxmultimap 
p14_name=max.multimapping
p14_numValues=1..1
p14_optional=
p14_prefix=
p14_prefix_when_specified=
p14_range=1+
p14_type=java.lang.Integer
p14_value=
p15_MODE=
p15_TYPE=Integer
p15_default_value=12
p15_description=Criterium for reporting de novo predicted splice junctions in the SJ.tab.out file \: for canonical splice sites at least one read with at least this overhang is needed.
p15_fileFormat=
p15_flag=--canonicaloverhang 
p15_name=min.report.canonical.junction.overhang
p15_numValues=1..1
p15_optional=
p15_prefix=
p15_prefix_when_specified=
p15_range=1+
p15_type=java.lang.Integer
p15_value=
p16_MODE=
p16_TYPE=Integer
p16_default_value=30
p16_description=Criterium for reporting de novo predicted splice junctions in the SJ.tab.out file \: for noncanonical splice sites at least 3 reads with at least this overhang are needed.
p16_fileFormat=
p16_flag=--noncanonicaloverhang 
p16_name=min.report.noncanonical.junction.overhang
p16_numValues=1..1
p16_optional=
p16_prefix=
p16_prefix_when_specified=
p16_range=1+
p16_type=java.lang.Integer
p16_value=
p17_MODE=
p17_TYPE=TEXT
p17_default_value=no
p17_description=By default all mapped reads are output in the SAM/BAM file. Set this to yes if you want to bring the SAM/BAM file in agreement with the SJ.tab.out file, by outputting only reads that are not spliced or map to splice junctions that are annotated or have been de novo predicted.
p17_fileFormat=
p17_flag=--maponlyreportedjunctions 
p17_name=map.only.reported.juntions
p17_numValues=1..1
p17_optional=
p17_prefix=
p17_prefix_when_specified=
p17_type=java.lang.String
p17_value=yes\=yes;no\=no
p18_MODE=
p18_TYPE=TEXT
p18_default_value=no
p18_description=Run STAR in 2-pass mode, that is, run STAR a first time, merge the found splice junctions with the splice junction annotation in the index, and run STAR a second time. Consult the documentation for more explanation.
p18_fileFormat=
p18_flag=--twopass 
p18_name=two.pass
p18_numValues=1..1
p18_optional=
p18_prefix=
p18_prefix_when_specified=
p18_type=java.lang.String
p18_value=yes\=yes;no\=no
p19_MODE=
p19_TYPE=TEXT
p19_default_value=no
p19_description=
p19_fileFormat=
p19_flag=--detectchimeric 
p19_name=detect.chimeric.transcripts
p19_numValues=1..1
p19_optional=
p19_prefix=
p19_prefix_when_specified=
p19_type=java.lang.String
p19_value=yes\=yes;no\=no
p1_MODE=IN
p1_TYPE=FILE
p1_description=A STAR index. Select a prebuilt index from https\://datasets.genepattern.org/?prefix\=data/module_support_files/STAR/ or upload your own as a ZIP file (you can make one using STAR.indexer).
p1_fileFormat=zip
p1_flag=--index
p1_name=star.index
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p20_MODE=
p20_TYPE=TEXT
p20_default_value=no
p20_description=
p20_fileFormat=
p20_flag=--outputunmapped 
p20_name=output.unmapped.reads
p20_numValues=1..1
p20_optional=
p20_prefix=
p20_prefix_when_specified=
p20_type=java.lang.String
p20_value=yes\=yes;no\=no
p21_MODE=
p21_TYPE=TEXT
p21_default_value=no
p21_description=Write a table with number of reads mapped per gene and a supplementary BAM file with mappings to transcriptome instead of to genome coordinates.
p21_fileFormat=
p21_flag=--quantify 
p21_name=quantify.genes
p21_numValues=1..1
p21_optional=
p21_prefix=
p21_prefix_when_specified=
p21_type=java.lang.String
p21_value=yes\=yes;no\=no
p22_MODE=
p22_TYPE=TEXT
p22_default_value=None
p22_description=Output a "wiggle" file for viewing in viewers like IGV or UCSC genome browser.
p22_fileFormat=
p22_flag=--wiggle 
p22_name=output.wiggle.file
p22_numValues=1..1
p22_optional=
p22_prefix=
p22_prefix_when_specified=
p22_type=java.lang.String
p22_value=None\=none;bedGraph\=file in BedGraph format;wiggle\=file in WIG format
p23_MODE=
p23_TYPE=TEXT
p23_default_value=all
p23_description=From which bases to generate the signal for the "wiggle" file. By default they are all used, but you can choose to use only the bases at the 5'-end of the 1<sup>st</sup> read (useful for CAGE/RAMPAGE) or only from the 2<sup>nd</sup> mate from read pairs.
p23_fileFormat=
p23_flag=--wigglesignal 
p23_name=wiggle.signal
p23_numValues=1..1
p23_optional=
p23_prefix=
p23_prefix_when_specified=
p23_type=java.lang.String
p23_value=all\=all;read1_5p\=only 5' from read 1;read2\=only from read 2
p24_MODE=
p24_TYPE=TEXT
p24_default_value=SAM
p24_description=
p24_fileFormat=
p24_flag=--format 
p24_name=output.format
p24_numValues=1..1
p24_optional=
p24_prefix=
p24_prefix_when_specified=
p24_type=java.lang.String
p24_value=SAM\=SAM unsorted;BAM Unsorted\=BAM unsorted ;BAM SortedByCoordinate\=BAM sorted by coordinate
p25_MODE=
p25_TYPE=TEXT
p25_default_value=OneBestScore
p25_description=Number of "hits" with higest score to label as "primary" in the SAM/BAM file. If you choose "only one" the others are labeled as "secondary" (all reads that map with lower than the highest score are labeled "secondary").
p25_fileFormat=
p25_flag=--HIflag 
p25_name=HI.flag
p25_numValues=1..1
p25_optional=
p25_prefix=
p25_prefix_when_specified=
p25_type=java.lang.String
p25_value=OneBestScore\=only one;AllBestScore\=all
p26_MODE=
p26_TYPE=TEXT
p26_default_value=STAR
p26_description=The prefix to use for the output file names.
p26_fileFormat=
p26_flag=--outputprefix 
p26_name=output.prefix
p26_numValues=0..1
p26_optional=on
p26_prefix=--outputprefix 
p26_prefix_when_specified=--outputprefix 
p26_type=java.lang.String
p26_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Unpaired reads or first mate for paired reads, as files in fastA or fastQ format. You can provide several files.
p2_fileFormat=fa;fasta;fastq;fq
p2_flag=--reads1 
p2_name=reads.pair.1
p2_numValues=1+
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=Second mate for paired reads.<p><b><i>The files and the sequences inside the files must be in the same order as for the first mates.</i></b>
p3_fileFormat=fa;fasta;fastq;fq
p3_flag=--reads2 
p3_name=reads.pair.2
p3_numValues=0+
p3_optional=on
p3_prefix=--reads2 
p3_prefix_when_specified=--reads2 
p3_type=java.io.File
p3_value=
p4_MODE=
p4_TYPE=Integer
p4_default_value=
p4_description=Set this if you want to map only a selected set of reads at the top of the input (mainly useful for testing).
p4_fileFormat=
p4_flag=--mapN 
p4_name=max.reads.to.align
p4_numValues=0..1
p4_optional=on
p4_prefix=--mapN 
p4_prefix_when_specified=--mapN 
p4_range=1+
p4_type=java.lang.Integer
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=no
p5_description=Align reads end to end and count all mistmatches. The default is to use instead "soft clipping" at both 5'- and 3'-end, that means to make a local alignment and ignore the contribution of the ends of the read to the final score if this improves the score. <b><i>This can be useful for ChIP-seq and other DNA sequencing applications with reads that have already been quality-trimmed.</i></b>
p5_fileFormat=
p5_flag=--alignendtoend 
p5_name=align.read.end.to.end
p5_numValues=1..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=yes\=yes;no\=no
p6_MODE=
p6_TYPE=Integer
p6_default_value=10
p6_description=Maximum number of mismatches per read. Note that a mate pair is counted as one read.
p6_fileFormat=
p6_flag=--maxNmismatch 
p6_name=max.number.mismatches
p6_numValues=1..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_range=0+
p6_type=java.lang.Integer
p6_value=
p7_MODE=
p7_TYPE=Floating Point
p7_default_value=0.3
p7_description=Maximum number of mismatches per read, expressed as the proportion between the number of mismatches and the <b><i>mapped</i></b> length of the read.  Note that a mate pair is counted as one read.
p7_fileFormat=
p7_flag=--maxFmismatch 
p7_name=max.fraction.mistaches
p7_numValues=1..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=
p7_range=0..1
p7_type=java.lang.Float
p7_value=
p8_MODE=
p8_TYPE=Integer
p8_default_value=3
p8_description=Minimum length that read must map at both sides of splice junction in order to accept mapping to a splice junction that is annotated in GTF of tab file.
p8_fileFormat=
p8_flag=--minoverhangannot 
p8_name=min.overhang.annotated.read
p8_numValues=1..1
p8_optional=
p8_prefix=
p8_prefix_when_specified=
p8_range=1+
p8_type=java.lang.Integer
p8_value=
p9_MODE=
p9_TYPE=Integer
p9_default_value=5
p9_description=Minimum length that read must map at both sides of splice junction in order to accept de novo discovery of splice junction.
p9_fileFormat=
p9_flag=--minoverhangnotannot 
p9_name=min.overhang.not.annotated.read
p9_numValues=1..1
p9_optional=
p9_prefix=
p9_prefix_when_specified=
p9_range=1+
p9_type=java.lang.Integer
p9_value=
privacy=public
publicationDate=09/27/2023 15\:49 
quality=production
taskDoc=http\://software.broadinstitute.org/cancer/software/genepattern/modules/docs/STAR.aligner/1
taskType=RNA-seq
userid=gbottu
version=Adding support for gzipped input data
