# STAR.indexer  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00371:1
#Tue Feb 10 19:12:07 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00371\:1
author=Guy Bottu;V.I.B.-B.I.T.S.
categories=RNA-seq
commandLine=perl /usr/local/bin/star_indexer_wrapper.pl --fastafilelist <fasta.file> <GTF.file> <tab.file> --indexdir <output.file> --overhang <overhang> --indexstringlength <index.string.length> --binsize <bin.size> --RAM <RAM.limit>
cpuType=any
description=The STAR indexer (version 2.7.10b) makes from a series of fastA files containing a genome an index for use with the STAR spliced read to genome aligner. It can optionally (but highly recommended \!) incorporate information about known intron-exon junctions.
fileFormat=zip
job.docker.image=genepattern/star.indexer\:v0.48
language=C++
name=STAR.indexer
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=One or several fastA files containing the genome to index.
p1_fileFormat=fa;fasta
p1_flag=--fastafilelist 
p1_name=fasta.file
p1_numValues=1+
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=A GTF file containing a list of gene model annotations. When provided, STAR will use it to improve the accuracy of the mapping of intron-exon splice junctions.
p2_fileFormat=gtf
p2_flag=--GTFfile 
p2_name=GTF.file
p2_numValues=0..1
p2_optional=on
p2_prefix=--GTFfile 
p2_prefix_when_specified=--GTFfile 
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=A file in tab-separated format containing a list of gene model annotations, usually an SJ.tab.out file generated by a previous run of STAR.aligner. You can use it instead of or together with a GTF file. Consult the documentation for more explanation.
p3_fileFormat=tab
p3_flag=--tabfile 
p3_name=tab.file
p3_numValues=0..1
p3_optional=on
p3_prefix=--tabfile 
p3_prefix_when_specified=--tabfile 
p3_type=java.io.File
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=
p4_description=The name of the directory (and ZIP file) in which to put the STAR index.
p4_fileFormat=
p4_flag=--indexdir 
p4_name=output.file
p4_numValues=0..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=
p5_MODE=
p5_TYPE=Integer
p5_default_value=100
p5_description=The length of the genomic sequence around the annotated intron-exon junctions. Ideally it should have a value <b>max(ReadLength) - 1</b>, but in most cases a generic value of 100 will work well.
p5_fileFormat=
p5_flag=--overhang 
p5_name=overhang
p5_numValues=1..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_range=1+
p5_type=java.lang.Integer
p5_value=
p6_MODE=
p6_TYPE=Integer
p6_default_value=14
p6_description=Length of the strings used for making the index. For small genomes (less than 1 Gbase) it can be useful to scale it down to <b>min(14, log<sub>2</sub>(GenomeLength)/2 - 1)</b>.
p6_fileFormat=
p6_flag=--indexstringlength 
p6_name=index.string.length
p6_numValues=1..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_range=1+
p6_type=java.lang.Integer
p6_value=
p7_MODE=
p7_TYPE=Integer
p7_default_value=18
p7_description=Size of the bins for storage. If the genome contains a large number of separate scaffolds ("references") instead of just the full chromosomes and maybe a few scaffolds you can reduce RAM consumption by setting this to <b>min(18, log<sub>2</sub>(GenomeLength/NumberOfReferences))</b>.
p7_fileFormat=
p7_flag=--binsize 
p7_name=bin.size
p7_numValues=1..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=
p7_range=1+
p7_type=java.lang.Integer
p7_value=
p8_MODE=
p8_TYPE=Integer
p8_default_value=31
p8_description=Upper limit for RAM allocated to indexing process, in Gbyte. For very large genomes you might heve to increase this, but make sure that the RAM is indeed physically present on the server and you have permission to make it available for the process. 
p8_fileFormat=
p8_flag=--RAM 
p8_name=RAM.limit
p8_numValues=1..1
p8_optional=
p8_prefix=
p8_prefix_when_specified=
p8_range=1+
p8_type=java.lang.Integer
p8_value=
privacy=public
publicationDate=02/08/2023 14\:58 
quality=production
taskDoc=http\://software.broadinstitute.org/cancer/software/genepattern/modules/docs/STAR.indexer/1
taskType=RNA-seq
userid=guy.bottu@vib.be
version=Rename index.dir parameter to output.file
