# STREAM.DetectLeafGenes  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00403:0.12
#Tue Feb 10 19:12:07 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00403\:0.12
author=Ted Liefeld, UCSD School of Medicine.
categories=Single-Cell
commandLine=python /stream/leaf_command_line.py -m <data.file> -of <output.filename> <root> <preference> <cutoff.zscore> <cutoff.pvalue> <percentile.expr> <use.precomputed> -n_jobs <job.cpuCount> 
cpuType=any
description=Detect marker genes for each leaf branch.
fileFormat=pkl
job.cpuCount=2
job.docker.image=genepattern/stream_detectleafgenes\:0.10
job.memory=8 Gb
job.walltime=1\:00\:00
language=any
minGenePatternVersion=3.9.13
name=STREAM.DetectLeafGenes
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A STREAM pkl file containing gene expression data
p1_fileFormat=pkl
p1_flag=
p1_name=data.file
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=<data.file_basename>
p2_description=output file name prefix
p2_fileFormat=
p2_flag=
p2_name=output.filename
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=
p3_description=The starting node for detecting leaf genes.
p3_fileFormat=
p3_flag=
p3_name=root
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=-root  
p3_type=java.lang.String
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=
p4_description=The preference of nodes. The branch with speficied nodes are preferred and will be dealt with first. The higher ranks the node have, The earlier the branch with that node will be analyzed.  Comma delimited eg S3,S4
p4_fileFormat=
p4_flag=
p4_name=preference
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=-preference 
p4_type=java.lang.String
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=1.5
p5_description=The z-score cutoff used for mean values of all leaf branches.
p5_fileFormat=
p5_flag=
p5_name=cutoff.zscore
p5_numValues=1..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=-cutoff_zscore   
p5_type=java.lang.String
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=0.01
p6_description=The p value cutoff used for Kruskal-Wallis H-test and post-hoc pairwise Conover\u00e2??s test.
p6_fileFormat=
p6_flag=
p6_name=cutoff.pvalue
p6_numValues=1..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=-cutoff_pvalue   
p6_type=java.lang.String
p6_value=
p7_MODE=
p7_TYPE=TEXT
p7_default_value=95
p7_description=Between 0 and 100. Between 0 and 100. Specify the percentile of gene expression greater than 0 to filter out some extreme gene expressions.
p7_fileFormat=
p7_flag=
p7_name=percentile.expr
p7_numValues=1..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=-percentile_expr   
p7_type=java.lang.String
p7_value=
p8_MODE=
p8_TYPE=TEXT
p8_default_value=-flag_use_precomputed 
p8_description=If True, the previously computed scaled gene expression will be used.
p8_fileFormat=
p8_flag=
p8_name=use.precomputed
p8_numValues=0..1
p8_optional=on
p8_prefix=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=\=Off;-flag_use_precomputed \=Use precomputed gene list
privacy=public
publicationDate=02/04/2020 13\:02 
quality=${quality.level}
requiredPatchLSIDs=
requiredPatchURLs=
taskDoc=doc.html
taskType=Single-cell
userid=ted
version=inital revision
