# STREAM.SeedEPGStructure  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00398:0.4
#Tue Feb 10 19:12:08 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00398\:0.4
author=Ted Liefeld, UCSD School of Medicine.
categories=Single-Cell
commandLine=python /stream/structure_command_line.py -m <data.file> -of <output.filename> <percent.neighbor.cells> <figure.width> <figure.height> <figure.legend.num.columns> <num.clusters> <damping> <preference.percentile> <max.clusters> <clustering> <component.x> <component.y> <num.components>
cpuType=any
description=Seeding the initial elastic principal graph prior to starting the trajectory learning process.
fileFormat=pkl
job.cpuCount=2
job.docker.image=genepattern/stream_seedepgstructure\:0.2
job.memory=8 Gb
job.walltime=1\:00\:00
language=any
minGenePatternVersion=3.9.13
name=STREAM.SeedEPGStructure
os=any
p10_MODE=
p10_TYPE=TEXT
p10_default_value=8
p10_description=figure height
p10_fileFormat=
p10_flag=
p10_name=figure.height
p10_numValues=0..1
p10_optional=on
p10_prefix=
p10_prefix_when_specified=-fig_height  
p10_type=java.lang.String
p10_value=
p11_MODE=
p11_TYPE=TEXT
p11_default_value=
p11_description=output file name prefix
p11_fileFormat=
p11_flag=
p11_name=output.filename
p11_numValues=1..1
p11_optional=
p11_prefix=
p11_prefix_when_specified=
p11_type=java.lang.String
p11_value=
p12_MODE=
p12_TYPE=TEXT
p12_default_value=kmeans
p12_description=Clustering method used to infer the initial nodes. Choose from affinity propagation, K-Means clustering, spectral clustering
p12_fileFormat=
p12_flag=
p12_name=clustering
p12_numValues=1..1
p12_optional=
p12_prefix=
p12_prefix_when_specified=-clustering 
p12_type=java.lang.String
p12_value=kmeans\=KMeans Clustering;ap\=Affinity Propagation;sc\=Spectral Clustering
p13_MODE=
p13_TYPE=TEXT
p13_default_value=0
p13_description=Component used for x axis.
p13_fileFormat=
p13_flag=
p13_name=component.x
p13_numValues=1..1
p13_optional=
p13_prefix=
p13_prefix_when_specified=-comp1 
p13_type=java.lang.String
p13_value=
p14_MODE=
p14_TYPE=TEXT
p14_default_value=1
p14_description=Component used for y axis.
p14_fileFormat=
p14_flag=
p14_name=component.y
p14_numValues=1..1
p14_optional=
p14_prefix=
p14_prefix_when_specified=-comp2  
p14_type=java.lang.String
p14_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A STREAM pkl file containing annotated and preprocessed gene expression data
p1_fileFormat=pkl
p1_flag=
p1_name=data.file
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=3
p2_description=Number of components to be plotted.
p2_fileFormat=
p2_flag=
p2_name=num.components
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=-n_comp   
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=
p3_default_value=0.1
p3_description=Neighbor percentage. The percentage of points used as neighbors for spectral clustering.
p3_fileFormat=
p3_flag=
p3_name=percent.neighbor.cells
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=-nb_pct   
p3_type=java.lang.String
p3_value=
p4_MODE=
p4_TYPE=
p4_default_value=10
p4_description=Number of clusters (only valid once 'clustering' is specificed as 'sc' or 'kmeans').
p4_fileFormat=
p4_flag=
p4_name=num.clusters
p4_numValues=1..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=-n_clusters   
p4_type=java.lang.String
p4_value=
p5_MODE=
p5_TYPE=
p5_default_value=0.75
p5_description=Damping factor (between 0.5 and 1) for affinity propagation.
p5_fileFormat=
p5_flag=
p5_name=damping
p5_numValues=1..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=-damping   
p5_type=java.lang.String
p5_value=
p6_MODE=
p6_TYPE=CHOICE
p6_default_value=50
p6_description=Preference percentile (between 0 and 100). The percentile of the input similarities for affinity propagation.
p6_fileFormat=
p6_flag=
p6_name=preference.percentile
p6_numValues=1..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=-pref_perc 
p6_type=java.lang.String
p6_value=
p7_default_value=200
p7_description=Number of clusters (only valid once 'clustering' is specificed as 'sc' or 'kmeans').
p7_fileFormat=
p7_flag=
p7_name=max.clusters
p7_numValues=1..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=-max_n_clusters  
p7_type=java.lang.String
p7_value=
p8_MODE=
p8_TYPE=TEXT
p8_default_value=8
p8_description=figure width 
p8_fileFormat=
p8_flag=
p8_name=figure.width
p8_numValues=0..1
p8_optional=on
p8_prefix=
p8_prefix_when_specified=-fig_width   
p8_type=java.lang.String
p8_value=
p9_MODE=
p9_TYPE=TEXT
p9_default_value=3
p9_description=The number of columns that the legend has.
p9_fileFormat=
p9_flag=
p9_name=figure.legend.num.columns
p9_numValues=1..1
p9_optional=
p9_prefix=
p9_prefix_when_specified=-fig_legend_ncol  
p9_type=java.lang.String
p9_value=
privacy=public
publicationDate=02/04/2020 12\:53 
quality=${quality.level}
requiredPatchLSIDs=
requiredPatchURLs=
taskDoc=doc.html
taskType=Single-cell
userid=ted
version=inital revision
