# STREAM.DetectDifferentiallyExpressedGenes  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00402:0.12
#Tue Feb 10 19:12:07 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00402\:0.12
author=Ted Liefeld, UCSD School of Medicine.
categories=Single-Cell
commandLine=python /stream/diffex_command_line.py -m <data.file> -of <output.filename> <figure.width> <figure.height> <root> <preference> <cutoff.zscore>  <percentile.expr> <flag.use.precomputed> <cutoff.logfc> <num.genes> -n_jobs <job.cpuCount> 
cpuType=any
description=Used to detect differentially expressed genes between pairs of branches.
fileFormat=pkl
job.cpuCount=2
job.docker.image=genepattern/stream_diffex\:0.10
job.memory=8 Gb
job.walltime=1\:00\:00
language=any
minGenePatternVersion=3.9.13
name=STREAM.DetectDifferentiallyExpressedGenes
os=any
p10_MODE=
p10_TYPE=TEXT
p10_default_value=95
p10_description=Between 0 and 100. Between 0 and 100. Specify the percentile of gene expression greater than 0 to filter out some extreme gene expressions. 
p10_fileFormat=
p10_flag=
p10_name=percentile.expr
p10_numValues=1..1
p10_optional=
p10_prefix=
p10_prefix_when_specified=-percentile_expr   
p10_type=java.lang.String
p10_value=
p11_MODE=
p11_TYPE=TEXT
p11_default_value=0.25
p11_description=The log-transformed fold change cutoff between a pair of branches.
p11_fileFormat=
p11_flag=
p11_name=cutoff.logfc
p11_numValues=1..1
p11_optional=
p11_prefix=
p11_prefix_when_specified=-cutoff_logfc   
p11_type=java.lang.String
p11_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A STREAM pkl file containing gene expression data
p1_fileFormat=pkl
p1_flag=
p1_name=data.file
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=8
p2_description=figure width 
p2_fileFormat=
p2_flag=
p2_name=figure.width
p2_numValues=0..1
p2_optional=on
p2_prefix=
p2_prefix_when_specified=-fig_width   
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=
p3_description=If True, the previously computed scaled gene expression will be used.
p3_fileFormat=
p3_flag=
p3_name=flag.use.precomputed
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=\=Off;-flag_use_precomputed \=Use precomputed gene list
p4_MODE=
p4_TYPE=TEXT
p4_default_value=8
p4_description=figure height
p4_fileFormat=
p4_flag=
p4_name=figure.height
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=-fig_height  
p4_type=java.lang.String
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=<data.file_basename>
p5_description=output file name prefix
p5_fileFormat=
p5_flag=
p5_name=output.filename
p5_numValues=1..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=15
p6_description=The number of genes to plot.
p6_fileFormat=
p6_flag=
p6_name=num.genes
p6_numValues=1..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=-num_genes  
p6_type=java.lang.String
p6_value=
p7_MODE=
p7_TYPE=TEXT
p7_default_value=
p7_description=The starting node.
p7_fileFormat=
p7_flag=
p7_name=root
p7_numValues=0..1
p7_optional=on
p7_prefix=
p7_prefix_when_specified=-root  
p7_type=java.lang.String
p7_value=
p8_MODE=
p8_TYPE=TEXT
p8_default_value=
p8_description=The preference of nodes. The branch with speficied nodes are preferred and will be dealt with first. The higher ranks the node have, The earlier the branch with tha node will be analyzed.  This will help generate the consistent results as shown in subway map and stream plot. Comma delimited eg S3,S4
p8_fileFormat=
p8_flag=
p8_name=preference
p8_numValues=0..1
p8_optional=on
p8_prefix=
p8_prefix_when_specified=-preference 
p8_type=java.lang.String
p8_value=
p9_MODE=
p9_TYPE=TEXT
p9_default_value=1.5
p9_description=The z-score cutoff used for Mann - Whitney U test.
p9_fileFormat=
p9_flag=
p9_name=cutoff.zscore
p9_numValues=1..1
p9_optional=
p9_prefix=
p9_prefix_when_specified=-cutoff_zscore   
p9_type=java.lang.String
p9_value=
privacy=public
publicationDate=02/04/2020 13\:02 
quality=${quality.level}
requiredPatchLSIDs=
requiredPatchURLs=
taskDoc=doc.html
taskType=Single-cell
userid=ted
version=inital revision
