# STREAM.FeatureSelection  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00396:0.6
#Tue Feb 10 19:12:08 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00396\:0.6
author=Ted Liefeld, UCSD School of Medicine.
categories=Single-Cell
commandLine=python /stream/featureselection_command_line.py -m <data.file> <output.filename> <loess.fraction> <percentile> <num.genes> -n_j <job.cpuCount> <feature> <num.principal.components> <max.principal.components> --flag <first.principal.component> --flag  <use.precomputed> --flag <find.variable.genes> --flag <find.principal.components> <figure.height> <figure.width>
cpuType=any
description=Select either or both of the most variable genes and then find the principal components using PCA. These will then be available for the downstram trajectory analysis.  
fileFormat=gz,tsv,mtx
job.cpuCount=2
job.docker.image=genepattern/stream_featureselection\:0.2
job.memory=8 Gb
job.walltime=1\:00\:00
language=any
minGenePatternVersion=3.9.13
name=STREAM.FeatureSelection
os=any
p10_MODE=
p10_TYPE=TEXT
p10_default_value=100
p10_description=The maximum number of principal components used for variance Ratio plot.
p10_fileFormat=
p10_flag=
p10_name=max.principal.components
p10_numValues=0..1
p10_optional=on
p10_prefix=
p10_prefix_when_specified=-max_pc  
p10_type=java.lang.String
p10_value=
p11_MODE=
p11_TYPE=TEXT
p11_default_value=
p11_description=If True, the first principal component will be included.
p11_fileFormat=
p11_flag=
p11_name=first.principal.component
p11_numValues=0..1
p11_optional=on
p11_prefix=
p11_prefix_when_specified=
p11_type=java.lang.String
p11_value=\=False;--flag_firstpc\=True
p12_MODE=
p12_TYPE=CHOICE
p12_default_value=--flag_useprecomputed
p12_description=If True, the PCA results from previous computing will be used.
p12_fileFormat=
p12_flag=
p12_name=use.precomputed
p12_numValues=0..1
p12_optional=on
p12_prefix=
p12_prefix_when_specified=
p12_type=java.lang.String
p12_value=\=FALSE;--flag_useprecomputed\=TRUE
p13_MODE=
p13_TYPE=TEXT
p13_default_value=8
p13_description=figure height.
p13_fileFormat=
p13_flag=
p13_name=figure.height
p13_numValues=0..1
p13_optional=on
p13_prefix=
p13_prefix_when_specified=-fig_height   
p13_type=java.lang.String
p13_value=
p14_MODE=
p14_TYPE=TEXT
p14_default_value=8
p14_description=figure width.
p14_fileFormat=
p14_flag=
p14_name=figure.width
p14_numValues=0..1
p14_optional=on
p14_prefix=
p14_prefix_when_specified=-fig_width   
p14_type=java.lang.String
p14_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A STREAM pkl file containing an annotated AnnData matrix of gene expression data
p1_fileFormat=pkl
p1_flag=
p1_name=data.file
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=CHOICE
p2_default_value=0.1
p2_description=Between 0 and 1. The fraction of the data used when estimating each y-value in LOWESS function.
p2_fileFormat=
p2_flag=
p2_name=loess.fraction
p2_numValues=0..1
p2_optional=on
p2_prefix=
p2_prefix_when_specified=-lf  
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=CHOICE
p3_default_value=95
p3_description=Between 0 and 100. Specify the percentile to select genes.Genes are ordered based on its distance from the fitted curve.
p3_fileFormat=
p3_flag=
p3_name=percentile
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=-per  
p3_type=java.lang.String
p3_value=
p4_MODE=
p4_TYPE=CHOICE
p4_default_value=
p4_description=Specify the number of selected genes. Genes are ordered based on its distance from the fitted curve.
p4_fileFormat=
p4_flag=
p4_name=num.genes
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=-n_g  
p4_type=java.lang.String
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=
p5_description=The output file name prefix.
p5_fileFormat=
p5_flag=
p5_name=output.filename
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=-of  
p5_type=java.lang.String
p5_value=
p6_MODE=
p6_TYPE=CHOICE
p6_default_value=var_genes
p6_description=Choose from the genes in the dataset, Features used for pricipal component analysis.  If None, all the genes will be used.  IF 'var_genes', the most variable genes obtained from select_variable_genes() will be used.
p6_fileFormat=
p6_flag=
p6_name=feature
p6_numValues=0..1
p6_optional=on
p6_prefix=
p6_prefix_when_specified=-feat 
p6_type=java.lang.String
p6_value=None\=None;var_genes\=var_genes
p7_MODE=
p7_TYPE=TEXT
p7_default_value=
p7_description=Find variable genes
p7_fileFormat=
p7_flag=
p7_name=find.variable.genes
p7_numValues=0..1
p7_optional=on
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=\=False;--flag_variable\=True
p8_MODE=
p8_TYPE=TEXT
p8_default_value=
p8_description=Do a principal compnents Analysis (PCA).
p8_fileFormat=
p8_flag=
p8_name=find.principal.components
p8_numValues=0..1
p8_optional=on
p8_prefix=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=\=False;--flag_pca\=True
p9_MODE=
p9_TYPE=TEXT
p9_default_value=15
p9_description=The number of selected principal components.
p9_fileFormat=
p9_flag=
p9_name=num.principal.components
p9_numValues=0..1 
p9_optional=on
p9_prefix=
p9_prefix_when_specified=-n_pc  
p9_type=java.lang.String
p9_value=
privacy=public
publicationDate=02/04/2020 12\:51 
quality=${quality.level}
requiredPatchLSIDs=
requiredPatchURLs=
taskDoc=doc.html
taskType=Single-cell
userid=ted
version=inital revision
