# STREAM.EPGAdjustFinalGraph  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00400:0.6
#Tue Feb 10 19:12:07 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00400\:0.6
author=Ted Liefeld, UCSD School of Medicine.
categories=Single-Cell
commandLine=python /stream/epg_adjustfinal_command_line.py -m <data.file> -of <output.filename> <figure.width> <figure.height> <figure.legend.num.columns> <component.x> <component.y> <num.components> <epg.max.steps>  <incremental.number.of.nodes> <epg.trimming.radius> <epg.alpha> -epg_n_processes <job.cpuCount>  <epg.lambda> <epg.mu> <epg.collapse.mode> <epg.collapse.parameter> <epg.extension.mode> <epg.extension.parameter> <epg.final.energy> <epg.beta>
cpuType=any
description=Adjust the final EPG trajectory structure by pruning, extending and otherwise modifying the branches to optimize for single-cell data
fileFormat=pkl
job.cpuCount=2
job.docker.image=genepattern/stream_epg_adjustfinal\:0.2
job.memory=8 Gb
job.walltime=1\:00\:00
language=any
minGenePatternVersion=3.9.13
name=STREAM.EPGAdjustFinalGraph
os=any
p10_MODE=
p10_TYPE=TEXT
p10_default_value=0
p10_description=Component used for x axis in plots.
p10_fileFormat=
p10_flag=
p10_name=component.x
p10_numValues=1..1
p10_optional=
p10_prefix=
p10_prefix_when_specified=-comp1 
p10_type=java.lang.String
p10_value=
p11_MODE=
p11_TYPE=TEXT
p11_default_value=1
p11_description=Component used for y axis in plots.
p11_fileFormat=
p11_flag=
p11_name=component.y
p11_numValues=1..1
p11_optional=
p11_prefix=
p11_prefix_when_specified=-comp2  
p11_type=java.lang.String
p11_value=
p12_MODE=
p12_TYPE=TEXT
p12_default_value=3
p12_description=Number of components to be plotted.
p12_fileFormat=
p12_flag=
p12_name=num.components
p12_numValues=1..1
p12_optional=
p12_prefix=
p12_prefix_when_specified=-n_comp 
p12_type=java.lang.String
p12_value=
p13_MODE=
p13_TYPE=TEXT
p13_default_value=0.02
p13_description=Alpha parameter of the penalized elastic energy.
p13_fileFormat=
p13_flag=
p13_name=epg.alpha
p13_numValues=1..1
p13_optional=
p13_prefix=
p13_prefix_when_specified=-epg_alpha  
p13_type=java.lang.String
p13_value=
p14_MODE=
p14_TYPE=TEXT
p14_default_value=0.02
p14_description=Lambda parameter used to compute the elastic energy.
p14_fileFormat=
p14_flag=
p14_name=epg.lambda
p14_numValues=1..1
p14_optional=
p14_prefix=
p14_prefix_when_specified=-epg_lambda   
p14_type=java.lang.String
p14_value=
p15_MODE=
p15_TYPE=TEXT
p15_default_value=0.1
p15_description=Mu parameter used to compute the elastic energy.
p15_fileFormat=
p15_flag=
p15_name=epg.mu
p15_numValues=1..1
p15_optional=
p15_prefix=
p15_prefix_when_specified=-epg_mu   
p15_type=java.lang.String
p15_value=
p16_MODE=
p16_TYPE=TEXT
p16_default_value=None
p16_description=The mode used to prune the graph.Choose from {{'PointNumber','PointNumber_Extrema','PointNumber_Leaves','EdgesNumber','EdgesLength'}}. 'PointNumber'\: branches with less than epg_collapse_par points (points projected on the extreme points are not considered) are removed; 'PointNumber_Extrema', branches with less than epg_collapse_par (points projected on the extreme points are not considered) are removed;  'PointNumber_Leaves', branches with less than epg_collapse_par points (points projected on non-leaf extreme points are not considered) are removed.
p16_fileFormat=
p16_flag=
p16_name=epg.collapse.mode
p16_numValues=1..1
p16_optional=
p16_prefix=
p16_prefix_when_specified=-epg_collapse_mode       
p16_type=java.lang.String
p16_value=None\=None;PointNumber\=PointNumber;PointNumber_Extrema\=PointNumber_Extrema;PointNumber_Leaves\=PointNumber_Leaves;EdgesNumber\=EdgesNumber;EdgesLength\=EdgesLength
p17_MODE=
p17_TYPE=TEXT
p17_default_value=5
p17_description=The paramter used to control different modes.
p17_fileFormat=
p17_flag=
p17_name=epg.collapse.parameter
p17_numValues=1..1
p17_optional=
p17_prefix=
p17_prefix_when_specified=-epg_collapse_par  
p17_type=java.lang.String
p17_value=
p18_MODE=
p18_TYPE=TEXT
p18_default_value=QuantDists
p18_description=The mode used to extend the leaves.  Choose from {{'QuantDists','QuantCentroid','WeigthedCentroid'}}; 'QuantCentroid'\:for each leaf node, the extreme points are ordered by their distance from the node and the centroid of the points further than epg_ext_par is returned; 'WeigthedCentroid'\:for each leaf node, a weight is computed for each points by raising the distance to the epg_ext_par power. Larger epg_ext_par results in a bigger influence of points further than the node; 'QuantDists'\:for each leaf node, the extreme points are ordered by their distance from the node and the 100*epg_ext_par th percentile of the points farther than epg_ext_par is returned.
p18_fileFormat=
p18_flag=
p18_name=epg.extension.mode
p18_numValues=1..1
p18_optional=
p18_prefix=
p18_prefix_when_specified=-epg_ext_mode   
p18_type=java.lang.String
p18_value=QuantDists\=QuantDists;QuantCentroid\=QuantCentroid;WeigthedCentroid\=WeigthedCentroid;None\=None
p19_MODE=
p19_TYPE=TEXT
p19_default_value=0.5
p19_description=The paramter used to control different modes.
p19_fileFormat=
p19_flag=
p19_name=epg.extension.parameter
p19_numValues=1..1
p19_optional=
p19_prefix=
p19_prefix_when_specified=-epg_ext_par  
p19_type=java.lang.String
p19_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A STREAM pkl file containing gene expression data
p1_fileFormat=pkl
p1_flag=
p1_name=data.file
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p20_MODE=
p20_TYPE=TEXT
p20_default_value=Penalized
p20_description=Indicate the final elastic energy associated with the configuration.
p20_fileFormat=
p20_flag=
p20_name=epg.final.energy
p20_numValues=1..1
p20_optional=
p20_prefix=
p20_prefix_when_specified=-epg_finalenergy   
p20_type=java.lang.String
p20_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=0.0
p2_description=Beta parameter of the penalized elastic energy.
p2_fileFormat=
p2_flag=
p2_name=epg.beta
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=-epg_beta    
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=8
p3_description=figure width 
p3_fileFormat=
p3_flag=
p3_name=figure.width
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=-fig_width   
p3_type=java.lang.String
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=3
p4_description=The number of columns that the legend has.
p4_fileFormat=
p4_flag=
p4_name=figure.legend.num.columns
p4_numValues=1..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=-fig_legend_ncol  
p4_type=java.lang.String
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=8
p5_description=figure height
p5_fileFormat=
p5_flag=
p5_name=figure.height
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=-fig_height  
p5_type=java.lang.String
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=
p6_description=output file name prefix
p6_fileFormat=
p6_flag=
p6_name=output.filename
p6_numValues=1..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=
p7_MODE=
p7_TYPE=TEXT
p7_default_value=50
p7_description=The maximum number of iteration steps.
p7_fileFormat=
p7_flag=
p7_name=epg.max.steps
p7_numValues=1..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=-epg_max_steps  
p7_type=java.lang.String
p7_value=
p8_MODE=
p8_TYPE=TEXT
p8_default_value=30
p8_description=Incremental number of nodes for elastic principal graph.
p8_fileFormat=
p8_flag=
p8_name=incremental.number.of.nodes
p8_numValues=1..1
p8_optional=
p8_prefix=
p8_prefix_when_specified=-incr_n_nodes 
p8_type=java.lang.String
p8_value=
p9_MODE=
p9_TYPE=TEXT
p9_default_value=Inf
p9_description=epg_trimmingradius\: `float`, optional (default\: 'Inf')
p9_fileFormat=
p9_flag=
p9_name=epg.trimming.radius
p9_numValues=1..1
p9_optional=
p9_prefix=
p9_prefix_when_specified=-epg_trimmingradius  
p9_type=java.lang.String
p9_value=
privacy=public
publicationDate=02/04/2020 12\:55 
quality=${quality.level}
requiredPatchLSIDs=
requiredPatchURLs=
taskDoc=doc.html
taskType=Single-cell
userid=ted
version=inital revision
