# STREAM.Preprocess  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00395:0.4
#Tue Feb 10 19:12:08 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00395\:0.4
author=Ted Liefeld, UCSD School of Medicine.
categories=Single-Cell
commandLine=python /stream/preprocess_command_line.py -m <data.file> <cell.label.file> <cell.label.color.file> <output.filename> <min.percent.genes> <min.count.genes> <min.num.cells> <min.percent.cells> <min.count.cells> <expression.cutoff> <normalize> <log.transform> <remove.mitochondrial.genes>
cpuType=any
description=Preprocess single cell RNA-seq data to prepare it for the STREAM trajectory analysis. This module will normalize, log transform, filter and remove mitochondiral genes.
fileFormat=gz,tsv,mtx
job.cpuCount=2
job.docker.image=genepattern/stream_preprocess\:0.2
job.memory=8 Gb
job.walltime=1\:00\:00
language=any
minGenePatternVersion=3.9.13
name=STREAM.Preprocess
os=any
p10_MODE=
p10_TYPE=TEXT
p10_default_value=
p10_description=The minimum percentage of cells expressing a gene to keep the gene.
p10_fileFormat=
p10_flag=
p10_name=min.percent.cells
p10_numValues=0..1
p10_optional=on
p10_prefix=
p10_prefix_when_specified=--min_percent_cells 
p10_type=java.lang.String
p10_value=
p11_MODE=
p11_TYPE=TEXT
p11_default_value=
p11_description=The minimum number of read counts for one cell to keep a gene.
p11_fileFormat=
p11_flag=
p11_name=min.count.cells
p11_numValues=0..1
p11_optional=on
p11_prefix=
p11_prefix_when_specified=--min_count_cells 
p11_type=java.lang.String
p11_value=
p12_MODE=
p12_TYPE=TEXT
p12_default_value=
p12_description=The minimum number of cells expression a gene.
p12_fileFormat=
p12_flag=
p12_name=min.num.cells
p12_numValues=0..1
p12_optional=on
p12_prefix=
p12_prefix_when_specified=--min_num_cells 
p12_type=java.lang.String
p12_value=
p13_MODE=
p13_TYPE=TEXT
p13_default_value=
p13_description=The expression cutoff used to determine if a gene is expressed. If expression is greater than expr_cutoff,the gene is considered 'expressed'.
p13_fileFormat=
p13_flag=
p13_name=expression.cutoff
p13_numValues=0..1
p13_optional=on
p13_prefix=
p13_prefix_when_specified=--expression_cutoff  
p13_type=java.lang.String
p13_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=A csv/tsv/pkl file containing gene expression data
p1_fileFormat=pkl;gz;tsv;tsv.gz
p1_flag=
p1_name=data.file
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=A tsv file containing cell labels.
p2_fileFormat=gz;tsv
p2_flag=
p2_name=cell.label.file
p2_numValues=0..1
p2_optional=on
p2_prefix=
p2_prefix_when_specified=-l 
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=A tsv file containing cell label colors expressed as hex values.
p3_fileFormat=gz;tsv
p3_flag=
p3_name=cell.label.color.file
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=-c 
p3_type=java.io.File
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=
p4_description=The output file name prefix.
p4_fileFormat=
p4_flag=
p4_name=output.filename
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=-of   
p4_type=java.lang.String
p4_value=
p5_MODE=
p5_TYPE=CHOICE
p5_default_value=
p5_description=Normalize gene expression based on library size.
p5_fileFormat=
p5_flag=
p5_name=normalize
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=\=FALSE;--norm\=TRUE
p6_MODE=
p6_TYPE=CHOICE
p6_default_value=
p6_description=Log2 transform the dataset.
p6_fileFormat=
p6_flag=
p6_name=log.transform
p6_numValues=0..1
p6_optional=on
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=\=FALSE;--log2\=TRUE
p7_MODE=
p7_TYPE=CHOICE
p7_default_value=
p7_description=Remove mitochondrial genes.
p7_fileFormat=
p7_flag=
p7_name=remove.mitochondrial.genes
p7_numValues=0..1
p7_optional=on
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=\=FALSE;--remove_mt_genes\=TRUE
p8_MODE=
p8_TYPE=TEXT
p8_default_value=
p8_description=The minimum percentage of genes expressed to keep a cell.
p8_fileFormat=
p8_flag=
p8_name=min.percent.genes
p8_numValues=0..1 
p8_optional=on
p8_prefix=
p8_prefix_when_specified=--min_percent_genes 
p8_type=java.lang.String
p8_value=
p9_MODE=
p9_TYPE=TEXT
p9_default_value=
p9_description=The minimum number of read counts for each gene to keep a cell.
p9_fileFormat=
p9_flag=
p9_name=min.count.genes
p9_numValues=0..1
p9_optional=on
p9_prefix=
p9_prefix_when_specified=--min_count_genes  
p9_type=java.lang.String
p9_value=
privacy=public
publicationDate=02/04/2020 12\:51 
quality=${quality.level}
requiredPatchLSIDs=
requiredPatchURLs=
taskDoc=doc.html
taskType=Single-cell
userid=ted
version=inital revision
