# TCGA.ssGSEA.ROC  urn:lsid:8080.gpserver.ip-172-31-26-71.ip-172-31-26-71.ec2.internal:genepatternmodules:689:10
#Tue Feb 10 19:12:09 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:8080.gpserver.ip-172-31-26-71.ip-172-31-26-71.ec2.internal\:genepatternmodules\:689\:10
author=Anthony S. Castanza
categories=pipeline;gsea
commandLine=<java>  -Dgenepattern.properties\=<resources> -DLSID\=<LSID> -DPIPELINE_ARG.StopAfterTask\=<PIPELINE_ARG.StopAfterTask> -DGenePatternURL\=<GenePatternURL>  org.genepattern.server.webapp.RunPipelineSoap <GenePatternURL>getPipelineModel.jsp?name\=<LSID>&userid\=<userid> <userid> TCGA.SampleSelection1.TCGA.Collection\=<TCGA.SampleSelection1.TCGA.Collection> TCGA.SampleSelection1.Gene.Symbol\=<TCGA.SampleSelection1.Gene.Symbol> TCGA.SampleSelection1.High.Expression\=<TCGA.SampleSelection1.High.Expression> TCGA.SampleSelection1.Low.Expression\=<TCGA.SampleSelection1.Low.Expression> ssGSEA2.gene.sets.database.files\=<ssGSEA2.gene.sets.database.files> ssGSEA2.min.gene.set.size\=<ssGSEA2.min.gene.set.size>
cpuType=any
creationDate=Mon Aug 14 22\:56\:25 UTC 2023
description=Pipeline for ssGSEA_ROC analysis of TCGA samples
gpVersion=3.9.11
language=Java
name=TCGA.ssGSEA.ROC
os=any
p1_MODE=
p1_TYPE=TEXT
p1_altDescription=TCGA Study for sample selection
p1_altName=TCGA.Collection
p1_default_value=GBM
p1_description=TCGA Study for sample selection
p1_fileFormat=
p1_flag=--id
p1_name=TCGA.SampleSelection1.TCGA.Collection
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_runTimePrompt=1
p1_type=java.lang.String
p1_value=LAML\=Acute Myeloid Leukemia (LAML);ACC\=Adrenocortical carcinoma (ACC);BLCA\=Bladder urothelial carcinoma (BLCA);LGG\=Brain Lower Grade Glioma (LGG);BRCA\=Breast invasive carcinoma (BRCA);CESC\=Cervical and endocervical cancers (CESC);CHOL\=Cholangiocarcinoma (CHOL);COAD\=Colon adenocarcinoma (COAD);COADREAD\=Colorectal adenocarcinoma (COADREAD);ESCA\=Esophageal carcinoma (ESCA);GBM\=Glioblastoma multiforme (GBM);GBMLGG\=Glioma (GBMLGG);HNSC\=Head and Neck squamous cell carcinoma (HNSC);KICH\=Kidney Chromophobe (KICH);KIRC\=Kidney renal clear cell carcinoma (KIRC);KIRP\=Kidney renal papillary cell carcinoma (KIRP);LIHC\=Liver hepatocellular carcinoma (LIHC);LUAD\=Lung adenocarcinoma (LUAD);LUSC\=Lung squamous cell carcinoma (LUSC);DLBC\=Lymphoid Neoplasm Diffuse Large B-cell Lymphoma (DLBC);MESO\=Mesothelioma (MESO);OV\=Ovarian serous cystadenocarcinoma (OV);KIPAN\=Pan-kidney cohort (KICH+KIRC+KIRP) (KIPAN);PAAD\=Pancreatic adenocarcinoma (PAAD);PCPG\=Pheochromocytoma and Paraganglioma (PCPG);PRAD\=Prostate adenocarcinoma (PRAD);READ\=Rectum adenocarcinoma (READ);SARC\=Sarcoma (SARC);SKCM\=Skin Cutaneous Melanoma (SKCM);STAD\=Stomach adenocarcinoma (STAD);STES\=Stomach and Esophageal carcinoma (STES);TGCT\=Testicular Germ Cell Tumors (TGCT);THYM\=Thymoma (THYM);THCA\=Thyroid carcinoma (THCA);UCS\=Uterine Carcinosarcoma (UCS);UCEC\=Uterine Corpus Endometrial Carcinoma (UCEC);UVM\=Uveal Melanoma (UVM)
p2_MODE=
p2_TYPE=TEXT
p2_altDescription=HGNC Gene Symbol to use for expression level thresholding
p2_altName=Gene.Symbol
p2_default_value=
p2_description=HGNC Gene Symbol to use for expression level thresholding
p2_fileFormat=
p2_flag=--symbol
p2_name=TCGA.SampleSelection1.Gene.Symbol
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_runTimePrompt=1
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=Floating Point
p3_altDescription=mRNA expression is greater than or equal to x standard deviations above the mean. <br>\n(mRNA expression z-scores relative to all samples)
p3_altName=High.Expression
p3_default_value=1
p3_description=mRNA expression is greater than or equal to x standard deviations above the mean. <br>\n(mRNA expression z-scores relative to all samples)
p3_fileFormat=
p3_flag=--high
p3_name=TCGA.SampleSelection1.High.Expression
p3_numValues=1..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_range=0+
p3_runTimePrompt=1
p3_type=java.lang.Float
p3_value=
p4_MODE=
p4_TYPE=Floating Point
p4_altDescription=mRNA expression is less than or equal to x standard deviations below the mean. <br>\n(mRNA expression z-scores relative to all samples)
p4_altName=Low.Expression
p4_default_value=-1
p4_description=mRNA expression is less than or equal to x standard deviations below the mean. <br>\n(mRNA expression z-scores relative to all samples)
p4_fileFormat=
p4_flag=--low
p4_name=TCGA.SampleSelection1.Low.Expression
p4_numValues=1..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_range=0-
p4_runTimePrompt=1
p4_type=java.lang.Float
p4_value=
p5_MODE=IN
p5_TYPE=FILE
p5_altDescription=Gene sets database from GSEA website.  Upload a gene set if your gene set is not listed as a choice from MsigDB.
p5_altName=gene.sets.database.files
p5_choiceDir=https\://www.gsea-msigdb.org/gsea/msigdb/gp_modules_gmt.json
p5_default_value=
p5_description=Gene sets database from GSEA website.  Upload a gene set if your gene set is not listed as a choice from MsigDB.
p5_fileFormat=gmt;gmx;grp
p5_flag=
p5_name=ssGSEA2.gene.sets.database.files
p5_numValues=1+
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_runTimePrompt=1
p5_type=java.io.File
p5_value=
p6_altDescription=Gene sets with overlap smaller than this are excluded from the analysis.
p6_altName=min.gene.set.size
p6_default_value=10
p6_description=Gene sets with overlap smaller than this are excluded from the analysis.
p6_fileFormat=
p6_name=ssGSEA2.min.gene.set.size
p6_optional=
p6_prefix_when_specified=
p6_runTimePrompt=1
p6_type=java.lang.Integer
p6_value=
privacy=public
quality=development
serializedModel=<?xml version\="1.0" ?>\n<program comments\="preserve" space\="ignore">\n\n\t<\!-- pipeline input parameters -->\n\t<param name\="TCGA.SampleSelection1.Gene.Symbol" type\="String"/>\n\t<param name\="TCGA.SampleSelection1.High.Expression" type\="String"/>\n\t<param name\="TCGA.SampleSelection1.Low.Expression" type\="String"/>\n\t<param name\="TCGA.SampleSelection1.TCGA.Collection" type\="String"/>\n\t<param name\="ssGSEA2.gene.sets.database.files" type\="File"/>\n\t<param name\="ssGSEA2.min.gene.set.size" type\="String"/>\n\n\t<\!-- pipeline metadata -->\n\t<variable name\="name" select\="'TCGA.ssGSEA.ROC'"/>\n\t<variable name\="description" select\="'Pipeline for ssGSEA_ROC analysis of TCGA samples'"/>\n\t<variable name\="author" select\="'Anthony S. Castanza'"/>\n\t<variable name\="privacy" select\="'public'"/>\n\t<variable name\="userid" select\="'acastanza'"/>\n\t<variable name\="version" select\="''"/>\n\n\t<\!-- task invocations -->\n\t<task\tname\="'TCGA.SampleSelection'"\n\t\tid\="1"\n\t\tLSID\="urn\:lsid\:genepattern.org\:module.analysis\:00417\:2"\n\t\t_description\="'Retrieve TCGA data from Broad FireBrowse and perform sample selection on the basis of expression levels for specific genes of interest for analysis using GSEA tools.'"\n\t\tTCGA.Collection\="$TCGA.SampleSelection1.TCGA.Collection"\n\t\tGene.Symbol\="$TCGA.SampleSelection1.Gene.Symbol"\n\t\tHigh.Expression\="$TCGA.SampleSelection1.High.Expression"\n\t\tLow.Expression\="$TCGA.SampleSelection1.Low.Expression"\n\t\tOutput.Type\="'scaled_estimate'"\n\t\tMSigDB.Version\="'latest'"/>\n\t<task\tname\="'ssGSEA'"\n\t\tid\="2"\n\t\tLSID\="urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00270\:10.1.0"\n\t\t_description\="'Performs single sample GSEA.  NOTE\: with the release of v10.0.1, this module was renamed from &quot;ssGSEAProjection&quot; to just &quot;ssGSEA&quot;'"\n\t\tinput.gct.file\="gpUseResult(1, 'gct')"\n\t\toutput.file.prefix\="''"\n\t\tgene.sets.database.files\="$ssGSEA2.gene.sets.database.files"\n\t\tgene.symbol.column\="'Name'"\n\t\tgene.set.selection\="'ALL'"\n\t\tsample.normalization.method\="'none'"\n\t\tweighting.exponent\="'0.75'"\n\t\tmin.gene.set.size\="$ssGSEA2.min.gene.set.size"\n\t\tcombine.mode\="'combine.add'"/>\n\t<task\tname\="'HeatMapViewer'"\n\t\tid\="3"\n\t\tLSID\="urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.visualizer\:00010\:13.11"\n\t\t_description\="'A configurable heat map viewer that provides users with several options for manipulating and visualizing array-based data'"\n\t\tdataset\="gpUseResult(2, 'gct')"/>\n\t<task\tname\="'ssGSEA.ROC'"\n\t\tid\="4"\n\t\tLSID\="urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00414\:1"\n\t\t_description\="'Generate ROC curves and calculate the AUC from ssGSEA results and a binary phenotype classification.'"\n\t\tPROJ.gct\="gpUseResult(2, 'gct')"\n\t\tCLS\="gpUseResult(1, 'cls')"\n\t\tReverse\="'FALSE'"\n\t\tPlot.Top.Results\="'20'"/>\n\n</program>
taskDoc=
taskType=pipeline
userid=acastanza
version=
