# tfsites.NormalizeTfDNAAffinityData  urn:lsid:genepattern.org:module.analysis:00441:4
#Tue Feb 10 19:12:10 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00441\:4
author=Joe Solvason
commandLine=python /build/tfsites-webportal/01-normalizeTfDnaAffinityData/01-normalizeTfDnaAffinityData.py -r <raw.data> -b <core.binding.site.definition> -d <DNA.sequence.column> -a <affinity.column>  -p <header.present> -S <output.image.as.svg> -o <output.filename>         
cpuType=any
description=NormalizeTfDnaAffinityData generates a relative affinity dataset which can then be used in other TFSites modules to score binding sites. This tool normalizes a raw affinity dataset relative to the sequence with the highest value that follows the core binding site definition. The resulting dataset will report the relative affinity value for every sequence in the original dataset, ranging from 0 to 1.
documentationUrl=https\://genepattern.github.io/tfsites.NormalizeTfDNAAffinityData/v2/
fileFormat=
job.docker.image=genepattern/tfsites\:16.3
language=any
name=tfsites.NormalizeTfDNAAffinityData
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=File containing the raw affinity dataset.
p1_fileFormat=.tsv
p1_flag=
p1_name=raw.data
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=relative-aff-data_site\=<core.binding.site.definition>
p2_description=Base name of the output files.
p2_fileFormat=
p2_flag=
p2_name=output.filename
p2_numValues=0..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=NNGGAWNN
p3_description=IUPAC definition of the core transcription factor binding site(see <a href\="https\://www.bioinformatics.org/sms/iupac.html">here</a>). The length of the IUPAC definition should be the same length k as the k-mers in the raw affinity file.
p3_fileFormat=
p3_flag=
p3_name=core.binding.site.definition
p3_numValues=0..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_MODE=
p4_TYPE=Integer
p4_default_value=1
p4_description=Number of the column containing the DNA sequences in the raw affinity file (1-indexed, 1 is the first column).
p4_fileFormat=
p4_flag=
p4_name=DNA.sequence.column
p4_numValues=1..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.Integer
p4_value=
p5_MODE=
p5_TYPE=Integer
p5_default_value=4
p5_description=Number of the column containing the raw affinity values in the input file (1-indexed, 1 is the first column).
p5_fileFormat=
p5_flag=
p5_name=affinity.column
p5_numValues=1..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.Integer
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=FALSE
p6_description=If True, a header exists in the PBM data file. If False, no header exists.
p6_fileFormat=
p6_flag=
p6_name=header.present
p6_numValues=0..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=FALSE\=FALSE;TRUE\=TRUE
p7_MODE=
p7_TYPE=TEXT
p7_default_value=FALSE
p7_description=If True, a header exists in the PBM data file. If False, no header exists.
p7_fileFormat=
p7_flag=
p7_name=output.image.as.svg
p7_numValues=0..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=FALSE\=FALSE;TRUE\=TRUE
privacy=public
publicationDate=09/09/2025 20\:22 
quality=production
src.repo=https\://github.com/genepattern/tfsites.DefineTfSites
taskDoc=
taskType=Transcription factor analysis
userid=ted
version=Draft initial release
