# tfsites.GenerateMotifDatabase  urn:lsid:genepattern.org:module.analysis:00459:3
#Tue Feb 10 19:12:10 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00459\:3
author=Joe Solvason
commandLine=python /build/tfsites-webportal/02-generateMotifDatabase/02-generateMotifDatabase.py -i <PFM.input.file> -b <background.nucleotide.frequencies> -p <use.pseudocounts.to.calculate.score>  <filter.keywords> -o <output.filename>  -f <input.format>       
cpuType=any
description=GenerateMotifDatabase can be used to obtain position weight matrix (PWM) data to score binding sites in other TFSites modules. This tool extracts the PFM(s) for one or more transcription factor(s) of interest and then converts each PFM to its respective PWM.
documentationUrl=https\://genepattern.github.io/tfsites.GenerateMotifDatabase/v2/
fileFormat=
job.docker.image=genepattern/tfsites\:16.3
language=any
name=tfsites.GenerateMotifDatabase
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=File containing multiple PFMs. It is formatted similar to a fasta file where the header line starts with ">" and is followed by that PFM.
p1_fileFormat=txt;jaspar;JASPAR
p1_flag=
p1_name=PFM.input.file
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=pfm
p2_description=Input whether the motif database is a PFM (counts of each nt at each position) or PWM (frequency of each nt at each position weighted by the background frequency of the genomes and adjusted by pseudocounts).
p2_fileFormat=
p2_flag=
p2_name=input.format
p2_numValues=0..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=pfm;pwm
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=File containing a single column with a list of keywords. The keywords can be the transcription factor name and/or matrix ID.
p3_fileFormat=tsv
p3_flag=
p3_name=filter.keywords
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=-k   
p3_type=java.io.File
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=FALSE
p4_description=Choose if you want to use pseudocounts to calculate the PWM score for binding sites.
p4_fileFormat=
p4_flag=
p4_name=use.pseudocounts.to.calculate.score
p4_numValues=0..1
p4_optional=
p4_prefix=
p4_prefix_when_specified=
p4_type=java.lang.String
p4_value=FALSE\=FALSE;TRUE\=TRUE
p5_MODE=
p5_TYPE=TEXT
p5_default_value=0.25,0.25,0.25,0.25
p5_description=Choose the nucleotide background frequencies in the order of A, T, G, and C.
p5_flag=
p5_name=background.nucleotide.frequencies
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=<PFM.input.file_basename>_out.txt
p6_description=Base name of the output files. 
p6_fileFormat=
p6_flag=
p6_name=output.filename
p6_numValues=1..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=
privacy=public
publicationDate=09/10/2025 09\:43 
quality=production
src.repo=https\://github.com/genepattern/tfsites.GenerateMotifDatabase
taskDoc=
taskType=Transcription factor analysis
userid=ted
version=Updated to new smaller docker container, crystallography code removed.
