# tfsites.PerturbTfSiteWithoutSideEffects  urn:lsid:genepattern.org:module.analysis:00480:2
#Tue Feb 10 19:12:11 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00480\:2
author=Joe Solvasson, modified into a GenePattern module as Ted Liefeld
commandLine=python /build/tfsites-webportal/07-perturbTfSiteWithoutSideEffects/07-combined-generateMotifDatabase-and-perturbTfSiteWithoutSideEffects.py  -s <DNA.sequence.to.annotate>  -n <primary.TF.name> <primary.affinity.reference.data>  <primary.core.binding.site.definition> <primary.PWM.data>  <primary.PWM.minimum.score>    <primary.SNV.effect.type.to.report> <affinity.optimization.threshold> <affinity.reduction.threshold> <secondary.affinity.information> <secondary.affinity.files> <secondary.PWM.data> <secondary.PWM.minimum.score> <secondary.minimum.binding.charge> -d .  <primary.motif.input.file> <primary.motif.input.format>  <primary.motif.filter.keywords> <primary.motif.use.pseudocounts> <primary.motif.background.frequencies> <primary.motif.output.name>  <secondary.motif.input.file> <secondary.motif.input.format> <secondary.motif.use.pseudocounts> <secondary.motif.filter.keywords>  <secondary.motif.background.frequencies> <secondary.motif.output.name>
cpuType=any
description=PerturbTfSiteWithoutSideEffects reports the secondary effects of mutations.
documentationUrl=https\://genepattern.github.io/tfsites.PerturbTfSiteWithoutSideEffects/v1/
fileFormat=
job.cpuCount=
job.docker.image=genepattern/tfsites\:17.1.3
job.memory=8 Gb
job.walltime=
language=any
name=tfsites.PerturbTfSiteWithoutSideEffects
os=any
p10_MODE=IN
p10_TYPE=FILE
p10_default_value=
p10_description=Affinity dataset used to assign a value to each binding site.
p10_fileFormat=
p10_flag=
p10_name=secondary.affinity.information
p10_numValues=0..1
p10_optional=on
p10_prefix=
p10_prefix_when_specified=-A  
p10_type=java.io.File
p10_value=
p11_MODE=IN
p11_TYPE=FILE
p11_default_value=
p11_description=Files referred to in the "secondary affinity information" file.
p11_fileFormat=
p11_flag=
p11_name=secondary.affinity.files
p11_numValues=0..99
p11_optional=on
p11_prefix=
p11_prefix_when_specified=-F  
p11_type=java.lang.String
p11_value=
p12_MODE=IN
p12_TYPE=FILE
p12_default_value=
p12_description=PWM dataset used to assign a value to each binding site.
p12_fileFormat=.txt
p12_flag=
p12_name=secondary.PWM.data
p12_numValues=0..1
p12_optional=on
p12_prefix=
p12_prefix_when_specified=-P 
p12_type=java.io.File
p12_value=
p13_MODE=
p13_TYPE=TEXT
p13_default_value=0.7
p13_description=PWM score required to predict a binding site.
p13_fileFormat=
p13_flag=
p13_name=secondary.PWM.minimum.score
p13_numValues=0..1
p13_optional=on
p13_prefix=
p13_prefix_when_specified=-M 
p13_type=java.lang.String
p13_value=
p14_MODE=
p14_TYPE=TEXT
p14_default_value=0.1
p14_description=The minimum change of affinity or PWM binding score required to classify an "increase" or "decrease".
p14_fileFormat=
p14_flag=
p14_name=secondary.minimum.binding.charge
p14_numValues=0..1
p14_optional=on
p14_prefix=
p14_prefix_when_specified=-B  
p14_type=java.lang.String
p14_value=
p15_MODE=IN
p15_TYPE=FILE
p15_default_value=
p15_description=File containing matrix data for primary motif database generation (JASPAR format). If provided, motif database will be generated first.
p15_fileFormat=.txt
p15_flag=
p15_name=primary.motif.input.file
p15_numValues=0..1
p15_optional=on
p15_prefix=
p15_prefix_when_specified=--motif_input_file   
p15_type=java.io.File
p15_value=
p16_MODE=
p16_TYPE=TEXT
p16_default_value=pfm
p16_description=Specify whether primary motif database input file contains PFMs or PWMs. Required if motif input file is provided.
p16_fileFormat=
p16_flag=
p16_name=primary.motif.input.format
p16_numValues=0..1
p16_optional=on
p16_prefix=
p16_prefix_when_specified=--motif_input_format    
p16_type=java.lang.String
p16_value=pfm\=PFM;pwm\=PWM
p17_MODE=IN
p17_TYPE=FILE
p17_default_value=
p17_description=File containing keywords to filter primary motifs during database generation.
p17_fileFormat=.tsv
p17_flag=
p17_name=primary.motif.filter.keywords
p17_numValues=0..1
p17_optional=on
p17_prefix=
p17_prefix_when_specified=--motif_filter_keywords   
p17_type=java.io.File
p17_value=
p18_MODE=
p18_TYPE=TEXT
p18_default_value=False
p18_description=Whether to use pseudocounts when generating primary motif database.
p18_fileFormat=
p18_flag=
p18_name=primary.motif.use.pseudocounts
p18_numValues=0..1
p18_optional=on
p18_prefix=
p18_prefix_when_specified=--motif_use_pseudocounts  
p18_type=java.lang.String
p18_value=True;False
p19_MODE=
p19_TYPE=TEXT
p19_default_value=0.25,0.25,0.25,0.25
p19_description=Background frequency for each nucleotide (comma-separated string in order of ATCG) in primary motif database generation.
p19_fileFormat=
p19_flag=
p19_name=primary.motif.background.frequencies
p19_numValues=0..1
p19_optional=on
p19_prefix=
p19_prefix_when_specified=--motif_background_frequencies  
p19_type=java.lang.String
p19_value=
p1_MODE=
p1_TYPE=TEXT
p1_default_value=
p1_description=File containing a DNA sequence to be annotated.
p1_fileFormat=
p1_flag=
p1_name=DNA.sequence.to.annotate
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.lang.String
p1_value=
p20_MODE=
p20_TYPE=TEXT
p20_default_value=generated_primary_motif_database.txt
p20_description=Name of primary motif database output file. If not specified, temporary file will be created.
p20_fileFormat=
p20_flag=
p20_name=primary.motif.output.name
p20_numValues=0..1
p20_optional=on
p20_prefix=
p20_prefix_when_specified=--motif_output_name  
p20_type=java.lang.String
p20_value=
p21_MODE=IN
p21_TYPE=FILE
p21_default_value=
p21_description=File containing matrix data for secondary motif database generation (JASPAR format). If provided, motif database will be generated first.
p21_fileFormat=.txt
p21_flag=
p21_name=secondary.motif.input.file
p21_numValues=0..1
p21_optional=on
p21_prefix=
p21_prefix_when_specified=--motif_input_file2   
p21_type=java.io.File
p21_value=
p22_MODE=
p22_TYPE=TEXT
p22_default_value=pfm
p22_description=Specify whether secondary motif database input file contains PFMs or PWMs. Required if motif input file is provided.
p22_fileFormat=
p22_flag=
p22_name=secondary.motif.input.format
p22_numValues=0..1
p22_optional=on
p22_prefix=
p22_prefix_when_specified=--motif_input_format2    
p22_type=java.lang.String
p22_value=pfm\=PFM;pwm\=PWM
p23_MODE=IN
p23_TYPE=FILE
p23_default_value=
p23_description=File containing keywords to filter secondary motifs during database generation.
p23_fileFormat=.tsv
p23_flag=
p23_name=secondary.motif.filter.keywords
p23_numValues=0..1
p23_optional=on
p23_prefix=
p23_prefix_when_specified=--motif_filter_keywords2   
p23_type=java.io.File
p23_value=
p24_MODE=
p24_TYPE=TEXT
p24_default_value=False
p24_description=Whether to use pseudocounts when generating secondary motif database.
p24_fileFormat=
p24_flag=
p24_name=secondary.motif.use.pseudocounts
p24_numValues=0..1
p24_optional=on
p24_prefix=
p24_prefix_when_specified=--motif_use_pseudocounts2  
p24_type=java.lang.String
p24_value=True;False
p25_MODE=
p25_TYPE=TEXT
p25_default_value=0.25,0.25,0.25,0.25
p25_description=Background frequency for each nucleotide (comma-separated string in order of ATCG) in secondary motif database generation.
p25_fileFormat=
p25_flag=
p25_name=secondary.motif.background.frequencies
p25_numValues=0..1
p25_optional=on
p25_prefix=
p25_prefix_when_specified=--motif_background_frequencies2  
p25_type=java.lang.String
p25_value=
p26_MODE=
p26_TYPE=TEXT
p26_default_value=generated_secondary_motif_database.txt
p26_description=Name of secondary motif database output file. If not specified, temporary file will be created.
p26_fileFormat=
p26_flag=
p26_name=secondary.motif.output.name
p26_numValues=0..1
p26_optional=on
p26_prefix=
p26_prefix_when_specified=--motif_output_name2  
p26_type=java.lang.String
p26_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=
p2_description=Name of the primary transcription factor to use for SNV analysis.
p2_fileFormat=
p2_flag=
p2_name=primary.TF.name
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=
p3_description=IUPAC definition of core TF binding site (see <a href\="https\://www.bioinformatics.org/sms/iupac.html">here</a>). Only optional if using PWM data but required if using affinity data.
p3_fileFormat=
p3_flag=
p3_name=primary.core.binding.site.definition
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=-c  
p3_type=java.lang.String
p3_value=
p4_MODE=IN
p4_TYPE=FILE
p4_default_value=
p4_description=PBM affinity dataset used to assign a value to each binding site.
p4_fileFormat=.tsv
p4_flag=
p4_name=primary.affinity.reference.data
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=-a   
p4_type=java.io.File
p4_value=
p5_MODE=IN
p5_TYPE=FILE
p5_default_value=
p5_description=PWM dataset used to assign a value to each binding site.
p5_fileFormat=.tsv
p5_flag=
p5_name=primary.PWM.data
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=-p  
p5_type=java.io.File
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=0.7
p6_description=PWM score required to predict a binding site.
p6_fileFormat=
p6_flag=
p6_name=primary.PWM.minimum.score
p6_numValues=1..1
p6_optional=on
p6_prefix=
p6_prefix_when_specified=-m  
p6_type=java.lang.String
p6_value=
p7_MODE=
p7_TYPE=TEXT
p7_default_value=all
p7_description=Specify one or more mutation types to analyze. SNV mutations can either increase (optimize) or decrease (sub-optimize) the affinity/score, delete a binding site, or create a binding site. Therefore, the possible mutation types are 'inc', 'dec', 'denovo', and 'del.' This option also takes the value 'all' if the user would like to analyze all of the listed mutation types.
p7_fileFormat=
p7_flag=
p7_name=primary.SNV.effect.type.to.report
p7_numValues=1..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=-e  
p7_type=java.lang.String
p7_value=inc;dec;denovo;del;all
p8_MODE=
p8_TYPE=TEXT
p8_default_value=1.25
p8_description=Fold change threshold for mutations that increase the affinity/score. Only SNVs with fold change above this threshold will be reported. By default, all SNVs will be reported.
p8_fileFormat=
p8_flag=
p8_name=affinity.optimization.threshold
p8_numValues=0..1
p8_optional=
p8_prefix=
p8_prefix_when_specified=-o  
p8_type=java.lang.String
p8_value=
p9_MODE=
p9_TYPE=TEXT
p9_default_value=1.25
p9_description=Fold change threshold for mutations that decrease the affinity/score. Only SNVs with fold change below this threshold will be reported. By default, all SNVs will be reported.
p9_fileFormat=
p9_flag=
p9_name=affinity.reduction.threshold
p9_numValues=0..1
p9_optional=
p9_prefix=
p9_prefix_when_specified=-b   
p9_type=java.lang.String
p9_value=
privacy=public
publicationDate=12/10/2025 12\:10 
quality=production
src.repo=https\://github.com/genepattern/tfsites.AnnotateAndVisualizeInSilicoSNVAnalysis
taskDoc=
taskType=Transcription factor analysis
userid=ted
version=Initial revision.
