# tfsites.FindTfSitesAlteredBySequenceVariation  urn:lsid:genepattern.org:module.analysis:00443:5
#Tue Feb 10 19:12:10 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00443\:5
author=Joe Solvasson, modified into a GenePattern module as Ted Liefeld
commandLine=python /build/tfsites-webportal/04-findTfSitesAlteredBySequenceVariation/04-combined-generateMotifDatabase-and-findTfSitesAlteredBySequenceVariation.py  -d <DNA.sequences.to.annotate> <affinity.reference.data>  <PWM.data>  <PWM.minimum.score>    <SNV.effect.type.to.report> <affinity.optimization.threshold> <affinity.reduction.threshold> <output.image.as.svg> <zoom.range> <plot.resolution> -n <TF.name> <core.binding.site.definition>  --output_name  <output.filename> <motif.input.file> <motif.input.format> <motif.use.pseudocounts> <motif.filter.keywords> <motif.use.pseudocounts> <motif.background.frequencies> <motif.output.name>
cpuType=any
description=FindTfSitesAlteredBySequenceVariation reports the effects of all possible in silico single-nucleotide variants (SNVs) in a given sequence, for one transcription factor. Possible SNV effects include increasing (or optimizing) the affinity/score of a binding site, decreasing the affinity/score of a binding site, deleting a binding site, or creating a binding site.
documentationUrl=https\://genepattern.github.io/tfsites.FindTfSitesAlteredBySequenceVariation/v2/
fileFormat=
job.cpuCount=
job.docker.image=genepattern/tfsites\:17.0.16
job.memory=8 Gb
job.walltime=
language=any
name=tfsites.FindTfSitesAlteredBySequenceVariation
os=any
p10_MODE=
p10_TYPE=TEXT
p10_default_value=1.5
p10_description=Fold change threshold for mutations that increase the affinity/score. Only SNVs with fold change above this threshold will be reported. By default, all SNVs will be reported.
p10_fileFormat=
p10_flag=
p10_name=affinity.optimization.threshold
p10_numValues=0..1
p10_optional=
p10_prefix=
p10_prefix_when_specified=-o  
p10_type=java.lang.String
p10_value=
p11_MODE=
p11_TYPE=TEXT
p11_default_value=0.9
p11_description=Fold change threshold for mutations that decrease the affinity/score. Only SNVs with fold change below this threshold will be reported. By default, all SNVs will be reported.
p11_fileFormat=
p11_flag=
p11_name=affinity.reduction.threshold
p11_numValues=0..1
p11_optional=
p11_prefix=
p11_prefix_when_specified=-b  
p11_type=java.lang.String
p11_value=
p12_TYPE=TEXT
p12_default_value=200
p12_description=Resolution of the plot, in dots (pixels) per inch.
p12_fileFormat=
p12_flag=
p12_name=plot.resolution
p12_numValues=0..1
p12_optional=
p12_prefix=
p12_prefix_when_specified=-R  
p12_type=java.lang.String
p12_value=
p13_MODE=
p13_TYPE=TEXT
p13_default_value=
p13_description=Given a start position and an end position, zoom into a portion of the sequence. The numbers in the range are inclusive and 0-indexed. For example, the first 200 nucleotides of the sequence would be specified as\: 0-199.
p13_fileFormat=
p13_flag=
p13_name=zoom.range
p13_numValues=0..1
p13_optional=on
p13_prefix=
p13_prefix_when_specified=-z  
p13_type=java.lang.String
p13_value=
p14_MODE=IN
p14_TYPE=FILE
p14_default_value=
p14_description=File containing matrix data for motif database generation (JASPAR format). If provided, motif database will be generated first.
p14_fileFormat=.txt
p14_flag=
p14_name=motif.input.file
p14_numValues=0..1
p14_optional=on
p14_prefix=
p14_prefix_when_specified=--motif_input_file   
p14_type=java.io.File
p14_value=
p15_MODE=
p15_TYPE=TEXT
p15_default_value=pfm
p15_description=Specify whether input file contains PFMs or PWMs. Required if motif input file is provided.
p15_fileFormat=
p15_flag=
p15_name=motif.input.format
p15_numValues=0..1
p15_optional=on
p15_prefix=
p15_prefix_when_specified=--motif_input_format    
p15_type=java.lang.String
p15_value=pfm\=PFM;pwm\=PWM
p16_MODE=IN
p16_TYPE=FILE
p16_default_value=
p16_description=File containing keywords to filter motifs during database generation.
p16_fileFormat=.tsv
p16_flag=
p16_name=motif.filter.keywords
p16_numValues=0..1
p16_optional=on
p16_prefix=
p16_prefix_when_specified=--motif_filter_keywords   
p16_type=java.io.File
p16_value=
p17_MODE=
p17_TYPE=TEXT
p17_default_value=False
p17_description=Whether to use pseudocounts when generating motif database.
p17_fileFormat=
p17_flag=
p17_name=motif.use.pseudocounts
p17_numValues=0..1
p17_optional=on
p17_prefix=
p17_prefix_when_specified=--motif_use_pseudocounts  
p17_type=java.lang.String
p17_value=True;False
p18_MODE=
p18_TYPE=TEXT
p18_default_value=0.25,0.25,0.25,0.25
p18_description=Background frequency for each nucleotide (comma-separated string in order of ATCG).
p18_fileFormat=
p18_flag=
p18_name=motif.background.frequencies
p18_numValues=0..1
p18_optional=on
p18_prefix=
p18_prefix_when_specified=--motif_background_frequencies  
p18_type=java.lang.String
p18_value=
p19_MODE=
p19_TYPE=TEXT
p19_default_value=generated_motif_database.txt
p19_description=Name of motif database output file. If not specified, temporary file will be created.
p19_fileFormat=
p19_flag=
p19_name=motif.output.name
p19_numValues=0..1
p19_optional=on
p19_prefix=
p19_prefix_when_specified=--motif_output_name  
p19_type=java.lang.String
p19_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=File containing one or more DNA sequences to be annotated.
p1_fileFormat=.tsv;.txt
p1_flag=
p1_name=DNA.sequences.to.annotate
p1_numValues=1..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=
p2_description=Name of the transcription factor to use for SNV analysis.
p2_fileFormat=
p2_flag=
p2_name=TF.name
p2_numValues=1..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=output
p3_description=Output filename prefix.
p3_fileFormat=
p3_flag=
p3_name=output.filename
p3_numValues=1..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=
p4_description=IUPAC definition of core TF binding site (see <a href\="https\://www.bioinformatics.org/sms/iupac.html">here</a>). Only optional if using PWM data but required if using affinity data.
p4_fileFormat=
p4_flag=
p4_name=core.binding.site.definition
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=-D  
p4_type=java.lang.String
p4_value=
p5_MODE=IN
p5_TYPE=FILE
p5_default_value=
p5_description=PBM affinity dataset used to assign a value to each binding site.
p5_fileFormat=.tsv
p5_flag=
p5_name=affinity.reference.data
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=-r   
p5_type=java.io.File
p5_value=
p6_MODE=IN
p6_TYPE=FILE
p6_default_value=
p6_description=PWM dataset used to assign a value to each binding site.
p6_fileFormat=.tsv
p6_flag=
p6_name=PWM.data
p6_numValues=0..1
p6_optional=on
p6_prefix=
p6_prefix_when_specified=-p  
p6_type=java.io.File
p6_value=
p7_MODE=
p7_TYPE=TEXT
p7_default_value=0.7
p7_description=PWM score required to predict a binding site.
p7_fileFormat=
p7_flag=
p7_name=PWM.minimum.score
p7_numValues=1..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=-s  
p7_type=java.lang.String
p7_value=
p8_MODE=
p8_TYPE=TEXT
p8_default_value=FALSE
p8_description=Option to output images as .svg in addition to .png. For manuscript preparation, .svg format is preferable.
p8_fileFormat=
p8_flag=
p8_name=output.image.as.svg
p8_numValues=1..1
p8_optional=
p8_prefix=
p8_prefix_when_specified=-S  
p8_type=java.lang.String
p8_value=TRUE\=TRUE;FALSE\=FALSE
p9_MODE=
p9_TYPE=TEXT
p9_default_value=all
p9_description=Specify one or more mutation types to analyze. SNV mutations can either increase (optimize) or decrease (sub-optimize) the affinity/score, delete a binding site, or create a binding site. Therefore, the possible mutation types are 'inc', 'dec', 'denovo', and 'del.' This option also takes the value 'all' if the user would like to analyze all of the listed mutation types.
p9_fileFormat=
p9_flag=
p9_name=SNV.effect.type.to.report
p9_numValues=1..1
p9_optional=on
p9_prefix=
p9_prefix_when_specified=-e   
p9_type=java.lang.String
p9_value=
privacy=public
publicationDate=10/29/2025 08\:52 
quality=production
src.repo=https\://github.com/genepattern/tfsites.AnnotateAndVisualizeInSilicoSNVAnalysis
taskDoc=
taskType=Transcription factor analysis
userid=ted
version=Added ability to generate motif DB then run all in one module (optionally).
