# tfsites.VisualizeTFSitesOnSequences  urn:lsid:genepattern.org:module.analysis:00442:5
#Tue Feb 10 19:12:11 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00442\:5
author=Joe Salvasson, modified into a GenePattern module as Ted Liefeld
commandLine=python /build/tfsites-webportal/03-visualizeTfSitesOnSequences/03-combined-generateMotifDatabase-and-visualizeTfSitesOnSequences.py <motif.input.file> <motif.input.format> <motif.filter.keywords> <motif.use.pseudocounts> <motif.background.frequencies> <motif.output.name> -d <DNA.sequences.to.annotate> <TF.affinity.information> <TF.affinity.files> <batch.motif.input.file> -m <PWM.minimum.score> -c <PWM.binding.site.color> -s <output.image.as.svg> -r <plot.resolution> <zoom.range> -o <output.filename>
cpuType=any
description=Annotates transcription factor binding sites across a DNA sequence with optional motif database generation. Multiple transcription factors can be analyzed. Each binding site is labeled with a unique binding site ID and its start and end position. If reference data is provided for a transcription factor, the affinity/score of this site will be labeled and the intensity of the binding site's color will be proportional. At least one of affinity information and files or batch motif files (or both) must be provided. If motif database parameters are provided, it will first generate a motif database and use it for visualization.
documentationUrl=https\://genepattern.github.io/tfsites.VisualizeTFSitesOnSequences/v3/
fileFormat=
job.cpuCount=2
job.docker.image=genepattern/tfsites\:17.0.19
job.memory=8GB
language=any
name=tfsites.VisualizeTFSitesOnSequences
os=any
p10_MODE=IN
p10_TYPE=FILE
p10_default_value=
p10_description=File containing a list of affinity data referenced in the TF affinity information file.
p10_fileFormat=.tsv
p10_flag=
p10_name=TF.affinity.files
p10_numValues=0..99
p10_optional=on
p10_prefix=
p10_prefix_when_specified=-R  
p10_type=java.io.File
p10_value=
p11_MODE=
p11_TYPE=TEXT
p11_default_value=FALSE
p11_description=Option to output images as .svg in addition to .png. For manuscript preparation, .svg format is preferable.
p11_fileFormat=
p11_flag=
p11_name=output.image.as.svg
p11_numValues=1
p11_optional=
p11_prefix=
p11_prefix_when_specified=
p11_type=java.lang.String
p11_value=FALSE;TRUE
p12_MODE=
p12_TYPE=TEXT
p12_default_value=grey
p12_description=Color of sites scored by PWMs on the output visualization. Find color options here.
p12_fileFormat=
p12_flag=
p12_name=PWM.binding.site.color
p12_numValues=1..1
p12_optional=
p12_prefix=
p12_prefix_when_specified=
p12_type=java.lang.String
p12_value=
p13_MODE=
p13_TYPE=Integer
p13_default_value=200
p13_description=Resolution of the plot, in dots (pixels) per inch. Manuscripts require 300 DPI. The DPI does not affect the resolution of .svg files.
p13_fileFormat=
p13_flag=
p13_name=plot.resolution
p13_numValues=0..1
p13_optional=
p13_prefix=
p13_prefix_when_specified=
p13_type=java.lang.Integer
p13_value=
p14_MODE=
p14_TYPE=TEXT
p14_default_value=
p14_description=Given a start position and an end position, zoom into a portion of the sequence. The numbers in the range are inclusive and 1-indexed. For example, the first 200 nucleotides of the sequence would be specified as\: 1-200.
p14_fileFormat=
p14_flag=
p14_name=zoom.range
p14_numValues=0..1
p14_optional=on
p14_prefix=
p14_prefix_when_specified=-z  
p14_type=java.lang.String
p14_value=
p15_MODE=
p15_TYPE=FLOAT
p15_default_value=0.7
p15_description=PWM score required to predict a binding site.
p15_fileFormat=
p15_flag=
p15_name=PWM.minimum.score
p15_numValues=0..1
p15_optional=on
p15_prefix=
p15_prefix_when_specified=
p15_type=java.lang.String
p15_value=
p16_MODE=
p16_TYPE=TEXT
p16_default_value=output
p16_description=Base name of the output files.
p16_fileFormat=
p16_flag=
p16_name=output.filename
p16_numValues=1..1
p16_optional=
p16_prefix=
p16_prefix_when_specified=
p16_type=java.lang.String
p16_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=File containing matrix data for motif database generation (JASPAR format). If provided, motif database will be generated first.
p1_fileFormat=.txt
p1_flag=
p1_name=motif.input.file
p1_numValues=0..1
p1_optional=on
p1_prefix=
p1_prefix_when_specified=--motif_input_file 
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=pfm
p2_description=Specify whether input file contains PFMs or PWMs. Required if motif input file is provided.
p2_fileFormat=
p2_flag=
p2_name=motif.input.format
p2_numValues=0..1
p2_optional=on
p2_prefix=
p2_prefix_when_specified=--motif_input_format 
p2_type=java.lang.String
p2_value=pfm\=PFM;pwm\=PWM
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=File containing keywords to filter motifs during database generation.
p3_fileFormat=.tsv
p3_flag=
p3_name=motif.filter.keywords
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=--motif_filter_keywords 
p3_type=java.io.File
p3_value=
p4_MODE=
p4_TYPE=TEXT
p4_default_value=False
p4_description=Whether to use pseudocounts when generating motif database.
p4_fileFormat=
p4_flag=
p4_name=motif.use.pseudocounts
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=--motif_use_pseudocounts 
p4_type=java.lang.String
p4_value=True;False
p5_MODE=
p5_TYPE=TEXT
p5_default_value=0.25,0.25,0.25,0.25
p5_description=Background frequency for each nucleotide (comma-separated string in order of ATCG).
p5_fileFormat=
p5_flag=
p5_name=motif.background.frequencies
p5_numValues=0..1
p5_optional=on
p5_prefix=
p5_prefix_when_specified=--motif_background_frequencies 
p5_type=java.lang.String
p5_value=
p6_MODE=
p6_TYPE=TEXT
p6_default_value=generated_motif_database.txt
p6_description=Name of motif database output file. If not specified, temporary file will be created.
p6_fileFormat=
p6_flag=
p6_name=motif.output.name
p6_numValues=0..1
p6_optional=on
p6_prefix=
p6_prefix_when_specified=--motif_output_name 
p6_type=java.lang.String
p6_value=
p7_MODE=IN
p7_TYPE=FILE
p7_default_value=
p7_description=File containing one or more DNA sequences to be annotated.
p7_fileFormat=.tsv
p7_flag=
p7_name=DNA.sequences.to.annotate
p7_numValues=1..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=
p7_type=java.io.File
p7_value=
p8_MODE=IN
p8_TYPE=FILE
p8_default_value=
p8_description=File containing all the information for the transcription factors being analyzed. This includes the TF name, color, binding site definition, affinity reference data (optional), and minimum affinity (optional).
p8_fileFormat=tsv
p8_flag=
p8_name=TF.affinity.information
p8_numValues=0..1
p8_optional=on
p8_prefix=
p8_prefix_when_specified=-t  
p8_type=java.io.File
p8_value=
p9_MODE=IN
p9_TYPE=FILE
p9_default_value=
p9_description=File containing PWMs to predict and score binding sites. This file can be obtained using GenerateMotifDatabase or will be generated automatically if motif generation parameters are provided.
p9_fileFormat=.tsv
p9_flag=
p9_name=batch.motif.input.file
p9_numValues=0..1
p9_optional=on
p9_prefix=
p9_prefix_when_specified=-p    
p9_type=java.io.File
p9_value=
privacy=public
publicationDate=10/29/2025 09\:49 
quality=production
src.repo=https\://github.com/genepattern/tfsites.VisualizeTFSitesOnSequences/
taskDoc=
taskType=Transcription factor analysis
userid=ted
version=Updated docker container to v17.0.19.
