# TransposeDataset  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00026:3
#Tue Feb 10 19:12:11 UTC 2026
JVMLevel=1.4
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00026\:3
author=GenePattern
commandLine=<java> <java_flags> -cp <libdir>TransposeDataset.jar<path.separator><libdir>broad-cg.jar<path.separator><libdir>trove.jar<path.separator><libdir>Jama-1.0.1.jar<path.separator><libdir>gp-modules.jar edu.mit.broad.modules.transpose.Transpose <input.filename> <output.file.format> <output.file.name>
cpuType=any
description=Transpose a Dataset - .res .gct, .odf
fileFormat=gct;Dataset
language=Java
name=TransposeDataset
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Dataset - .res .gct, .odf
p1_fileFormat=res;gct;Dataset
p1_name=input.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=gct
p2_description=The output file format
p2_name=output.file.format
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=gct;odf
p3_default_value=<input.filename_basename>.transposed
p3_description=The name of the output file
p3_name=output.file.name
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
pipelineModel=
privacy=public
quality=production
serializedModel=
taskType=Preprocess & Utilities
userid=GenePattern (gp-help@broad.mit.edu)
version=Added gct as an output format
