# tximport.DESeq2  urn:lsid:genepattern.org:module.analysis:00422:5
#Tue Feb 10 19:12:11 UTC 2026
JVMLevel=
LSID=urn\:lsid\:genepattern.org\:module.analysis\:00422\:5
author=Anthony S. Castanza;UCSD-MesirovLab
categories=differential expression
commandLine=<Rscript> <libdir>tximport.deseq2.R --quant\=<Quantifications> --type\=<Quant.Type> --txdb\=<Transcriptome.Database> --info\=<Sample.Info> --counts\=<Output.Normalized.Counts> --tpm\=<Output.TPM> --basename\=<output.file.base> --annotate\=<Annotate.DEGs> --reverse\=<Reverse.Sign> --split\=<Split.Identifiers>  --filter\=<Min.Count.Filter> --seed\=<random.seed>
cpuType=any
description=Imports RNA-seq quantifications from frequently used pipelines using the tximport package and outputs a DESeq2 "normalized counts" file in .GCT format suitable for use with GSEA, and/or a TPM .GCT suitable for ssGSEA.<br>\nIf a Sample Info file is provided containing assignments of samples to phenotypes, gene level differential expression will be calculated using DESeq2 for the two phenotypes.
documentationUrl=https\://github.com/genepattern/tximport.DESeq2/blob/main/docs/v1/index.md
fileFormat=cls;gct;txt
job.docker.image=genepattern/tximport_deseq2\:1.0
language=any
name=tximport.DESeq2
os=any
p10_MODE=
p10_TYPE=TEXT
p10_default_value=TRUE
p10_description=Some pipelines produce a gene label that combines a reference ID and a Gene Symbol joined by an underscore (e.g. ENSG00000141510_TP53).\n<br>\n<b>TRUE</b> will attempt to split these into the reference ID and the Gene Symbol. The reference ID will be used as the NAME column of the GCT and the Gene Symbol will be used as the Description.\n<br>\n<b>FALSE</b> will leave the identifiers as-is.\n
p10_fileFormat=
p10_flag=--split
p10_name=Split.Identifiers
p10_numValues=1..1
p10_optional=
p10_prefix=
p10_prefix_when_specified=
p10_type=java.lang.String
p10_value=TRUE\=TRUE;FALSE\=FALSE
p11_MODE=
p11_TYPE=Integer
p11_default_value=1
p11_description=Keep genes with more than <Min.Count.Filter> counts summed over all samples (default\: 1 count; 0 \= disabled)
p11_fileFormat=
p11_flag=--filter
p11_name=Min.Count.Filter
p11_numValues=1..1
p11_optional=
p11_prefix=
p11_prefix_when_specified=
p11_range=0+
p11_type=java.lang.Integer
p11_value=
p12_MODE=
p12_TYPE=TEXT
p12_default_value=779948241
p12_description=Integer used to configure the workspace. Setting this to a constant ensures uniformity for any operations that use random numbers.
p12_fileFormat=
p12_flag=--seed
p12_name=random.seed
p12_numValues=1..1
p12_optional=
p12_prefix=
p12_prefix_when_specified=
p12_type=java.lang.String
p12_value=
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Output files from the respective pipeline. Files must be named with the sample ID and the appropriate extension for the quantification tool.\n<br>\nExample\:\n".genes.results" files output from RSEM\: Sample_1.genes.results\n<br>\n".quant.sf" or ".quant.sf.gz" files output from Salmon/Sailfish\: Sample_1.quant.sf/Sample_1.quant.sf.gz\n<br>\n".abundance.h5" or ".abundance.tsv" files output from Kallisto\: Sample_1.abundance.h5/Sample_1.abundance.h5.gz/Sample_1.abundance.tsv/Sample_1.abundance.tsv.gz\n<br><br>\nAll files must have been quantified using the same application and the same transcriptome.\n<br>\nSupports gzip (.gz) files.
p1_fileFormat=gz;h5;results;sf;tsv
p1_flag=--quant
p1_name=Quantifications
p1_numValues=1+
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=<b>Optional</b> tab delimited text file containing Sample ID to Phenotype mappings. Sample IDs should match exactly the ID used in the input file (without the file extension).<br>\nIf provided, this file will be used to compute deferentially expressed genes using DESeq2.\n<br>By default, Log2(FC) will be calculated for the first Factor level vs the second Factor level (Phenotype_A vs. Phenotype_B).\n<br><br>\n<style type\="text/css">\n.tg  {border-collapse\:collapse;border-spacing\:0;}\n.tg td{border-color\:black;border-style\:solid;border-width\:1px;font-family\:Arial, sans-serif;font-size\:12px;}\n.tg th{border-color\:black;border-style\:solid;border-width\:1px;font-family\:Arial, sans-serif;font-size\:12px;\n  font-weight\:normal;}\n.tg .tg-0pky{border-color\:inherit;text-align\:left;vertical-align\:top}\n</style>\n<table class\="tg">\n<tbody>\n  <tr>\n    <th class\="tg-0pky">SampleID</th>\n    <th class\="tg-0pky">Factor</th>\n  </tr>\n  <tr>\n    <td class\="tg-0pky">Sample_1</td>\n    <td class\="tg-0pky">Phenotype_A</td>\n  </tr>\n  <tr>\n    <td class\="tg-0pky">Sample_2</td>\n    <td class\="tg-0pky">Phenotype_A</td>\n  </tr>\n  <tr>\n    <td class\="tg-0pky">Sample_3</td>\n    <td class\="tg-0pky">Phenotype_B</td>\n  </tr>\n  <tr>\n    <td class\="tg-0pky">Sample_4</td>\n    <td class\="tg-0pky">Phenotype_B</td>\n  </tr>\n</tbody>\n</table>\n<br>\nCovariates can be provided as additional "Factor" columns. The first factor column (the second column in the table) will always be used as the primary factor for the differential expression analysis.
p2_fileFormat=txt
p2_flag=--info
p2_name=Sample.Info
p2_numValues=0..1
p2_optional=on
p2_prefix=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=
p3_TYPE=TEXT
p3_default_value=SALMON
p3_description=Select the type of quantifications to be imported.
p3_fileFormat=
p3_flag=--type
p3_name=Quant.Type
p3_numValues=1..1
p3_optional=
p3_prefix=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=RSEM\=RSEM .genes.results;SALMON\=Salmon .quant.sf;SAILFISH\=Sailfish .quant.sf;KallistoH5\=Kallisto .abundance.h5;KallistoTSV\=Kallisto .abundance.tsv
p4_MODE=IN
p4_TYPE=FILE
p4_default_value=
p4_description=For Salmon/Sailfish/Kallisto data providing the transcriptome file used to quantify the data is <b>required</b> and must be provided in GTF/GFF3 format. This parameter is not utilized for RSEM data.<br/>(Supports gzip [.gz] files).<br/>
p4_fileFormat=gff3;gtf;gz
p4_flag=--txdb
p4_name=Transcriptome.Database
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=
p4_type=java.io.File
p4_value=
p5_MODE=
p5_TYPE=TEXT
p5_default_value=TRUE
p5_description=Compute count normalization with DESeq2 and output the normalized matrix. This is the ideal output for compatibility with GSEA.
p5_fileFormat=
p5_flag=--counts
p5_name=Output.Normalized.Counts
p5_numValues=1..1
p5_optional=
p5_prefix=
p5_prefix_when_specified=
p5_type=java.lang.String
p5_value=TRUE\=TRUE;FALSE\=FALSE
p6_MODE=
p6_TYPE=TEXT
p6_default_value=TRUE
p6_description=Transcripts per million (TPM) quantifications will be extracted and output. This is the ideal output for compatibility with ssGSEA.
p6_fileFormat=
p6_flag=--tpm
p6_name=Output.TPM
p6_numValues=1..1
p6_optional=
p6_prefix=
p6_prefix_when_specified=
p6_type=java.lang.String
p6_value=TRUE\=TRUE;FALSE\=FALSE
p7_MODE=
p7_TYPE=TEXT
p7_default_value=Merged.Data
p7_description=The base name of the output file(s). File extensions will be added automatically.
p7_fileFormat=
p7_flag=--basename
p7_name=output.file.base
p7_numValues=1..1
p7_optional=
p7_prefix=
p7_prefix_when_specified=
p7_type=java.lang.String
p7_value=
p8_MODE=
p8_TYPE=TEXT
p8_default_value=FALSE
p8_description=If computing differentially expressed genes, by default, Log2(FC) will be calculated for the first Factor level vs the second Factor level (Phenotype_A vs. Phenotype_B). Setting Reverse.Sign \= TRUE will reverse the direction of the calculation and Log2(FC) will be calculated for the second Factor level vs the first Factor level (Phenotype_B vs. Phenotype_A).
p8_fileFormat=
p8_flag=--reverse
p8_name=Reverse.Sign
p8_numValues=1..1
p8_optional=
p8_prefix=
p8_prefix_when_specified=
p8_type=java.lang.String
p8_value=TRUE\=TRUE;FALSE\=FALSE
p9_MODE=
p9_TYPE=TEXT
p9_default_value=TRUE
p9_description=If a Sample Info file and a Transcriptome Database have been provided, setting Annotate DEGs to TRUE will attempt to add gene symbols to the computed differential expression analysis.<br>Note\: This does not affect the .GCT files which will still output only the underlying Gene IDs.
p9_fileFormat=
p9_flag=--annotate
p9_name=Annotate.DEGs
p9_numValues=1..1
p9_optional=
p9_prefix=
p9_prefix_when_specified=
p9_type=java.lang.String
p9_value=TRUE\=TRUE;FALSE\=FALSE
privacy=public
publicationDate=03/04/2024 14\:39 
quality=production
taskDoc=tximport.DESeq2.pdf
taskType=differential expression
userid=edwin5588
version=
