# txt2odf  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00372:3
#Tue Feb 10 19:12:12 UTC 2026
JVMLevel=
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00372\:3
author=Edwin Juarez;GenePattern - Mesirov Lab
categories=Data Format Conversion
commandLine=<python_3.6> <libdir>txt2odf.py <txt_file> <prune_gct> <gct> <cls>
cpuType=any
description=This module turns a TXT file into an ODF file which can be used with other GenePattern Modules.
fileFormat=odf
job.docker.image=genepattern/docker-python36\:0.5
language=Python
name=txt2odf
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=The text file to be reformatted.
p1_fileFormat=txt
p1_flag=-t
p1_name=txt_file
p1_numValues=0..1
p1_optional=
p1_prefix=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=
p2_TYPE=TEXT
p2_default_value=False
p2_description=Whether or not to prune the GCT file to match the TXT file.
p2_fileFormat=
p2_flag=-p
p2_name=prune_gct
p2_numValues=0..1
p2_optional=
p2_prefix=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=True\=True;False\=False
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=This is the GCT file which was originally used. *Set prune_gct to True if you want this file pruned*
p3_fileFormat=gct
p3_flag=-g
p3_name=gct
p3_numValues=0..1
p3_optional=on
p3_prefix=
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
p4_MODE=IN
p4_TYPE=FILE
p4_default_value=
p4_description=This is the CLS file which was originally used.
p4_fileFormat=cls
p4_flag=-c
p4_name=cls
p4_numValues=0..1
p4_optional=on
p4_prefix=
p4_prefix_when_specified=
p4_type=java.io.File
p4_value=
privacy=public
publicationDate=07/25/2018 18\:21 
quality=production
taskDoc=doc.html
taskType=Data Format Conversion
userid=edjuaro
version=Cleaning up the release
