# UploadFile  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00216:0.1
#Tue Feb 10 19:12:12 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00216\:0.1
author=Adrian Png, BC Cancer Research Centre
commandLine=<java> -cp <libdir>uploadfile.jar net.sf.flowcyt.gp.module.StageFiles -in <input.file> -out <output.filename>
cpuType=any
description=A utility for users to upload and share a common input file for use by modules within a pipeline.
fileFormat=
language=Java
name=UploadFile
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Please specify the file you wish to upload.
p1_fileFormat=
p1_name=input.file
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_default_value=<input.file_file>
p2_description=Please specify the new filename if required.
p2_fileFormat=
p2_name=output.filename
p2_optional=
p2_prefix_when_specified=
p2_type=java.lang.String
p2_value=
pipelineModel=
privacy=public
publicationDate=09/15/2010 17\:18 
quality=development
requiredPatchLSIDs=
requiredPatchURLs=
serializedModel=
taskType=Preprocess & Utilities
userid=apng
version=
