# VennDiagram  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.visualizer:00105:1
#Tue Feb 10 19:12:12 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.visualizer\:00105\:1
author=GenePattern
commandLine=<java> <java_flags> -cp <libdir>gp-modules.jar org.genepattern.gui.venn.VennDiagram <feature.list.one> <feature.list.two> <feature.list.three>
cpuType=any
description=Displays a Venn diagram
language=Java
name=VennDiagram
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Feature list one - .grp, .txt
p1_fileFormat=grp;txt
p1_name=feature.list.one
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=Feature list two - .grp, .txt
p2_fileFormat=grp;txt
p2_name=feature.list.two
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_MODE=IN
p3_TYPE=FILE
p3_default_value=
p3_description=Feature list three - .grp, .txt
p3_fileFormat=grp;txt
p3_name=feature.list.three
p3_optional=on
p3_prefix_when_specified=
p3_type=java.io.File
p3_value=
privacy=public
publicationDate=05/30/2007 11\:20 
quality=production
taskType=Visualizer
userid=GenePattern
version=
