# XChromosomeCorrect  urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00093:3.1
#Tue Feb 10 19:12:13 UTC 2026
JVMLevel=1.5
LSID=urn\:lsid\:broad.mit.edu\:cancer.software.genepattern.module.analysis\:00093\:3.1
author=David Twomey and Joshua Gould
commandLine=<java> <java_flags> -cp <libdir>snp.jar<path.separator><libdir>commons-math-1.1.jar<path.separator><libdir>Jama-1.0.1.jar<path.separator><libdir>log4j-1.2.13.jar<path.separator><libdir>gp-modules.jar<path.separator><libdir>opencsv-1.7.jar org.genepattern.modules.XCorrect.Xcorrect <snp.filename> <sample.info.filename> <output.file>
cpuType=any
description=Corrects X Chromosome SNP's for male samples.
fileFormat=snp
language=Java
name=XChromosomeCorrect
os=any
p1_MODE=IN
p1_TYPE=FILE
p1_default_value=
p1_description=Summarized probe intensity data in .snp format
p1_fileFormat=snp
p1_name=snp.filename
p1_optional=
p1_prefix_when_specified=
p1_type=java.io.File
p1_value=
p2_MODE=IN
p2_TYPE=FILE
p2_default_value=
p2_description=A Sample information file that contains gender information
p2_fileFormat=
p2_name=sample.info.filename
p2_optional=
p2_prefix_when_specified=
p2_type=java.io.File
p2_value=
p3_default_value=<snp.filename_basename>.xcorrected.snp
p3_description=Output file name
p3_fileFormat=
p3_name=output.file
p3_optional=
p3_prefix_when_specified=
p3_type=java.lang.String
p3_value=
privacy=public
publicationDate=04/24/2008 11\:07 
quality=production
taskType=SNP Analysis
userid=GenePattern
version=Fixed bug that required sample info file to have a Ploidy(numeric) column
